### ISSUE TITLE
native android app Process crashes

### ISSUE THREAD

**Issue by lbutterfly** [wix/Detox#1093]
#### Description
1. android app Process crashes after update detox 8.2.3 to 9.1.2. 
2. My app is native app, not an react-native app

#### Steps to Reproduce
My app is success for detox 8.2.3, Then I follow this Guide 
 (https://github.com/wix/detox/blob/master/docs/Guide.Migration.md#migrating-from-detox-8xx-to-9xx) update to 9.1.2, And also install react-native use "npm install react-native", But when I command "detox test". app will crash after launch.

which step missing ?

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.1.2
* React Native: 0.55.4
* Node: v11.0.0
* Device: Emulator Nexus_6_API_28
* Xcode: 10.0.0
* macOS: 10.14

#### Device and verbose Detox logs

Detox logs: 
[detox_log.txt](https://github.com/wix/Detox/files/2698005/detox_log.txt)

Device logs:
[devices_log.txt](https://github.com/wix/Detox/files/2698007/devices_log.txt)
```
12-20 16:31:55.876 15543-15626/com.motherapp.herman_miller_android.debug E/UncaughtException: java.lang.ClassCastException: com.motherapp.herman_miller_android.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.wix.detox.ReactNativeSupport.getInstanceManager(ReactNativeSupport.java:65)
        at com.wix.detox.ReactNativeSupport.waitForReactNativeLoad(ReactNativeSupport.java:120)
        at com.wix.detox.ReactNativeCompat.waitForReactNativeLoad(ReactNativeCompat.java:33)
        at com.wix.detox.DetoxManager.start(DetoxManager.java:72)
        at com.wix.detox.Detox$1$1.run(Detox.java:133)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at com.wix.detox.Detox$1.run(Detox.java:136)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by rotemmiz** [comment]
You are right, this is a real issue. We started removing usage of reflection to react-native APIs. We need to do a better job at only loading react native support classes when react native exists in classpath.

**Comment by LeoNatan** [comment]
This is an old issue. If still relevant, please reproduce on a modern version of Detox and open a new issue.
