### ISSUE TITLE
Error EXEC_FAIL "Can't find service: power"

### ISSUE THREAD

**Issue by denis-panov** [wix/Detox#1099]
#### Description
I'm trying to use detox in our CI pipeline and I have created bash script to perform automated testing. Script works fine for iOS but failing for Android. I'm getting following error:
```
adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
ERROR: [exec.js/EXEC_FAIL, #4] Can't find service: power
```

#### Steps to Reproduce
1. Download Detox demo app [LINK](https://github.com/wix/Detox/tree/master/examples/demo-react-native)
2. Copy sh script from attach to project folder and replace:

>cd $SOURCE_DIRECTORY  #--> Path to project folder
>
> [detox.sh](https://github.com/wix/Detox/files/2710364/detox.sh.txt)

3. Run bash script

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 9.1.2
* React Native: 0.51.1
* Node: 8.5.0
* Device: emulator(system-images;android-25;google_apis;arm64-v8a)
* macOS: High Sierra 10.13.6 (17G3025)

#### Device and verbose Detox logs
```
detox[8534] INFO:  [DetoxServer.js] server listening on localhost:50615...
detox[8534] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50615
detox[8534] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=9f0477ec-c7c6-97e0-fa7d-6c2110940198
detox[8534] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=9f0477ec-c7c6-97e0-fa7d-6c2110940198
detox[8534] DEBUG: [exec.js/EXEC_CMD, #0] /Users/usr/Library/Android/sdk/emulator/emulator -list-avds --verbose
detox[8534] DEBUG: [exec.js/EXEC_CMD, #1] /Users/usr/Library/Android/sdk/platform-tools/adb  devices
detox[8534] DEBUG: [exec.js/EXEC_CMD, #2] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
detox[8534] DEBUG: [exec.js/EXEC_CMD, #3] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[8534] DEBUG: [exec.js/EXEC_CMD, #4] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[8534] ERROR: [exec.js/EXEC_FAIL, #4] "/Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""" failed with code = 1, stdout and stderr:

detox[8534] ERROR: [exec.js/EXEC_FAIL, #4] 
detox[8534] ERROR: [exec.js/EXEC_FAIL, #4] Can't find service: power
detox[8534] ERROR: [index.js/DETOX_INIT_ERROR] 
 { Error: Command failed: /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
Can't find service: power
 `/Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""` (exited with error code 1)
    at callback (/Users/usr/agent/2.144.0/work/1/s/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  name: 'ChildProcessError',
  code: 1,
  childProcess: 
   { ChildProcess: { [Function: ChildProcess] super_: [Object] },
     fork: [Function],
     _forkChild: [Function],
     exec: [Function],
     execFile: [Function],
     spawn: [Function],
     spawnSync: [Function: spawnSync],
     execFileSync: [Function: execFileSync],
     execSync: [Function: execSync] },
  stdout: '',
  stderr: 'Can\'t find service: power\n' }
detox[8534] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=9f0477ec-c7c6-97e0-fa7d-6c2110940198
detox[8534] ERROR: [EmulatorTelnet.js/TELNET_ERROR] connect ECONNREFUSED 127.0.0.1:23
  err: Error: connect ECONNREFUSED 127.0.0.1:23
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```

**Comment by noomorph** [comment]
A google search gave me very few results on this.

<img width="50%" alt="screen shot 2018-12-28 at 11 54 06 am" src="https://user-images.githubusercontent.com/1962469/50511795-b4225880-0a97-11e9-800d-b475f4e97b35.png">

Looks like something really exotic, might be related to CI + Android emulator configuration. Try out other emulators or another environment (local machine, another CI, etc). Also, using ARM emulators with Detox is discouraged on CI due to slowness, so I recommend trying out with x86 emulator.

**Comment by TillSchroder** [comment]
I'm seeing the same issue, but only when I launch the emulator manually with -no-window. @denis-panov do you see this issue also outside of CI?

**Comment by denis-panov** [comment]
Hi, @TillSchroder. No, I can reproduce this error only in CI. Sometimes it error looks like:
```
detox[8636] INFO:  [DetoxServer.js] server listening on localhost:50493...
detox[8636] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50493
detox[8636] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=d934c583-6554-9ea8-9026-f589e3fe974e
detox[8636] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=d934c583-6554-9ea8-9026-f589e3fe974e
detox[8636] DEBUG: [exec.js/EXEC_CMD, #0] /Users/usr/Library/Android/sdk/emulator/emulator -list-avds --verbose
detox[8636] DEBUG: [exec.js/EXEC_CMD, #1] /Users/usr/Library/Android/sdk/platform-tools/adb  devices
detox[8636] DEBUG: [exec.js/EXEC_CMD, #2] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
detox[8636] DEBUG: [exec.js/EXEC_CMD, #3] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[8636] DEBUG: [exec.js/EXEC_CMD, #4] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[8636] DEBUG: [exec.js/EXEC_CMD, #5] /Users/usr/Library/Android/sdk/build-tools/28.0.3/aapt dump badging "/Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[8636] DEBUG: [exec.js/EXEC_CMD, #6] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.detox.rn.example"
detox[8636] DEBUG: [exec.js/EXEC_CMD, #7] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.detox.rn.example
detox[8636] DEBUG: [exec.js/EXEC_CMD, #8] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.detox.rn.example.test"
detox[8636] DEBUG: [exec.js/EXEC_CMD, #9] /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk
  1) "before all" hook

  0 passing (5m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



detox[8636] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=d934c583-6554-9ea8-9026-f589e3fe974e

  0 passing (5m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



detox[8636] ERROR: [exec.js/EXEC_FAIL, #9] "/Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk" failed with code = 1, stdout and stderr:

detox[8636] ERROR: [exec.js/EXEC_FAIL, #9] 
detox[8636] ERROR: [exec.js/EXEC_FAIL, #9] adb: failed to install /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk: 
detox[8636] ERROR: [index.js/DETOX_INIT_ERROR] 
 { Error: Command failed: /Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk
adb: failed to install /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk:  `/Users/usr/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk` (exited with error code 1)
    at callback (/Users/usr/agent/2.144.0/work/1/s/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  name: 'ChildProcessError',
  code: 1,
  childProcess: 
   { ChildProcess: { [Function: ChildProcess] super_: [Object] },
     fork: [Function],
     _forkChild: [Function],
     exec: [Function],
     execFile: [Function],
     spawn: [Function],
     spawnSync: [Function: spawnSync],
     execFileSync: [Function: execFileSync],
     execSync: [Function: execSync] },
  stdout: '',
  stderr: 'adb: failed to install /Users/usr/agent/2.144.0/work/1/s/android/app/build/outputs/apk/debug/app-debug.apk: ' }
detox[8636] ERROR: [EmulatorTelnet.js/TELNET_ERROR] connect ECONNREFUSED 127.0.0.1:5554
  err: Error: connect ECONNREFUSED 127.0.0.1:5554
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
child_process.js:634
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose  --cleanup  --debug-synchronization 1000 --grep :ios: --invert     --artifacts-location "artifacts/android.emu.debug.2018-12-26 13-59-47Z" 
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at runMocha (/Users/usr/agent/2.144.0/work/1/s/node_modules/detox/local-cli/detox-test.js:129:6)
    at run (/Users/usr/agent/2.144.0/work/1/s/node_modules/detox/local-cli/detox-test.js:82:7)
    at Object.<anonymous> (/Users/usr/agent/2.144.0/work/1/s/node_modules/detox/local-cli/detox-test.js:217:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
``` 
But installing apk via adb worked fine `$ANDROID_HOME/platform-tools/adb install app-debug.apk`

**Comment by rotemmiz** [comment]
@denis-panov this seems to be a different issue in your second comment. Please provide a more detailed information about your CI, ADB version, emulator version, and open a different issue for the second one.

If this happens on Travis/circle or any other SaaS CI please provide a reproducable project.
