### ISSUE TITLE
Can't install app with Detox, but the path is correct

### ISSUE THREAD

**Issue by pauldcollins** [wix/Detox#1108]
#### Description
I hope I'm posting in the right place, it's an issue with setting up.... I've installed Detox with Jest and tried to run the initial tests. The tests are failing because it can't find my app, even though the path is definitely correct. It opens the iOS simulator, but it can't install the app. I've searched for anyone experiencing the same problem, but not luck. I've tried reinstalling `node_modules`, yarn, npm, etc, but can't get it to resolve, still no luck. I've also tried moving `jest` and `detox` from `devDependencies` into `dependencies`, but that didn't work either. 

Here is my `package.json`, with the correct path:

```
  "detox": {
    "test-runner": "jest",
    "specs": "e2e",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/[my-app]",
        "build": "xcodebuild -workspace ios/[my-app].xcworkspace -scheme [my-app] -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  },
```

#### Steps to Reproduce

Here is the relevant output when I run `detox test`.

**The first test that fails, based on not installing the app**

```
detox test
configuration="ios.sim.debug" artifactsLocation="artifacts/ios.sim.debug.2019-01-04 07-35-29Z" node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
detox[37365] INFO:  [DetoxServer.js] server listening on localhost:64138...
 FAIL  e2e/firstTest.spec.js (6.065s)
  Example
    ✕ should have welcome screen (6ms)

  ● Example › should have welcome screen

    ChildProcessError: Command failed: /usr/bin/xcrun simctl install 010FB665-B094-4250-82F8-1D9508B20FED "/Users/[my-user-name]/Sites/app/ios/build/Build/Products/Debug-iphonesimulator/[my-app].app"
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
    Failed to install the requested application
    An application bundle was not found at the provided path.
    Provide a valid path to the desired application bundle.
     `/usr/bin/xcrun simctl install 010FB665-B094-4250-82F8-1D9508B20FED "/Users/[my-user-name]/Sites/app/ios/build/Build/Products/Debug-iphonesimulator/[my-app].app"` (exited with error code 2)

      at callback (../node_modules/child-process-promise/lib/index.js:33:27)
```

And the main error text:

```
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
detox[37365] ERROR: [exec.js/EXEC_FAIL, #4] "/usr/bin/xcrun simctl install 010FB665-B094-4250-82F8-1D9508B20FED "/Users/[my-user-name]/Sites/app/ios/build/Build/Products/Debug-iphonesimulator/[my-app].app"" failed with code = 2, stdout and stderr:

detox[37365] ERROR: [exec.js/EXEC_FAIL, #4]
detox[37365] ERROR: [exec.js/EXEC_FAIL, #4] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.

detox[37365] ERROR: [index.js/DETOX_INIT_ERROR]
 { ChildProcessError: Command failed: /usr/bin/xcrun simctl install 010FB665-B094-4250-82F8-1D9508B20FED "/Users/[my-user-name]/Sites/app/ios/build/Build/Products/Debug-iphonesimulator/[my-app].app"
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
 `/usr/bin/xcrun simctl install 010FB665-B094-4250-82F8-1D9508B20FED "/Users/[my-user-name]/Sites/app/ios/build/Build/Products/Debug-iphonesimulator/[my-app].app` (exited with error code 2)
    at callback (/Users/[my-user-name]/Sites/app/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  name: 'ChildProcessError',
  code: 2,
  childProcess:
   { ChildProcess: { [Function: ChildProcess] super_: [Object] },
     fork: [Function],
     _forkChild: [Function],
     exec: [Function],
     execFile: [Function],
     spawn: [Function],
     spawnSync: [Function: spawnSync],
     execFileSync: [Function: execFileSync],
     execSync: [Function: execSync] },
  stdout: '',
  stderr: 'An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):\nFailed to install the requested application\nAn application bundle was not found at the provided path.\nProvide a valid path to the desired application bundle.\n' }
child_process.js:644
    throw err;
    ^
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.1.2
* React Native: 0.55.4
* Node: 8.10.0
* Device: iPhone 7 Simulator
* Xcode: 10.1
* macOS: 10.13.6 (High Sierra)

#### Device and verbose Detox logs

Please let me know if you need anything else. Thanks for any help.

**Comment by karanjthakkar** [comment]
@pauldcollins Have you run `detox build` before running the test? Do you see the application binary at this path: `/Users/[my-user-name]/Sites/app/ios/build/Build/Products/Debug-iphonesimulator/`?
