### ISSUE TITLE
SimulatorKit.SimDisplayScreenshotWriter.ScreenshotError when taking screenshot

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1118]
It seems, from time to time, that when Detox attempts to take a screenshot, there is a failure on simctl part to take this screenshot.

Two things:

- We shouldn't fail a test if artifacts fail–they are nice to have but not a must, specially on screenshots
- From the log below, it seems screenshot is taken very soon after install; this could be the issue why simctl fails to take a screenshot:

```
[production E2E] detox[60505] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:65162
[17:03:18][production E2E] detox[60505] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=a6dd9a00-0898-c9fb-e71d-d6fc8d1ecedd
[17:03:18][production E2E] detox[60505] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=a6dd9a00-0898-c9fb-e71d-d6fc8d1ecedd
[17:03:18][production E2E] detox[60505] DEBUG: [exec.js/EXEC_CMD, #0] applesimutils --list --byType "iPhone X" --byOS "iOS 11.3"
[17:03:18][production E2E] detox[60505] DEBUG: [exec.js/EXEC_TRY, #0] Searching for device matching iPhone X, iOS 11.3...
[17:03:19][production E2E] detox[60505] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byId "6D0365DB-F632-4239-8E07-23E3925215BB"
[17:03:24][production E2E] detox[60505] DEBUG: [exec.js/EXEC_CMD, #2] /usr/bin/xcrun simctl uninstall 6D0365DB-F632-4239-8E07-23E3925215BB ent.wix.ios.dev
[17:03:24][production E2E] detox[60505] DEBUG: [exec.js/EXEC_TRY, #2] Uninstalling ent.wix.ios.dev...
[17:03:31][production E2E] detox[60505] DEBUG: [exec.js/EXEC_SUCCESS, #2] ent.wix.ios.dev uninstalled
[17:03:31][production E2E] detox[60505] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl install 6D0365DB-F632-4239-8E07-23E3925215BB "/Users/builduser/buildAgent/work/f290b15cabe27d46/build/e2e.ios/devRelease/WixOneApp.app"
[17:03:31][production E2E] detox[60505] DEBUG: [exec.js/EXEC_TRY, #3] Installing /Users/builduser/buildAgent/work/f290b15cabe27d46/build/e2e.ios/devRelease/WixOneApp.app...
[17:04:30][production E2E] detox[60505] DEBUG: [exec.js/EXEC_SUCCESS, #3] /Users/builduser/buildAgent/work/f290b15cabe27d46/build/e2e.ios/devRelease/WixOneApp.app installed
[17:04:30][production E2E] Regression - First Time Screen (3m:33s)
[17:04:30][Regression - First Time Screen] First time screen and video view (3m:33s)
[17:04:30][First time screen and video view] [Test Output]
detox[60505] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl io 6D0365DB-F632-4239-8E07-23E3925215BB screenshot "/Users/builduser/buildAgent/temp/buildTmp/280fbf9f-1d6c-4bad-a30c-ea9b307c1000.png"
detox[60505] ERROR: [exec.js/EXEC_FAIL, #4] "/usr/bin/xcrun simctl io 6D0365DB-F632-4239-8E07-23E3925215BB screenshot "/Users/builduser/buildAgent/temp/buildTmp/280fbf9f-1d6c-4bad-a30c-ea9b307c1000.png"" failed with code = 2, stdout and stderr:

detox[60505] ERROR: [exec.js/EXEC_FAIL, #4] 
detox[60505] ERROR: [exec.js/EXEC_FAIL, #4] An error was encountered processing the command (domain=SimulatorKit.SimDisplayScreenshotWriter.ScreenshotError, code=2):
Error creating the image

detox[60505] ERROR: [ArtifactsManager.js/PLUGIN_ERROR] Caught exception inside function call: SimulatorScreenshotter.onBeforeEach({ title: 'First time screen and video view',
  fullName: 'Regression - First Time Screen First time screen and video view',
  status: 'running' })
  err: ChildProcessError: Command failed: /usr/bin/xcrun simctl io 6D0365DB-F632-4239-8E07-23E3925215BB screenshot "/Users/builduser/buildAgent/temp/buildTmp/280fbf9f-1d6c-4bad-a30c-ea9b307c1000.png"
  An error was encountered processing the command (domain=SimulatorKit.SimDisplayScreenshotWriter.ScreenshotError, code=2):
  Error creating the image
   `/usr/bin/xcrun simctl io 6D0365DB-F632-4239-8E07-23E3925215BB screenshot "/Users/builduser/buildAgent/temp/buildTmp/280fbf9f-1d6c-4bad-a30c-ea9b307c1000.png"` (exited with error code 2)
      at callback (/Users/builduser/buildAgent/work/f290b15cabe27d46/node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:283:5)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:915:16)
      at Socket.stream.socket.on (internal/child_process.js:336:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:561:12)
[MOCK SERVER] listening on port 2480
```

CC @viktorijasujetaite @d4vidi

**Comment by LeoNatan** [comment]
When searching for "SimulatorKit.SimDisplayScreenshotWriter.ScreenshotError" on the internets, it always seems Detox related.

#864 seems related

Could be just a bug in simctl. We should not be blocking tests on such failures.

**Comment by noomorph** [comment]
It does not make tests fail, it only prints an error to the log. Search the reason for the failing test elsewhere. At most, it might be a symptom of a simulator issue, etc.

**Comment by LeoNatan** [comment]
Seems like CI failure is unrelated to screenshot error.
