### ISSUE TITLE
Support for .ipa

### ISSUE THREAD

**Issue by justinmakaila** [wix/Detox#1124]
#### Description

We're currently using detox to test our react-native application and fastlane to distribute on CI. I went to update our `build` configuration to use our `fastlane` config, which under the hood uses [`build_app`](https://docs.fastlane.tools/actions/build_app/). I've attempted to use the `ipa` output from the `build_app` command to no avail with `Detox`. This has forced me to manually implement the `xcodebuild` step provided by fastlane to output an `app` file instead.

FWIW, the config docs say that you can point to an `ipa`.

The logs of the error produced when passing an `ipa` are provided in the below section.

#### Steps to Reproduce

Config in package.json:
```js
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/[Redacted}.app",
        "build": "fastlane ios ui configuration:Release --env production",
        "type": "ios.simulator",
        "name": "iPhone 8"
      }
```
where `fastlane iOS ui` is a lane that takes in some parameters, and then would run `build_app` to output a signed `ipa` to a location.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: `9.1.2`
* React Native: `0.57.1`
* Node: `10.11.0
* Device: `iPhone 8`
* Xcode: `10.1/10B61
* macOS: `10.13.6`

#### Device and verbose Detox logs

```
detox[23913] ERROR: [index.js/DETOX_INIT_ERROR] 
 Error: field CFBundleIdentifier not found inside Info.plist of app binary at <projectDir>/packages/<packageName>/ios/build/Build/Products/Release-iphonesimulator/[Redacted].ipa
    at SimulatorDriver.getBundleIdFromBinary (<projectDir>/packages/<packageName>/node_modules/detox/src/devices/drivers/SimulatorDriver.js:70:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
child_process.js:651
    throw err;
    ^

Error: Command failed: node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at runJest (<projectDir>/packages/<packageName>/node_modules/detox/local-cli/detox-test.js:154:6)
    at run (<projectDir>/packages/<packageName>/node_modules/detox/local-cli/detox-test.js:85:7)
    at Object.<anonymous> (<projectDir>/packages/<packageName>/node_modules/detox/local-cli/detox-test.js:217:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

**Comment by LeoNatan** [comment]
You are confusing things. An `.ipa` is an archive, basically a zip file, of an `.app`, which in turn is the main bundle of you app. You can extract the `.ipa` file to disk, and point Detox to the `.app` inside.

However, this will most likely not work in your case. Normally, `.ipa` contains only `arm*` architecture, ready for devices. Detox runs on simulators, so you need `x86-64` architecture. It wouldn't make sense to have `x86-64` inside an `.ipa` archive.

You should make sure your build tools create valid `x86-64` `.app` bundle. If the tools then wrap that bundle in an `.ipa` archive, you can always use `unzip` to extract it.
