### ISSUE TITLE
com.wix.detox.espresso.ReactNativeNetworkIdlingResource

### ISSUE THREAD

**Issue by zeeshan-plero** [wix/Detox#1154]
*Detox: 10.0.3
* React Native: 0.56
* Node: 9.4.0
* Device: android

Having the issue while calling any action on element. All testing are running successfully for IOS but for android its not working

Error: Wait for [com.wix.detox.espresso.ReactNativeNetworkIdlingResource] to become idle timed out

 await element(by.id('onboarding-button')).tap();
Error: Wait for [com.wix.detox.espresso.ReactNativeNetworkIdlingResource] to become idle timed out

**Comment by Fghurayri** [comment]
I am having the exact same issue.

* React Native: 0.55.4
* Detox: 10.0.10
* Device: Android
* Node: v8.12.0
* Host OS: Linux solus 4.20.10-111.current

**Comment by Fghurayri** [comment]
Here is the output with the `--loglevel trace` command:

```
 faisal  ~/Code   develop ● ?  detox test --loglevel trace -c android.emu.debug                                                                                                 1 ↵
configuration="android.emu.debug" loglevel="trace" artifactsLocation="artifacts/android.emu.debug.2019-03-04 14-25-50Z" node_modules/.bin/jest "e2e" --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$' 
detox[21571] INFO:  [DetoxServer.js] server listening on localhost:46115...
detox[21571] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:46115
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"25d98262-e9bc-5b85-e5ad-8699c3dc12d8","role":"tester"},"messageId":0}
detox[21571] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8
detox[21571] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"25d98262-e9bc-5b85-e5ad-8699c3dc12d8","role":"tester"},"messageId":0}
 
detox[21571] DEBUG: [exec.js/EXEC_CMD, #0] /home/faisal/Android/Sdk/emulator/emulator -list-avds --verbose
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #0] Nexus_5X_API_23
Pixel_2_API_28

detox[21571] DEBUG: [exec.js/EXEC_CMD, #1] /home/faisal/Android/Sdk/platform-tools/adb  devices
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #1] List of devices attached
emulator-5554	device


detox[21571] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 5554, host: localhost
detox[21571] DEBUG: [exec.js/EXEC_CMD, #2] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #2] 1

detox[21571] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-5554' })
detox[21571] DEBUG: [exec.js/EXEC_CMD, #3] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #3] 28

detox[21571] DEBUG: [exec.js/EXEC_CMD, #4] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #4]   mWakefulness=Awake
  mWakefulnessChanging=false
  mWakeLockSummary=0x0
  mUserActivitySummary=0x4
  mWakeUpWhenPluggedOrUnpluggedConfig=false
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false

detox[21571] DEBUG: [exec.js/EXEC_CMD, #5] /home/faisal/Android/Sdk/build-tools/28.0.3/aapt dump badging "/home/faisal/Zain/Services/waawMobile/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #5] package: name='com.sa.maana' versionCode='30' versionName='2.1.0' platformBuildVersionName='8.1.0'

detox[21571] DEBUG: [exec.js/EXEC_CMD, #6] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.sa.maana"
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #6] package:com.sa.maana.test
package:com.sa.maana

detox[21571] DEBUG: [exec.js/EXEC_CMD, #7] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 uninstall com.sa.maana
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #7] Success

detox[21571] DEBUG: [exec.js/EXEC_CMD, #8] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.sa.maana.test"
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #8] package:com.sa.maana.test

detox[21571] DEBUG: [exec.js/EXEC_CMD, #9] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 uninstall com.sa.maana.test
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #9] Success

detox[21571] DEBUG: [exec.js/EXEC_CMD, #10] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 install -r -g -t /home/faisal/Zain/Services/waawMobile/android/app/build/outputs/apk/debug/app-debug.apk
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #10] Success

detox[21571] DEBUG: [exec.js/EXEC_CMD, #11] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 install -r -g -t /home/faisal/Zain/Services/waawMobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #11] Success

detox[21571] DEBUG: [exec.js/EXEC_CMD, #12] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "am force-stop com.sa.maana"
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #12] 
detox[21571] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({ deviceId: 'emulator-5554',
  bundleId: 'com.sa.maana',
  launchArgs: 
   { '-e detoxServer': 'ws://localhost:46115',
     '-e detoxSessionId': '25d98262-e9bc-5b85-e5ad-8699c3dc12d8' } })
detox[21571] DEBUG: [exec.js/EXEC_CMD, #13] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "pm list instrumentation"
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #13] instrumentation:com.sa.maana.test/android.support.test.runner.AndroidJUnitRunner (target=com.sa.maana)
instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)

detox[21571] DEBUG: [exec.js/SPAWN_CMD, #14] [pid=21631] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r "-e detoxServer ws://localhost:46115 -e detoxSessionId 25d98262-e9bc-5b85-e5ad-8699c3dc12d8" -e debug false com.sa.maana.test/android.support.test.runner.AndroidJUnitRunner
detox[21571] DEBUG: [exec.js/EXEC_CMD, #15] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell "ps | grep \"com\.sa\.maana$\""
detox[21571] TRACE: [exec.js/EXEC_SUCCESS, #15] u0_a212       9277  1715 1471992 107852 0                   0 R com.sa.maana

detox[9277] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({ deviceId: 'emulator-5554',
  bundleId: 'com.sa.maana',
  launchArgs: 
   { '-e detoxServer': 'ws://localhost:46115',
     '-e detoxSessionId': '25d98262-e9bc-5b85-e5ad-8699c3dc12d8' },
  pid: 9277 })
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [exec.js/SPAWN_STDOUT, #14] INSTRUMENTATION_STATUS: class=com.sa.maana.DetoxTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.sa.maana.DetoxTest:
INSTRUMENTATION_STATUS: test=runDetoxTests

detox[21571] TRACE: [exec.js/SPAWN_STDOUT, #14] INSTRUMENTATION_STATUS_CODE: 1

detox[21571] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8
detox[21571] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}
 
detox[21571] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeAll()
detox[21571] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "First Passing Test! should have welcome screen"
detox[21571] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeEach({ title: 'should have welcome screen',
  fullName: 'First Passing Test! should have welcome screen',
  status: 'running' })
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"reactNativeReload","params":{},"messageId":-1000}
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=tester action=reactNativeReload (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}
 
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxAssertion"},"method":"assertMatcher","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["WelcomeScreen"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForSufficientlyVisible","args":[]}}]},"messageId":1}
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
 FAIL  e2e/firstTest.spec.js (63.579s)
  First Passing Test!
    ✕ should have welcome screen (28192ms)

  ● First Passing Test! › should have welcome screen

    Error: Wait for [com.wix.detox.espresso.ReactNativeNetworkIdlingResource] to become idle timed out

       5 | 
       6 |   it('should have welcome screen', async () => {
    >  7 |     await expect(element(by.id('WelcomeScreen'))).toBeVisible();
       8 |     return true;
       9 |   });
      10 | });
      
      at Client.execute (../node_modules/detox/src/client/Client.js:80:28)
      at InvocationManager.execute (../node_modules/detox/src/invoke.js:11:33)
      at MatcherAssertionInteraction.execute (../node_modules/detox/src/android/expect.js:122:29)
      at ExpectElement.toBeVisible (../node_modules/detox/src/android/expect.js:262:87)
      at Object._callee2$ (firstTest.spec.js:7:51)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:152:20)
      at ../node_modules/regenerator-runtime/runtime.js:187:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:186:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:209:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at Object.<anonymous>.runtime.async (../node_modules/regenerator-runtime/runtime.js:233:14)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        63.628s, estimated 64s
Ran all test suites matching /e2e/i with tests matching "^((?!:ios:).)*$".
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=testee action=error (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":1,"type":"error","params":{"error":"Wait for [com.wix.detox.espresso.ReactNativeNetworkIdlingResource] to become idle timed out"}}
 
detox[21571] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "First Passing Test! should have welcome screen"
detox[21571] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterEach({ title: 'should have welcome screen',
  fullName: 'First Passing Test! should have welcome screen',
  status: 'failed' })
detox[21571] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"cleanup","params":{"stopRunner":false},"messageId":2}
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=tester action=cleanup (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [DetoxServer.js/MESSAGE] role=testee action=cleanupDone (sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8)
detox[21571] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":2,"type":"cleanupDone","params":{}}
 
detox[21571] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 21631]: /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:46115 -e detoxSessionId 25d98262-e9bc-5b85-e5ad-8699c3dc12d8 -e debug false com.sa.maana.test/android.support.test.runner.AndroidJUnitRunner
detox[21571] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8
detox[21571] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 21631]: /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:46115 -e detoxSessionId 25d98262-e9bc-5b85-e5ad-8699c3dc12d8 -e debug false com.sa.maana.test/android.support.test.runner.AndroidJUnitRunner
detox[21571] TRACE: [exec.js/SPAWN_END, #14] /home/faisal/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r "-e detoxServer ws://localhost:46115 -e detoxSessionId 25d98262-e9bc-5b85-e5ad-8699c3dc12d8" -e debug false com.sa.maana.test/android.support.test.runner.AndroidJUnitRunner terminated with SIGINT
detox[21571] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=25d98262-e9bc-5b85-e5ad-8699c3dc12d8
child_process.js:645
    throw err;
    ^

Error: Command failed: node_modules/.bin/jest "e2e" --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$' 
    at checkExecSyncError (child_process.js:602:13)
    at Object.execSync (child_process.js:642:13)
    at runJest (/home/faisal/Zain/Services/waawMobile/node_modules/detox/local-cli/detox-test.js:166:6)
    at run (/home/faisal/Zain/Services/waawMobile/node_modules/detox/local-cli/detox-test.js:86:7)
    at Object.<anonymous> (/home/faisal/Zain/Services/waawMobile/node_modules/detox/local-cli/detox-test.js:229:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```
