### ISSUE TITLE
Detox error running tests on real Android device

### ISSUE THREAD

**Issue by quirimmo** [wix/Detox#1174]
#### Description

I am trying to run some simple test on my real Android device, attached with USB to my machine. 

If I run the same tests through the emulator everything works fine, but with the real android device I get the following errors:

>  Example › should show the welcome screen
> 
>     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
> 
>       at mapper (../node_modules/jest-jasmine2/build/queue_runner.js:41:52)
> 
>   ● Example › should show the welcome screen
> 
>     ReferenceError: device is not defined
> 
>        5 | describe('Example', () => {
>        6 |   beforeAll(async () => {
>     >  7 |     await device.launchApp({ delete: true, newInstance: true });
>          |     ^
>        8 |   });
>        9 |
>       10 |   it('should show the welcome screen', async () => {
> 
>       at Object.beforeAll (firstTest.spec.js:7:5)

This is my detox config:

```
"android.emu.debug-original-device-win": {
        "binaryPath": "android/app/build/outputs/apk/dev/debug/app-dev-debug.apk",
        "build": "pushd android && gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
        "type": "android.attached",
        "name": "73QDU17803001744"
      },
```

The app runs correctly on my device, but the tests do not start at all.

I've tried to run the tests using the `RCT_METRO_PORT=8099` env variable and doing the `adb reverse tcp:8099 tcp:8099`, but no luck. 

What is this issue related to? And how can I get it through? 

Thanks a lot

#### Steps to Reproduce
The official page related to Android works totally fine with emulator. 
When I try to run tests on my real Android device, I get the issue above. 

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 10.0.9
* React Native: 0.57.7
* Node: 8.11.1
* Device: Honor 8

#### Device and verbose Detox logs

> $ set RCT_METRO_PORT=8099&& detox test --configuration android.emu.debug-original-device-win -l verbose
> configuration="android.emu.debug-original-device-win" loglevel="verbose" artifactsLocation="artifacts\\android.emu.debug-original-device-win.2019-02-26 14-24-33Z" node_modules\.bin\jest "e2e" --config=e2e/config.json --maxWorkers=1 "--testNamePattern=^((?!:ios:).)*$"
> detox[13064] INFO:  [DetoxServer.js] server listening on localhost:61909...
> detox[13064] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:61909
> detox[13064] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=39bf037f-902b-c3fb-79b6-284793175467
> detox[13064] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=39bf037f-902b-c3fb-79b6-284793175467
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #0] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb  devices
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #1] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "getprop ro.build.version.sdk"
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #2] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #3] C:\Users\quiri\AppData\Local\Android\Sdk\build-tools\28.0.3\aapt dump badging "E:\Development\poinz\poinz-app\android\app\build\outputs\apk\dev\debug\app-dev-debug.apk" | findstr /C:"package: name="
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #4] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "pm list packages ch.poinz.dev"
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #5] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 uninstall ch.poinz.dev
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #6] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "pm list packages ch.poinz.dev.test"
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #7] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 uninstall ch.poinz.dev.test
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #8] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 install -r -g -t E:\Development\poinz\poinz-app\android\app\build\outputs\apk\dev\debug\app-dev-debug.apk
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #9] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 install -r -g -t E:\Development\poinz\poinz-app\android\app\build\outputs\apk\androidTest\dev\debug\app-dev-debug-androidTest.apk
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #10] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "am force-stop ch.poinz.dev"
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #11] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "pm list instrumentation"
> detox[13064] DEBUG: [exec.js/SPAWN_CMD, #12] [pid=11416] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell am instrument -w -r "-e detoxServer ws://localhost:61909 -e detoxSessionId 39bf037f-902b-c3fb-79b6-284793175467" -e debug false ch.poinz.dev.test/android.support.test.runner.AndroidJUnitRunner
> detox[13064] DEBUG: [exec.js/EXEC_CMD, #13] C:\Users\quiri\AppData\Local\Android\Sdk\platform-tools\adb -s 73QDU17803001744 shell "ps | grep \"ch\.poinz\.dev$\""
> detox[13064] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=39bf037f-902b-c3fb-79b6-284793175467)
>  FAIL  e2e/firstTest.spec.js (121.725s)
>   Example
>     × should show the welcome screen
>     × should close the welcome screen and show the home screen
>     × should open the deep link https://poinz.page.link/rewards
> 
>   ● Example › should show the welcome screen
> 
>     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
> 
>       at mapper (../node_modules/jest-jasmine2/build/queue_runner.js:41:52)
> 
>   ● Example › should show the welcome screen
> 
>     ReferenceError: device is not defined
> 
>        5 | describe('Example', () => {
>        6 |   beforeAll(async () => {
>     >  7 |     await device.launchApp({ delete: true, newInstance: true });
>          |     ^
>        8 |   });
>        9 |
>       10 |   it('should show the welcome screen', async () => {
> 
>       at Object.beforeAll (firstTest.spec.js:7:5)
> 
>   ● Example › should show the welcome screen
> 
>     ReferenceError: waitFor is not defined
> 
>        9 |
>       10 |   it('should show the welcome screen', async () => {
>     > 11 |     await waitFor(element(by.id('welcome'))).toBeVisible().withTimeout(5000);
>          |     ^
>       12 |     await expect(element(by.id('welcome'))).toBeVisible();
>       13 |   });
>       14 |
> 
>       at Object.it (firstTest.spec.js:11:5)
> 
>   ● Example › should close the welcome screen and show the home screen
> 
>     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
> 
>       at mapper (../node_modules/jest-jasmine2/build/queue_runner.js:41:52)
> 
>   ● Example › should close the welcome screen and show the home screen
> 
>     ReferenceError: device is not defined
> 
>        5 | describe('Example', () => {
>        6 |   beforeAll(async () => {
>     >  7 |     await device.launchApp({ delete: true, newInstance: true });
>          |     ^
>        8 |   });
>        9 |
>       10 |   it('should show the welcome screen', async () => {
> 
>       at Object.beforeAll (firstTest.spec.js:7:5)
> 
>   ● Example › should close the welcome screen and show the home screen
> 
>     ReferenceError: element is not defined
> 
>       14 |
>       15 |   it('should close the welcome screen and show the home screen', async () => {
>     > 16 |     await element(by.label('terms')).tap();
>          |     ^
>       17 |     await element(by.label('close')).tap();
>       18 |     await waitFor(element(by.id('home'))).toBeVisible().withTimeout(5000);
>       19 |     await expect(element(by.id('home'))).toBeVisible();
> 
>       at Object.it (firstTest.spec.js:16:5)
> 
>   ● Example › should open the deep link https://poinz.page.link/rewards
> 
>     Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
> 
>       at mapper (../node_modules/jest-jasmine2/build/queue_runner.js:41:52)
> 
>   ● Example › should open the deep link https://poinz.page.link/rewards
> 
>     ReferenceError: device is not defined
> 
>        5 | describe('Example', () => {
>        6 |   beforeAll(async () => {
>     >  7 |     await device.launchApp({ delete: true, newInstance: true });
>          |     ^
>        8 |   });
>        9 |
>       10 |   it('should show the welcome screen', async () => {
> 
>       at Object.beforeAll (firstTest.spec.js:7:5)
> 
>   ● Example › should open the deep link https://poinz.page.link/rewards
> 
>     ReferenceError: device is not defined
> 
>       21 |
>       22 |   it('should open the deep link https://poinz.page.link/rewards', async () => {
>     > 23 |     await device.relaunchApp({ url: 'https://poinz.page.link/rewards' });
>          |     ^
>       24 |     await waitFor(element(by.label('deals'))).toBeVisible().withTimeout(20000);
>       25 |     await expect(element(by.label('deals'))).toBeVisible();
>       26 |   });
> 
>       at Object.it (firstTest.spec.js:23:5)
> 
> Test Suites: 1 failed, 1 total
> Tests:       3 failed, 3 total
> Snapshots:   0 total
> Time:        121.806s, estimated 122s

**Comment by quirimmo** [comment]
I had to do the following steps in order to make it work. Posting it hoping it will be helpful for someone else .

1. In the detox config inside your `package.json` , add the following:

```
"session": {
      "sessionId": "manualsession",
      "server": "ws://192.168.1.10:8099" // ip of your machine where detox is running
    },
```
2. Start the detox server on your machine in another shell through the command:

`detox run-server`

You should see an output saying:

> [DetoxServer.js] server listening on localhost:8099...

3. In your script for running `detox test`, specify the env variable pointing to 8099 port `RCT_METRO_PORT=8099`

4. Run `adb reverse tcp:8099 tcp:8099`

You should now be able to run your tests on your attached device too. 

Closing the issue as fixed with the above steps.
