### ISSUE TITLE
Example demo-react-native tests failing on Windows 10 and physical Android device.

### ISSUE THREAD

**Issue by geomih** [wix/Detox#1175]
#### Description
I tried to run the demo-react-native example. The app is installed and runs correctly but the tests are failing even after using one of the suggestions in #1100 .

#### Steps to Reproduce
1. I created my own configuration for Windows
```
  "android.att.debug": {
    "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
    "build": "cd android && gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd..",
    "type": "android.attached",
    "name": "d0edde7d"
  }
```
2. Built config with ```detox build --configuration android.att.debug```
3. Start packager ```npm run start```
4. Run test ```detox test --configuration android.att.debug -l verbose```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 10.0.11
* React Native: 0.51.1
* Node: v11.7.0
* Device: SM-T590
* adb: Android Debug Bridge version 1.0.40 Version 4986621
* Android Version: 8.1.0 (API 27)

#### Device and verbose Detox logs
After adding ```log[level]({ event: 'EXEC_FAIL', stdout: true }, err);``` at exec.js:35
```C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native>detox test --configuration android.att.debug -l verbose --reuse
node_modules\.bin\mocha e2e --opts e2e/mocha.opts --configuration android.att.debug --loglevel verbose   --reuse  --grep :ios: --invert     --artifacts-location "artifacts\android.att.debug.2019-02-26 14-19-27Z"


detox[17088] INFO:  [DetoxServer.js] server listening on localhost:51036...
detox[17088] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:51036
detox[17088] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=d6138acc-1257-981a-866e-368285c4d349
detox[17088] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=d6138acc-1257-981a-866e-368285c4d349
detox[17088] DEBUG: [exec.js/EXEC_CMD, #0] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb  devices
detox[17088] DEBUG: [exec.js/EXEC_CMD, #1] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "getprop ro.build.version.sdk"
detox[17088] DEBUG: [exec.js/EXEC_CMD, #2] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[17088] DEBUG: [exec.js/EXEC_CMD, #3] C:\Users\gmichail\AppData\Local\Android\Sdk\build-tools\28.0.3\aapt dump badging "C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native\android\app\build\outputs\apk\debug\app-debug.apk" | findstr /C:"package: na
me="
detox[17088] DEBUG: [exec.js/EXEC_CMD, #4] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "am force-stop com.detox.rn.example"
detox[17088] DEBUG: [exec.js/EXEC_CMD, #5] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "pm list instrumentation"
detox[17088] DEBUG: [exec.js/SPAWN_CMD, #6] [pid=4720] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell am instrument -w -r "-e detoxServer ws://localhost:51036 -e detoxSessionId d6138acc-1257-981a-866e-368285c4d349" -e debug false c
om.detox.rn.example.test/android.support.test.runner.AndroidJUnitRunner
detox[17088] DEBUG: [exec.js/EXEC_CMD, #7] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "ps | grep \"com\.detox\.rn\.example$\""
detox[17088] ERROR: [exec.js/EXEC_FAIL, #7] "C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "ps | grep \"com\.detox\.rn\.example$\""" failed with code = 1, stdout and stderr:

detox[17088] ERROR: [exec.js/EXEC_FAIL, #7] { ChildProcessError: Command failed: C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "ps | grep \"com\.detox\.rn\.example$\""
 `C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "ps | grep \"com\.detox\.rn\.example$\""` (exited with error code 1)
    at callback (C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native\node_modules\child-process-promise\lib\index.js:33:27)
    at ChildProcess.exithandler (child_process.js:304:5)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  name: 'ChildProcessError',
  code: 1,
  childProcess:
   { ChildProcess: [Function: ChildProcess],
     fork: [Function: fork],
     _forkChild: [Function: _forkChild],
     exec: [Function: exec],
     execFile: [Function: execFile],
     spawn: [Function: spawn],
     spawnSync: [Function: spawnSync],
     execFileSync: [Function: execFileSync],
     execSync: [Function: execSync] },
  stdout: '',
  stderr: '' }
detox[17088] ERROR: [exec.js/EXEC_FAIL, #7]
detox[17088] ERROR: [exec.js/EXEC_FAIL, #7]
detox[17088] DEBUG: [exec.js/EXEC_CMD, #8] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "ps | grep \"com\.detox\.rn\.example$\""
detox[17088] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=d6138acc-1257-981a-866e-368285c4d349)
```

I was able to avoid this error by using the suggestion at  #1100 and setting in file AdroidDriver.js ```await sleep(3000);``` and now I am getting this:

```
C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native>detox test --configuration android.att.debug -l verbose --reuse
node_modules\.bin\mocha e2e --opts e2e/mocha.opts --configuration android.att.debug --loglevel verbose   --reuse  --grep :ios: --invert     --artifacts-location "artifacts\android.att.debug.2019-02-26 14-16-15Z"


detox[11864] INFO:  [DetoxServer.js] server listening on localhost:50978...
detox[11864] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50978
detox[11864] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=4c0180e3-6851-d70f-ef0c-a64654fd62c5
detox[11864] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=4c0180e3-6851-d70f-ef0c-a64654fd62c5
detox[11864] DEBUG: [exec.js/EXEC_CMD, #0] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb  devices
detox[11864] DEBUG: [exec.js/EXEC_CMD, #1] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "getprop ro.build.version.sdk"
detox[11864] DEBUG: [exec.js/EXEC_CMD, #2] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[11864] DEBUG: [exec.js/EXEC_CMD, #3] C:\Users\gmichail\AppData\Local\Android\Sdk\build-tools\28.0.3\aapt dump badging "C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native\android\app\build\outputs\apk\debug\app-debug.apk" | findstr /C:"package: na
me="
detox[11864] DEBUG: [exec.js/EXEC_CMD, #4] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "am force-stop com.detox.rn.example"
detox[11864] DEBUG: [exec.js/EXEC_CMD, #5] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "pm list instrumentation"
detox[11864] DEBUG: [exec.js/SPAWN_CMD, #6] [pid=8672] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell am instrument -w -r "-e detoxServer ws://localhost:50978 -e detoxSessionId 4c0180e3-6851-d70f-ef0c-a64654fd62c5" -e debug false c
om.detox.rn.example.test/android.support.test.runner.AndroidJUnitRunner
detox[11864] DEBUG: [exec.js/EXEC_CMD, #7] C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell "ps | grep \"com\.detox\.rn\.example$\""
detox[11864] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=4c0180e3-6851-d70f-ef0c-a64654fd62c5)
  1) "before all" hook

  0 passing (2m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



detox[11864] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 8672]: C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell am instrument -w -r -e detoxServer ws://localhost:50978 -e detoxSessionId 4c0180e3-6851-d70f-ef0c-a64654fd62c5 -e deb
ug false com.detox.rn.example.test/android.support.test.runner.AndroidJUnitRunner
detox[11864] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=4c0180e3-6851-d70f-ef0c-a64654fd62c5
detox[11864] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 8672]: C:\Users\gmichail\AppData\Local\Android\Sdk\platform-tools\adb -s d0edde7d shell am instrument -w -r -e detoxServer ws://localhost:50978 -e detoxSessionId 4c0180e3-6851-d70f-ef0c-a64654fd62c5 -e deb
ug false com.detox.rn.example.test/android.support.test.runner.AndroidJUnitRunner

  0 passing (2m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



child_process.js:665
    throw err;
    ^

Error: Command failed: node_modules\.bin\mocha e2e --opts e2e/mocha.opts --configuration android.att.debug --loglevel verbose   --reuse  --grep :ios: --invert     --artifacts-location "artifacts\android.att.debug.2019-02-26 14-16-15Z"
    at checkExecSyncError (child_process.js:625:11)
    at Object.execSync (child_process.js:662:13)
    at runMocha (C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native\node_modules\detox\local-cli\detox-test.js:140:6)
    at run (C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native\node_modules\detox\local-cli\detox-test.js:83:7)
    at Object.<anonymous> (C:\Users\gmichail\IdeaProjects\Detox\examples\demo-react-native\node_modules\detox\local-cli\detox-test.js:229:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by noomorph** [comment]
I'll take a look at it after I finish a couple of other pull requests.
