### ISSUE TITLE
Development script build.js was run on client machine

### ISSUE THREAD

**Issue by evgeni-wix** [wix/Detox#1182]
Saw this when running npm install:

```
detox@10.0.10 build /Users/evgenis/WebstormProjects/wix-one-app-engine/node_modules/detox
> node scripts/build.js


Packaging Detox iOS sources
child_process.js:642
   throw err;
   ^

Error: spawnSync ios/EarlGrey/Scripts/setup-earlgrey.sh ENOENT
   at Object.spawnSync (internal/child_process.js:998:20)
   at spawnSync (child_process.js:606:24)
   at Object.execFileSync (child_process.js:634:13)
   at sh (/Users/evgenis/WebstormProjects/wix-one-app-engine/node_modules/detox/scripts/utils.js:6:23)
   at packageIosSources (/Users/evgenis/WebstormProjects/wix-one-app-engine/node_modules/detox/scripts/pack_ios.js:10:3)
   at Object.<anonymous> (/Users/evgenis/WebstormProjects/wix-one-app-engine/node_modules/detox/scripts/build.js:6:3)
   at Module._compile (internal/modules/cjs/loader.js:721:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
   at Module.load (internal/modules/cjs/loader.js:620:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@10.0.10 build: `node scripts/build.js`
npm ERR! Exit status 1
```

**Comment by LeoNatan** [comment]
@rotemmiz Can you think of a reason why the dev script would run during `npm install`?

**Comment by LeoNatan** [comment]
I don't think we've seen a reproduction of this. Closing for now.
