### ISSUE TITLE
Detox init error in CircleCI.

### ISSUE THREAD

**Issue by matt-wright86** [wix/Detox#1191]
#### Description
When attempting to run tests in both CircleCI and TravisCI, we get a DETOX_INIT_ERROR. The tests run and pass locally every time.

#### Steps to Reproduce
pushing a branch to Github triggers the CircleCI to start the Detox test.

#### CircleCI config.yml
```
version: 2
jobs:
  build:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run:
          name: Install homebrew dependencies
          command: |
            brew tap wix/brew
            brew install applesimutils
      - run:
          name: Install local project dependencies and test
          command: |
            gem install xcpretty
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            cd ./RoobeeRestaurant
            nvm install 11.6.0
            nvm use 11.6.0
            yarn global add react-native-cli
            yarn global add detox-cli
            yarn install
            node node_modules/react-native/local-cli/cli.js start &
            detox build --configuration ios.sim.release
            detox test --platform ios --configuration ios.sim.release --cleanup --loglevel trace
```

#### Detox config in package.json 
```
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/RoobeeRestaurant.app",
        "build": "react-native run-ios --scheme 'RoobeeRestaurant (development)' --simulator 'iPad Air 2' --port 9091",
        "type": "ios.simulator",
        "name": "iPad Pro (10.5-inch)"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/RoobeeRestaurant.app",
        "build": "xcodebuild -project ios/RoobeeRestaurant.xcodeproj -scheme 'RoobeeRestaurant (development)' -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -UseNewBuildSystem=NO | xcpretty",
        "type": "ios.simulator",
        "name": "iPad Air 2"
      }
    },
    "test-runner": "jest"
  }
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 10.0.5
* React Native: 0.58.3
* Node: 11.6.0
* Device: iPad Air 2 (12.1)
* Xcode: 9.4.1
* macOS: macOS 10.13.3 (17D102)
  - https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-430/index.html

#### What we've tried
- Forcing 'use legacy build' with xcargs: "-UseModernBuildSystem=NO"
- Forcing 'use legacy build' with xcargs: "-UseNewBuildSystem=NO"
- Downgrading React Native version to 0.57.8
- Upgrading Xcode to version 10.1.0
  - https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-474/index.html

#### Device and verbose Detox logs
```
detox[51591] ERROR: [index.js/DETOX_INIT_ERROR] 
 Exception '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter' was thrown while invoking connect on target WebSocketModule with params (
    ...
detox[22659] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[22659] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41)
detox[22659] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41)
detox[22659] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41
detox[22659] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41
detox[22659] TRACE: [DetoxServer.js/MESSAGE] role=testee action=AppWillTerminateWithError (sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41)
detox[22659] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"AppWillTerminateWithError","messageId":-10000,"params":{"threadNumber":8,"errorDetails":"Exception '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil...\n(\n\t0   CoreFoundation                      0x000000010889412b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x0000000107186f41 objc_exception_throw + 48\n\t2   RoobeeRestaurant                    0x0000000105b26005 RCTFormatError + 0\n\t3   RoobeeRestaurant                    0x0000000105b80156 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 798\n\t4   RoobeeRestaurant                    0x0000000105b7fcbc ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78\n\t5   EarlGrey                            0x0000000116b3e082 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 50\n\t6   libdispatch.dylib                   0x000000010c80a177 _dispatch_call_block_and_release + 12\n\t7   libdispatch.dylib                   0x000000010c80b1ba _dispatch_client_callout + 8\n\t8   libdispatch.dylib                   0x000000010c812d3d _dispatch_queue_serial_drain + 654\n\t9   libdispatch.dylib                   0x000000010c8135a0 _dispatch_queue_invoke + 329\n\t10  libdispatch.dylib                   0x000000010c80fc97 _dispatch_queue_override_invoke + 477\n\t11  libdispatch.dylib                   0x000000010c815980 _dispatch_root_queue_drain + 568\n\t12  libdispatch.dylib                   0x000000010c8156ea _dispatch_worker_thread3 + 119\n\t13  libsystem_pthread.dylib             0x000000010ccca5a2 _pthread_wqthread + 1299\n\t14  libsystem_pthread.dylib             0x000000010ccca07d start_wqthread + 13\n)","queueName":"com.facebook.react.WebSocketModuleQueue"}}
 
detox[22659] ERROR: [index.js/DETOX_INIT_ERROR] 
 Exception '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil...
(
	0   CoreFoundation                      0x000000010889412b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107186f41 objc_exception_throw + 48
	2   RoobeeRestaurant                    0x0000000105b26005 RCTFormatError + 0
	3   RoobeeRestaurant                    0x0000000105b80156 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 798
	4   RoobeeRestaurant                    0x0000000105b7fcbc ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	5   EarlGrey                            0x0000000116b3e082 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 50
	6   libdispatch.dylib                   0x000000010c80a177 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010c80b1ba _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010c812d3d _dispatch_queue_serial_drain + 654
	9   libdispatch.dylib                   0x000000010c8135a0 _dispatch_queue_invoke + 329
	10  libdispatch.dylib                   0x000000010c80fc97 _dispatch_queue_override_invoke + 477
	11  libdispatch.dylib                   0x000000010c815980 _dispatch_root_queue_drain + 568
	12  libdispatch.dylib                   0x000000010c8156ea _dispatch_worker_thread3 + 119
	13  libsystem_pthread.dylib             0x000000010ccca5a2 _pthread_wqthread + 1299
	14  libsystem_pthread.dylib             0x000000010ccca07d start_wqthread + 13
)
detox[22659] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
detox[22659] DEBUG: [exec.js/EXEC_CMD, #7] /usr/bin/xcrun simctl shutdown 17AAD115-10E3-4B0D-8749-08FA9078C590
detox[22659] DEBUG: [exec.js/EXEC_TRY, #7] Shutting down 17AAD115-10E3-4B0D-8749-08FA9078C590...
detox[22659] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41
detox[22659] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=49bcb82a-384f-9cd5-7b3e-2303ff881d41
 FAIL  e2e/login.spec.js (21.917s)
  Login
    ✕ should log in a user with email and password (5ms)

  ● Login › should log in a user with email and password

    Failed: "Exception '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil...
    (
    	0   CoreFoundation                      0x000000010889412b __exceptionPreprocess + 171
    	1   libobjc.A.dylib                     0x0000000107186f41 objc_exception_throw + 48
    	2   RoobeeRestaurant                    0x0000000105b26005 RCTFormatError + 0
    	3   RoobeeRestaurant                    0x0000000105b80156 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 798
    	4   RoobeeRestaurant                    0x0000000105b7fcbc ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
    	5   EarlGrey                            0x0000000116b3e082 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 50
    	6   libdispatch.dylib                   0x000000010c80a177 _dispatch_call_block_and_release + 12
    	7   libdispatch.dylib                   0x000000010c80b1ba _dispatch_client_callout + 8
    	8   libdispatch.dylib                   0x000000010c812d3d _dispatch_queue_serial_drain + 654
    	9   libdispatch.dylib                   0x000000010c8135a0 _dispatch_queue_invoke + 329
    	10  libdispatch.dylib                   0x000000010c80fc97 _dispatch_queue_override_invoke + 477
    	11  libdispatch.dylib                   0x000000010c815980 _dispatch_root_queue_drain + 568
    	12  libdispatch.dylib                   0x000000010c8156ea _dispatch_worker_thread3 + 119
    	13  libsystem_pthread.dylib             0x000000010ccca5a2 _pthread_wqthread + 1299
    	14  libsystem_pthread.dylib             0x000000010ccca07d start_wqthread + 13
    )"

       6 | jasmine.getEnv().addReporter(adapter);
       7 | 
    >  8 | beforeAll(async () => {
         | ^
       9 |   await detox.init(config);
      10 | });
      11 | 

      at Env.beforeAll (../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:39:24)
      at Object.beforeAll (init.js:8:1)
          at Array.forEach (<anonymous>)

  ● Login › should log in a user with email and password

    ReferenceError: device is not defined

      1 | describe('Login', () => {
      2 |   beforeEach(async () => {
    > 3 |     await device.reloadReactNative();
        |           ^
      4 |   });
      5 | 
      6 |   it('should log in a user with email and password', async () => {

      at Object.device (login.spec.js:3:11)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:152:20)
      at ../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:187:11
      at callInvokeWithMethodAndArg (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:186:16)
      at AsyncIterator.enqueue (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:209:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at Object.<anonymous>.runtime.async (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:233:14)
      at Object._callee (login.spec.js:2:14)

  ● Login › should log in a user with email and password

    ReferenceError: element is not defined

      4 |   });
      5 | 
    > 6 |   it('should log in a user with email and password', async () => {
        |                                                      ^
      7 |     await expect(element(by.id('emailInput'))).toBeVisible()
      8 |     await element(by.id('emailInput')).tap()
      9 |     await element(by.id('emailInput')).replaceText('info@republicdiner.com')

      at Object._callee2$ (login.spec.js:6:54)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:152:20)
      at ../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:187:11
      at callInvokeWithMethodAndArg (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:186:16)
      at AsyncIterator.enqueue (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:209:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at Object.<anonymous>.runtime.async (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:233:14)
      at Object._callee2 (login.spec.js:6:54)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        21.987s
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
detox[22659] TRACE: [exec.js/EXEC_SUCCESS, #7] 
detox[22659] DEBUG: [exec.js/EXEC_SUCCESS, #7] 17AAD115-10E3-4B0D-8749-08FA9078C590 shut down
child_process.js:662
    throw err;
    ^

Error: Command failed: node_modules/.bin/jest "e2e" --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' 
    at checkExecSyncError (child_process.js:622:11)
    at Object.execSync (child_process.js:659:13)
    at runJest (/Users/distiller/project/RoobeeRestaurant/node_modules/detox/local-cli/detox-test.js:166:6)
    at run (/Users/distiller/project/RoobeeRestaurant/node_modules/detox/local-cli/detox-test.js:86:7)
    at Object.<anonymous> (/Users/distiller/project/RoobeeRestaurant/node_modules/detox/local-cli/detox-test.js:229:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
Exited with code 1
```

**Comment by LeoNatan** [comment]
The crash is happening inside your code. I'm not sure how this is a Detox issue.

**Comment by LeoNatan** [comment]
Also, make sure you are running a release build in CI, not debug.

**Comment by matt-wright86** [comment]
The root of the problem here was missing environment variables in our CI build. This problem is now resolved, thank you.
