### ISSUE TITLE
Introduce proguard minification into test app

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1216]
**Is your feature request related to a problem? Please describe.**
As observed in internal projects, it seems that when minification is enabled (over react native itself in particular), Detox can find itself in troubling situations due to usage of reflection.
Therefore, it'd be better (and future-proof) if we minify the test app and introduce proguard rules to protect Detox in that sense.

**Describe the solution you'd like**
Minify react-native in test app and introduce a proper proguard rules schema, integrated into the `build.gradle`.

**Describe alternatives you've considered**
N/A

**Additional context**
This is an error effectively observed in one of the internal projects:
```
E  java.lang.NoSuchMethodException: No similar method getUIViewOperationQueue with params [] could be found on type class com.facebook.react.uimanager.UIImplementation.
E      at org.joor.Reflect.similarMethod(Reflect.java:488)
E      at org.joor.Reflect.call(Reflect.java:418)
E      at org.joor.Reflect.call(Reflect.java:364)
E      at com.wix.detox.espresso.ReactNativeUIModuleIdlingResource.isIdleNow(ReactNativeUIModuleIdlingResource.java:83)
E      at android.support.test.espresso.base.IdlingResourceRegistry.allResourcesAreIdle(IdlingResourceRegistry.java:265)
E      at android.support.test.espresso.base.IdlingResourceRegistry$6.isIdleNow(IdlingResourceRegistry.java:299)
```

**Comment by d4vidi** [comment]
After a bit of an investigation work, it seems that since Detox is a test-dependency in app, proguard usage is a bit tangled. Here are a insights I believe are true:
1. Since Detox is a test-dep (`androidTestImplementation`), whatever we put inside our `proguard-rules.pro` only affects the `androidTest` apk (typically under `android/app/build/outputs/mapping/androidTest/...`). Therefore, there's no point in trying to add rules such as `-keep class com.facebook.react.**`, since they are effectively scarce.
2. Unlike what the documentation for `consumerProguardFiles` says, it _does_ bring the associated rules files into affect even if the library isn't served as an `aar` (as in our case) -- so we ought to keep it starting now.
3. Continuing point 1, still a need remains of affecting the actual (production) apk when running in instrumentation mode. *This* is what the `testProguardFiles` is for. In our case, since we need to have all of facebook available, this is the way to go (i.e. introducing a custom test proguard rules files and subscribing it using `testProguardFiles`).
