### ISSUE TITLE
[IOS] Can't run any test Plugin/Preset files are not allowed to export objects

### ISSUE THREAD

**Issue by ishigamii** [wix/Detox#1219]
**Describe the bug**
After Following the getting started guide on my react-native project I can't make the first test run and always get this error :

```
  ● Test suite failed to run

    Plugin/Preset files are not allowed to export objects, only functions. In /Users/xxx/Documents/ReactJS/xxx/node_modules/babel-preset-flow/lib/index.js

      at createDescriptor (../node_modules/jest-config/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
          at Array.map (<anonymous>)
...
Error: Command failed: node_modules/.bin/jest "e2e" --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runJest (/Users/xxx/Documents/ReactJS/xxx/node_modules/detox/local-cli/detox-test.js:170:6)
    at run (/Users/xxx/Documents/ReactJS/xxx/node_modules/detox/local-cli/detox-test.js:88:7)
    at Object.<anonymous> (/Users/xxx/Documents/ReactJS/xxx/node_modules/detox/local-cli/detox-test.js:233:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**To Reproduce**
Didn't try to reproduce on another project but it seems to me it's just a configuration missing or something

**Expected behavior**
Launching the test

**Screenshots**
none

**Environment :**
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
  detox: 11.0.2 => 11.0.2,
```

and my devDependencies are : 
```
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-jest": "23.6.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react-native": "4.0.1",
    "detox": "^11.0.2",
    "eslint": "^5.12.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.12.3",
    "flow-bin": "^0.89.0",
    "jest": "^24.5.0",
    "prettier-eslint": "^8.8.2",
    "prop-types": "^15.6.2",
    "react-test-renderer": "16.7.0"
  },
```

**Comment by LeoNatan** [comment]
I'm not sure this is a Detox bug. It looks like a Babel misconfiguration.
