### ISSUE TITLE
Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

### ISSUE THREAD

**Issue by punksta** [wix/Detox#1355]
I followed the common android android guide then I builded test release apk and tried to run tests.

detox test --configuration android.emu.release

<details>
  <summary>output</summary>

```
detox[695] INFO:  [test.js] configuration="android.emu.release" artifactsLocation="artifacts/android.emu.release.2019-05-02 15-04-17Z" recordLogs="none" takeScreenshots="manual" recordVideos="none" recordPerformance="none" node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$' "e2e"
● Validation Warning:

  Unknown option "setupFilesAfterEnv" with value ["./init.js"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

 FAIL  e2e/firstTest.spec.js
  ● Test suite failed to run

    Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

      at throwVersionError (../node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
      at Object.assertVersion (../node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
      at _default (../node_modules/@babel/plugin-proposal-decorators/lib/index.js:43:7)
      at ../node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.798s
Ran all test suites matching /e2e/i with tests matching "^((?!:ios:).)*$".
detox[695] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$' "e2e"
```

</details>

package.json
<details>
  <summary>content</summary>

```
{
  "name": "learnerapp",
  "version": "1.3.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "flow": "flow",
  },
  "rnpm": {
    "assets": [
      "./src/assets/font/"
    ]
  },
  "detox": {
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_28_x86"
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
        "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_28_x86"
      }
    },
    "test-runner": "jest",
    "runner-config": "e2e/config.json"
  },
  "dependencies": {
    "react": "^16.6.3",
    "react-native": "^0.57.8",
  },
  "devDependencies": {
    "@babel/core": "7.2.2",
    "@babel/plugin-proposal-decorators": "7.2.2",
    "@babel/runtime": "7.2.0",
    "amazon-s3-uri": "0.0.3",
    "app-icon": "^0.8.1",
    "aws-sdk": "^2.395.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "23.0.1",
    "babel-plugin-rewrite-require": "^1.14.5",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "detox": "^12.6.1",
    "flow-bin": "^0.78.0",
    "fs-extra": "^3.0.1",
    "inquirer": "^4.0.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.50.0",
    "prettier": "1.9.2",
    "react-native-asset": "^1.1.2",
    "react-test-renderer": "16.6.1",
    "reactotron-react-native": "^1.12.3"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "/node_modules/(?!react-native|react-navigation)"
    ]
  },
  "react-native": {
    "crypto": "crypto-browserify",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "stream": "stream-browserify",
    "vm": "vm-browserify"
  },
  "browser": {
    "crypto": "crypto-browserify",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "stream": "stream-browserify",
    "vm": "vm-browserify"
  }
}
```

</details>

.babelrc

<details>
  <summary>content</summary>

```
{
	"presets": ["module:metro-react-native-babel-preset"],
	"plugins": [
		["@babel/plugin-proposal-decorators", {"legacy": true}],
		[
			"babel-plugin-rewrite-require",
			{
				"aliases": {
					"crypto": "crypto-browserify",
					"stream": "stream-browserify",
					"vm": "vm-browserify"
				}
			}
		]
	],
	"env": {
		"production": {
			"plugins": ["transform-remove-console"]
		}
	}
}
```
</details>

**Comment by punksta** [comment]
fixed by updating jest to 24
