### ISSUE TITLE
nyc is broken unless a full path to mocha/other test runner is provided

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1386]
The error:

```
detox[10479] INFO:  [test.js] node_modules/.bin/nyc mocha --opts e2e/mocha.opts --configuration ios.none --grep :android: --invert --record-performance all --artifacts-location "artifacts/ios.none.2019-05-15 14-24-19Z" "e2e"
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn mocha ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
detox[10479] ERROR: [cli.js] Error: Command failed: node_modules/.bin/nyc mocha --opts e2e/mocha.opts --configuration ios.none --grep :android: --invert --record-performance all --artifacts-location "artifacts/ios.none.2019-05-15 14-24-19Z" "e2e"
```

We saw the same error on @rotemmiz 's Mac.

**Comment by LeoNatan** [comment]
@d4vidi @rotemmiz Changed the title to better describe the problem.
As we discussed, we need to provide the correct environment vars in Detox CLI.

**Comment by noomorph** [comment]
Shall we close it? Anyways, the `detox/test` e2e project moved to Jest.

**Comment by LeoNatan** [comment]
No, because this is a real issue in the detox CLI, unrelated to mocha or jest.

**Comment by d4vidi** [comment]
@LeoNatan wouldn't it be better to create a more specific issue, now that we've stopped using `nyc`?

**Comment by LeoNatan** [comment]
If you want to close this and create another one, sure. Or you can just change the title of this one.

**Comment by LeoNatan** [comment]
Fixed in latest release.
