### ISSUE TITLE
Detox hangs for a few minutes and then starts up a new simulator and continues with the tests

### ISSUE THREAD

**Issue by SMJ93** [wix/Detox#1623]
**Describe the bug**

When running Detox tests on iOS the tests will randomly hang (usually about 5min in). Then after a couple of minutes it will fail the test and open up a new simulator with the label `iPhone 6 -Detox -- 12.4` and continue running the rest of the tests:

![Screenshot 2019-08-22 at 18 18 51](https://user-images.githubusercontent.com/2145641/63535616-c8750300-c509-11e9-8b0f-d0196ee17d5b.png)

It stops on a different test each time which makes me think it loses connection to the device before timing out and booting up another.

If we run the tests individual (file by file) they all work.

It was working fine a couple of days ago, all we've done is add more tests.

**To Reproduce**

Run a long test suite (ours is now 15 minutes).

**Expected behavior**
I would expect it not to hang / pause and to continue with all of the tests on the same simulator

**Screenshots**

**Environment (please complete the following information):**
 - Detox: 14.0.0
 - React Native: 0.59.10
 - Node: 10.5.0
 - Device: iPhone 6 12.4 simulator
 - Xcode: 10.3
 - iOS: 12.4
 - macOS: 10.14.6

**Device and Verbose Detox Logs**

```
Timeout - Async callback was not invoked within the 200000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 200000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

ReferenceError: waitFor is not defined

      12 |
      13 | export const waitForElementToBeVisibleWithTimeout = async(testID, timeout = 2000) => {
    > 14 |   await waitFor(getElementById(testID)).toBeVisible().withTimeout(timeout);
         |   ^
      15 | }
      16 |
      17 | export const expectElementToBeVisible = async(testID) => {

      at Object.waitForElementToBeVisibleWithTimeout (helpers/index.js:14:3)
      at waitForElementToBeVisibleWithTimeout (common/login.js:4:17)
      at Object.it (b/b.test.js:9:11)
```

Repeats this for each test in the suite before showing:

```
detox[79686] INFO:  [DetoxServer.js] server listening on localhost:65505...
detox[79686] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:65505
detox[79686] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d
detox[79686] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d
detox[79686] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[79686] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone 6" --byOS "12.4"
detox[79686] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone 6...
detox[79686] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "840EF445-E330-483B-9218-61EB5D32250C"
detox[79686] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl boot 840EF445-E330-483B-9218-61EB5D32250C
detox[79686] DEBUG: [exec.js/EXEC_TRY, #3] Booting device 840EF445-E330-483B-9218-61EB5D32250C
detox[79686] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl bootstatus 840EF445-E330-483B-9218-61EB5D32250C
detox[79686] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl uninstall 840EF445-E330-483B-9218-61EB5D32250C com.a.b.branch
detox[79686] DEBUG: [exec.js/EXEC_TRY, #5] Uninstalling com.a.b.branch...
detox[79686] DEBUG: [exec.js/EXEC_SUCCESS, #5] com.a.b.branch uninstalled
detox[79686] DEBUG: [exec.js/EXEC_CMD, #6] /usr/bin/xcrun simctl install 840EF445-E330-483B-9218-61EB5D32250C "~/work/a/a-a-ui/ios/build/Build/Products/Release-iphonesimulator/dealsapp.app"
detox[79686] DEBUG: [exec.js/EXEC_TRY, #6] Installing /Users/a/Documents/work/a/deals-light-ui/ios/build/Build/Products/Release-iphonesimulator/dealsapp.app...
detox[79686] DEBUG: [exec.js/EXEC_SUCCESS, #6] /Users/a/Documents/work/a/deals-light-ui/ios/build/Build/Products/Release-iphonesimulator/dealsapp.app installed
detox[79686] DEBUG: [exec.js/EXEC_CMD, #7] /usr/bin/xcrun simctl terminate 840EF445-E330-483B-9218-61EB5D32250C com.a.a.branch
detox[79686] DEBUG: [exec.js/EXEC_TRY, #7] Terminating com.a.a.branch...
detox[79686] DEBUG: [exec.js/EXEC_SUCCESS, #7] com.a.a.branch terminated
detox[79686] DEBUG: [exec.js/EXEC_CMD, #8] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/a/Library/Detox/ios/7fdb30180dd3923c730747eebfa10bd0b3dc6358/Detox.framework/Detox" /usr/bin/xcrun simctl launch 840EF445-E330-483B-9218-61EB5D32250C com.a.a.branch --args -detoxServer "ws://localhost:65505" -detoxSessionId "ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d"
detox[79686] DEBUG: [exec.js/EXEC_TRY, #8] Launching com.a.a.branch...
detox[79686] DEBUG: [exec.js/EXEC_CMD, #9] /usr/bin/xcrun simctl get_app_container 840EF445-E330-483B-9218-61EB5D32250C com.a.a.branch
detox[79686] INFO:  [AppleSimUtils.js] com.a.a.branch launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 840EF445-E330-483B-9218-61EB5D32250C log stream --level debug --style compact --predicate 'processImagePath beginsWith "/Users/a/Library/Developer/CoreSimulator/Devices/840EF445-E330-483B-9218-61EB5D32250C/data/Containers/Bundle/Application/BF81C13D-35FC-4D13-ABE5-5FEA9A8196F6/dealsapp.app"'
detox[79686] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d)
detox[79686] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d
detox[79686] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d
detox[79686] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d
detox[79686] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d
detox[79686] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=ef49fb61-d8ed-9ef5-a2c8-d87d3448e41d)
detox[79686] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
 PASS  a/a.test.js (53.776s)
```

Let me know if you need anything else!

**Comment by LeoNatan** [comment]
Please follow the instructions in the documentation to debug your sync issue.

**Comment by SMJ93** [comment]
@LeoNatan it seems to be working now 🤔 weird! I will close the issue for now, thanks for the quick response!
