### ISSUE TITLE
react-native-restart works for Detox on iOS but not on Android

### ISSUE THREAD

**Issue by henrymoulton** [wix/Detox#1685]
**Describe the bug**
When using [react-native-restart](https://github.com/avishayil/react-native-restart) the tests hang on Android. iOS seems to work fine.

The ideal behaviour is to restart the app during run-time / manual testing to enable swapping between different configurations in a UAT environment. We use react-native-restart to clear the redux store and load the new configuration. Ideally Detox would continue using this workflow, however it is broken on Android.

This is part of [something I'm doing](https://github.com/wix/Detox/issues/1683) building up an example for Detox that uses common native dependencies found in production.

https://www.npmjs.com/package/react-native-restart

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Clone https://github.com/henrymoulton/Detox/tree/feat/react-native-restart
2. Run yarn e2e:ios  to confirm tests pass for iOS
3. Run yarn e2e:android-debug to confirm tests fail for Android

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

**Expected behavior**
Tests should pass.

**Screenshots**

**Environment (please complete the following information):**
 - Detox:  "detox": "^14.3.4",
 - React Native: "react-native": "0.59.10",
 - Node: v10.16.0
 - Device: "name": "Nexus_5X_API_26" and "name": "iPhone 11 Pro",
 - OS: OS X 10.14.6

**Device and Verbose Detox Logs**
Provide the device and "trace" Detox logs so we can understand what happened. You can obtain them by passing the loglevel param: `detox test --loglevel trace`

Android (failing):
```
detox[45070] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "Example should restart the app"
detox[45070] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeEach({ title: 'should restart the app',
  fullName: 'Example should restart the app',
  status: 'running' })
detox[45070] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"reactNativeReload","params":{},"messageId":-1000}
detox[45070] TRACE: [DetoxServer.js/MESSAGE] role=tester action=reactNativeReload (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
detox[45070] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
detox[45070] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}
 
detox[45070] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["restart_button"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]},"messageId":6}
detox[45070] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
        detox[45070] TRACE: [DetoxServer.js/MESSAGE] role=testee action=error (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
detox[45070] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":6,"type":"error","params":{"error":"Error performing 'single click - At Coordinates: 539, 1258 and precision: 16, 16' on view '(with tag value: is \"restart_button\" and view has effective visibility=VISIBLE)'."}}
 
    1) should restart the app
detox[45070] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "Example should restart the app"
detox[45070] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterEach({ title: 'should restart the app',
  fullName: 'Example should restart the app',
  status: 'failed',
  timedOut: false })

detox[45070] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
detox[45070] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"cleanup","params":{"stopRunner":false},"messageId":-49642}
detox[45070] TRACE: [DetoxServer.js/MESSAGE] role=tester action=cleanup (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
detox[45070] TRACE: [DetoxServer.js/MESSAGE] role=testee action=cleanupDone (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
detox[45070] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-49642,"type":"cleanupDone","params":{}}
 
detox[45070] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 45090]: /Users/henrymoulton/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:63385 -e detoxSessionId 139945d0-bf11-d744-4653-2f2e86a1cc54 -e debug ZmFsc2U= com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner
detox[45070] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54
detox[45070] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 45090]: /Users/henrymoulton/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:63385 -e detoxSessionId 139945d0-bf11-d744-4653-2f2e86a1cc54 -e debug ZmFsc2U= com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner
detox[45070] TRACE: [exec.js/SPAWN_END, #16] /Users/henrymoulton/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:63385 -e detoxSessionId 139945d0-bf11-d744-4653-2f2e86a1cc54 -e debug ZmFsc2U= com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner terminated with SIGINT
detox[45070] DEBUG: [exec.js/EXEC_CMD, #18] /Users/henrymoulton/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse --remove tcp:63385
detox[45070] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54
detox[45070] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=139945d0-bf11-d744-4653-2f2e86a1cc54)
detox[45070] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully

  3 passing (38s)
  1 failing

  1) Example
       should restart the app:
     Error: Error performing 'single click - At Coordinates: 539, 1258 and precision: 16, 16' on view '(with tag value: is "restart_button" and view has effective visibility=VISIBLE)'.
      at Client.execute (node_modules/detox/src/client/Client.js:92:28)
      at InvocationManager.execute (node_modules/detox/src/invoke.js:11:39)
      at ActionInteraction.execute (node_modules/detox/src/android/expect.js:128:35)
      at Element.tap (node_modules/detox/src/android/expect.js:220:88)
      at Context.it (e2e/example.spec.js:21:44)
      at process._tickCallback (internal/process/next_tick.js:68:7)



detox[45070] TRACE: [exec.js/EXEC_SUCCESS, #18] 
detox[45068] ERROR: [cli.js] Error: Command failed: node_modules/.bin/mocha --opts e2e/mocha.opts --configuration android.emu.debug --loglevel trace --grep :ios: --invert --artifacts-location "artifacts/android.emu.debug.2019-10-02 11-31-03Z" "e2e"
```

iOS (passing):
```
detox[45316] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "Example should restart the app"
detox[45316] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeEach({ title: 'should restart the app',
  fullName: 'Example should restart the app',
  status: 'running' })
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"reactNativeReload","params":{},"messageId":-1000}
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=tester action=reactNativeReload (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"ready","messageId":-1000,"params":{}}
 
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"restart_button"}]}}]}},"method":"performAction:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYActions"},"method":"actionForTap","args":[]}}]},"messageId":7}
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=testee action=invokeResult (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"invokeResult","messageId":7,"params":{"result":"(GREYElementInteraction)"}}
 
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"welcome"}]}}]}},"method":"assertWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForSufficientlyVisible","args":[]}}]},"messageId":8}
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=testee action=invokeResult (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"invokeResult","messageId":8,"params":{"result":"(GREYElementInteraction)"}}
 
    ✓ should restart the app (1627ms)
detox[45316] TRACE: [Detox.js/DETOX_AFTER_EACH] passed test: "Example should restart the app"
detox[45316] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterEach({ title: 'should restart the app',
  fullName: 'Example should restart the app',
  status: 'passed',
  timedOut: false })

detox[45316] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"cleanup","params":{"stopRunner":true},"messageId":-49642}
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=tester action=cleanup (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [DetoxServer.js/MESSAGE] role=testee action=cleanupDone (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"cleanupDone","messageId":-49642,"params":{}}
 
detox[45316] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9
detox[45316] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9
detox[45316] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=9dfdf086-70d1-4c85-fd9a-f7f7ba1a32c9)
detox[45316] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
```

**Comment by henrymoulton** [comment]
Just leaving an update here, I'm going to try and see if I can mock this out with calls to restart the actual app.

**Comment by rotemmiz** [comment]
What's the difference in functionality of this library from device.reloadReactNative() ?

**Comment by henrymoulton** [comment]
I'm not sure however `device.reloadReactNative()` has a [warning](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicereloadreactnative) about it:

> Note: This functionality does not work without faults. Under certain conditions, the system may not behave as expected and/or even crash. In these cases, use device.launchApp() to launch the app cleanly instead of only reloading the JS bundle.

Going to see if `device.launchApp()` works better

**Comment by rotemmiz** [comment]
This warning should be applied to `react-native-restart` as well, as it does exactly the same thing. Relaunching the app to get a clean launch state the the most recommended approach, but it is much slower than `reloadReactNative`

**Comment by henrymoulton** [comment]
Thanks, we went for this.
