### ISSUE TITLE
Sometimes jest can't find detox functions and throws ReferenceError

### ISSUE THREAD

**Issue by martinvol** [wix/Detox#1723]
**Describe the bug**

Sometimes jest can't find functions defined by detox.

```
● Transfer Works › NUX->Language

    ReferenceError: by is not defined

      30 | describe('Transfer Works', () => {
      31 |   beforeEach(async () => {
    > 32 |     bannerDismiss(by.id('errorBanner'))
         |                   ^
      33 |     bannerDismiss(by.id('SmartTopAlertButton'))
      34 |   })
      35 |
```

I can confirm the emulator is up and running because I can shh to the CI and take a screenshot.

Previously, with `RN=0.59.10` and `detox=14.0.2`, I solved this error by running `react-native run-android` before but it still happened from time to time. Now after the upgrade (see details below) it seems to happen way more often but not always.

**To Reproduce**

`$ yarn detox test -c android.emu.debug -a e2e/tmp/ --take-screenshots=failing --record-logs=failing --detectOpenHandles -l verbose`

You can see a full log starting from a clear macOS box here: https://circleci.com/gh/celo-org/celo-monorepo/54233

**Expected behavior**

Jest/detox finds its functions

**Environment (please complete the following information):**
 - Detox: 14.5.0
 - React Native: 0.61.2
 - Node: 10.16.3
 - Device: created with `avdmanager create avd -n Nexus_5X_API_28_x86 -k "system-images;android-26;google_apis;x86" -g google_apis -d "Nexus 5"`
 - OS: macOs

**Device and Verbose Detox Logs**

```
$ ENVFILE=".env.test" yarn test:detox
yarn run v1.15.2
$ CELO_TEST_CONFIG=e2e detox test -c android.emu.debug -a e2e/tmp/ --take-screenshots=failing --record-logs=failing --detectOpenHandles -l verbose
detox[14536] INFO:  [test.js] configuration="android.emu.debug" loglevel="verbose" artifactsLocation="e2e/tmp/" recordLogs="failing" takeScreenshots="failing" recordVideos="none" recordPerformance="none" reportSpecs=true readOnlyEmu=false node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$' --detectOpenHandles "e2e"
detox[14537] INFO:  [DetoxServer.js] server listening on localhost:50441...
detox[14537] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50441
detox[14537] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=f7dfb7f7-ab8e-8ec4-afc2-60f8c24bd77b
detox[14537] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=f7dfb7f7-ab8e-8ec4-afc2-60f8c24bd77b
detox[14537] DEBUG: [exec.js/EXEC_CMD, #0] /usr/local/share/android-sdk/emulator/emulator -list-avds --verbose
detox[14537] DEBUG: [exec.js/EXEC_CMD, #1] /usr/local/share/android-sdk/platform-tools/adb  devices
detox[14537] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
emulator-5554	device


detox[14537] DEBUG: [exec.js/EXEC_CMD, #2] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #3] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #4] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[14537] DEBUG: [exec.js/EXEC_CMD, #5] /usr/local/share/android-sdk/build-tools/28.0.3/aapt dump badging "/Users/distiller/src/packages/mobile/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[14537] DEBUG: [exec.js/EXEC_CMD, #6] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "pm list packages org.celo.mobile.debug"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #7] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 uninstall org.celo.mobile.debug
detox[14537] DEBUG: [exec.js/EXEC_CMD, #8] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "pm list packages org.celo.mobile.debug.test"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #9] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 uninstall org.celo.mobile.debug.test
detox[14537] DEBUG: [exec.js/EXEC_CMD, #10] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/distiller/src/packages/mobile/android/app/build/outputs/apk/debug/app-debug.apk"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #11] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/distiller/src/packages/mobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #12] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "am force-stop org.celo.mobile.debug"
detox[14537] DEBUG: [exec.js/EXEC_CMD, #13] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "date +\"%m-%d %T.000\""
detox[14537] DEBUG: [exec.js/EXEC_CMD, #14] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 reverse tcp:50441 tcp:50441
detox[14537] DEBUG: [exec.js/EXEC_CMD, #15] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "pm list instrumentation"
detox[14537] DEBUG: [exec.js/SPAWN_CMD, #16] [pid=14561] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:50441 -e detoxSessionId f7dfb7f7-ab8e-8ec4-afc2-60f8c24bd77b -e debug ZmFsc2U= org.celo.mobile.debug.test/androidx.test.runner.AndroidJUnitRunner
detox[14537] DEBUG: [exec.js/EXEC_CMD, #17] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "ps | grep \"org\.celo\.mobile\.debug$\""
detox[14537] DEBUG: [exec.js/SPAWN_CMD, #18] [pid=14563] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell "logcat -T \"10-31 10:41:33.000\" --pid=6720 -f /sdcard/10412263_0.log"
detox[14537] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=f7dfb7f7-ab8e-8ec4-afc2-60f8c24bd77b)
detox[14537] DEBUG: [exec.js/EXEC_CMD, #19] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell du /sdcard/10412263_0.log
detox[14537] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 14561]: /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:50441 -e detoxSessionId f7dfb7f7-ab8e-8ec4-afc2-60f8c24bd77b -e debug ZmFsc2U= org.celo.mobile.debug.test/androidx.test.runner.AndroidJUnitRunner
detox[14537] DEBUG: [exec.js/EXEC_CMD, #20] /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 reverse --remove tcp:50441
Transfer Works: NUX->Language
Transfer Works: NUX->Language [FAIL]
Transfer Works: NUX->Join
Transfer Works: NUX->Join [FAIL]
Transfer Works: NUX->Pin
Transfer Works: NUX->Pin [FAIL]
Transfer Works: NUX->Invite
Transfer Works: NUX->Invite [PENDING]
Transfer Works: NUX->ImportContacts
Transfer Works: NUX->ImportContacts [PENDING]
Transfer Works: NUX->VerifyEducation
Transfer Works: NUX->VerifyEducation [PENDING]
Transfer Works: NUX->Verify
Transfer Works: NUX->Verify [PENDING]
Transfer Works: Wallet Home
Transfer Works: Wallet Home [PENDING]
Transfer Works: Wallet Home->Send
Transfer Works: Wallet Home->Send [PENDING]

 FAIL  e2e/Transfer.spec.js (121.932s)
  Transfer Works
    ✕ NUX->Language (13ms)
    ✕ NUX->Join (7ms)
    ✕ NUX->Pin (6ms)
    ○ skipped NUX->Invite
    ○ skipped NUX->ImportContacts
    ○ skipped NUX->VerifyEducation
    ○ skipped NUX->Verify
    ○ skipped Wallet Home
    ○ skipped Wallet Home->Send

  ● Transfer Works › NUX->Language

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › NUX->Language

    ReferenceError: by is not defined

      30 | describe('Transfer Works', () => {
      31 |   beforeEach(async () => {
    > 32 |     bannerDismiss(by.id('errorBanner'))
         |                   ^
      33 |     bannerDismiss(by.id('SmartTopAlertButton'))
      34 |   })
      35 |

      at Object._callee$ (Transfer.spec.js:32:19)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../../../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../../../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../../../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../../../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../../../node_modules/regenerator-runtime/runtime.js:216:14)
      at Object._callee (Transfer.spec.js:31:14)

  ● Transfer Works › NUX->Language

    ReferenceError: element is not defined

      34 |   })
      35 |
    > 36 |   it('NUX->Language', async () => {
         |                       ^
      37 |     await element(by.id('ChooseLanguage/en-US')).tap()
      38 |     await element(by.id('ChooseLanguageButton')).tap()
      39 |   })

      at Object._callee2$ (Transfer.spec.js:36:23)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../../../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../../../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../../../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../../../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../../../node_modules/regenerator-runtime/runtime.js:216:14)
      at Object._callee2 (Transfer.spec.js:36:23)

  ● Transfer Works › NUX->Join

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › NUX->Join

    ReferenceError: by is not defined

      30 | describe('Transfer Works', () => {
      31 |   beforeEach(async () => {
    > 32 |     bannerDismiss(by.id('errorBanner'))
         |                   ^
      33 |     bannerDismiss(by.id('SmartTopAlertButton'))
      34 |   })
      35 |

      at Object._callee$ (Transfer.spec.js:32:19)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../../../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../../../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../../../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../../../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../../../node_modules/regenerator-runtime/runtime.js:216:14)
      at Object._callee (Transfer.spec.js:31:14)

  ● Transfer Works › NUX->Join

    ReferenceError: waitFor is not defined

      39 |   })
      40 |
    > 41 |   it('NUX->Join', async () => {
         |                   ^
      42 |     await waitFor(element(by.id('JoinCeloContinueButton')))
      43 |       .toBeVisible()
      44 |       .withTimeout(2000)

      at Object._callee3$ (Transfer.spec.js:41:19)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../../../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../../../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../../../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../../../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../../../node_modules/regenerator-runtime/runtime.js:216:14)
      at Object._callee3 (Transfer.spec.js:41:19)

  ● Transfer Works › NUX->Pin

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › NUX->Pin

    ReferenceError: by is not defined

      30 | describe('Transfer Works', () => {
      31 |   beforeEach(async () => {
    > 32 |     bannerDismiss(by.id('errorBanner'))
         |                   ^
      33 |     bannerDismiss(by.id('SmartTopAlertButton'))
      34 |   })
      35 |

      at Object._callee$ (Transfer.spec.js:32:19)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../../../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../../../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../../../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../../../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../../../node_modules/regenerator-runtime/runtime.js:216:14)
      at Object._callee (Transfer.spec.js:31:14)

  ● Transfer Works › NUX->Pin

    ReferenceError: element is not defined

      54 |   })
      55 |
    > 56 |   it('NUX->Pin', async () => {
         |                  ^
      57 |     await expect(element(by.id('SystemAuthTitle'))).toBeVisible()
      58 |     await expect(element(by.id('SystemAuthContinue'))).toBeVisible()
      59 |     enterPin()

      at Object._callee4$ (Transfer.spec.js:56:18)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../../../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../../../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../../../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../../../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../../../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../../../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../../../node_modules/regenerator-runtime/runtime.js:216:14)
      at Object._callee4 (Transfer.spec.js:56:18)

  ● Transfer Works › NUX->Invite

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › NUX->ImportContacts

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › NUX->VerifyEducation

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › NUX->Verify

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › Wallet Home

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Transfer Works › Wallet Home->Send

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by martinvol** [comment]
Here you can see a build (see `Run test itself` step) where the tests fail on the first try and then success on the second.
https://circleci.com/gh/celo-org/celo-monorepo/56523?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by d4vidi** [comment]
@martinvol Sorry if the log had you confused, but your problem is that tests time-out (check the logs more carefully). Typically, when detox' global are not found it means the initialization failed.
