### ISSUE TITLE
Error: Can't find a simulator to match with "iPhone 6s".

### ISSUE THREAD

**Issue by SMJ93** [wix/Detox#1763]
Detox was working fine as expected a couple of weeks ago - i've not updated anything to my knowledge and now I keep getting the following error:

```
Error: Can't find a simulator to match with "iPhone 6s", run 'xcrun simctl list' to list your supported devices.
      It is advised to only state a device type, and not to state iOS version, e.g. "iPhone 7"
    at AppleSimUtils.findDevicesUDID (/Users/user/Documents/work/app/e2e/node_modules/detox/src/devices/ios/AppleSimUtils.js:47:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I run `applesimutils --list --byName "iPhone 6s"` it shows 2 devices:

```
[
  {
    "deviceType" : {
      "name" : "iPhone 6s",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 6s.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"
    },
    "state" : "Shutdown",
    "isAvailable" : true,
    "name" : "iPhone 6s",
    "udid" : "A87C2EF9-95D2-4562-99BE-E1A39A63ABB1",
    "os" : {
      "buildversion" : "17B102",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
      "isAvailable" : true,
      "name" : "iOS 13.2",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-13-2",
      "version" : "13.2.2"
    }
  },
  {
    "deviceType" : {
      "name" : "iPhone 6s",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 6s.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"
    },
    "state" : "Shutdown",
    "isAvailable" : true,
    "name" : "iPhone 6s",
    "udid" : "F5A2C1D3-5416-431C-A9B5-6054A238283D",
    "os" : {
      "buildversion" : "16E226",
      "bundlePath" : "\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS 12.2.simruntime",
      "isAvailable" : true,
      "name" : "iOS 12.2",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-12-2",
      "version" : "12.2"
    }
  }
]
```

I've tried adding and removing the simulator through `xcode` and `xcrun`, but nothing seems to work.

**Comment by SMJ93** [comment]
@LeoNatan, any ideas how to fix this?

**Comment by SMJ93** [comment]
Also posted on https://stackoverflow.com/questions/58876482/error-cant-find-a-simulator-to-match-with-iphone-6s

**Comment by SMJ93** [comment]
Looking into this a bit more, the `node_modules/detox/src/utils/exec.js` is returning the array of simulators as you would expect from  line 64.

But inside `e2e/node_modules/detox/src/devices/ios/AppleSimUtils.js` at line 262 it returns an empty array? Any ideas why they might be getting stripped / does something happen in between?

**Comment by LeoNatan** [comment]
Make sure you are using the latest applesimutils and that you are specifying the query correctly.

**Comment by SMJ93** [comment]
Yep, I am using the latest `0.7.6`. It's returns the results as expected when logging, but it gets removed in `_execAppleSimUtils` for some reason :/

**Comment by SMJ93** [comment]
Omgggggg it was the Detox version. Updating detox to `14.7.1` fixed it.
