### ISSUE TITLE
App is Crashing while opening in Release Mode

### ISSUE THREAD

**Issue by Praveencena88** [wix/Detox#1781]
Currently Build is happening fine with the ``` detox build``` command but while running the test command app launches and crashes immediately.But for Debug its working fine both build & test.

**Running Command :** 
```
detox test  --configuration android.emu.release --loglevel verbose 
```

Versions : 
```
"react-native": "^0.61.4",
"detox": "^14.8.2",
"mocha": "^6.2.2",
Device  : External (Samsung A5)
Windows: 10
```

Error : 

```
11-26 17:03:54.435 17053-17266/? E/AndroidRuntime: FATAL EXCEPTION: com.wix.detox.manager
    Process: com.serviceguide_test, PID: 17053
    java.lang.NoSuchMethodError: No static method checkExpressionValueIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V in class Le/a/a/b; or its super classes (declaration of 'e.a.a.b' appears in /data/app/com.serviceguide_test-NRU2aKNbReVvnChAeV73CQ==/base.apk)
        at com.wix.detox.DetoxCrashHandler.<clinit>(DetoxCrashHandler.kt:17)
        at com.wix.detox.DetoxManager.initCrashHandler(DetoxManager.java:131)
        at com.wix.detox.DetoxManager.start(DetoxManager.java:69)
        at com.wix.detox.Detox$1$1.run(Detox.java:131)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at com.wix.detox.Detox$1.run(Detox.java:134)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Praveencena88** [comment]
@rotemmiz  can u see this issue ?

**Comment by Praveencena88** [comment]
looks like kotlin issue i have updated new version of kotlin and checked stil getting the error with the crash

**Comment by Praveencena88** [comment]
what kind of information you need?
