### ISSUE TITLE
Unable to detect react-native-phone-input component

### ISSUE THREAD

**Issue by Codnpix** [wix/Detox#1787]
## Unable to detect react-native-phone-input component
We use PhoneInput from the react-native-phone-input package ( https://www.npmjs.com/package/react-native-phone-input ) and it seems like the testID property is not supported, and I can't figure out any way to detect it. I tried by label, by type, but I always get null and the test fails.

I'm not sure if this is an issue with Detox or with the react-native-phone-input package, but as I'm very new using Detox there may be something I don't know about.

The component I'm trying to detect looks like this (this.props.testID is defined in parent component without any possible mistake from there)
```jsx
<View>
                <PhoneInput
                    value={this.state.formatedPhoneNumber}
                    ref={ref => {
                        this.phone = ref;
                    }}
                    //...
                    testID={this.props.testID}
                />
                <CountryPicker
                    ref={ref => {
                        this.countryPicker = ref;
                    }}
                    //...
                >
                    <View />
                </CountryPicker>
                <SimpleButton
                    //...
                    testID="phoneNumberInputSubmit"
                >
                    {t("Validate")}
                </SimpleButton>
            </View>
```
and the test I'm trying to pass looks like this : 
```javascript
it("should go to phone login screen", async () => {
        await expect(element(by.id("connectWithPhone"))).toBeVisible();
        await element(by.id("connectWithPhone")).tap();
        await expect(element(by.id("phoneLoginScreen"))).toBeVisible();
       // works until there

        await expect(element(by.id("phoneNumberInput"))).toBeVisible(); 
       //crashes here with error "got null"
        
        // ...
    });
```

this is my Detox configuration in package.json
```json
"devDependencies": {
    ...
    "detox": "^14.8.4",
    "jest": "^24.9.0",
  ...
  },
"detox": {
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "device": {
          "avdName": "Nexus_6_API_26"
        }
      },
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/truckfly.app",
        "build": "xcodebuild -project ios/truckfly.xcodeproj -scheme truckfly -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "device": {
          "type": "iPhone 11 Pro"
        }
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
        "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
        "type": "android.emulator",
        "device": {
          "avdName": "Nexus_6_API_26"
        }
      }
    },
    "test-runner": "jest"
  }
```

I'm trying to pass the test on the android.emu.release configuration. I didn't work on the Ios configuration yet, and for some reason I never get to launch the android.debug configuration but this is another story...

* Detox: 14.8.4
* React Native:0.59
* Node:8.10.0
* Device: emulator Nexus_6_API_26

#### Device and verbose Detox logs
```
Connection by phone
    ✓ should have tutorial screen (2158ms)
    ✓ should skip tutorial (2574ms)
    ✕ should go to phone login screen (2482ms)

  ● Connection by phone › should go to phone login screen

    'at least 75 percent of the view's area is displayed to the user.' doesn't match the selected view.
    Expected: at least 75 percent of the view's area is displayed to the user.
         Got: null

      78 |         await expect(element(by.id("phoneLoginScreen"))).toBeVisible();
      79 | 
    > 80 |         await expect(element(by.id("phoneNumberInput"))).toBeVisible();
         |                                                          ^
      81 |         
      82 |         // await element(by.id("phoneNumberInput")).tap();
      83 |         // await element(by.id("phoneNumberInput")).typeText(detoxFakeUserPhone);

      at Client.execute (../node_modules/detox/src/client/Client.js:92:28)
      at InvocationManager.execute (../node_modules/detox/src/invoke.js:11:39)
      at MatcherAssertionInteraction.execute (../node_modules/detox/src/android/expect.js:128:35)
      at ExpectElement.toBeVisible (../node_modules/detox/src/android/expect.js:275:112)
      at _callee4$ (tests/connection-testcases.js:80:58)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:145:13

detox[12655] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:ios:).)*$' --maxWorkers 1 "e2e/testLoop3.spec.js"
```

Thank you if you can help me find a way to solve this !

**Comment by LeoNatan** [comment]
I'm not sure what you expect from the Detox team here. It looks like your dependency does not implement standard practices well. I suggest you open an issue with them.
