### ISSUE TITLE
java.lang.NoSuchFieldException: mUiBackgroundMessageQueueThread 

### ISSUE THREAD

**Issue by spencerelliott** [wix/Detox#1796]
**Describe the bug**
When attempting to run detox tests on Android, I receive a `java.lang.NoSuchFieldException: mUiBackgroundMessageQueueThread` exception before the tests are run. This prevents the tests from running. It occurs in both release and debug builds. These tests work when running on the iOS simulator.

**To Reproduce**

- Install Detox
- Setup Android project
- Build detox tests
- Run `detox test`
- After app is uploaded to emulator and tests are about to be run, an exception is displayed

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

**Expected behavior**
The tests are run successfully, just as it does on the iOS simulator.

**Environment (please complete the following information):**
 - Detox: 14.8.5
 - React Native: 0.61.4
 - Node: 12.12.0
 - Device: Android emulator
 - OS: Android 8.1/9.0

**Device and Verbose Detox Logs**
Android project configuration files:
https://gist.github.com/spencerelliott/7b17b143c8999a49d654637d93fe76c8

Logcat:
```
12-11 13:43:44.307  3650  3855 I DetoxManager: DetoxServerUrl: ws://10.0.2.2:62874
12-11 13:43:44.307  3650  3855 I DetoxManager: DetoxSessionId: 07375112-8351-3cac-47dd-dbd7e238f4f2
12-11 13:43:44.311  3650  3650 D DetoxRNLoading: Got new RN-context directly and immediately
12-11 13:43:44.315  3650  3855 I DetoxRNIdleRes: Setting up Espresso Idling Resources for React Native.
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: Could not find queue: mUiBackgroundMessageQueueThread
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: org.joor.ReflectException: org.joor.ReflectException: java.lang.NoSuchFieldException: mUiBackgroundMessageQueueThread
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at org.joor.Reflect.field(Reflect.java:286)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.reactnative.MQThreadsReflector.getQueue(ReactNativeIdlingResources.kt:19)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.reactnative.ReactNativeIdlingResources.setupMQThreadsInterrogators(ReactNativeIdlingResources.kt:113)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.reactnative.ReactNativeIdlingResources.registerAll(ReactNativeIdlingResources.kt:83)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.reactnative.ReactNativeExtension.setupIdlingResources(ReactNativeExtension.kt:104)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.reactnative.ReactNativeExtension.setupIdlingResources$default(ReactNativeExtension.kt:102)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.reactnative.ReactNativeExtension.waitForRNBootstrap(ReactNativeExtension.kt:60)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.DetoxManager.initReactNativeIfNeeded(DetoxManager.java:122)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.DetoxManager.start(DetoxManager.java:67)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.Detox$1$1.run(Detox.java:131)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at android.os.Handler.handleCallback(Handler.java:790)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at android.os.Looper.loop(Looper.java:164)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at com.wix.detox.Detox$1.run(Detox.java:134)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at java.lang.Thread.run(Thread.java:764)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: Caused by: org.joor.ReflectException: java.lang.NoSuchFieldException: mUiBackgroundMessageQueueThread
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at org.joor.Reflect.field0(Reflect.java:310)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at org.joor.Reflect.field(Reflect.java:282)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	... 14 more
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: Caused by: java.lang.NoSuchFieldException: mUiBackgroundMessageQueueThread
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at java.lang.Class.getField(Class.java:1601)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	at org.joor.Reflect.field0(Reflect.java:295)
12-11 13:43:44.316  3650  3855 E DetoxRNIdleRes: 	... 15 more
```

**Comment by LeoNatan** [comment]
@d4vidi @rotemmiz  Did something change in RN?

**Comment by d4vidi** [comment]
Hi @spencerelliott, the exception was removed in `14.9.0` - but really, it was never a bug, just a log. If you could try to pinpoint what you actual problem is with Android e2e's we'll try to assist.
