### ISSUE TITLE
Bug with @expo/react-native-action-sheet and detox in debug mode

### ISSUE THREAD

**Issue by compojoom** [wix/Detox#1807]
**Describe the bug**
We've stumbled on a bug with detox and @expo/react-native-action-sheet in debug mode (debug mode build by detox).
Basically one has a button -> open action sheet. When pressed we open an action sheet with few button on it. Like this here:
![grafik](https://user-images.githubusercontent.com/693770/71062878-dbbc7600-216b-11ea-8952-560c1824f72c.png)

This works fine when detox builds a release version of the app. But when the app is launched in debug mode pressing the "open action sheet" button doesn't show the action sheet.

I can see in the **Layout Inspector** that the actionsheet is rendered in View Hierarchy, but it is not visible on the screen and the overlay-ed view doesn't accept any presses, so the app appears frozen. 

**To Reproduce**
here is a repo where I've reproduced the issue:
https://github.com/compojoom/rnDetoxActionSheetBug

just do:
```
detox build -c android.emu.debug
```
and then
```
detox test -c android.emu.debug
```

You'll notice that the test will fail on the Visibility check.
If you build the app in release mode:
```
detox build -c android.emu.release
```
You will be able to press the "open action sheet" button and you'll see the rendered action sheet. 

Please note: if one builds the app in debug mode with react-native the actionsheet is displayed on the screen without any issues. 
Also the test works fine on iOS in debug mode.

**Expected behavior**
I would expect the action sheet to be rendered both in debug and release mode.

**Screenshots**
release mode:
![grafik](https://user-images.githubusercontent.com/693770/71062878-dbbc7600-216b-11ea-8952-560c1824f72c.png)

debug mode - no action sheet rendered after pressing the "open action sheet" button:
![grafik](https://user-images.githubusercontent.com/693770/71063248-9f3d4a00-216c-11ea-844b-1c9934c626e0.png)

**Environment (please complete the following information):**
 - Detox: 14.9.1
 - React Native: 0.61.5
 - Node: 12.9.1
 - Device: Pixel 2 api 28
 - OS: mac OS /android emulator

**Device and Verbose Detox Logs**
```
$ detox test -c android.emu.debug -n Pixel_2_API_28 --loglevel trace
detox[2156] INFO:  [test.js] configuration="android.emu.debug" loglevel="trace" deviceName="Pixel_2_API_28" reportSpecs=true readOnlyEmu=false DETOX_START_TIMESTAMP=1576653181894 node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:ios:).)*$' --maxWorkers 1 "e2e"
detox[2157] INFO:  [DetoxServer.js] server listening on localhost:50738...
detox[2157] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50738
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a","role":"tester"},"messageId":0}
detox[2157] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a
detox[2157] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a","role":"tester"},"messageId":0}

detox[2157] DEBUG: [exec.js/EXEC_CMD, #0] "/usr/local/share/android-sdk/emulator/emulator" -list-avds --verbose
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #0] 7.3_Foldable_API_29
8_Foldable_API_29
Nexus_5X_API_27
Nexus_5_API_29
Nexus_S_API_29
Pixel_2_API_26
Pixel_2_API_28
Pixel_2_API_29
Pixel_3_API_24
Pixel_3_API_29

detox[2157] DEBUG: [EmulatorDriver.js/ACQUIRE_DEVICE] Looking up a device based on Pixel_2_API_28
detox[2157] DEBUG: [exec.js/EXEC_CMD, #1] "/usr/local/share/android-sdk/platform-tools/adb"  devices
detox[2157] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
emulator-19378	device


detox[2157] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 19378, host: localhost
detox[2157] DEBUG: [EmulatorDriver.js/ACQUIRE_DEVICE] Found emulator-19378!
detox[2157] DEBUG: [EmulatorDriver.js/ACQUIRE_DEVICE] Settled on emulator-19378
detox[2157] DEBUG: [exec.js/EXEC_CMD, #2] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "getprop dev.bootcomplete"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #2] 1

detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-19378' })
detox[2157] DEBUG: [exec.js/EXEC_CMD, #3] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "getprop ro.build.version.sdk"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #3] 28

detox[2157] DEBUG: [exec.js/EXEC_CMD, #4] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #4]   mWakefulness=Awake
  mWakefulnessChanging=false
  mWakeLockSummary=0x0
  mUserActivitySummary=0x1
  mWakeUpWhenPluggedOrUnpluggedConfig=false
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false

detox[2157] DEBUG: [exec.js/EXEC_CMD, #5] "/usr/local/share/android-sdk/build-tools/29.0.2/aapt" dump badging "/Users/xxx/Development/rnDetoxActionSheetBug/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #5] package: name='com.rndetoxactionsheetbug' versionCode='1' versionName='1.0' compileSdkVersion='28' compileSdkVersionCodename='9'

detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-19378', bundleId: 'com.rndetoxactionsheetbug' })
detox[2157] DEBUG: [exec.js/EXEC_CMD, #6] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "pm list packages com.rndetoxactionsheetbug"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #6] package:com.rndetoxactionsheetbug
package:com.rndetoxactionsheetbug.test

detox[2157] DEBUG: [exec.js/EXEC_CMD, #7] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 uninstall com.rndetoxactionsheetbug
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #7] Success

detox[2157] DEBUG: [exec.js/EXEC_CMD, #8] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "pm list packages com.rndetoxactionsheetbug.test"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #8] package:com.rndetoxactionsheetbug.test

detox[2157] DEBUG: [exec.js/EXEC_CMD, #9] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 uninstall com.rndetoxactionsheetbug.test
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #9] Success

detox[2157] DEBUG: [exec.js/EXEC_CMD, #10] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 install -r -g -t "/Users/xxx/Development/rnDetoxActionSheetBug/android/app/build/outputs/apk/debug/app-debug.apk"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #10] Performing Streamed Install
Success

detox[2157] DEBUG: [exec.js/EXEC_CMD, #11] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 install -r -g -t "/Users/xxx/Development/rnDetoxActionSheetBug/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #11] Performing Streamed Install
Success

detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-19378', bundleId: 'com.rndetoxactionsheetbug' })
detox[2157] DEBUG: [exec.js/EXEC_CMD, #12] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "am force-stop com.rndetoxactionsheetbug"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #12]
detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-19378',
  bundleId: 'com.rndetoxactionsheetbug',
  launchArgs: {
    detoxServer: 'ws://localhost:50738',
    detoxSessionId: '4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a'
  }
})
detox[2157] DEBUG: [exec.js/EXEC_CMD, #13] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "date +\"%m-%d %T.000\""
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #13] 12-18 08:13:04.000

detox[2157] DEBUG: [exec.js/EXEC_CMD, #14] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 reverse tcp:50738 tcp:50738
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #14]
detox[2157] DEBUG: [exec.js/EXEC_CMD, #15] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "pm list instrumentation"
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #15] instrumentation:com.rndetoxactionsheetbug.test/androidx.test.runner.AndroidJUnitRunner (target=com.rndetoxactionsheetbug)
instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)

detox[2157] DEBUG: [exec.js/SPAWN_CMD, #16] [pid=2181] /usr/local/share/android-sdk/platform-tools/adb -s emulator-19378 shell am instrument -w -r -e detoxServer ws://localhost:50738 -e detoxSessionId 4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a -e debug ZmFsc2U= com.rndetoxactionsheetbug.test/androidx.test.runner.AndroidJUnitRunner
detox[2157] TRACE: [exec.js/SPAWN_STDOUT, #16] INSTRUMENTATION_STATUS: class=com.rndetoxactionsheetbug.DetoxTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.rndetoxactionsheetbug.DetoxTest:
INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS_CODE: 1

detox[2157] DEBUG: [exec.js/EXEC_CMD, #17] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 shell "ps | grep \"com\.rndetoxactionsheetbug$\""
detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #17] u0_a112      14992  1937 1428884 101228 0                   0 R com.rndetoxactionsheetbug

detox[14992] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({
  deviceId: 'emulator-19378',
  bundleId: 'com.rndetoxactionsheetbug',
  launchArgs: {
    detoxServer: 'ws://localhost:50738',
    detoxSessionId: '4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a'
  },
  pid: 14992
})
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a
detox[2157] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}

detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeAll()
Example: should view actionsheet buttons
detox[2157] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "Example should view actionsheet buttons"
detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeEach({
  title: 'should view actionsheet buttons',
  fullName: 'Example should view actionsheet buttons',
  status: 'running'
})
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"reactNativeReload","params":{},"messageId":-1000}
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=tester action=reactNativeReload (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}

detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["openActionSheet"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]},"messageId":1}
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=testee action=invokeResult (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":1,"type":"invokeResult","params":{"result":null}}

detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxAssertion"},"method":"assertMatcher","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForText","args":["button 1"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForSufficientlyVisible","args":[]}}]},"messageId":2}
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=testee action=error (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":2,"type":"error","params":{"error":"'at least 75 percent of the view's area is displayed to the user.' doesn't match the selected view.\nExpected: at least 75 percent of the view's area is displayed to the user.\n     Got: \"ReactTextView{id=29, visibility=VISIBLE, width=156, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@ecc6258, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=45.0, text=button 1, input-type=0, ime-target=false, has-links=false}\"\n"}}

Example: should view actionsheet buttons [FAIL]

detox[2157] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "Example should view actionsheet buttons"
detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterEach({
  title: 'should view actionsheet buttons',
  fullName: 'Example should view actionsheet buttons',
  status: 'failed',
  timedOut: false
})
detox[2157] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"cleanup","params":{"stopRunner":false},"messageId":-49642}
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=tester action=cleanup (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [DetoxServer.js/MESSAGE] role=testee action=cleanupDone (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-49642,"type":"cleanupDone","params":{}}

detox[2157] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 2181]: /usr/local/share/android-sdk/platform-tools/adb -s emulator-19378 shell am instrument -w -r -e detoxServer ws://localhost:50738 -e detoxSessionId 4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a -e debug ZmFsc2U= com.rndetoxactionsheetbug.test/androidx.test.runner.AndroidJUnitRunner
detox[2157] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a
detox[2157] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 2181]: /usr/local/share/android-sdk/platform-tools/adb -s emulator-19378 shell am instrument -w -r -e detoxServer ws://localhost:50738 -e detoxSessionId 4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a -e debug ZmFsc2U= com.rndetoxactionsheetbug.test/androidx.test.runner.AndroidJUnitRunner
detox[2157] TRACE: [exec.js/SPAWN_END, #16] /usr/local/share/android-sdk/platform-tools/adb -s emulator-19378 shell am instrument -w -r -e detoxServer ws://localhost:50738 -e detoxSessionId 4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a -e debug ZmFsc2U= com.rndetoxactionsheetbug.test/androidx.test.runner.AndroidJUnitRunner terminated with SIGINT
detox[2157] DEBUG: [exec.js/EXEC_CMD, #18] "/usr/local/share/android-sdk/platform-tools/adb" -s emulator-19378 reverse --remove tcp:50738
detox[2157] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a
detox[2157] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=4babf4e1-552b-28e0-dc6d-f96ef3ef8d9a)
detox[2157] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
 FAIL  e2e/firstTest.spec.js (15.564s)
  Example
    ✕ should view actionsheet buttons (1629ms)

  ● Example › should view actionsheet buttons

    'at least 75 percent of the view's area is displayed to the user.' doesn't match the selected view.
    Expected: at least 75 percent of the view's area is displayed to the user.
         Got: "ReactTextView{id=29, visibility=VISIBLE, width=156, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@ecc6258, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=45.0, text=button 1, input-type=0, ime-target=false, has-links=false}"

       6 |   it('should view actionsheet buttons', async () => {
       7 |     await element(by.id('openActionSheet')).tap();
    >  8 |     await expect(element(by.text('button 1'))).toBeVisible();
         |                                                ^
       9 |   });
      10 |
      11 | });

      at Client.execute (../node_modules/detox/src/client/Client.js:92:28)
      at InvocationManager.execute (../node_modules/detox/src/invoke.js:11:39)
      at MatcherAssertionInteraction.execute (../node_modules/detox/src/android/expect.js:128:35)
      at ExpectElement.toBeVisible (../node_modules/detox/src/android/expect.js:275:112)
      at _callee2$ (firstTest.spec.js:8:48)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

detox[2157] TRACE: [exec.js/EXEC_SUCCESS, #18]
detox[2156] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:ios:).)*$' --maxWorkers 1 "e2e"

```

**Comment by LeoNatan** [comment]
Unfortunately, we are unable to provide Expo support. Please investigate with the Expo team why their component is misbehaving.

**Comment by compojoom** [comment]
@LeoNatan - well that's the thing...

So you are saying that despite the fact that building the app with react-native in debug mode works fine - it's an @expo/react-native-action-sheet bug?

To me that doesn't really make sense. If I'm to run the app outside of a detox build then everything is working fine. It's only in a detox build that one is not able to view the action-sheet.

How is this not a detox bug???

**Comment by LeoNatan** [comment]
I am saying that we don't have the resources to investigate Expo issues. Past experience indicates that usually it's not a Detox issue.

If it's a Detox issue, your issue certainly hasn't helped pointing out what the issue is. Have you done any investigation to determine if Expo or Detox? Once you do that and can show for sure where Detox breaks that code, post here or open a new issue.

**Comment by compojoom** [comment]
Ok. I'll try to investigate further. I'm still failing to see how this is not a detox bug, but I'll look further. 

The @expo/react-native-action-sheet uses a JS implementation on Android. 

This JS implementation works fine when the app is built with Android studio in debug and release mode.

When build with detox in debug mode - the view is not rendered. The only new thing we are adding is detox to the mix. So if it was working on a clean rn build and we add detox I doubt that it is an expo bug. 

Anyway. I'll look further into that and will report.

**Comment by LeoNatan** [comment]
Detox does not touch JavaScript in anyway.

**Comment by compojoom** [comment]
Ok, I'll write again once I know more.
