### ISSUE TITLE
`lerna run build` failing

### ISSUE THREAD

**Issue by adamski** [wix/detox#182]
Following the [Contributing Guide](https://github.com/wix/detox/blob/master/docs/Guide.Contributing.md) I hit an error on running `lerna run build`, main issue seems to be `babel: command not found`.

Log output below:

```
1 verbose cli   'build' ]
2 info using npm@5.0.4
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle detox-server@2.0.3~prebuild: detox-server@2.0.3
6 silly lifecycle detox-server@2.0.3~prebuild: no script for prebuild, continuing
7 info lifecycle detox-server@2.0.3~build: detox-server@2.0.3
8 verbose lifecycle detox-server@2.0.3~build: unsafe-perm in lifecycle true
9 verbose lifecycle detox-server@2.0.3~build: PATH: /Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/myuser/dev/react-projects/detox/detox-server/node_modules/.bin:/Users/myuser/dev/react-projects/detox/detox-server/node_modules/.bin:/Users/myuser/dev/react-projects/detox/node_modules/.bin:/Users/myuser/dev/react-projects/node_modules/.bin:/Users/myuser/dev/node_modules/.bin:/Users/myuser/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/myuser/.nvm/versions/node/v7.10.0/bin:/Users/myuser/.rvm/gems/ruby-2.3.0/bin:/Users/myuser/.rvm/gems/ruby-2.3.0@global/bin:/Users/myuser/.rvm/rubies/ruby-2.3.0/bin:/Users/myuser/.rvm/bin:/Users/myuser/.nvm/versions/node/v7.10.0/bin:/Applications/Android Studio.app/Contents/gradle/gradle-2.14.1/bin/gradle:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Android Studio.app/Contents/gradle/gradle-2.14.1/bin/gradle:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/Applications/Android Studio.app/Contents/gradle/gradle-2.14.1/bin/gradle:/Users/myuser/dev/SDKs/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/myuser/dev/SDKs/android-sdk/platform-tools:/usr/local/mysql/bin:/usr/local/git/bin:/Users/myuser/dev/Android/android-ndk-r9d/tools:/Users/myuser/dev/Android/android-ndk-r9d/platform-tools:/Users/myuser/dev/Android/adt-bundle-mac-x86_64-20140321/sdk:/Users/myuser/dev/SDKs/android-sdk/platform-tools:/usr/local/mysql/bin:/usr/local/git/bin:/Users/myuser/dev/Android/android-ndk-r9d/tools:/Users/myuser/dev/Android/android-ndk-r9d/platform-tools:/Users/myuser/dev/Android/adt-bundle-mac-x86_64-20140321/sdk
10 verbose lifecycle detox-server@2.0.3~build: CWD: /Users/myuser/dev/react-projects/detox/detox-server
11 silly lifecycle detox-server@2.0.3~build: Args: [ '-c', 'BABEL_ENV=test babel src -d lib' ]
12 info lifecycle detox-server@2.0.3~build: Failed to exec build script
13 verbose stack Error: detox-server@2.0.3 build: `BABEL_ENV=test babel src -d lib`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid detox-server@2.0.3
15 verbose cwd /Users/myuser/dev/react-projects/detox/detox-server
16 verbose Darwin 16.6.0
17 verbose argv "/Users/myuser/.nvm/versions/node/v7.10.0/bin/node" "/Users/myuser/.nvm/versions/node/v7.10.0/bin/npm" "run" "build"
18 verbose node v7.10.0
19 verbose npm  v5.0.4
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error detox-server@2.0.3 build: `BABEL_ENV=test babel src -d lib`
24 error spawn ENOENT
25 error Failed at the detox-server@2.0.3 build script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by rotemmiz** [comment]
Try running npm run build inside /detox-server.
What is the output?

**Comment by adamski** [comment]
@rotemmiz 

```
sh: babel: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! detox-server@2.0.3 build: `BABEL_ENV=test babel src -d lib`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the detox-server@2.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

**Comment by rotemmiz** [comment]
Did you run 'lerna bootstrap' ?

**Comment by adamski** [comment]
Yes, looks like I missed that step.. thanks, seems to be working now.
