### ISSUE TITLE
Unable to find module Event Dispatcher

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [wix/Detox#1837]
**Describe the bug**
The error screen `Unable to find module Event Dispatcher` happers to the ios simulator and breaks some of the test cases (randomly). 

I am experiencing this issues after upgrading from react-native 0.60.6 to 0.61.5

The issue is very similar to the [one described in this post](https://stackoverflow.com/a/56160671/7295772) as I did see warning errors (which I supressed) `Unable to find module for UIManager` when runing the test suite. Debugging is disabled and restarting/resetting the device is not a viable solution as the problem keeps reproducing himself. I disabled `FastRefresh` and the problem persisted.

I believe the issues is connected to the usage of [`device.reloadreactnative()`](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicereloadreactnative) used from both my [authentication specs](https://github.com/fabriziobertoglio1987/surf-react-native/blob/master/e2e/authenticated.spec.js#L3) and [public specs](https://github.com/fabriziobertoglio1987/surf-react-native/blob/master/e2e/public.spec.js#L3)

**To Reproduce**

I experience this issue on detox 0.15.0

The opensource project clone is [here](https://github.com/fabriziobertoglio1987/surf-react-native) available, but it is not a fully reproducible example.

The opensource project does not include configuration files (like Google Api keys, keystores...etc..) and it will not build. 
A readme with explanation on how to configure the project is not currently available and WorkInProgress. I may be able to prepare it if required. 

The detox test suite was fully working previously and I did not experience this issue when building/running the app. I am available to prepare a full-working example available on Github based on your request in the upcoming days.  It will take me considerable effort as some of files can not be shared with the public.

**Steps to reproduce**

Ideally you should clone the public project, set it up and run the test suite, but it will not be easy as some dependencies are not configured in the public project (keystores, google sign in api keys..etc..). For this reason the open source project will not build. 

1. run the command `npm start --reset-cache`
2. run `detox build` to build the project
3. run `detox test` to run the suite case

[This is the video recording of the issue (logs included)](https://fabriziobertoglio.s3.eu-central-1.amazonaws.com/detox+Unable+to+find+event+dispatcher.mov)

**Expected behavior**
As the EventDispatcher error does not appear when testing manually on the same ios simulator, the error must be connected with the detox latest release 15.0.0 and react native 0.61.5

I expect Detox to run without issues or errors.

**Environment (please complete the following information):**
 - Detox: 15.0.0
 - React Native: 0.61.5
 - Node: 12.14.0
 - Device: xcode simulator iPhone 11 - ios 13.3
 - Xcode: 11.3
 - iOS: 13.3
 - macOS: 10.15.2

**Device and Verbose Detox Logs**
<details>
  <summary>Click to expand!</summary>
  
```
  ● authenticated › displays the forecast page

    Cannot perform action due to constraint(s) failure.
    Exception with Action: {
      "Action Name":  "Tap",
      "Element Description":  "<RCTView:0x7f8978d042b0; AX=Y; AX.id='profileButton'; AX.label=''; AX.frame={{354, 807}, {45, 61}}; AX.activationPoint={376.5, 837.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{354, 36}, {45, 61}}; opaque; alpha=1>",
      "Failed Constraint(s)":  "interactable",
      "All Constraint(s)":  "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
      "Recovery Suggestion":  "Adjust element properties so that it matches the failed constraint(s)."
    }


    [
      {
        "Description":  "Cannot perform action due to constraint(s) failure.",
        "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code":  "1",
        "File Name":  "GREYBaseAction.m",
        "Function Name":  "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
        "Line":  "66"
      }
    ]

    Hierarchy: <RCTRedBoxWindow:0x7f896fe643f0; AX=N; AX.frame={{0, 0}, {414, 896}}; AX.activationPoint={207, 448}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 896}}; opaque; alpha=1>
      |--<UITransitionView:0x7f896fd85460; AX=N; AX.frame={{0, 0}, {414, 896}}; AX.activationPoint={207, 448}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 896}}; opaque; alpha=1>
      |  |--<UIDropShadowView:0x7f896fd47850; AX=N; AX.frame={{0, 0}, {414, 896}}; AX.activationPoint={207, 448}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 896}}; opaque; alpha=1>
      |  |  |--<UIView:0x7f896ff038c0; AX=N; AX.frame={{0, 0}, {414, 896}}; AX.activationPoint={207, 448}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 896}}; opaque; alpha=1>
      |  |  |  |--<UIView:0x7f896ffd5ef0; AX=N; AX.frame={{0, 862}, {414, 34}}; AX.activationPoint={207, 879}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 862}, {414, 34}}; opaque; alpha=1>
      |  |  |  |--<UIView:0x7f896ffd5d80; AX=N; AX.frame={{0, 803}, {414, 1}}; AX.activationPoint={207, 803.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 803}, {414, 1}}; opaque; alpha=1>
      |  |  |  |--<UIButton:0x7f896ff73d70; AX=Y; AX.id='redbox-extra'; AX.label='Extra Info (⌘E)'; AX.frame={{310.5, 802}, {103.5, 60}}; AX.activationPoint={362.25, 832}; AX.traits='UIAccessibilityTraitButton'; AX.focused='N'; frame={{310.5, 802}, {103.5, 60}}; alpha=1>
      |  |  |  |  |--<UIButtonLabel:0x7f896ff69880; AX=N; AX.label='Extra Info (⌘E)'; AX.frame={{333.5, 816}, {58, 32}}; AX.activationPoint={362.5, 832}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{23, 14}, {58, 32}}; alpha=1; UIE=N; text='Extra Info
    (⌘E)'>
      |  |  |  |--<UIButton:0x7f896ff794a0; AX=Y; AX.id='redbox-copy'; AX.label='Copy (⌥⌘C)'; AX.frame={{207, 802}, {103.5, 60}}; AX.activationPoint={258.75, 832}; AX.traits='UIAccessibilityTraitButton'; AX.focused='N'; frame={{207, 802}, {103.5, 60}}; alpha=1>
      |  |  |  |  |--<UIButtonLabel:0x7f896ff40ce0; AX=N; AX.label='Copy (⌥⌘C)'; AX.frame={{237.5, 816}, {43, 32}}; AX.activationPoint={259, 832}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{30.5, 14}, {43, 32}}; alpha=1; UIE=N; text='Copy
    (⌥⌘C)'>
      |  |  |  |--<UIButton:0x7f896fca9370; AX=Y; AX.id='redbox-reload'; AX.label='Reload (⌘R)'; AX.frame={{103.5, 802}, {103.5, 60}}; AX.activationPoint={155.25, 832}; AX.traits='UIAccessibilityTraitButton'; AX.focused='N'; frame={{103.5, 802}, {103.5, 60}}; alpha=1>
      |  |  |  |  |--<UIButtonLabel:0x7f896fc9e630; AX=N; AX.label='Reload (⌘R)'; AX.frame={{134.5, 816}, {42, 32}}; AX.activationPoint={155.5, 832}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{31, 14}, {42, 32}}; alpha=1; UIE=N; text='Reload
    (⌘R)'>
      |  |  |  |--<UIButton:0x7f896fd5c200; AX=Y; AX.id='redbox-dismiss'; AX.label='Dismiss (ESC)'; AX.frame={{0, 802}, {103.5, 60}}; AX.activationPoint={51.75, 832}; AX.traits='UIAccessibilityTraitButton'; AX.focused='N'; frame={{0, 802}, {103.5, 60}}; alpha=1>
      |  |  |  |  |--<UIButtonLabel:0x7f896fdbb9b0; AX=N; AX.label='Dismiss (ESC)'; AX.frame={{28.5, 816}, {47, 32}}; AX.activationPoint={52, 832}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{28.5, 14}, {47, 32}}; alpha=1; UIE=N; text='Dismiss
    (ESC)'>
      |  |  |  |--<UITableView:0x7f89708d8600; AX=N; AX.frame={{0, 0}, {414, 802}}; AX.activationPoint={207, 401}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 802}}; opaque; alpha=1>
      |  |  |  |  |--<_UIScrollViewScrollIndicator:0x7f896fc9caf0; AX=N; AX.label='Vertical scroll bar, 8 pages'; AX.value='0%'; AX.frame={{381, 34.5}, {30, 767.5}}; AX.activationPoint={409.5, 89.25}; AX.traits='UIAccessibilityTraitAdjustable'; AX.focused='N'; frame={{408, -6.5}, {3, 103.5}}; opaque; alpha=0>
      |  |  |  |  |  |--<UIView:0x7f896fc9cc80; AX=N; AX.frame={{408, 37.5}, {3, 103.5}}; AX.activationPoint={409.5, 89.25}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {3, 103.5}}; opaque; alpha=1>
      |  |  |  |  |--<_UIScrollViewScrollIndicator:0x7f896fc9c7f0; AX=N; AX.label='Horizontal scroll bar, 1 page'; AX.value='0%'; AX.frame={{0, 769}, {414, 30}}; AX.activationPoint={205.5, 797.5}; AX.traits='UIAccessibilityTraitAdjustable'; AX.focused='N'; frame={{3, 752}, {405, 3}}; opaque; alpha=0>
      |  |  |  |  |  |--<UIView:0x7f896fc9c980; AX=N; AX.frame={{3, 796}, {405, 3}}; AX.activationPoint={205.5, 797.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {405, 3}}; opaque; alpha=1>
      |  |  |  |  |--<UITableViewCell:0x7f896fcf45f0; AX=N; AX.frame={{0, 44}, {414, 60}}; AX.activationPoint={207, 74}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 60}}; opaque; alpha=1; text='Unable to find module for EventDispatcher'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fc04b60; AX=N; AX.frame={{0, 44}, {414, 60}}; AX.activationPoint={207, 74}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 60}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fc35f10; AX=Y; AX.id='redbox-error'; AX.label='Unable to find module for EventDispatcher'; AX.frame={{20, 44}, {374, 60}}; AX.activationPoint={207, 74}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 0}, {374, 60}}; opaque; alpha=1; UIE=N; text='Unable to find module for EventDispatcher'>
      |  |  |  |  |--<UITableViewCell:0x7f896fdb9010; AX=N; AX.frame={{0, 104}, {414, 50}}; AX.activationPoint={207, 129}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 60}, {414, 50}}; opaque; alpha=1; text='-[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fdac5d0; AX=N; AX.frame={{0, 104}, {414, 50}}; AX.activationPoint={207, 129}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fedfcd0; AX=Y; AX.label='RCTCxxBridge.mm:502'; AX.frame={{20, 139}, {126, 13}}; AX.activationPoint={83, 145.5}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 35}, {126, 13}}; opaque; alpha=1; UIE=N; text='RCTCxxBridge.mm:502'>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f8978c27e20; AX=Y; AX.label='-[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:]'; AX.frame={{20, 103.5}, {371, 33}}; AX.activationPoint={205.5, 120}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, -0.5}, {371, 33}}; opaque; alpha=1; UIE=N; text='-[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:]'>
      |  |  |  |  |--<UITableViewCell:0x7f896ff7ba60; AX=N; AX.frame={{0, 154}, {414, 50}}; AX.activationPoint={207, 179}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 110}, {414, 50}}; opaque; alpha=1; text='-[RCTCxxBridge moduleForClass:]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896ff45e80; AX=N; AX.frame={{0, 154}, {414, 50}}; AX.activationPoint={207, 179}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896ffa5f50; AX=Y; AX.label='-[RCTCxxBridge moduleForClass:]'; AX.frame={{20, 168.5}, {261.5, 16.5}}; AX.activationPoint={150.75, 176.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {261.5, 16.5}}; opaque; alpha=1; UIE=N; text='-[RCTCxxBridge moduleForClass:]'>
      |  |  |  |  |--<UITableViewCell:0x7f896ff36f40; AX=N; AX.frame={{0, 204}, {414, 50}}; AX.activationPoint={207, 229}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 160}, {414, 50}}; opaque; alpha=1; text='-[RCTBridge(RCTEventDispatcher) eventDispatcher]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fe7f760; AX=N; AX.frame={{0, 204}, {414, 50}}; AX.activationPoint={207, 229}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fef9190; AX=Y; AX.label='-[RCTBridge(RCTEventDispatcher) eventDispatcher]'; AX.frame={{20, 210.5}, {371, 33}}; AX.activationPoint={205.5, 227}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 6.5}, {371, 33}}; opaque; alpha=1; UIE=N; text='-[RCTBridge(RCTEventDispatcher) eventDispatcher]'>
      |  |  |  |  |--<UITableViewCell:0x7f896fddee10; AX=N; AX.frame={{0, 254}, {414, 50}}; AX.activationPoint={207, 279}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 210}, {414, 50}}; opaque; alpha=1; text='__createEventSetter_block_invoke_2'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fddf2c0; AX=N; AX.frame={{0, 254}, {414, 50}}; AX.activationPoint={207, 279}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fddf870; AX=Y; AX.label='__createEventSetter_block_invoke_2'; AX.frame={{20, 268.5}, {287, 16.5}}; AX.activationPoint={163.5, 276.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {287, 16.5}}; opaque; alpha=1; UIE=N; text='__createEventSetter_block_invoke_2'>
      |  |  |  |  |--<UITableViewCell:0x7f896fddbdb0; AX=N; AX.frame={{0, 304}, {414, 50}}; AX.activationPoint={207, 329}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 260}, {414, 50}}; opaque; alpha=1; text='-[RCTVideo observeValueForKeyPath:ofObject:change:context:]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fddc260; AX=N; AX.frame={{0, 304}, {414, 50}}; AX.activationPoint={207, 329}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fdcec20; AX=Y; AX.label='-[RCTVideo observeValueForKeyPath:ofObject:change:context:]'; AX.frame={{20, 310.5}, {371, 33}}; AX.activationPoint={205.5, 327}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 6.5}, {371, 33}}; opaque; alpha=1; UIE=N; text='-[RCTVideo observeValueForKeyPath:ofObject:change:context:]'>
      |  |  |  |  |--<UITableViewCell:0x7f896ffc2e60; AX=N; AX.frame={{0, 354}, {414, 50}}; AX.activationPoint={207, 379}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 310}, {414, 50}}; opaque; alpha=1; text='NSKeyValueNotifyObserver'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896ffc31f0; AX=N; AX.frame={{0, 354}, {414, 50}}; AX.activationPoint={207, 379}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896ffc37a0; AX=Y; AX.label='NSKeyValueNotifyObserver'; AX.frame={{20, 368.5}, {202.5, 16.5}}; AX.activationPoint={121.25, 376.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {202.5, 16.5}}; opaque; alpha=1; UIE=N; text='NSKeyValueNotifyObserver'>
      |  |  |  |  |--<UITableViewCell:0x7f896ffa6c70; AX=N; AX.frame={{0, 404}, {414, 50}}; AX.activationPoint={207, 429}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 360}, {414, 50}}; opaque; alpha=1; text='NSKeyValueDidChange'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896ffbad50; AX=N; AX.frame={{0, 404}, {414, 50}}; AX.activationPoint={207, 429}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fff22e0; AX=Y; AX.label='NSKeyValueDidChange'; AX.frame={{20, 418.5}, {160.5, 16.5}}; AX.activationPoint={100.25, 426.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {160.5, 16.5}}; opaque; alpha=1; UIE=N; text='NSKeyValueDidChange'>
      |  |  |  |  |--<UITableViewCell:0x7f896fdd3fb0; AX=N; AX.frame={{0, 454}, {414, 50}}; AX.activationPoint={207, 479}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 410}, {414, 50}}; opaque; alpha=1; text='NSKeyValueDidChangeWithPerThreadPendingNotifications'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fdd9590; AX=N; AX.frame={{0, 454}, {414, 50}}; AX.activationPoint={207, 479}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fdd9a20; AX=Y; AX.label='NSKeyValueDidChangeWithPerThreadPendingNotifications'; AX.frame={{20, 460.5}, {371, 33}}; AX.activationPoint={205.5, 477}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 6.5}, {371, 33}}; opaque; alpha=1; UIE=N; text='NSKeyValueDidChangeWithPerThreadPendingNotifications'>
      |  |  |  |  |--<UITableViewCell:0x7f896feb6090; AX=N; AX.frame={{0, 504}, {414, 50}}; AX.activationPoint={207, 529}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 460}, {414, 50}}; opaque; alpha=1; text='-[AVPlayer setRate:withVolumeRampDuration:playImmediately:rateChangeReason:]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896feb6540; AX=N; AX.frame={{0, 504}, {414, 50}}; AX.activationPoint={207, 529}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fecc5b0; AX=Y; AX.label='-[AVPlayer setRate:withVolumeRampDuration:playImmediately:rateChangeReason:]'; AX.frame={{20, 510.5}, {371, 33}}; AX.activationPoint={205.5, 527}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 6.5}, {371, 33}}; opaque; alpha=1; UIE=N; text='-[AVPlayer setRate:withVolumeRampDuration:playImmediately:rateChangeReason:]'>
      |  |  |  |  |--<UITableViewCell:0x7f896fff9070; AX=N; AX.frame={{0, 554}, {414, 50}}; AX.activationPoint={207, 579}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 510}, {414, 50}}; opaque; alpha=1; text='-[AVPlayer setRate:]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fff9400; AX=N; AX.frame={{0, 554}, {414, 50}}; AX.activationPoint={207, 579}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fff9760; AX=Y; AX.label='-[AVPlayer setRate:]'; AX.frame={{20, 568.5}, {169, 16.5}}; AX.activationPoint={104.5, 576.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {169, 16.5}}; opaque; alpha=1; UIE=N; text='-[AVPlayer setRate:]'>
      |  |  |  |  |--<UITableViewCell:0x7f896fffb410; AX=N; AX.frame={{0, 604}, {414, 50}}; AX.activationPoint={207, 629}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 560}, {414, 50}}; opaque; alpha=1; text='-[RCTVideo removeFromSuperview]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fffbb00; AX=N; AX.frame={{0, 604}, {414, 50}}; AX.activationPoint={207, 629}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896ffa8350; AX=Y; AX.label='-[RCTVideo removeFromSuperview]'; AX.frame={{20, 618.5}, {261.5, 16.5}}; AX.activationPoint={150.75, 626.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {261.5, 16.5}}; opaque; alpha=1; UIE=N; text='-[RCTVideo removeFromSuperview]'>
      |  |  |  |  |--<UITableViewCell:0x7f896ff6aa70; AX=N; AX.frame={{0, 654}, {414, 50}}; AX.activationPoint={207, 679}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 610}, {414, 50}}; opaque; alpha=1; text='-[UIView dealloc]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896ff31b10; AX=N; AX.frame={{0, 654}, {414, 50}}; AX.activationPoint={207, 679}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896ffe15c0; AX=Y; AX.label='-[UIView dealloc]'; AX.frame={{20, 668.5}, {143.5, 16.5}}; AX.activationPoint={91.75, 676.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {143.5, 16.5}}; opaque; alpha=1; UIE=N; text='-[UIView dealloc]'>
      |  |  |  |  |--<UITableViewCell:0x7f896ff53b70; AX=N; AX.frame={{0, 704}, {414, 50}}; AX.activationPoint={207, 729}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 660}, {414, 50}}; opaque; alpha=1; text='-[RCTView dealloc]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896ff97090; AX=N; AX.frame={{0, 704}, {414, 50}}; AX.activationPoint={207, 729}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896ffba520; AX=Y; AX.label='-[RCTView dealloc]'; AX.frame={{20, 718.5}, {152, 16.5}}; AX.activationPoint={96, 726.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {152, 16.5}}; opaque; alpha=1; UIE=N; text='-[RCTView dealloc]'>
      |  |  |  |  |--<UITableViewCell:0x7f896ffb8690; AX=N; AX.frame={{0, 754}, {414, 50}}; AX.activationPoint={207, 779}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 710}, {414, 50}}; opaque; alpha=1; text='-[__NSArrayM dealloc]'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896ff711d0; AX=N; AX.frame={{0, 754}, {414, 50}}; AX.activationPoint={207, 779}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896ff67c40; AX=Y; AX.label='-[__NSArrayM dealloc]'; AX.frame={{20, 768.5}, {177.5, 16.5}}; AX.activationPoint={108.75, 776.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {177.5, 16.5}}; opaque; alpha=1; UIE=N; text='-[__NSArrayM dealloc]'>
      |  |  |  |  |--<UITableViewCell:0x7f896fc87500; AX=N; AX.frame={{0, 804}, {414, 50}}; AX.activationPoint={207, 829}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 760}, {414, 50}}; opaque; hidden; alpha=1; text='objc_object::sidetable_release(bool)'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fc87890; AX=N; AX.frame={{0, 804}, {414, 50}}; AX.activationPoint={207, 829}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fc87d20; AX=Y; AX.label='objc_object::sidetable_release(bool)'; AX.frame={{20, 818.5}, {303.5, 16.5}}; AX.activationPoint={171.75, 826.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {303.5, 16.5}}; opaque; alpha=1; UIE=N; text='objc_object::sidetable_release(bool)'>
      |  |  |  |  |--<UITableViewCell:0x7f8978e00bf0; AX=N; AX.frame={{0, 854}, {414, 50}}; AX.activationPoint={207, 879}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 810}, {414, 50}}; opaque; hidden; alpha=1; text='_object_remove_assocations'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f8978e010a0; AX=N; AX.frame={{0, 854}, {414, 50}}; AX.activationPoint={207, 879}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f8978e01650; AX=Y; AX.label='_object_remove_assocations'; AX.frame={{20, 868.5}, {219.5, 16.5}}; AX.activationPoint={129.75, 876.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {219.5, 16.5}}; opaque; alpha=1; UIE=N; text='_object_remove_assocations'>
      |  |  |  |  |--<UITableViewCell:0x7f8978e116c0; AX=N; AX.frame={{0, 904}, {414, 50}}; AX.activationPoint={207, 929}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 860}, {414, 50}}; opaque; hidden; alpha=1; text='objc_destructInstance'>
      |  |  |  |  |  |--<UITableViewCellContentView:0x7f896fc7f7f0; AX=N; AX.frame={{0, 904}, {414, 50}}; AX.activationPoint={207, 929}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 50}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<UITableViewLabel:0x7f896fc7fc80; AX=Y; AX.label='objc_destructInstance'; AX.frame={{20, 918.5}, {177.5, 16.5}}; AX.activationPoint={108.75, 926.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 14.5}, {177.5, 16.5}}; opaque; alpha=1; UIE=N; text='objc_destructInstance'>

      34 |   it('displays the forecast page', async () => {
      35 |     var flatlist = await element(by.id("flatlist"))
    > 36 |     await element(by.id("profileButton")).tap()
         |                                           ^
      37 |     await expect(flatlist).toBeNotVisible()
      38 |   })
      39 | });

      at Client.execute (../node_modules/detox/src/client/Client.js:92:28)
      at InvocationManager.execute (../node_modules/detox/src/invoke.js:11:39)
      at ActionInteraction.execute (../node_modules/detox/src/ios/expect.js:200:35)
      at Element.tap (../node_modules/detox/src/ios/expect.js:297:88)
      at _callee6$ (authenticated.spec.js:36:43)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:145:13
```
</details>

**Comment by fabriziobertoglio1987** [comment]
I found a workaround to the problem 

I removed [`await device.reloadReactNative();` from my `beforeEach` callback](https://github.com/fabriziobertoglio1987/surf-react-native/blob/master/e2e/authenticated.spec.js#L3).

Instead I am [using the backbutton](https://github.com/wix/Detox/issues/828#issuecomment-404880787) to run the test cases without refresh `cmd + r`.

```javascript 
describe('authenticated', () => {
  beforeEach(async () => {
    // await device.reloadReactNative();
    // await device.launchApp()
    console.disableYellowBox = true;
  });
```
As explained in the [docs](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicereloadreactnative)

>**`device.reloadReactNative()`**
>Note: This functionality does not work without faults. Under certain conditions, the system may not behave as expected and/or even crash. In these cases, use device.launchApp() to launch the app cleanly instead of only reloading the JS bundle.

**Comment by LeoNatan** [comment]
Something is wrong with the way you are building. Detox is not responsible for building your app.
