### ISSUE TITLE
Detox hangs after adding custom Youtube library

### ISSUE THREAD

**Issue by eleddie** [wix/Detox#1842]
**Describe the bug**
I wanted to add youtube videos to my app and found react-native-youtube, but it worked with cocoa pods and I don't use cocoa pods in my project. I had to modify the [Youtube Library for React Native](https://github.com/inProgress-team/react-native-youtube) in order to make it work without cocoa pods so [I forked the repo and made my own](https://github.com/eleddie/react-native-youtube) and works perfectly fine with both android and ios.

Then I `detox build` and `detox test` and after the build it just hangs here:

<img width="1164" alt="Screen Shot 2020-01-08 at 5 31 01 PM" src="https://user-images.githubusercontent.com/13477629/71996634-d3bc9700-323c-11ea-8c33-cfab5e767c8e.png">

**To Reproduce**

- [X] I have tested this issue on the latest Detox release and it still reproduces

I created a repo with a [reproducible demo](https://github.com/eleddie/DetoxYoutubeIssue).
In order to reproduce it you need to create a Youtube API key, I didn't upload mine to the repo so here are the steps: https://developers.google.com/youtube/android/player/register

After you have it, just place it in the `key.js` file.

You'll be able to run the app normally with `react-native run-ios` or via xcode but `detox test` will hang.

The problem comes when you link the youtube library here:
<img width="1345" alt="Screen Shot 2020-01-08 at 5 35 53 PM" src="https://user-images.githubusercontent.com/13477629/71997320-f69b7b00-323d-11ea-8be8-4694e10b177d.png">

[Here's](https://github.com/eleddie/DetoxYoutubeIssue/tree/detox_working) a version of the code only with the library unlinked and the tests work just fine

**Expected behavior**
The tests should be able to run with the youtube library linked

**Environment (please complete the following information):**
 - Detox: 15.0.0
 - React Native: 0.59.10
 - Node: 12.3.1
 - Device: iPhone 11 Simulator
 - Xcode: 1.3 (11C29)
 - iOS: 13.3
 - macOS: 10.15.2 (19C57)

**Device and Verbose Detox Logs**
```
detox[97396] INFO:  [test.js] node_modules/.bin/mocha --opts e2e/mocha.opts --configuration ios.sim.debug --loglevel trace --grep :android: --invert "e2e"


(node:97397) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
detox[97397] INFO:  [DetoxServer.js] server listening on localhost:58472...
detox[97397] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:58472
detox[97397] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"458f94e1-5b7f-74a0-7858-42a10350d31d","role":"tester"},"messageId":0}
detox[97397] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=458f94e1-5b7f-74a0-7858-42a10350d31d
detox[97397] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=458f94e1-5b7f-74a0-7858-42a10350d31d
detox[97397] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"458f94e1-5b7f-74a0-7858-42a10350d31d","role":"tester"},"messageId":0}
 
detox[97397] DEBUG: [exec.js/EXEC_CMD, #0] applesimutils --list --byType "iPhone 11"
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #0] [
  {
    "deviceType" : {
      "name" : "iPhone 11",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11"
    },
    "state" : "Booted",
    "isAvailable" : true,
    "name" : "iPhone 11",
    "udid" : "E54D735E-2B6D-4210-A05C-7EF10FE4941D",
    "os" : {
      "buildversion" : "17C45",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
      "isAvailable" : true,
      "name" : "iOS 13.3",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-13-3",
      "version" : "13.3"
    }
  }
]

detox[97397] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byId E54D735E-2B6D-4210-A05C-7EF10FE4941D --maxResults 1
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #1] [
  {
    "deviceType" : {
      "name" : "iPhone 11",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11"
    },
    "state" : "Booted",
    "isAvailable" : true,
    "name" : "iPhone 11",
    "udid" : "E54D735E-2B6D-4210-A05C-7EF10FE4941D",
    "os" : {
      "buildversion" : "17C45",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
      "isAvailable" : true,
      "name" : "iOS 13.3",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-13-3",
      "version" : "13.3"
    }
  }
]

detox[97397] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'E54D735E-2B6D-4210-A05C-7EF10FE4941D' })
detox[97397] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({
  deviceId: 'E54D735E-2B6D-4210-A05C-7EF10FE4941D',
  bundleId: 'org.reactjs.native.example.DetoxYoutubeIssue'
})
detox[97397] DEBUG: [exec.js/EXEC_CMD, #2] /usr/bin/xcrun simctl uninstall E54D735E-2B6D-4210-A05C-7EF10FE4941D org.reactjs.native.example.DetoxYoutubeIssue
detox[97397] DEBUG: [exec.js/EXEC_TRY, #2] Uninstalling org.reactjs.native.example.DetoxYoutubeIssue...
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #2] 
detox[97397] DEBUG: [exec.js/EXEC_SUCCESS, #2] org.reactjs.native.example.DetoxYoutubeIssue uninstalled
detox[97397] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl install E54D735E-2B6D-4210-A05C-7EF10FE4941D "/Users/eduardosanchez/Documents/Syntax/Glofox/DetoxYoutubeIssue/ios/build/Build/Products/Debug-iphonesimulator/DetoxYoutubeIssue.app"
detox[97397] DEBUG: [exec.js/EXEC_TRY, #3] Installing /Users/eduardosanchez/Documents/Syntax/Glofox/DetoxYoutubeIssue/ios/build/Build/Products/Debug-iphonesimulator/DetoxYoutubeIssue.app...
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #3] 
detox[97397] DEBUG: [exec.js/EXEC_SUCCESS, #3] /Users/eduardosanchez/Documents/Syntax/Glofox/DetoxYoutubeIssue/ios/build/Build/Products/Debug-iphonesimulator/DetoxYoutubeIssue.app installed
detox[97397] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({
  deviceId: 'E54D735E-2B6D-4210-A05C-7EF10FE4941D',
  bundleId: 'org.reactjs.native.example.DetoxYoutubeIssue'
})
detox[97397] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl terminate E54D735E-2B6D-4210-A05C-7EF10FE4941D org.reactjs.native.example.DetoxYoutubeIssue
detox[97397] DEBUG: [exec.js/EXEC_TRY, #4] Terminating org.reactjs.native.example.DetoxYoutubeIssue...
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #4] 
detox[97397] DEBUG: [exec.js/EXEC_SUCCESS, #4] org.reactjs.native.example.DetoxYoutubeIssue terminated
detox[97397] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({
  deviceId: 'E54D735E-2B6D-4210-A05C-7EF10FE4941D',
  bundleId: 'org.reactjs.native.example.DetoxYoutubeIssue'
})
detox[97397] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  bundleId: 'org.reactjs.native.example.DetoxYoutubeIssue',
  deviceId: 'E54D735E-2B6D-4210-A05C-7EF10FE4941D',
  launchArgs: {
    detoxServer: 'ws://localhost:58472',
    detoxSessionId: '458f94e1-5b7f-74a0-7858-42a10350d31d'
  }
})
detox[97397] DEBUG: [exec.js/EXEC_CMD, #5] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/eduardosanchez/Library/Detox/ios/b9806453eb762f03e7f7832639ef620b89b0d977/Detox.framework/Detox" /usr/bin/xcrun simctl launch E54D735E-2B6D-4210-A05C-7EF10FE4941D org.reactjs.native.example.DetoxYoutubeIssue --args -detoxServer "ws://localhost:58472" -detoxSessionId "458f94e1-5b7f-74a0-7858-42a10350d31d"
detox[97397] DEBUG: [exec.js/EXEC_TRY, #5] Launching org.reactjs.native.example.DetoxYoutubeIssue...
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #5] org.reactjs.native.example.DetoxYoutubeIssue: 97441

detox[97397] DEBUG: [exec.js/EXEC_CMD, #6] /usr/bin/xcrun simctl get_app_container E54D735E-2B6D-4210-A05C-7EF10FE4941D org.reactjs.native.example.DetoxYoutubeIssue
detox[97397] TRACE: [exec.js/EXEC_SUCCESS, #6] /Users/eduardosanchez/Library/Developer/CoreSimulator/Devices/E54D735E-2B6D-4210-A05C-7EF10FE4941D/data/Containers/Bundle/Application/8CEADF82-F898-4B61-9FFC-F765D2BBAD64/DetoxYoutubeIssue.app

detox[97397] INFO:  [AppleSimUtils.js] org.reactjs.native.example.DetoxYoutubeIssue launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn E54D735E-2B6D-4210-A05C-7EF10FE4941D log stream --level debug --style compact --predicate 'processImagePath beginsWith "/Users/eduardosanchez/Library/Developer/CoreSimulator/Devices/E54D735E-2B6D-4210-A05C-7EF10FE4941D/data/Containers/Bundle/Application/8CEADF82-F898-4B61-9FFC-F765D2BBAD64/DetoxYoutubeIssue.app"'
detox[97441] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({
  bundleId: 'org.reactjs.native.example.DetoxYoutubeIssue',
  deviceId: 'E54D735E-2B6D-4210-A05C-7EF10FE4941D',
  launchArgs: {
    detoxServer: 'ws://localhost:58472',
    detoxSessionId: '458f94e1-5b7f-74a0-7858-42a10350d31d'
  },
  pid: 97441
})
detox[97397] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[97397] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=458f94e1-5b7f-74a0-7858-42a10350d31d)
detox[97397] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=458f94e1-5b7f-74a0-7858-42a10350d31d)
  1) "before all" hook in "{root}"

  0 passing (2m)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)


```

**Comment by LeoNatan** [comment]
Please follow the instructions here and post log:

https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only

**Comment by eleddie** [comment]
No luck with the logs. I tried [this](https://github.com/wix/Detox/issues/1503#issuecomment-508515053) but still it shows nothing after
`xcrun simctl spawn booted log stream --level debug --style compact --predicate "category=='EarlGreyStatistics'"`

I stays in:
```
➜  ~ xcrun simctl spawn booted log stream --level debug --style compact --predicate "category=='EarlGreyStatistics'"

Error from getpwuid_r: 0 (Undefined error: 0)
Filtering the log data using "category == "EarlGreyStatistics""
```

I changed my init.js file to:
```
const detox = require('detox');
const config = require('../package.json').detox;
const adapter = require('detox/runners/mocha/adapter');

before(async function () {
  await detox.init(config, { launchApp: false });
  await device.launchApp({
    newInstance: true,
    launchArgs: { 'detoxPrintBusyIdleResources': 'YES' }
  });
});

beforeEach(async function () {
  await adapter.beforeEach(this);
});

afterEach(async function () {
  await adapter.afterEach(this);
});

after(async () => {
  await detox.cleanup();
});
```

Could it not be working with mocha? All the issues regarding `detoxPrintBusyIdleResources` are using jest.

**Comment by LeoNatan** [comment]
It’s unrelated to the JS test runner. It’s a native command. If you see no output, it means Detox is not running. Follow the “debugging in Xcode” guide in the docs to see if there is some major issue between Detox and your forked lib.

**Comment by eleddie** [comment]
Thanks for the quick response. I followed the guide and the tests work fine thus I don't get any information on how to make it work with a normal `detox test`. Any ideas?

**Comment by LeoNatan** [comment]
If it works with Xcode, I don’t think it’s a problem with Detox.

**Comment by eleddie** [comment]
It could be something like this https://github.com/wix/Detox/issues/1826 since it shows this:
```
detox[6875] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.
```
but I can't find any url to add to the blacklist. Any other ways to log the requests?

**Comment by LeoNatan** [comment]
No. In that case, what I suggested first would have shown this.

**Comment by eleddie** [comment]
I can't run the app following `debugging in Xcode` in a real device. I get this:
```
/Users/eduardosanchez/Library/Developer/Xcode/DerivedData/DetoxYoutubeIssue-bxtznflfrgokdkgeprrgzwnvbyhq/Build/Products/Debug-iphoneos/Detox.framework/Detox' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/eduardosanchez/Library/Developer/Xcode/DerivedData/DetoxYoutubeIssue-bxtznflfrgokdkgeprrgzwnvbyhq/Build/Products/Debug-iphoneos/Detox.framework/Detox' for architecture arm64
```

**Comment by LeoNatan** [comment]
Real devices are not supported in Detox, only simulators.

**Comment by eleddie** [comment]
Even though the project was working fine, I added the youtube framework to embedded libraries and the tests started to work.
Thanks for the help. I'll close the issue

**Comment by LeoNatan** [comment]
Embedded binaries is used for dynamic frameworks. Make sure this is what your fork is producing.

You should be using Xcode 11 by now, which simplifies these steps. A reminder that starting April 2020, Apple will require Xcode 11 for store submissions.

Another note is that RN 0.6x.y+ require CocoaPods, unfortunately. So you won't have a choice but to move.

**Comment by eleddie** [comment]
Thanks for the advice. Will definitely check it out 👍
