### ISSUE TITLE
yarn install build error

### ISSUE THREAD

**Issue by mluu510** [wix/Detox#1866]
when i run yarn install i get this:
`
[12/31] ⠈ detox
error /Users/mluu/Developer/mobile2/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/mluu/Developer/mobile2/node_modules/detox
Output:
/Users/mluu/Library/Detox/ios/10dbe0f0b761264d99edb06a7f9b999416aad111 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/mluu/Library/Detox/ios/10dbe0f0b761264d99edb06a7f9b999416aad111 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/mluu/Developer/mobile2/node_modules/detox/ios_src...
child_process.js:637
    throw err;
    ^

Error: Command failed: /Users/mluu/Developer/mobile2/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Object.<anonymous> (/Users/mluu/Developer/mobile2/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
`

what the heck is going on?

**Comment by LeoNatan** [comment]
Please try using the latest Detox version. You should see a better error message. If it persists, open a new BUG issue and provide the requested logs.

Thanks
