### ISSUE TITLE
Android app crashes on launch with latest Detox & React Native

### ISSUE THREAD

**Issue by brunobar79** [wix/Detox#1922]
**Describe the bug**

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1.  Run `detox build -c android.emu.debug`
2. Run `detox test -c android.emu.debug`
3.  App crashes after launch 

BTW. I can manually launch the app after that and it works fine.

This is the crash log from `adb logcat`

```
2020-02-20 21:25:16.557 14825-14916/me.rainbow E/TimersIdlingResource: Failed to determine proper implementation-strategy for timers idling resource
    
    --------- beginning of crash
2020-02-20 21:25:16.558 14825-14916/me.rainbow E/AndroidRuntime: FATAL EXCEPTION: com.wix.detox.manager
    Process: me.rainbow, PID: 14825
    kotlin.KotlinNullPointerException
        at com.wix.detox.reactnative.ReactNativeIdlingResources.setupCustomRNIdlingResources(ReactNativeIdlingResources.kt:113)
        at com.wix.detox.reactnative.ReactNativeIdlingResources.registerAll(ReactNativeIdlingResources.kt:71)
        at com.wix.detox.reactnative.ReactNativeExtension.setupIdlingResources(ReactNativeExtension.kt:104)
        at com.wix.detox.reactnative.ReactNativeExtension.setupIdlingResources$default(ReactNativeExtension.kt:102)
        at com.wix.detox.reactnative.ReactNativeExtension.waitForRNBootstrap(ReactNativeExtension.kt:60)
        at com.wix.detox.DetoxManager.initReactNativeIfNeeded(DetoxManager.java:129)
        at com.wix.detox.DetoxManager.access$000(DetoxManager.java:25)
        at com.wix.detox.DetoxManager$1.run(DetoxManager.java:72)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at com.wix.detox.Detox$1.run(Detox.java:131)
        at java.lang.Thread.run(Thread.java:919)

```

**Expected behavior**
App shouldn't crash and tests should run normally

**Screenshots**

Here's a video that shows the issue: https://recordit.co/heHwoUjbxw

**Device and Verbose Detox Logs**

**Environment (please complete the following information):**
 - Detox: v15.2.2
 - React Native: v0.62.rc.2
 - Node: v13.70
 - Device: Nexus 5 API 29
 - OS: MacOSx
 - Test-runner (select one):Jest+jasmine

**Comment by d4vidi** [comment]
@brunobar79 We do not yet officially support RN .62, both because it's in RC but also we're waiting for feedback regarding internal Detox integ. work currently in progress (see #1886).

**Comment by firdausious** [comment]
@brunobar79  @d4vidi  Found this one too.. exactly the same... still happen in newest RC..

Environment:
- Detox: v16.0.1
- React Native: v0.62.rc.5
- Node: v12.12.0
- Device: Pixel 3 API 29
- OS: MacOS
- Test-runner:Mocha

**Comment by d4vidi** [comment]
RN .62 is not yet officially supported by Detox (Android), although we _did_ expect it to work immediately since it is now in part integrated into RN itself. Nevertheless, now that .62 is out of beta we'll smooth things out asap.
