### ISSUE TITLE
Tests that refer to source that uses a native module, fail to compile with syntax error.

### ISSUE THREAD

**Issue by jonmountjoy** [wix/Detox#1941]
### Description

If my detox test references a file in my source code base that uses `react-native-sqlite-storage`, the test fails in some pre-compilation step with a SyntaxError.  Referencing `axios` in the same way, doesn't yield a problem.

Most of detox doesn't start - it fails quickly.

I have a simple [React Native app](https://github.com/jonmountjoy/detox-problem), to which I've only added detox, `axios` and `react-native-sqlite-storage`.

- I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

1. Clone [this repo](https://github.com/jonmountjoy/detox-problem)
2. yarn install; detox build; detox test

Alternatively, `yarn add react-native-sqlite-storage` and modify your test to include a reference to a file that requires it.

#### Expected behavior

I expect the test to start, not to have an odd syntax error.

#### Environment (please complete the following information):
 - Detox: 15.4.2
 - React Native: 0.61.5
 - Node: 10.17.0

#### If you are experiencing a timeout in your test
- [ ] I have followed the instructions under [Lower-level Idling Resources Debug](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) and am providing the log below:

#### If you are seeing a build problem (e.g. during `npm install`)
- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs

```
detox test --loglevel trace
detox[82974] INFO:  [test.js] node_modules/.bin/mocha --opts e2e/mocha.opts --configuration ios.sim.debug --loglevel trace --grep :android: --invert "e2e"
(node:82975) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.

/private/tmp/jsNodeBug/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/private/tmp/jsNodeBug/node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/private/tmp/jsNodeBug/node_modules/react-native-sqlite-storage/lib/sqlite.core.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/private/tmp/jsNodeBug/node_modules/react-native-sqlite-storage/sqlite.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/private/tmp/jsNodeBug/src/Engine.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/private/tmp/jsNodeBug/e2e/firstTest.spec.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /private/tmp/jsNodeBug/node_modules/mocha/lib/mocha.js:314:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/private/tmp/jsNodeBug/node_modules/mocha/lib/mocha.js:311:14)
    at /private/tmp/jsNodeBug/node_modules/mocha/lib/mocha.js:347:12
    at new Promise (<anonymous>)
    at Mocha.loadFilesAsync (/private/tmp/jsNodeBug/node_modules/mocha/lib/mocha.js:346:12)
    at singleRun (/private/tmp/jsNodeBug/node_modules/mocha/lib/cli/run-helpers.js:107:15)
    at exports.runMocha (/private/tmp/jsNodeBug/node_modules/mocha/lib/cli/run-helpers.js:144:11)
    at Object.exports.handler (/private/tmp/jsNodeBug/node_modules/mocha/lib/cli/run.js:306:11)
    at Object.runCommand (/private/tmp/jsNodeBug/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/private/tmp/jsNodeBug/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/private/tmp/jsNodeBug/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/private/tmp/jsNodeBug/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/private/tmp/jsNodeBug/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
detox[82974] ERROR: [cli.js] Error: Command failed: node_modules/.bin/mocha --opts e2e/mocha.opts --configuration ios.sim.debug --loglevel trace --grep :android: --invert "e2e"

```

**Comment by LeoNatan** [comment]
Detox runs in its own Node process, which runs on your Mac, not the simulator. That sqlite package has native dependencies: https://github.com/andpor/react-native-sqlite-storage/tree/master/platforms

How do you expect Detox to be able to use those? That's not how things work.

**Comment by jonmountjoy** [comment]
Ah - I thought it ran on the app in the simulator, which is what I need.  

Thank you - my apologies.

**Comment by LeoNatan** [comment]
Cheers. Check out our mocking docs.
