### ISSUE TITLE
"at least 75 percent of the view's area is displayed to the user"

### ISSUE THREAD

**Issue by andybee** [wix/Detox#1951]
**Describe the bug**
Any test that attempts to locate an element by ID returns the error "at least 75 percent of the view's area is displayed to the user".

**To Reproduce**
- [x] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**
Element is selected, or other error related to inability to select the item.

**Device and Verbose Detox Logs**
```
    com.wix.detox.espresso.DetoxErrors$DetoxRuntimeException: 30.0sec timeout expired without matching of given matcher: at least 75 percent of the view's area is displayed to the user.
    	at com.wix.detox.espresso.DetoxAssertion.waitForAssertMatcher(DetoxAssertion.java:58)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:443)
    	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
    	at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
    	at com.wix.invoke.types.Target.invoke(Target.java:59)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
    	at com.wix.detox.InvokeActionHandler.handle(DetoxActionHandlers.kt:52)
    	at com.wix.detox.DetoxManager$4.run(DetoxManager.java:121)
    	at android.os.Handler.handleCallback(Handler.java:873)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loop(Looper.java:193)
    	at com.wix.detox.Detox$1.run(Detox.java:135)
    	at java.lang.Thread.run(Thread.java:764)
```

**Environment (please complete the following information):**
 - Detox: 15.4.4
 - React Native: 0.61.5
 - Node: 12.16.1
 - Device: Emulator (Pixel XL API 28)
 - OS: macOS 10.14.6
 - Test-runner (select one): Jest+jasmine

**Comment by d4vidi** [comment]
@andybee I'm sorry but I won't be able to help without screenshots and actual device logs. The description is too generic.
