### ISSUE TITLE
Detox is unable to launch the app on the simulator and failed with timeout error

### ISSUE THREAD

**Issue by Binay1286** [wix/Detox#2026]
#### Description
Seeing thsi issue on MacOS Catalina. detox unable to launch the app on the Simulator.
Works fine on Macos HighSierra.
-->

* Detox: 14.3.1
* react-native-cli: 2.0.1
react-native: 0.60.5
* Node:v12.16.2
* Device: simulator iPhone X 12.2
* Xcode: 11.1
* macOS: Cartalina

#### Device and verbose Detox logs
02HW045446:e2e-react-native-detox binay$ detox test --debug-synchronization 200
detox[18076] INFO:  [test.js] configuration="ios.sim.release" debugSynchronization=200 artifactsLocation="artifacts/ios.sim.release.2020-04-29 22-47-07Z" recordLogs="none" takeScreenshots="manual" recordVideos="none" recordPerformance="none" reportSpecs=true node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' "e2e"
detox[18077] INFO:  [DetoxServer.js] server listening on localhost:57623...
my-test.test.js assigned to undefined

Example: should show "Step One" at the begging
Example: should show "Step One" at the begging [FAIL]
Example: should render "See Your Changes" in the second slide
Example: should render "See Your Changes" in the second slide [FAIL]
Example: should enable swiping back and forth
Example: should enable swiping back and forth [FAIL]
Example: should render "Debug" and have a Button to click in the third slide
Example: should render "Debug" and have a Button to click in the third slide [FAIL]
Example: should render "Learn More" and change text in the fourth slide
Example: should render "Learn More" and change text in the fourth slide [FAIL]

 FAIL  e2e/my-test.test.js (301.035s)
  Example
    ✕ should show "Step One" at the begging (4ms)
    ✕ should render "See Your Changes" in the second slide (1ms)
    ✕ should enable swiping back and forth (2ms)
    ✕ should render "Debug" and have a Button to click in the third slide (1ms)
    ✕ should render "Learn More" and change text in the fourth slide (1ms)

  ● Example › should show "Step One" at the begging

    Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Example › should show "Step One" at the begging

    ReferenceError: device is not defined

      3 | describe('Example', () => {
      4 |   beforeEach(async () => {
    > 5 |     await device.disableSynchronization();
        |           ^
      6 |     await device.setURLBlacklist(['.*127.0.0.1.*']);
      7 |     //await device.reloadReactNative();
      8 |   });

      at _callee$ (my-test.test.js:5:11)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee (my-test.test.js:4:14)

  ● Example › should show "Step One" at the begging

    ReferenceError: element is not defined

       8 |   });
       9 | 
    > 10 |   it('should show "Step One" at the begging', async () => {
         |                                               ^
      11 |     await expect(element(by.text('Step One'))).toBeVisible();
      12 |   });
      13 | 

      at _callee2$ (my-test.test.js:10:47)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee2 (my-test.test.js:10:47)

  ● Example › should render "See Your Changes" in the second slide

    Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Example › should render "See Your Changes" in the second slide

    ReferenceError: device is not defined

      3 | describe('Example', () => {
      4 |   beforeEach(async () => {
    > 5 |     await device.disableSynchronization();
        |           ^
      6 |     await device.setURLBlacklist(['.*127.0.0.1.*']);
      7 |     //await device.reloadReactNative();
      8 |   });

      at _callee$ (my-test.test.js:5:11)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee (my-test.test.js:4:14)

  ● Example › should render "See Your Changes" in the second slide

    ReferenceError: element is not defined

      12 |   });
      13 | 
    > 14 |   it('should render "See Your Changes" in the second slide', async () => {
         |                                                              ^
      15 |     await element(by.id('slides')).swipe('left');
      16 |     await expect(element(by.text('See Your Changes'))).toBeVisible();
      17 |   });

      at _callee3$ (my-test.test.js:14:62)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee3 (my-test.test.js:14:62)

  ● Example › should enable swiping back and forth

    Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Example › should enable swiping back and forth

    ReferenceError: device is not defined

      3 | describe('Example', () => {
      4 |   beforeEach(async () => {
    > 5 |     await device.disableSynchronization();
        |           ^
      6 |     await device.setURLBlacklist(['.*127.0.0.1.*']);
      7 |     //await device.reloadReactNative();
      8 |   });

      at _callee$ (my-test.test.js:5:11)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee (my-test.test.js:4:14)

  ● Example › should enable swiping back and forth

    ReferenceError: element is not defined

      17 |   });
      18 | 
    > 19 |   it('should enable swiping back and forth', async () => {
         |                                              ^
      20 |     await expect(element(by.text('Step One'))).toBeVisible();
      21 |     await element(by.id('slides')).swipe('left');
      22 |     await element(by.id('slides')).swipe('right');

      at _callee4$ (my-test.test.js:19:46)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee4 (my-test.test.js:19:46)

  ● Example › should render "Debug" and have a Button to click in the third slide

    Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Example › should render "Debug" and have a Button to click in the third slide

    ReferenceError: device is not defined

      3 | describe('Example', () => {
      4 |   beforeEach(async () => {
    > 5 |     await device.disableSynchronization();
        |           ^
      6 |     await device.setURLBlacklist(['.*127.0.0.1.*']);
      7 |     //await device.reloadReactNative();
      8 |   });

      at _callee$ (my-test.test.js:5:11)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee (my-test.test.js:4:14)

  ● Example › should render "Debug" and have a Button to click in the third slide

    ReferenceError: element is not defined

      24 |   });
      25 | 
    > 26 |   it('should render "Debug" and have a Button to click in the third slide', async () => {
         |                                                                             ^
      27 |     await element(by.id('slides')).swipe('left');
      28 |     await element(by.id('slides')).swipe('left');
      29 |     await expect(element(by.text('Debug'))).toBeVisible();

      at _callee5$ (my-test.test.js:26:77)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee5 (my-test.test.js:26:77)

  ● Example › should render "Learn More" and change text in the fourth slide

    Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Example › should render "Learn More" and change text in the fourth slide

    ReferenceError: device is not defined

      3 | describe('Example', () => {
      4 |   beforeEach(async () => {
    > 5 |     await device.disableSynchronization();
        |           ^
      6 |     await device.setURLBlacklist(['.*127.0.0.1.*']);
      7 |     //await device.reloadReactNative();
      8 |   });

      at _callee$ (my-test.test.js:5:11)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee (my-test.test.js:4:14)

  ● Example › should render "Learn More" and change text in the fourth slide

    ReferenceError: element is not defined

      33 |   });
      34 | 
    > 35 |   it('should render "Learn More" and change text in the fourth slide', async () => {
         |                                                                        ^
      36 |     await element(by.id('slides')).swipe('left');
      37 |     await element(by.id('slides')).swipe('left');
      38 |     await element(by.id('slides')).swipe('left');

      at _callee6$ (my-test.test.js:35:72)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:170:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:192:13)
      at AsyncIterator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:219:14)
      at Object._callee6 (my-test.test.js:35:72)

Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

**Comment by LeoNatan** [comment]
Try upgrading applesimutils. Also, please open issues with the designated issue templates.

**Comment by Binay1286** [comment]
Thanks LeoNatan. Sure going forward will keep that in mind while opening issues.
I have the latest applesimutils version 0.7.7 installed.

Could you please help me with the below issue?below is the part of code from Detoxserver.js file,
class DetoxServer {
  constructor({ port, log, standalone = false }) {
    this.wss = new WebSocketServer({ port });
    this.sessions = {};
    this.standalone = standalone;
    this.log = log.child({ __filename });
    this.log.info(`server listening on localhost:${this.wss.options.port}...`);
    this._setup();
  }

  _setup() {
    this.wss.on('connection', (ws) => {
      let sessionId;
      let role;
      ws.on('message', (str) => {
        try {
          const action = JSON.parse(str);
          if (!action.type) {
            return;
          }

So my issue here is the _setup() function called when you execute the command detox test but it never entered inside the loop  this.wss.on('connection', (ws) => {} for which the applesimutils.js does not start and also the the Login with the tester never happen.

Appreciate your help.

**Comment by LeoNatan** [comment]
Please open a new issue with your finding. I am not familiar with this part of the code.
