### ISSUE TITLE
DetoxRuntimeError: Failed to run application on the device on Android

### ISSUE THREAD

**Issue by ManAnRuck** [wix/Detox#2042]
**Describe the bug**

with github actions I get very often the same issue.
1 test works great 3 others are failing.
it looks like the emulator is running  (I see the completed progress bar of the bundler ./index.js)
but then I get the following error messages:

```
2020-05-06T15:52:20.7250140Z Loading dependency graph, done.
2020-05-06T15:54:12.4560040Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #29] ""/Users/runner/android-sdk/platform-tools/adb" -s emulator-17542 shell "ps | grep \"de\.democracydeutschland\.app\.internal$\""" failed with code = 1, stdout and stderr:
2020-05-06T15:54:12.4560460Z 
2020-05-06T15:54:12.4560900Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #29] 
2020-05-06T15:54:12.4561230Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #29] 
2020-05-06T15:54:15.1112660Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #30] ""/Users/runner/android-sdk/platform-tools/adb" -s emulator-17542 shell "ps | grep \"de\.democracydeutschland\.app\.internal$\""" failed with code = 1, stdout and stderr:
2020-05-06T15:54:15.1114830Z 
2020-05-06T15:54:15.1115460Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #30] 
2020-05-06T15:54:15.1115910Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #30] 
2020-05-06T15:55:25.6101620Z  BUNDLE  [android, dev] ./index.js â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“ 100.0% (1709/1709), done.
2020-05-06T15:55:25.6102350Z 
2020-05-06T15:55:29.7432860Z detox[8903] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
2020-05-06T15:55:29.7534490Z  DetoxRuntimeError: Failed to run application on the device
2020-05-06T15:55:29.7634660Z 
2020-05-06T15:55:29.7736620Z HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
2020-05-06T15:55:29.7767360Z     at EmulatorDriver._getInstrumentationCrashError (/Users/runner/runners/2.169.1/work/democracy-client/democracy-client/packages/mobile-app/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:170:12)
2020-05-06T15:55:29.7771560Z     at EmulatorDriver.instrumentationCloseListener (/Users/runner/runners/2.169.1/work/democracy-client/democracy-client/packages/mobile-app/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:133:67)
2020-05-06T15:55:29.7852090Z     at EmulatorDriver._terminateInstrumentation (/Users/runner/runners/2.169.1/work/democracy-client/democracy-client/packages/mobile-app/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:161:12)
2020-05-06T15:55:29.7852690Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-05-06T15:55:29.7884560Z     at ChildProcess.<anonymous> (/Users/runner/runners/2.169.1/work/democracy-client/democracy-client/packages/mobile-app/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:279:7)
2020-05-06T15:55:29.7886340Z detox[8903] INFO:  Verification.test.ts is assigned to emulator-17542 (test)
2020-05-06T15:55:29.7887130Z detox[8903] INFO:  Verification: Szenario 1: Verifizieren via BurgerMenu/Profil
2020-05-06T15:56:24.0239080Z detox[8903] ERROR: [exec.js/EXEC_FAIL, #53] ""/Users/runner/android-sdk/platform-tools/adb" -s emulator-17542 shell "ps | grep \"de\.democracydeutschland\.app\.internal$\""" failed with code = 1, stdout and stderr:
```

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

**GitHub Action (trace logs)**
https://github.com/demokratie-live/democracy-client/runs/650341537?check_suite_focus=true

**Device and Verbose Detox Logs**

**Environment (please complete the following information):**
 - Detox: 16.4.0
 - React Native: 0.61.5
 - Node: 12.16.3
 - Device: Nexus 5X (29)
 - OS: mac (GitHub Actions)
 - Test-runner (select one): Jest+jasmine

**Comment by piotrpietruszewski99** [comment]
+1

**Comment by d4vidi** [comment]
@ManAnRuck,
1. Seems that your app has crashed prematurely -- failed to launch. Naturally, tests can succeed that way... https://github.com/demokratie-live/democracy-client/runs/650341537?check_suite_focus=true#step:14:508
2. Please use `release` builds on CI rather than debug.
