### ISSUE TITLE
SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by rishabh876** [wix/Detox#2044]
Hi, I am pretty new to React Native and Detox and facing some issue debugging the root cause of this issue. 

Basically for our test environment we first run our docker using
`npm run e2e -- --docker start`

e2e script is defined in package.json as 
`"e2e": "ts-node e2e/runner.ts",`

The error that I get is:

> @cb/mobile@0.0.1 e2e /Users/rishabhharit/Documents/GitHub/clearbook/packages/cb-mobile
> ts-node e2e/runner.ts "--docker" "start"

> /Users/rishabhharit/Documents/GitHub/clearbook/packages/cb-mobile/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

> SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:891:16)
    at Module._compile (internal/modules/cjs/loader.js:941:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Object.require.extensions.<computed> [as .js] (/Users/rishabhharit/Documents/GitHub/clearbook/packages/cb-mobile/node_modules/ts-node/src/index.ts:807:44)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rishabhharit/Documents/GitHub/clearbook/packages/cb-mobile/node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cb/mobile@0.0.1 e2e: `ts-node e2e/runner.ts "--docker" "start"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cb/mobile@0.0.1 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rishabhharit/.npm/_logs/2020-05-07T08_58_41_483Z-debug.log

[2020-05-07T08_58_41_483Z-debug.log](https://github.com/wix/Detox/files/4591898/2020-05-07T08_58_41_483Z-debug.log)

[runner.ts.zip](https://github.com/wix/Detox/files/4591946/runner.ts.zip)

Now I am unsure where to look at. Will provide more info as per request.

**Comment by noomorph** [comment]
This issue looks totally out of scope of the Detox project, closing.
