### ISSUE TITLE
Is it possible to run Detox tests on AWS Device Farm?

### ISSUE THREAD

**Issue by JavierGuevara-dou** [wix/Detox#2121]
I am trying to run my Detox tests on AWS Device Farm, I made the respective configurations of device name, session config, DetoxServer execution, adb reverse but not having positive results.

Detox version 16.7.0

I am getting this error in logs:

`DetoxRuntimeError: Failed to run application on the device

  HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
      at AttachedAndroidDriver._getInstrumentationCrashError (/tmp/scratchW57jK5.scratch/test-packageaVGUzQ/package/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:165:12)
      at AttachedAndroidDriver.instrumentationCloseListener (/tmp/scratchW57jK5.scratch/test-packageaVGUzQ/package/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:128:67)
      at Promise.race.Promise (/tmp/scratchW57jK5.scratch/test-packageaVGUzQ/package/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:129:55)
      at new Promise (<anonymous>)
      at AttachedAndroidDriver.waitUntilReady (/tmp/scratchW57jK5.scratch/test-packageaVGUzQ/package/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:127:11)
      at Device.launchApp (/tmp/scratchW57jK5.scratch/test-packageaVGUzQ/package/node_modules/detox/src/devices/Device.js:74:29)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)`

Some configuration I am missing maybe... someone has advice or ideas about this??

**Comment by JavierGuevara-dou** [comment]
https://stackoverflow.com/questions/62337085/your-tests-have-timed-out-and-called-detox-cleanup-while-it-was-waiting-for-r
