### ISSUE TITLE
BUILD FAILED Ld build/Build/Products/Debug-iphonesimulator

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#214]
**I'm trying to use Wix/Detox to test my react-native app (the iOS version). I have successfully followed the instructions (up until "detox build") at https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md**

**However, when running "detox build" in my project directory, I get the following error:**

    ** BUILD FAILED **
    
    The following commands produced analyzer issues:
    	Analyze RNFIRMessaging.m
    (1 command with analyzer issues)
    
    The following build commands failed:
    	Ld build/Build/Products/Debug-iphonesimulator/<myAppName>.app/<myAppName> normal x86_64
    (1 failure)
    child_process.js:524
        throw err;
        ^
    
    Error: Command failed: xcodebuild -project ios/<myAppName>.xcodeproj -scheme <myAppName> -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
        at checkExecSyncError (child_process.js:481:13)
        at Object.execSync (child_process.js:521:13)
        at Object.<anonymous> (/Users/<myUserName>/Documents/react-native-projects/<myAppName>/node_modules/detox/local-cli/detox-build.js:26:6)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:423:7)

**When running "detox test," I get the following error:**

    node_modules/.bin/mocha e2e --opts e2e/mocha.opts      
    
    
    detox info 09:31:22: server listening on localhost:50342...
    detox info 1: Listing devices... 
      1) "before all" hook

      0 passing (376ms)
      1 failing
    
      1)  "before all" hook:
         Error: field CFBundleIdentifier not found inside Info.plist of app binary at /Users/<myUserName>/Documents/react-native-projects/<myAppName>/ios/build/Build/Products/Debug-iphonesimulator/<myAppName>.app
          at SimulatorDriver._callee2$ (node_modules/detox/lib/devices/SimulatorDriver.js:28:19)
          at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
          at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
          at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:116:21)
          at step (node_modules/detox/lib/devices/SimulatorDriver.js:1:809)
          at node_modules/detox/lib/devices/SimulatorDriver.js:1:1008
    
    
    
    child_process.js:524
        throw err;
        ^
    
    Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts      
        at checkExecSyncError (child_process.js:481:13)
        at Object.execSync (child_process.js:521:13)
        at Object.<anonymous> (/Users/<myUserName>/Documents/react-native-projects/<myAppName>/node_modules/detox/local-cli/detox-test.js:46:4)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:423:7)

I have an e2e folder in my project directory with three files: init.js, mocha.opts, and firstTest.spec.js.

**firstTest.spec.js looks like this:**

    /* eslint-env node, mocha */
    /* global element, expect, device, by */

    describe('FiestTest', () => {
      beforeEach(async () => {
        await device.reloadReactNative()
      })
    
      it('Shoudl find the phoneInput field and the init value as "09"', async () => {
        await expect(element(by.id('LoginPage-phoneInput'))).toBeVisible()
        await element(by.id('LoginPage-phoneInput')).typeText('09120710732')
        await expect(element(by.id('LoginPage-loginGuideTxt'))).toBeVisible()
        await element(by.id('LoginPage-loginBtn')).tap()
      })
      it('Dummy1"', async () => {
        await device.reloadReactNative()
      })
      it('Dummy2', async () => {
        await device.reloadReactNative()
      })
      it('Dummy3', async () => {
        await device.reloadReactNative()
      })
    })

**init.js looks like this:**

    /* eslint-env node, mocha */
    
    require('babel-polyfill')
    const detox = require('detox')
    const config = require('../package.json').detox
    
    before(async () => {
      await detox.init(config)
    })
    
    after(async () => {
      await detox.cleanup()
    })

**And mocha.opts looks like this:**

    --recursive --timeout 120000 --bail

**Your help is highly appreciated!**

**Comment by mhyousefi** [comment]
**I ran the following command and it solved the build issue:**

`watchman watch-del-all; npm start -- --reset-cache`
