### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by jeanyJer** [wix/detox#215]
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release

  1) "before all" hook

  0 passing (296ms)
  1 failing

  1)  "before all" hook:
     TypeError: URL is not a constructor
      at Detox._callee$ (node_modules/detox/lib/Detox.js:58:49)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/detox/lib/Detox.js:1:1379)
      at node_modules/detox/lib/Detox.js:1:1539
      at process._tickCallback (internal/process/next_tick.js:109:7)
child_process.js:524
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.<anonymous> (/Users/devxu/Documents/workspace/detox/examples/demo-react-native/node_modules/detox/local-cli/detox-test.js:46:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

**Comment by rotemmiz** [comment]
Post your test code please, something must be wrong with it.

**Comment by jeanyJer** [comment]
@rotemmiz I just download the detox demo , and run it with the guide. But **Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release** always happened

**Comment by rotemmiz** [comment]
Are you following the requirements ? Using Node >7.6.0 ? 
https://github.com/wix/detox/tree/master/examples/demo-react-native#requirements

**Comment by jeanyJer** [comment]
@rotemmiz I have solved it .  Just like u said,  I upgrade my node version
