### ISSUE TITLE
waited a whole minute for the new RN-context

### ISSUE THREAD

**Issue by swabbass** [wix/Detox#2197]
**Describe the bug**

Running metro bundle that takes a bit more than one minutes cause the app to crash 
A good solution is a flag to increase this timeout or to change it.
**To Reproduce**

- [ ] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. have large project bundle (js) 
2. run detox test with debug configuration

**Expected behavior**

Tests to run.
**Screenshots**

**Device and Verbose Detox Logs**

```
    java.lang.RuntimeException: waited a whole minute for the new RN-context
        at com.wix.detox.reactnative.ReactNativeLoadingMonitor.awaitNewRNContext(ReactNativeLoadingMonitor.kt:56)
        at com.wix.detox.reactnative.ReactNativeLoadingMonitor.getNewContext(ReactNativeLoadingMonitor.kt:21)
        at com.wix.detox.reactnative.ReactNativeExtension.awaitNewReactNativeContext(ReactNativeExtension.kt:99)
        at com.wix.detox.reactnative.ReactNativeExtension.waitForRNBootstrap(ReactNativeExtension.kt:58)
        at com.wix.detox.DetoxManager.initReactNativeIfNeeded(DetoxManager.java:137)
        at com.wix.detox.DetoxManager.access$000(DetoxManager.java:26)
        at com.wix.detox.DetoxManager$2.run(DetoxManager.java:79)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at com.wix.detox.Detox$1.run(Detox.java:173)
        at java.lang.Thread.run(Thread.java:919)
```
**Environment (please complete the following information):**
 - Detox: 16.8.0
 - React Native: 0.62.0
 - Node: 10.16.0
 - Device: emulator pixel 3a xl
 - OS: Android 10
 - Test-runner: `jest-circus`

**Comment by d4vidi** [comment]
@swabbass `17.3.2`
