### ISSUE TITLE
Example app does not work when running test

### ISSUE THREAD

**Issue by robertclarkson** [wix/Detox#2304]
**Describe the bug**
Can not run the example app "demo-react-native". Errors out with the following error:
```
detox[6535] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=7f535840-9e09-9b31-f487-c35b2911ddaa)
```

**To Reproduce**

- [ X ] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
I ran all of the following commands 
```
git clone https://github.com/wix/Detox.git
cd Detox/
cd examples/
cd demo-react-native
npm install
detox build --configuration android.emu.release
detox test --configuration android.emu.release --loglevel trace
```
I did also have to change the avdName to match my emulator:
from 
```
"device": {
   "avdName": "Pixel_API_28"
}
```
to 
```
"device": {
    "avdName": "Pixel_2_API_28"
}
```
**Expected behavior**
Should work correctly

**Environment (please complete the following information):**
 - Detox: 17.4.5
CLI 
 - react-native-cli: 2.0.1
 - react-native: 0.62.2
package.json 
  - "react": "16.11.x",
   - "react-native": "0.62.x"
 - Node: v12.16.3
 - Device: emulator Pixel_API_28
 - OS: Ubuntu 18.04
 - Test-runner (select one): `jest-circus` ?

**Device and Verbose Detox Logs**
<details>
  <summary>Click to expand!</summary>  
```
detox[8682] INFO:  [test.js] node_modules/.bin/mocha --config e2e/.mocharc.json --configuration android.emu.release --invert --grep :ios: --use-custom-logger "true" e2e


detox[8694] INFO:  [DetoxServer.js] server listening on localhost:43745...
detox[8694] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
    at MonitoredInstrumentation._getInstrumentationCrashError (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:68:12)
    at MonitoredInstrumentation._rejectPendingCrashPromise (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:56:37)
    at MonitoredInstrumentation._onInstrumentationTerminated (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:51:10)
    at Instrumentation._onTerminated (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:52:18)
  1) "before all" hook in "{root}"
detox[8694] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.


  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
      at MonitoredInstrumentation._getInstrumentationCrashError (node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:68:12)
      at MonitoredInstrumentation._rejectPendingCrashPromise (node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:56:37)
      at MonitoredInstrumentation._onInstrumentationTerminated (node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:51:10)
      at Instrumentation._onTerminated (node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:52:18)



detox[8682] ERROR: [cli.js] Error: Command failed: node_modules/.bin/mocha --config e2e/.mocharc.json --configuration android.emu.release --invert --grep :ios: --use-custom-logger "true" e2e

tinfoil@tinfoil-ubuntu:~/Detox/examples/demo-react-native$ detox test --configuration android.emu.release --loglevel trace
detox[8801] INFO:  [test.js] node_modules/.bin/mocha --config e2e/.mocharc.json --configuration android.emu.release --loglevel trace --invert --grep :ios: --use-custom-logger "true" e2e


detox[8813] TRACE: [Detox.js/DETOX_CREATE] created a Detox instance with config:
{"artifactsConfig":{"rootDir":"artifacts/android.emu.release.2020-09-02 22-24-16Z","plugins":{"log":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"screenshot":{"enabled":true,"shouldTakeAutomaticSnapshots":false,"keepOnlyFailedTestsArtifacts":false},"video":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"instruments":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"timeline":{"enabled":false}},"pathBuilder":{"_rootDir":"artifacts/android.emu.release.2020-09-02 22-24-16Z"}},"behaviorConfig":{"init":{"reinstallApp":true,"exposeGlobals":true,"launchApp":true},"cleanup":{"shutdownDevice":false}},"cliConfig":{"configuration":"android.emu.release","loglevel":"trace","useCustomLogger":"true"},"deviceConfig":{"binaryPath":"android/app/build/outputs/apk/release/app-release.apk","build":"cd android ; ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release ; cd -","type":"android.emulator","device":{"avdName":"Pixel_API_28"}},"runnerConfig":{"testRunner":"mocha","runnerConfig":"e2e/.mocharc.json","specs":"e2e"},"sessionConfig":{"autoStart":true,"server":"ws://localhost:42771","sessionId":"bbccc999-5193-fe99-734f-59cdba1b29ca"},"errorBuilder":{"filepath":"/home/tinfoil/Detox/examples/demo-react-native/detox.config.js","contents":{"test-runner":"mocha","runner-config":"e2e/.mocharc.json","specs":"e2e","behavior":{"init":{"exposeGlobals":true}},"configurations":{"ios.sim.release":{"binaryPath":"ios/build/Build/Products/Release-iphonesimulator/example.app","build":"export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -project ios/example.xcodeproj -UseNewBuildSystem=NO -scheme example -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -quiet","type":"ios.simulator","device":{"type":"iPhone 11 Pro"}},"ios.sim.debug":{"binaryPath":"ios/build/Build/Products/Debug-iphonesimulator/example.app","build":"xcodebuild -project ios/example.xcodeproj -UseNewBuildSystem=NO -scheme example -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build","type":"ios.simulator","device":{"type":"iPhone 11 Pro"}},"ios.none":{"binaryPath":"ios/build/Build/Products/Debug-iphonesimulator/example.app","build":"xcodebuild -project ios/example.xcodeproj -UseNewBuildSystem=NO -scheme example -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build","type":"ios.none","device":{"type":"iPhone 11 Pro"},"session":{"server":"ws://localhost:8099","sessionId":"com.wix.demo.react.native"}},"android.emu.debug":{"binaryPath":"android/app/build/outputs/apk/debug/app-debug.apk","build":"cd android ; ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug ; cd -","type":"android.emulator","device":{"avdName":"Pixel_API_28"}},"android.emu.release":{"binaryPath":"android/app/build/outputs/apk/release/app-release.apk","build":"cd android ; ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release ; cd -","type":"android.emulator","device":{"avdName":"Pixel_API_28"}}}},"configurationName":"android.emu.release"}}
detox[8813] INFO:  [DetoxServer.js] server listening on localhost:42771...
detox[8813] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:42771
detox[8813] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"bbccc999-5193-fe99-734f-59cdba1b29ca","role":"tester"},"messageId":0}
detox[8813] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=bbccc999-5193-fe99-734f-59cdba1b29ca
detox[8813] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=bbccc999-5193-fe99-734f-59cdba1b29ca
detox[8813] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"bbccc999-5193-fe99-734f-59cdba1b29ca","role":"tester"},"messageId":0}
 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #0] "/home/tinfoil/Android/Sdk/emulator/emulator" -list-avds --verbose
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #0] Pixel_API_28

detox[8813] DEBUG: [exec.js/EXEC_CMD, #1] "/home/tinfoil/Android/Sdk/emulator/emulator" -version
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #1] Android emulator version 30.0.26.0 (build_id 6755297) (CL:N/A)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.


detox[8813] DEBUG: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 30, minor: 0, patch: 26 }
detox[8813] DEBUG: [AndroidDriver.js/ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_API_28"
detox[8813] DEBUG: [exec.js/EXEC_CMD, #2] "/home/tinfoil/Android/Sdk/platform-tools/adb"  devices
detox[8813] DEBUG: [exec.js/EXEC_SUCCESS, #2] List of devices attached
emulator-5554	device


detox[8813] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 5554, host: localhost
detox[8813] DEBUG: [FreeDeviceFinder.js/DEVICE_LOOKUP] Found a matching & free device emulator-5554
detox[8813] DEBUG: [AndroidDriver.js/ALLOCATE_DEVICE] Settled on emulator-5554
detox[8813] DEBUG: [exec.js/EXEC_CMD, #3] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "getprop dev.bootcomplete"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #3] 1

detox[8813] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-5554', type: 'Pixel_API_28' })
detox[8813] DEBUG: [exec.js/EXEC_CMD, #4] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #4] 28

detox[8813] DEBUG: [exec.js/EXEC_CMD, #5] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #5] 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #6] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "settings put global window_animation_scale 0"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #6] 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #7] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "settings put global transition_animation_scale 0"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #7] 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #8] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #8]   mWakefulness=Awake
  mWakefulnessChanging=false
  mWakeLockSummary=0x1
  mUserActivitySummary=0x1
  mWakeUpWhenPluggedOrUnpluggedConfig=false
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false

detox[8813] DEBUG: [exec.js/EXEC_CMD, #9] "/home/tinfoil/Android/Sdk/build-tools/30.0.2/aapt" dump badging "/home/tinfoil/Detox/examples/demo-react-native/android/app/build/outputs/apk/release/app-release.apk" | grep -e "package: name="
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #9] package: name='com.detox.rn.example' versionCode='1' versionName='1.0' compileSdkVersion='29' compileSdkVersionCodename='10'

detox[8813] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-5554', bundleId: 'com.detox.rn.example' })
detox[8813] DEBUG: [exec.js/EXEC_CMD, #10] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.detox.rn.example"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #10] package:com.detox.rn.example.test
package:com.detox.rn.example

detox[8813] DEBUG: [exec.js/EXEC_CMD, #11] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 uninstall com.detox.rn.example
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #11] Success

detox[8813] DEBUG: [exec.js/EXEC_CMD, #12] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.detox.rn.example.test"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #12] package:com.detox.rn.example.test

detox[8813] DEBUG: [exec.js/EXEC_CMD, #13] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 uninstall com.detox.rn.example.test
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #13] Success

detox[8813] DEBUG: [exec.js/EXEC_CMD, #14] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #14] 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #15] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #15] 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #16] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 push "/home/tinfoil/Detox/examples/demo-react-native/android/app/build/outputs/apk/release/app-release.apk" "/data/local/tmp/detox/Application.apk"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #16] /home/tinfoil/Detox/examples/demo-react-native/android/app/build/outputs/apk/release/app-release.apk: 1 file pushed, 0 skipped. 676.4 MB/s (18531059 bytes in 0.026s)

detox[8813] DEBUG: [exec.js/EXEC_CMD, #17] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #17] Success

detox[8813] DEBUG: [exec.js/EXEC_CMD, #18] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 push "/home/tinfoil/Detox/examples/demo-react-native/android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk" "/data/local/tmp/detox/Test.apk"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #18] /home/tinfoil/Detox/examples/demo-react-native/android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk: 1 file pushed, 0 skipped. 2898.6 MB/s (1036351 bytes in 0.000s)

detox[8813] DEBUG: [exec.js/EXEC_CMD, #19] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Test.apk"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #19] Success

detox[8813] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-5554', bundleId: 'com.detox.rn.example' })
detox[8813] DEBUG: [exec.js/EXEC_CMD, #20] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop com.detox.rn.example"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #20] 
detox[8813] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({ deviceId: 'emulator-5554', bundleId: 'com.detox.rn.example' })
detox[8813] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-5554',
  bundleId: 'com.detox.rn.example',
  launchArgs: {
    detoxServer: 'ws://localhost:42771',
    detoxSessionId: 'bbccc999-5193-fe99-734f-59cdba1b29ca'
  }
})
detox[8813] DEBUG: [exec.js/EXEC_CMD, #21] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "date +\"%m-%d %T.000\""
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #21] 09-03 10:24:17.000

detox[8813] DEBUG: [exec.js/EXEC_CMD, #22] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 reverse tcp:42771 tcp:42771
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #22] 
detox[8813] DEBUG: [exec.js/EXEC_CMD, #23] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "pm list instrumentation"
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #23] instrumentation:com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner (target=com.detox.rn.example)
instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)
instrumentation:sports.kiwi.test/com.android.test.runner.MultiDexTestRunner (target=sports.kiwi)

detox[8813] DEBUG: [exec.js/SPAWN_CMD, #24] [pid=8895] /home/tinfoil/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:42771 -e detoxSessionId bbccc999-5193-fe99-734f-59cdba1b29ca -e debug false com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner
detox[8813] DEBUG: [exec.js/EXEC_CMD, #25] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.detox\.rn\.example$\""
detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #25] u0_a137       5289  1740 1461768 100728 0                   0 S com.detox.rn.example

detox[5289] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({
  deviceId: 'emulator-5554',
  bundleId: 'com.detox.rn.example',
  launchArgs: {
    detoxServer: 'ws://localhost:42771',
    detoxSessionId: 'bbccc999-5193-fe99-734f-59cdba1b29ca'
  },
  pid: 5289
})
detox[8813] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[8813] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=bbccc999-5193-fe99-734f-59cdba1b29ca)
detox[8813] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=bbccc999-5193-fe99-734f-59cdba1b29ca)
detox[8813] TRACE: [exec.js/SPAWN_STDOUT, #24] INSTRUMENTATION_STATUS: class=com.example.DetoxTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.example.DetoxTest:

detox[8813] TRACE: [exec.js/SPAWN_STDOUT, #24] INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS_CODE: 1

detox[8813] TRACE: [exec.js/SPAWN_STDOUT, #24] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

detox[8813] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 8895]: /home/tinfoil/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:42771 -e detoxSessionId bbccc999-5193-fe99-734f-59cdba1b29ca -e debug false com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner
detox[8813] TRACE: [exec.js/SPAWN_END, #24] /home/tinfoil/Android/Sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:42771 -e detoxSessionId bbccc999-5193-fe99-734f-59cdba1b29ca -e debug false com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner finished with code = 0
detox[8813] DEBUG: [exec.js/EXEC_CMD, #26] "/home/tinfoil/Android/Sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:42771
detox[8813] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
    at MonitoredInstrumentation._getInstrumentationCrashError (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:68:12)
    at MonitoredInstrumentation._rejectPendingCrashPromise (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:56:37)
    at MonitoredInstrumentation._onInstrumentationTerminated (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:51:10)
    at Instrumentation._onTerminated (/home/tinfoil/Detox/examples/demo-react-native/node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:52:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  1) "before all" hook in "{root}"
detox[8813] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeCleanup()
detox[8813] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

detox[8813] TRACE: [exec.js/EXEC_SUCCESS, #26] 
detox[8813] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=bbccc999-5193-fe99-734f-59cdba1b29ca
detox[8813] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
      at MonitoredInstrumentation._getInstrumentationCrashError (node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:68:12)
      at MonitoredInstrumentation._rejectPendingCrashPromise (node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:56:37)
      at MonitoredInstrumentation._onInstrumentationTerminated (node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:51:10)
      at Instrumentation._onTerminated (node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:52:18)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)



detox[8801] ERROR: [cli.js] Error: Command failed: node_modules/.bin/mocha --config e2e/.mocharc.json --configuration android.emu.release --loglevel trace --invert --grep :ios: --use-custom-logger "true" e2e
```
</details>

**Comment by ReshmiCode** [comment]
I'm having an error building the iOS version
<img width="1058" alt="Screen Shot 2020-09-03 at 10 37 22 AM" src="https://user-images.githubusercontent.com/16989366/92136321-81cf0f80-edd1-11ea-9bdd-32bf6297ba90.png">

**Comment by FatjonRrapaj** [comment]
@ReshmiCode Try this config:

  "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/Truckers Network.app",
        "build": "xcodebuild -workspace ios/dc.xcworkspace -scheme dc -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "device": {
          "type": "iPhone 8 Plus"
        }
      }

**Comment by d4vidi** [comment]
@robertclarkson seems that your app is crashing on launch. Visit the _device_ logs to get to complete picture (for example, by running Detox with `detox test ... --record-logs all`).

**Comment by robertclarkson** [comment]
Thanks for the help I'm not sure what was causing this now but it is now working.
