### ISSUE TITLE
postinstall script fails for detox@15.5.0

### ISSUE THREAD

**Issue by jayshah123** [wix/Detox#2350]
### Description
detox installation postinstall fails for detox 15.5.0
- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. npm install
```
/Users/jay.shah/Library/Detox/ios/0df729392f205c2e9f04eba5815391828fb10225 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/jay.shah/Library/Detox/ios/0df729392f205c2e9f04eba5815391828fb10225 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/jay.shah/Documents/freshworkspace/ipartner/node_modules/detox/ios_src...
child_process.js:637
    throw err;
    ^

Error: Command failed: /Users/jay.shah/Documents/freshworkspace/ipartner/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Object.<anonymous> (/Users/jay.shah/Documents/freshworkspace/ipartner/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

```
#### Expected behavior
install should work properly

#### Environment (please complete the following information):
 - Detox: 15.5.0
 - React Native: 0.61.5
 - Node: 10.15.0
 - Device: mac OSX 
 - Xcode: 12
 - iOS: 14
 - macOS: 10.15.6 

#### If you are seeing a build problem (e.g. during `npm install`)
- [ X] I am providing the `npm install` log below:
https://gist.github.com/jayshah123/b00d6630083b96c22b27e8e58e793528

**Comment by LeoNatan** [comment]
Use latest release with Xcode 12. iOS 14 is not yet supported, so make sure to test on iOS 13 devices for the time being.

**Comment by LeoNatan** [comment]
Follow iOS 14 support here: https://github.com/wix/Detox/issues/2346

**Comment by jayshah123** [comment]
Appreciate the quick revert, thanks.
