### ISSUE TITLE
Unable to run tests on Android

### ISSUE THREAD

**Issue by wnz99** [wix/Detox#2364]
**Describe the bug**
I've followed the instructions to install Detox on an existing React Native application but cannot run the tests. 

I've tried to to build the app separately (not through Detox) and it runs on the emulator without issues.

**To Reproduce**

- [ x ] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Follow the initial setup instructions.
2. Add the following configuration to `.detoxrc.json`

```
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "configurations": {
    "android.emu.debug": {
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_2_API_28"
      }
    },
    "android.emu.release": {
      "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
      "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release --scan && cd ..",
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_2_API_28"
      }
    }
  }
}
```
3. Build the app with `detox build --configuration android.emu.debug`
4. Run the tests with `detox test --configuration android.emu.debug `

**Expected behavior**
Tests should run

**Screenshots**
![image](https://user-images.githubusercontent.com/12447140/94360079-d5680c80-00a2-11eb-8425-c11e5dbb1201.png)

**Device and Verbose Detox Logs**
```
(base) whitenoise@xxx:~/Desktop/pole-app/packages/pole-app-mobile$ detox test --configuration android.emu.debug --loglevel trace
detox[110455] INFO:  [test.js] configuration="android.emu.debug" loglevel="trace" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1601194514327 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e              
watchman warning:  Recrawled this watch 19 times, most recently because:
dir missing from internal stateTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del /home/whitenoise/Desktop/pole-app/packages/pole-app-mobile ; watchman watch-project /home/whitenoise/Desktop/pole-app/packages/pole-app-mobile`

detox[110467] TRACE: [Detox.js/DETOX_CREATE] created a Detox instance with config:
{"artifactsConfig":{"rootDir":"artifacts/android.emu.debug.2020-09-27 08-15-14Z","plugins":{"log":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"screenshot":{"enabled":true,"shouldTakeAutomaticSnapshots":false,"keepOnlyFailedTestsArtifacts":false},"video":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"instruments":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"timeline":{"enabled":false}},"pathBuilder":{"_rootDir":"artifacts/android.emu.debug.2020-09-27 08-15-14Z"}},"behaviorConfig":{"init":{"reinstallApp":true,"exposeGlobals":true,"launchApp":true},"cleanup":{"shutdownDevice":false}},"cliConfig":{"configuration":"android.emu.debug","forceAdbInstall":"false","loglevel":"trace","useCustomLogger":"true"},"deviceConfig":{"binaryPath":"android/app/build/outputs/apk/debug/app-debug.apk","build":"cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..","type":"android.emulator","device":{"avdName":"Pixel_2_API_28"}},"runnerConfig":{"testRunner":"jest","runnerConfig":"e2e/config.json","specs":"e2e"},"sessionConfig":{"autoStart":true,"server":"ws://localhost:35143","sessionId":"857ed74b-3be3-7ad4-2fb7-e14672024205"},"errorBuilder":{"filepath":"/home/whitenoise/Desktop/pole-app/packages/pole-app-mobile/.detoxrc.json","contents":{"testRunner":"jest","runnerConfig":"e2e/config.json","configurations":{"android.emu.debug":{"binaryPath":"android/app/build/outputs/apk/debug/app-debug.apk","build":"cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..","type":"android.emulator","device":{"avdName":"Pixel_2_API_28"}},"android.emu.release":{"binaryPath":"android/app/build/outputs/apk/release/app-release.apk","build":"cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release --scan && cd ..","type":"android.emulator","device":{"avdName":"Pixel_2_API_28"}}}},"configurationName":"android.emu.debug"}}                                                                                                                               
detox[110467] INFO:  [DetoxServer.js] server listening on localhost:35143...
detox[110467] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:35143
detox[110467] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"857ed74b-3be3-7ad4-2fb7-e14672024205","role":"tester"},"messageId":0}
detox[110467] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=857ed74b-3be3-7ad4-2fb7-e14672024205
detox[110467] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=857ed74b-3be3-7ad4-2fb7-e14672024205
detox[110467] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"857ed74b-3be3-7ad4-2fb7-e14672024205","role":"tester"},"messageId":0}
 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #0] "/home/whitenoise/Android/Sdk/emulator/emulator" -list-avds --verbose
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #0] 2.7_QVGA_API_R
Nexus_S_API_R
Pixel_2_API_28
Pixel_3a_API_29

detox[110467] DEBUG: [exec.js/EXEC_CMD, #1] "/home/whitenoise/Android/Sdk/emulator/emulator" -version
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #1] Android emulator version 30.0.26.0 (build_id 6755297) (CL:N/A)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.


detox[110467] DEBUG: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 30, minor: 0, patch: 26, toString: [Function: toString] }
detox[110467] DEBUG: [AndroidDriver.js/ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_2_API_28"
detox[110467] DEBUG: [exec.js/EXEC_CMD, #2] "/home/whitenoise/Android/Sdk/platform-tools/adb"  devices
detox[110467] DEBUG: [exec.js/EXEC_SUCCESS, #2] List of devices attached
emulator-14500  device


detox[110467] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 14500, host: localhost
detox[110467] DEBUG: [FreeDeviceFinder.js/DEVICE_LOOKUP] Found a matching & free device emulator-14500
detox[110467] DEBUG: [AndroidDriver.js/ALLOCATE_DEVICE] Settled on emulator-14500
detox[110467] DEBUG: [exec.js/EXEC_CMD, #3] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "getprop dev.bootcomplete"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #3] 1

detox[110467] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-14500', type: 'Pixel_2_API_28' })
detox[110467] DEBUG: [exec.js/EXEC_CMD, #4] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "getprop ro.build.version.sdk"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #4] 28

detox[110467] DEBUG: [exec.js/EXEC_CMD, #5] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "settings put global animator_duration_scale 0"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #5] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #6] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "settings put global window_animation_scale 0"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #6] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #7] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "settings put global transition_animation_scale 0"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #7] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #8] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #8]   mWakefulness=Awake
  mWakefulnessChanging=false
  mWakeLockSummary=0x0
  mUserActivitySummary=0x1
  mWakeUpWhenPluggedOrUnpluggedConfig=false
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false

detox[110467] DEBUG: [exec.js/EXEC_CMD, #9] "/home/whitenoise/Android/Sdk/build-tools/30.0.0-rc2/aapt" dump badging "/home/whitenoise/Desktop/pole-app/packages/pole-app-mobile/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #9] package: name='com.poleappmobile' versionCode='1' versionName='1.0' compileSdkVersion='28' compileSdkVersionCodename='9'

detox[110467] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-14500', bundleId: 'com.poleappmobile' })
detox[110467] DEBUG: [exec.js/EXEC_CMD, #10] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "pm list packages com.poleappmobile"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #10] package:com.poleappmobile.test

detox[110467] DEBUG: [exec.js/EXEC_CMD, #11] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "pm list packages com.poleappmobile.test"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #11] package:com.poleappmobile.test

detox[110467] DEBUG: [exec.js/EXEC_CMD, #12] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 uninstall com.poleappmobile.test
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #12] Success

detox[110467] DEBUG: [exec.js/EXEC_CMD, #13] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "rm -fr /data/local/tmp/detox"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #13] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #14] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "mkdir -p /data/local/tmp/detox"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #14] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #15] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 push "/home/whitenoise/Desktop/pole-app/packages/pole-app-mobile/android/app/build/outputs/apk/debug/app-debug.apk" "/data/local/tmp/detox/Application.apk"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #15] /home/whitenoise/Desktop/pole-app/packages/pole-app-mobile/android/app/build/outputs/apk/debug/app-debug.apk: 1 file pushed, 0 skipped. 215.6 MB/s (79316574 bytes in 0.351s)

detox[110467] DEBUG: [exec.js/EXEC_CMD, #16] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #16] Success

detox[110467] DEBUG: [exec.js/EXEC_CMD, #17] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 push "/home/whitenoise/Desktop/pole-app/packages/pole-app-mobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" "/data/local/tmp/detox/Test.apk"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #17] /home/whitenoise/Desktop/pole-app/packages/pole-app-mobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk: 1 file pushed, 0 skipped. 1615.2 MB/s (884206 bytes in 0.001s)

detox[110467] DEBUG: [exec.js/EXEC_CMD, #18] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "pm install -r -g -t /data/local/tmp/detox/Test.apk"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #18] Success

detox[110467] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-14500', bundleId: 'com.poleappmobile' })
detox[110467] DEBUG: [exec.js/EXEC_CMD, #19] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "am force-stop com.poleappmobile"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #19] 
detox[110467] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({ deviceId: 'emulator-14500', bundleId: 'com.poleappmobile' })
detox[110467] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-14500',
  bundleId: 'com.poleappmobile',
  launchArgs: {
    detoxServer: 'ws://localhost:35143',
    detoxSessionId: '857ed74b-3be3-7ad4-2fb7-e14672024205'
  }
})
detox[110467] DEBUG: [exec.js/EXEC_CMD, #20] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "date +\"%m-%d %T.000\""
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #20] 09-27 09:15:17.000

detox[110467] DEBUG: [exec.js/EXEC_CMD, #21] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 reverse tcp:35143 tcp:35143
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #21] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #22] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "pm list instrumentation"
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #22] instrumentation:com.poleappmobile.test/androidx.test.runner.AndroidJUnitRunner (target=com.poleappmobile)
instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)

detox[110467] DEBUG: [exec.js/SPAWN_CMD, #23] [pid=110568] /home/whitenoise/Android/Sdk/platform-tools/adb -s emulator-14500 shell am instrument -w -r -e detoxServer ws://localhost:35143 -e detoxSessionId 857ed74b-3be3-7ad4-2fb7-e14672024205 -e debug false com.poleappmobile.test/androidx.test.runner.AndroidJUnitRunner
detox[110467] TRACE: [exec.js/SPAWN_STDOUT, #23] onError: commandError=true message=INSTRUMENTATION_FAILED: com.poleappmobile.test/androidx.test.runner.AndroidJUnitRunner

detox[110467] ERROR: [exec.js/SPAWN_STDERR, #23] android.util.AndroidException: INSTRUMENTATION_FAILED: com.poleappmobile.test/androidx.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:486)
        at com.android.commands.am.Am.runInstrument(Am.java:194)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

detox[110467] TRACE: [exec.js/SPAWN_STDOUT, #23] INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: com.poleappmobile
INSTRUMENTATION_STATUS: id=ActivityManagerService
detox[110467] TRACE: [exec.js/SPAWN_STDOUT, #23] 
INSTRUMENTATION_STATUS_CODE: -1

detox[110467] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 110568]: /home/whitenoise/Android/Sdk/platform-tools/adb -s emulator-14500 shell am instrument -w -r -e detoxServer ws://localhost:35143 -e detoxSessionId 857ed74b-3be3-7ad4-2fb7-e14672024205 -e debug false com.poleappmobile.test/androidx.test.runner.AndroidJUnitRunner
detox[110467] TRACE: [exec.js/SPAWN_END, #23] /home/whitenoise/Android/Sdk/platform-tools/adb -s emulator-14500 shell am instrument -w -r -e detoxServer ws://localhost:35143 -e detoxSessionId 857ed74b-3be3-7ad4-2fb7-e14672024205 -e debug false com.poleappmobile.test/androidx.test.runner.AndroidJUnitRunner finished with code = 1
detox[110467] DEBUG: [exec.js/EXEC_CMD, #24] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 reverse --remove tcp:35143
detox[110467] TRACE: [exec.js/EXEC_SUCCESS, #24] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #25] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "ps | grep \"com\.poleappmobile$\""
detox[110467] ERROR: [exec.js/EXEC_FAIL, #25] ""/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "ps | grep \"com\.poleappmobile$\""" failed with code = 1, stdout and stderr:

detox[110467] ERROR: [exec.js/EXEC_FAIL, #25] 
detox[110467] ERROR: [exec.js/EXEC_FAIL, #25] 
detox[110467] DEBUG: [exec.js/EXEC_CMD, #26] "/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "ps | grep \"com\.poleappmobile$\""
detox[110467] ERROR: [exec.js/EXEC_FAIL, #26] ""/home/whitenoise/Android/Sdk/platform-tools/adb" -s emulator-14500 shell "ps | grep \"com\.poleappmobile$\""" failed with code = 1, stdout and stderr:

detox[110467] ERROR: [exec.js/EXEC_FAIL, #26] 
detox[110467] ERROR: [exec.js/EXEC_FAIL, #26] 

 RUNS  e2e/firstTest.e2e.js
^C
(base) whitenoise@xxx:~/Desktop/pole-app/packages/pole-app-mobile$ detox[110455] ERROR: [cli.js] Error: Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
```

**Environment (please complete the following information):**
 - Detox: 17.6.1
 - React Native: 0.63.2
 - Node: v12.13.1
 - Device: Android emulator Pixel_2_API_28
 - OS: Ubuntu
 - Test-runner (select one): `jest-circus`

**Comment by wnz99** [comment]
Please ignore and close, the following command solved the issue:

```
adb uninstall com.poleappmobile
```

For some reasons I had to uninstall the package from the emulator, first.
