### ISSUE TITLE
npm ERR! Failed at the detox@12.6.1 postinstall script

### ISSUE THREAD

**Issue by dev-jccastro** [wix/Detox#2365]
### Description
Hi guys, I'm currently trying to clone my existing react native project to a new Machine. I keep on getting this error when I run 'npm install'. Do you have any solution for this? Hope you can help me.

macOS: 10.15.6,
Xcode: 12.0.1
node: v14.12.0.
<img width="1680" alt="Screen Shot 2020-09-28 at 5 07 29 PM" src="https://user-images.githubusercontent.com/30177538/94414781-53193e80-01af-11eb-82bb-2565d0ec7982.png">

**Comment by ca057** [comment]
This happened to me as well on a fresh install of my `node_modules`. Over the weekend I updated Xcode to its latest version, this is the first time I’m trying to installing the `node_modules` of this project since then. I tried `detox clean-framework-cache` with no success.

We have `detox@^15.4.2`, I’m running macOS 10.15.7 with Xcode 12.0.1

Is there more information I can provide?

**Comment by dev-jccastro** [comment]
@ca057 Thanks for this information, but I'm wondering because I do not have Detox on my package.json. Can you teach me how can I update it to 17.6.1?

**Comment by LeoNatan** [comment]
Use latest Detox. If you don’t have it, some dependency of your app brings it. Ask them to update Detox.

**Comment by vish2595** [comment]
I am getting the same error, but detox isn't my direct dependency.
logs :
```
npm http fetch GET 304 https://registry.npmjs.org/object-visit 93ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/copy-descriptor 88ms (from cache)
npm verb prepareGitDep undefined: installing devDeps and running prepare script.
⸨  ░░░░░░░░░░░░░░░░⸩ ⠏ fetchMetadata: verb prepareGitDep undefined: installing devDeps and running prnpm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > dtrace-provider@0.8.8 install /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/dtrace-provider
npm ERR! prepareGitDep > node-gyp rebuild || node suppress-error.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep   ACTION binding_gyp_ndtp_target_build_ndtp .
npm ERR! prepareGitDep   TOUCH Release/obj.target/ndtp.stamp
npm ERR! prepareGitDep
npm ERR! prepareGitDep > fsevents@1.2.13 install /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/fsevents
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/.node
npm ERR! prepareGitDep   CXX(target) Release/obj.target/fse/fsevents.o
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/fse.node
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@2.6.11 postinstall /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
npm ERR! prepareGitDep > https://opencollective.com/core-js
npm ERR! prepareGitDep > https://www.patreon.com/zloirock
npm ERR! prepareGitDep
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > detox@12.6.1 postinstall /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox
npm ERR! prepareGitDep > node scripts/postinstall.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep Extracting Detox sources...
npm ERR! prepareGitDep Building Detox.framework from /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src...
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm ERR! prepareGitDep npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm ERR! prepareGitDep npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep + xcodebuild -version
npm ERR! prepareGitDep +++ dirname /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/scripts/build_framework.ios.sh
npm ERR! prepareGitDep ++ dirname /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/scripts
npm ERR! prepareGitDep + detoxRootPath=/Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox
npm ERR! prepareGitDep ++ node -p 'require('\''/Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/package.json'\'').version'
npm ERR! prepareGitDep + detoxVersion=12.6.1
npm ERR! prepareGitDep ++ echo 12.6.1
npm ERR! prepareGitDep ++ xcodebuild -version
npm ERR! prepareGitDep ++ shasum
npm ERR! prepareGitDep ++ awk '{print $1}'
npm ERR! prepareGitDep + sha1=5b2335a846e3075ccdce642546a7cf4c7f94df79
npm ERR! prepareGitDep + detoxFrameworkDirPath=/Users/vishalrawat/Library/Detox/ios/5b2335a846e3075ccdce642546a7cf4c7f94df79
npm ERR! prepareGitDep + detoxFrameworkPath=/Users/vishalrawat/Library/Detox/ios/5b2335a846e3075ccdce642546a7cf4c7f94df79/Detox.framework
npm ERR! prepareGitDep + main
npm ERR! prepareGitDep + '[' -d /Users/vishalrawat/Library/Detox/ios/5b2335a846e3075ccdce642546a7cf4c7f94df79 ']'
npm ERR! prepareGitDep + prepareAndBuildFramework
npm ERR! prepareGitDep + '[' -d /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios ']'
npm ERR! prepareGitDep + detoxSourcePath=/Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + extractSources /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + detoxSourcePath=/Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + echo 'Extracting Detox sources...'
npm ERR! prepareGitDep + mkdir -p /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + tar -xjf /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/Detox-ios-src.tbz -C /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + buildFramework /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + detoxSourcePath=/Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src
npm ERR! prepareGitDep + echo 'Building Detox.framework from /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src...'
npm ERR! prepareGitDep + mkdir -p /Users/vishalrawat/Library/Detox/ios/5b2335a846e3075ccdce642546a7cf4c7f94df79
npm ERR! prepareGitDep + /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/scripts/build_universal_framework.sh /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/ios_src/Detox.xcodeproj /Users/vishalrawat/Library/Detox/ios/5b2335a846e3075ccdce642546a7cf4c7f94df79
npm ERR! prepareGitDep child_process.js:642
npm ERR! prepareGitDep     throw err;
npm ERR! prepareGitDep     ^
npm ERR! prepareGitDep
npm ERR! prepareGitDep Error: Command failed: /Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/scripts/build_framework.ios.sh
npm ERR! prepareGitDep     at checkExecSyncError (child_process.js:621:11)
npm ERR! prepareGitDep     at Object.execFileSync (child_process.js:639:15)
npm ERR! prepareGitDep     at Object.<anonymous> (/Users/vishalrawat/.npm/_cacache/tmp/git-clone-ebb8c381/node_modules/detox/scripts/postinstall.js:2:27)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:956:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:812:32)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
npm ERR! prepareGitDep     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
npm ERR! prepareGitDep     at internal/main/run_main_module.js:17:11 {
npm ERR! prepareGitDep   status: 65,
npm ERR! prepareGitDep   signal: null,
npm ERR! prepareGitDep   output: [ null, null, null ],
npm ERR! prepareGitDep   pid: 28648,
npm ERR! prepareGitDep   stdout: null,
npm ERR! prepareGitDep   stderr: null
npm ERR! prepareGitDep }
npm ERR! prepareGitDep npm WARN react-native-macos@0.60.0-microsoft.50 requires a peer of react@16.8.6 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN @react-native-community/cli@2.10.0 requires a peer of react-native@^0.60.0 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! detox@12.6.1 postinstall: `node scripts/postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the detox@12.6.1 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/vishalrawat/.npm/_logs/2020-09-28T13_41_19_447Z-debug.log
npm ERR! prepareGitDep
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 168002ms
npm verb stack Error: premature close
npm verb stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
npm verb stack     at PassThrough.emit (events.js:215:7)
npm verb stack     at emitCloseNT (internal/streams/destroy.js:69:8)
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:79:21)
npm verb cwd /Users/vishalrawat/work/YorQd
npm verb Darwin 19.6.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v12.13.0
npm verb npm  v6.13.4
npm ERR! premature close
npm verb exit [ 1, true ]
npm timing npm Completed in 181564ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vishalrawat/.npm/_logs/2020-09-28T13_41_19_737Z-debug.log
```
