### ISSUE TITLE
Detox fails on postinstall phase on Xcode 12.0

### ISSUE THREAD

**Issue by cgandiaf** [wix/Detox#2371]
Hi everyone!!
I have an issue installing detox library with react native 0.63.2
When I do npm install, the process fails with the next output: 

```> detox@15.5.0 postinstall /Users/carmen.gandia/code/react_native_couples/node_modules/detox
> node scripts/postinstall.js

/Users/carmen.gandia/Library/Detox/ios/0df729392f205c2e9f04eba5815391828fb10225 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/carmen.gandia/Library/Detox/ios/0df729392f205c2e9f04eba5815391828fb10225 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/carmen.gandia/code/react_native_couples/node_modules/detox/ios_src...
child_process.js:637
    throw err;
    ^

Error: Command failed: /Users/carmen.gandia/code/react_native_couples/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.<anonymous> (/Users/carmen.gandia/code/react_native_couples/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 15397,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@15.5.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the detox@15.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carmen.gandia/.npm/_logs/2020-09-29T14_10_45_417Z-debug.log

```

Attached detox build log (extracted from ~/Library/Detox/ios/0df729392f205c2e9f04eba5815391828fb10225):

[detox_ios.log](https://github.com/wix/Detox/files/5299686/detox_ios.log)

It seems like an issue with Xcode 12 or the new version of Switch

Thank you!!!

**Comment by javierbustamante** [comment]
I'm having the same problem!!!

**Comment by LeoNatan** [comment]
Use latest Detox. This has been asked before. Use search.

**Comment by emgroves** [comment]
@LeoNatan seeing this with the latest detox (17.8.0) still. Only see two issues with it; both closed.

**Comment by emgroves** [comment]
I'm also seeing this on the latest Detox (17.8) and react-native 63.3. Still digging to see if I can find a resolution or a workaround.

**Comment by LeoNatan** [comment]
Please provide the build log from ~/Library/Detox

**Comment by emgroves** [comment]
I've just blown away my `node_modules` for the first time since updating to XCode 12. 

I started getting this error immediately after trying to delete my node modules and reinstall. It's giving the same error even when I try to `npm uninstall detox --save-dev`. I'm currently stuck in a process of trying to remove detox so I can build temporarily without our tests; but this is coming back on most paths I'm taking. 

[detox_ios.log](https://github.com/wix/Detox/files/5315215/detox_ios.log)

**Comment by LeoNatan** [comment]
Hm, this is odd. I’ll look into it. Thanks!

**Comment by emgroves** [comment]
Here's the npm stack I inevitably run into as well: 

```npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > dtrace-provider@0.8.8 install /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/dtrace-provider
npm ERR! prepareGitDep > node-gyp rebuild || node suppress-error.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   ACTION binding_gyp_ndtp_target_build_ndtp .
npm ERR! prepareGitDep   TOUCH Release/obj.target/ndtp.stamp
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > fsevents@1.2.13 install /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/fsevents
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/.node
npm ERR! prepareGitDep   CXX(target) Release/obj.target/fse/fsevents.o
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/fse.node
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > core-js@2.6.11 postinstall /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep 
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
npm ERR! prepareGitDep > https://opencollective.com/core-js 
npm ERR! prepareGitDep > https://www.patreon.com/zloirock 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > detox@12.6.1 postinstall /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox
npm ERR! prepareGitDep > node scripts/postinstall.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
npm ERR! prepareGitDep          deleting /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e and trying to rebuild.
npm ERR! prepareGitDep Extracting Detox sources...
npm ERR! prepareGitDep Building Detox.framework from /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src...
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm ERR! prepareGitDep npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm ERR! prepareGitDep npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep + xcodebuild -version
npm ERR! prepareGitDep +++ dirname /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/scripts/build_framework.ios.sh
npm ERR! prepareGitDep ++ dirname /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/scripts
npm ERR! prepareGitDep + detoxRootPath=/Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox
npm ERR! prepareGitDep ++ node -p 'require('\''/Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/package.json'\'').version'
npm ERR! prepareGitDep + detoxVersion=12.6.1
npm ERR! prepareGitDep ++ echo 12.6.1
npm ERR! prepareGitDep ++ xcodebuild -version
npm ERR! prepareGitDep ++ shasum
npm ERR! prepareGitDep ++ awk '{print $1}'
npm ERR! prepareGitDep + sha1=0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
npm ERR! prepareGitDep + detoxFrameworkDirPath=/Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
npm ERR! prepareGitDep + detoxFrameworkPath=/Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e/Detox.framework
npm ERR! prepareGitDep + main
npm ERR! prepareGitDep + '[' -d /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e ']'
npm ERR! prepareGitDep + '[' '!' -d /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e/Detox.framework ']'
npm ERR! prepareGitDep + echo '/Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
npm ERR! prepareGitDep          deleting /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e and trying to rebuild.'
npm ERR! prepareGitDep + rm -rf /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
npm ERR! prepareGitDep + prepareAndBuildFramework
npm ERR! prepareGitDep + '[' -d /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios ']'
npm ERR! prepareGitDep + detoxSourcePath=/Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + extractSources /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + detoxSourcePath=/Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + echo 'Extracting Detox sources...'
npm ERR! prepareGitDep + mkdir -p /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + tar -xjf /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/Detox-ios-src.tbz -C /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + buildFramework /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + detoxSourcePath=/Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src
npm ERR! prepareGitDep + echo 'Building Detox.framework from /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src...'
npm ERR! prepareGitDep + mkdir -p /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
npm ERR! prepareGitDep + /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/scripts/build_universal_framework.sh /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/ios_src/Detox.xcodeproj /Users/ericgroves/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
npm ERR! prepareGitDep child_process.js:651
npm ERR! prepareGitDep     throw err;
npm ERR! prepareGitDep     ^
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Error: Command failed: /Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/scripts/build_framework.ios.sh
npm ERR! prepareGitDep     at checkExecSyncError (child_process.js:630:11)
npm ERR! prepareGitDep     at Object.execFileSync (child_process.js:648:15)
npm ERR! prepareGitDep     at Object.<anonymous> (/Users/ericgroves/.npm/_cacache/tmp/git-clone-3fede5a7/node_modules/detox/scripts/postinstall.js:2:27)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:1158:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:1002:32)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
npm ERR! prepareGitDep     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
npm ERR! prepareGitDep     at internal/main/run_main_module.js:18:47 {
npm ERR! prepareGitDep   status: 65,
npm ERR! prepareGitDep   signal: null,
npm ERR! prepareGitDep   output: [ null, null, null ],
npm ERR! prepareGitDep   pid: 55462,
npm ERR! prepareGitDep   stdout: null,
npm ERR! prepareGitDep   stderr: null
npm ERR! prepareGitDep }
npm ERR! prepareGitDep npm WARN react-native-macos@0.60.0-microsoft.50 requires a peer of react@16.8.6 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN @react-native-community/cli@2.10.0 requires a peer of react-native@^0.60.0 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! detox@12.6.1 postinstall: `node scripts/postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the detox@12.6.1 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/ericgroves/.npm/_logs/2020-10-01T23_13_00_411Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ericgroves/.npm/_logs/2020-10-01T23_13_00_597Z-debug.log
```

It's weird that the error keeps referencing detox 12.6.1. Package.json references detox `17.8.0` and react-native `16.3.3`. 

All the logs seem to end with the same error. I attached the log from the most recent uninstall try (that matches the above npm output)

[detox_ios.log](https://github.com/wix/Detox/files/5315226/detox_ios.log)

Is there any good documentation on a manual remove process?

I'm not sure why if I manually remove `detox` from package.json dependencies, delete my package-lock, and clear npm cache, I somehow get the same result trying to `npm install` a package.json that currently has no reference to detox?

**Comment by LeoNatan** [comment]
You might have a dependency somewhere with an old Detox.

To test, start a new RN project, add Detox and see if it fails.

**Comment by emgroves** [comment]
Oof - I didn't even think about that. I'll browse my dependencies and see who is using Detox. Creating a fresh app with Detox seems to install OK. 

Must be a package that has detox listed outside of `devDependencies`, right?

**Comment by LeoNatan** [comment]
Could be. Grep recursively and see.

**Comment by emgroves** [comment]
Yup; found the culprit. https://github.com/react-native-community/async-storage, 1.12.0 seems to allow it to pass successfully. Thanks for the quick responses, @LeoNatan!

**Comment by LeoNatan** [comment]
So there is no bug. Thanks
