### ISSUE TITLE
Issue with the --headless argument 

### ISSUE THREAD

**Issue by mmusil** [wix/Detox#2450]
**Describe the bug**
When running android tests in a container, `emulator -version` does not work because of missing libpulse.so.0 library. 
```
detox[5433] DEBUG: [exec.js/EXEC_CMD, #1] "/opt/android/sdk/emulator/emulator" -version
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] ""/opt/android/sdk/emulator/emulator" -version" failed with code = 127, stdout and stderr:

detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] 
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] /opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
```

This command has to be run with `-no-window` option. 
**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Install the latest detox with any runner.
2. Attempt to run `detox test --headless -l verbose`.
3. Notice in the log, that `qemu-system-x86_64` is used instead of `qemu-system-x86_64-headless`

**Expected behaviour**

The --headless command should properly work and set the -no-window argument for calling the emulator.

**Device and Verbose Detox Logs**

```
$ detox test --headless -l verbose
detox[5421] INFO:  [test.js] loglevel="verbose" headless=true useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1604495540237 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[5433] INFO:  [DetoxServer.js] server listening on localhost:40525...
detox[5433] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:40525
detox[5433] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=0e6a721c-b8c6-40ce-b426-34eece00c820
detox[5433] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=0e6a721c-b8c6-40ce-b426-34eece00c820
detox[5433] DEBUG: [exec.js/EXEC_CMD, #0] "/opt/android/sdk/emulator/emulator" -list-avds --verbose
detox[5433] DEBUG: [exec.js/EXEC_CMD, #1] "/opt/android/sdk/emulator/emulator" -version
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] ""/opt/android/sdk/emulator/emulator" -version" failed with code = 127, stdout and stderr:

detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] 
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] /opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory

detox[5433] ERROR: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Could not detect emulator binary version ChildProcessError: Command failed: "/opt/android/sdk/emulator/emulator" -version
/opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
 `"/opt/android/sdk/emulator/emulator" -version` (exited with error code 127)
    at callback (/home/circleci/unifiedpush-cookbook/react-native/push/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  code: 127,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawn],
    spawnSync: [Function: spawnSync]
  },
  stdout: '',
  stderr: '/opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory\n'
}
detox[5433] WARN:  [AVDValidator.js/AVD_VALIDATION] Emulator version detection failed (See previous logs)
```

**Environment (please complete the following information):**
 - Detox: 17.11.0
 - React Native: 0.63: does not matter
 - Node: v12.19.0: does not matter
 - Device: docker
 - OS: does not matter
 - Test-runner (select one): does not matter
 - Android emulator: 30.1.5.0

**Comment by SMJ93** [comment]
Hi @mmusil, did you manage to get this working? I get the following error when running detox in Azure on a linux machine:

```
/usr/local/lib/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
```

**Comment by mmusil** [comment]
Hi @SMJ93, could you post verbose logs please? Would like to know if it's on the same emulator command or on something different. :)  It works fine for me since my PR was merged.

**Comment by SMJ93** [comment]
Hey @mmusil, thanks for getting back to me so quickly! I found the issue - Azure do not support the Android emulator on Windows or Linux machines 🤦  Switching back to macOS worked!

**Comment by mmusil** [comment]
@SMJ93 That sounds rather odd, but I'm not familiar with Azure at all :man_shrugging:... I'm currently trying to make android emulator work in docker container on OpenStack RHEL machine and it is a bit tricky because of KVM, but possible. :sweat_smile:

**Comment by SMJ93** [comment]
@mmusil haha yep! Now we are looking at using CircleCI instead of Azure 😂  Good luck!

**Comment by austonpramodh** [comment]
@SMJ93 Were you able to run the android emulator reliably on CircleCi?

I keep getting below error but the app doesn't crash. Is this normal?

```
detox[16578] ERROR: [EXEC_FAIL, #187] ""/opt/android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"io\.app\.appName$\""" failed with error = ChildProcessError: Command failed: "/opt/android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"io\.app\.appName$\""
 `"/opt/android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"io\.app\.appName$\""` (exited with error code 1) (code=1), stdout and stderr:
```

Also, sometimes I get the below log and the test starts failing on the below code.

```
Test Failed: 10.0sec timeout expired without matching of given matcher: at least 75 percent of the view's area is displayed to the user.

      34 | export const waitToBeVisible = async (props: WaitForProps) => {
      35 |   const elem = await waitForHelper(props);
    > 36 |   await waitFor(elem).toBeVisible().withTimeout(10000);
         |                                     ^
      37 |   return elem;
      38 | };
      39 |

      at waitToBeVisible$ (step-definitions.ts:36:37)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:154:20)
      at ../node_modules/regenerator-runtime/runtime.js:164:13
      at tryCallOne (../node_modules/react-native/node_modules/promise/lib/core.js:37:12)
```
These errors don't occur always, but sometimes. I would say around 3/10 tests fail due to this. I would love to get some help, please.

**Comment by SMJ93** [comment]
@austonpramodh this looks to me like [Detox flakiness](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Flakiness.md) and not a CircleCI issue, maybe try scrolling to the `View` in question so it is 100% in view?
