### ISSUE TITLE
iPhone X home indicator line color changes make screenshot tests fail

### ISSUE THREAD

**Issue by SudoPlz** [wix/Detox#2454]
### Description
Hi there,
I tried updating my snapshots to match the new UI and noticed that the iPhone X home indicator line color behaviour was not consistent on the iOS simulator.

Sometimes it would change color while scrolling to the next bottom tab bar (why it does that I don't know, it makes no sense, and we don't change the background at all), and therefore it would make my tests fail
Bellow I attach the screenshot diff that made my test fail.

What can I do?

- Can I make detox avoid content outside the safe area?

Thanks

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Expected behavior
Screenshot tests to pass

#### Screenshots
![screenshot-test-e-2-e-js-screenshots-should-have-the-same-appointments-blank-past-state-1-diff](https://user-images.githubusercontent.com/3070948/98240537-3ae8cc00-1f72-11eb-930d-20c3857cc1df.png)

#### Environment (please complete the following information):
 - Detox: 17.11.0
 - React Native: 0.61.5
 - Node: 10.19.0
 - Device: iPhone 11 on iOS Simulator 13.5
 - Xcode: 11.5
 - iOS: 13.5
 - macOS: 10.15.6 Catalina

#### Device and verbose Detox logs

<details>
  <summary>Click to expand verbose logs!</summary>
  
  ```shell
** BUILD SUCCEEDED **

detox[3582] INFO:  [test.js] useCustomLogger=true DETOX_START_TIMESTAMP=1604579038787 reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 e2e
detox[3583] INFO:  [DetoxServer.js] server listening on localhost:49445...
detox[3583] INFO:  [AppleSimUtils.js] com.example.client.ios launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn D990C87C-8988-4A4D-9EB4-E54782E4D3C6 log stream --level debug --style compact --predicate 'process == "client_mobile_app"'
detox[3583] INFO:  Screenshots is assigned to D990C87C-8988-4A4D-9EB4-E54782E4D3C6 {"type":"iPhone 11"}
detox[3583] INFO:  Screenshots: should have the same Add Business blank state
detox[3583] INFO:  Screenshots: should have the same Add Business blank state [FAIL]
detox[3583] INFO:  Screenshots: should have the same Appointments blank upcoming state
detox[3583] INFO:  Screenshots: should have the same Appointments blank upcoming state [FAIL]
detox[3583] INFO:  Screenshots: should have the same Appointments blank past state
detox[3583] INFO:  Screenshots: should have the same Appointments blank past state [FAIL]
detox[3583] INFO:  Screenshots: should have the same Packages blank state
detox[3583] INFO:  Screenshots: should have the same Packages blank state [FAIL]
detox[3583] INFO:  Screenshots: should have the same Certificates blank past state
detox[3583] INFO:  Screenshots: should have the same Certificates blank past state [FAIL]
detox[3583] INFO:  Screenshots: should have the same Subscriptions blank past state
detox[3583] INFO:  Screenshots: should have the same Subscriptions blank past state [FAIL]

 FAIL  e2e/screenshotTest.e2e.js (28.16 s)
  Screenshots
    ✕ should have the same Add Business blank state (1610 ms)
    ✕ should have the same Appointments blank upcoming state (2490 ms)
    ✕ should have the same Appointments blank past state (3256 ms)
    ✕ should have the same Packages blank state (2872 ms)
    ✕ should have the same Certificates blank past state (3329 ms)
    ✕ should have the same Subscriptions blank past state (3067 ms)

  ● Screenshots › should have the same Add Business blank state

    Expected image to match or be a close match to snapshot but was 0.07635923481711525% different from snapshot (1133 differing pixels).
    See diff for details: /Users/auser/Development/Example/clientApp/e2e/__image_snapshots__/__diff_output__/screenshot-test-e-2-e-js-screenshots-should-have-the-same-add-business-blank-state-1-diff.png

      15 |     const imagePath = await device.takeScreenshot('AddBusiness');
      16 |     const image = await readFile(imagePath);
    > 17 |     jestExpect(image).toMatchImageSnapshot();
         |                       ^
      18 |   });
      19 |
      20 |   it('should have the same Appointments blank upcoming state', async () => {

      at _callee$ (screenshotTest.e2e.js:17:23)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

  ● Screenshots › should have the same Appointments blank upcoming state

    Expected image to match or be a close match to snapshot but was 0.07635923481711525% different from snapshot (1133 differing pixels).
    See diff for details: /Users/auser/Development/Example/clientApp/e2e/__image_snapshots__/__diff_output__/screenshot-test-e-2-e-js-screenshots-should-have-the-same-appointments-blank-upcoming-state-1-diff.png

      23 |     const imagePath = await device.takeScreenshot('Upcoming');
      24 |     const image = await readFile(imagePath);
    > 25 |     jestExpect(image).toMatchImageSnapshot();
         |                       ^
      26 |   });
      27 |
      28 |   it('should have the same Appointments blank past state', async () => {

      at _callee2$ (screenshotTest.e2e.js:25:23)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

  ● Screenshots › should have the same Appointments blank past state

    Expected image to match or be a close match to snapshot but was 0.19773874223602486% different from snapshot (2934 differing pixels).
    See diff for details: /Users/auser/Development/Example/clientApp/e2e/__image_snapshots__/__diff_output__/screenshot-test-e-2-e-js-screenshots-should-have-the-same-appointments-blank-past-state-1-diff.png

      31 |     const imagePath = await device.takeScreenshot('Past');
      32 |     const image = await readFile(imagePath);
    > 33 |     jestExpect(image).toMatchImageSnapshot();
         |                       ^
      34 |   });
      35 |
      36 |   it('should have the same Packages blank state', async () => {

      at _callee3$ (screenshotTest.e2e.js:33:23)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

  ● Screenshots › should have the same Packages blank state

    Expected image to match or be a close match to snapshot but was 0.28676835317460314% different from snapshot (4255 differing pixels).
    See diff for details: /Users/auser/Development/Example/clientApp/e2e/__image_snapshots__/__diff_output__/screenshot-test-e-2-e-js-screenshots-should-have-the-same-packages-blank-state-1-diff.png

      39 |     const imagePath = await device.takeScreenshot('Packages');
      40 |     const image = await readFile(imagePath);
    > 41 |     jestExpect(image).toMatchImageSnapshot();
         |                       ^
      42 |   });
      43 |
      44 |   it('should have the same Certificates blank past state', async () => {

      at _callee4$ (screenshotTest.e2e.js:41:23)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

  ● Screenshots › should have the same Certificates blank past state

    Expected image to match or be a close match to snapshot but was 0.07635923481711525% different from snapshot (1133 differing pixels).
    See diff for details: /Users/auser/Development/Example/clientApp/e2e/__image_snapshots__/__diff_output__/screenshot-test-e-2-e-js-screenshots-should-have-the-same-certificates-blank-past-state-1-diff.png

      47 |     const imagePath = await device.takeScreenshot('Certificates');
      48 |     const image = await readFile(imagePath);
    > 49 |     jestExpect(image).toMatchImageSnapshot();
         |                       ^
      50 |   });
      51 |
      52 |   it('should have the same Subscriptions blank past state', async () => {

      at _callee5$ (screenshotTest.e2e.js:49:23)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

  ● Screenshots › should have the same Subscriptions blank past state

    Expected image to match or be a close match to snapshot but was 0.07635923481711525% different from snapshot (1133 differing pixels).
    See diff for details: /Users/auser/Development/Example/clientApp/e2e/__image_snapshots__/__diff_output__/screenshot-test-e-2-e-js-screenshots-should-have-the-same-subscriptions-blank-past-state-1-diff.png

      55 |     const imagePath = await device.takeScreenshot('Subscriptions');
      56 |     const image = await readFile(imagePath);
    > 57 |     jestExpect(image).toMatchImageSnapshot();
         |                       ^
      58 |   });
      59 | });
      60 |

      at _callee6$ (screenshotTest.e2e.js:57:23)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:135:20)
      at ../node_modules/regenerator-runtime/runtime.js:145:13

 › 6 snapshots failed.
detox[3583] INFO:  [DetoxServer.js] server listening on localhost:49511...
detox[3583] INFO:  [AppleSimUtils.js] com.example.client.ios launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn D990C87C-8988-4A4D-9EB4-E54782E4D3C6 log stream --level debug --style compact --predicate 'process == "client_mobile_app"'
detox[3583] INFO:  Add Business Input is assigned to D990C87C-8988-4A4D-9EB4-E54782E4D3C6 {"type":"iPhone 11"}
detox[3583] INFO:  Add Business Input: should not be in an error state when blank
detox[3583] INFO:  Add Business Input: should not be in an error state when blank [OK]
detox[3583] INFO:  Add Business Input: should be in an error state
detox[3583] INFO:  Add Business Input: should be in an error state [OK]
detox[3583] INFO:  Add Business Input: should be in a valid state
detox[3583] INFO:  Add Business Input: should be in a valid state [OK]

 PASS  e2e/inputTest.e2e.js (9.439 s)
  Add Business Input
    ✓ should not be in an error state when blank (13 ms)
    ✓ should be in an error state (1192 ms)
    ✓ should be in a valid state (289 ms)

detox[3582] ERROR: [cli.js] Error: Command failed: jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 e2e

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client_mobile_app@1.1.3 e2e: `detox build && detox test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client_mobile_app@1.1.3 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/auser/.npm/_logs/2020-11-05T12_24_37_539Z-debug.log
    }
  ```
</details>

**Comment by LeoNatan** [comment]
Yes, this is why screenshot testing is not advised. The home indicator is beyond the control of Detox.

**Comment by LeoNatan** [comment]
Technical reverse-engineering, if you are interested: https://medium.com/@nathangitter/reverse-engineering-the-iphone-x-home-indicator-color-a4c112f84d34

**Comment by sajadghawami** [comment]
For anyone being as stubborn as i am about using screenshot testing, this might help you:

https://github.com/flowkey/react-native-home-indicator

You can remove the home indicator on demand while running your tests.

**Comment by dmaulick** [comment]
@sajadghawami - did you ever get a complete solution for visual tests using detox?
We are running into this issue as well as a scrolling issue on android: https://github.com/wix/Detox/issues/3485#issue-1303967646
