### ISSUE TITLE
Unable to install dependencies on React Native project after upgrade due to an error when running the build_framework.ios.sh script

### ISSUE THREAD

**Issue by mcreusot** [wix/Detox#2468]
### Description
I attempted to update a React Native project from `0.59.10` to `0.63.3`. Since then, on a MacOS device, I am not able to install the dependencies of my project through `npm install` because the postinstall.js script encounters an error when building the Detox framework.
Detox is neither used nor in the dependencies of the project.

- [ ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Clone project
2. Install dependencies `npm install`

For the record, when I run the command `npm install -D detox`, the installation works just fine but I run `npm install` right after this command, it will fail in the same way.

#### Expected behavior
The dependencies are correctly installed

#### Environment (please complete the following information):
 - Detox: 14.9.2 (from the logs of npm but it is not declared in the package.json file of the project)
 - React Native: 0.63.3
 - Node: 11.15.0
 - Device: Mac
 - Xcode: 12.0
 - iOS: Target is set to iOS 9.0 in .xcodeproj file
 - macOS: Catalina 10.15.6

#### If you are seeing a build problem (e.g. during `npm install`)
- [x] I am providing the `npm install` log below:

```
user@machine project_folder % npm install
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > dtrace-provider@0.8.8 install /Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/dtrace-provider
npm ERR! prepareGitDep > node-gyp rebuild || node suppress-error.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   ACTION binding_gyp_ndtp_target_build_ndtp .
npm ERR! prepareGitDep   TOUCH Release/obj.target/ndtp.stamp
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > fsevents@1.2.13 install /Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/fsevents
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/.node
npm ERR! prepareGitDep   CXX(target) Release/obj.target/fse/fsevents.o
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/fse.node
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > core-js@2.6.11 postinstall /Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep 
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
npm ERR! prepareGitDep > https://opencollective.com/core-js 
npm ERR! prepareGitDep > https://www.patreon.com/zloirock 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > detox@14.9.2 postinstall /Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/detox
npm ERR! prepareGitDep > node scripts/postinstall.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Extracting Detox sources...
npm ERR! prepareGitDep Building Detox.framework from /Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/detox/ios_src...
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep child_process.js:660
npm ERR! prepareGitDep     throw err;
npm ERR! prepareGitDep     ^
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Error: Command failed: /Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/detox/scripts/build_framework.ios.sh
npm ERR! prepareGitDep     at checkExecSyncError (child_process.js:639:11)
npm ERR! prepareGitDep     at Object.execFileSync (child_process.js:657:15)
npm ERR! prepareGitDep     at Object.<anonymous> (/Users/user/.npm/_cacache/tmp/git-clone-9591e57d/node_modules/detox/scripts/postinstall.js:2:27)
npm ERR! prepareGitDep     at Module._compile (internal/modules/cjs/loader.js:816:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:685:32)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
npm ERR! prepareGitDep     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
npm ERR! prepareGitDep     at internal/main/run_main_module.js:21:11
npm ERR! prepareGitDep npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN @octokit/plugin-request-log@1.0.2 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN @react-native-community/geolocation@2.0.2 No repository field.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! detox@14.9.2 postinstall: `node scripts/postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the detox@14.9.2 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/user/.npm/_logs/2020-11-16T14_36_31_226Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-11-16T14_36_32_005Z-debug.log
```

#### detox_ios.log

I am not able to put the full log file because it would be a lot of work to anonimyze the whole file but I can give the failing command found in the logs : 

```
The following build commands failed:
	CompileC /Users/user/Library/Developer/Xcode/DerivedData/Detox-ahbwgarbmgzdbtaktwywffunlmvz/Build/Intermediates.noindex/EarlGrey.build/Release-iphoneos/EarlGrey.build/Objects-normal/arm64/GREYActions.o EarlGrey/Action/GREYActions.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

### Additional informations

- When using the `npm install -D detox` command, I am able to install my dependencies and I can use the detox-cli to clean the cache and rebuild the framework and these 2 commands (`detox clean-framework-cache` and `detox build-framework-cache`) run without encountering any error but when I run `the npm install` command, the install fails again.
- I tried all the commands mentionned here with both the New Build System and the Legacy Build System of XCode with the same result.
- The NPM logs indicate that the version of detox is 14.9.2 but after running the command `find ./node_modules/ -name package.json | xargs grep detox@14`, there is no dependency using detox 14.

**Comment by LeoNatan** [comment]
Some of your dependency is bringing a very old version of Detox. There is nothing we can do. Find the dependency that is responsible and fix it.

**Comment by LeoNatan** [comment]
The problem in this case comes from Xcode 12, not RN upgrade. We’ve already upgraded Detox to support Xcode 12, but one of your dependencies has hardcoded Detox to an old version. Detox should not even be found under dependencies but under dev dependencies, so it’s even dumber on their part. Sorry, you must find that dependency and either remove it or open an issue and hope for a fix.

**Comment by mcreusot** [comment]
Okay, I will investigate on which dependency cause this problem.
Thanks for your time

**Comment by mcreusot** [comment]
As a dirty workaround, we decided to completely disable the post install script of Detox using the environment variable DETOX_DISABLE_POSTINSTALL=1.
Since we don't use Detox in this project but it is still required by another dependency, it won't be a problem for us.
