### ISSUE TITLE
android.attached not working on latest Detox version

### ISSUE THREAD

**Issue by j320** [wix/Detox#2478]
**Describe the bug**
Running tests on a launched emulator throws error

**To Reproduce**

Steps to reproduce:
1. Launch an emulator, run _adb devices_ and get the emulator name
2. Add the emulator name to the configuration:
```
"android.emu.debug": {
                    "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
                    "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
                    "type": "android.attached",
                    "device": {
                        "adbName": "emulator-5554"
                    }
                }
```
3. Build the app using _detox build_ and then execute tests using _detox test_

**Expected behavior**
App is installed on the emulator and tests are executed

**Device and Verbose Detox Logs**

```
TypeError: Cannot read property 'includes' of undefined
    at FreeDeviceFinder._isDeviceFreeAndMatching (/node_modules/detox/src/devices/drivers/android/tools/FreeDeviceFinder.js:27:41)
    at FreeDeviceFinder.findFreeDevice (/node_modules/detox/src/devices/drivers/android/tools/FreeDeviceFinder.js:14:22)
    at async safeAsync (/node_modules/detox/src/utils/safeAsync.js:4:13)
    at async /node_modules/detox/src/devices/DeviceRegistry.js:30:24
    at async ExclusiveLockfile.exclusively (/node_modules/detox/src/utils/ExclusiveLockfile.js:38:15)
    at async AttachedAndroidDriver.acquireFreeDevice (/node_modules/detox/src/devices/drivers/android/attached/AttachedAndroidDriver.js:21:21)
    at async Device.prepare (/node_modules/detox/src/devices/Device.js:16:22)
    at async Detox._doInit (/node_modules/detox/src/Detox.js:166:5)

```
**Environment:**
 - Detox: 17.13.0
 - React Native: 0.63.2
 - Node: 14.5.1
 - OS: Android

**Comment by railsjack** [comment]
It's same to me. 
@j320  Which version is working without this issue?

**Comment by d4vidi** [comment]
@j320 thanks for reporting this. I believe this has already been fixed. I'll double check and release a version, if needed.

**Comment by pradeipp** [comment]
Hi @d4vidi I'm facing similar issues. When I run tests on my samsung galaxy a51, the tests are incredibly flaky, with this error being thrown in almost all instances:
```
DetoxRuntimeError: The pending request #1 ("invoke") has been rejected due to the following error:

The app has unexpectedly disconnected from Detox server. 
```

and then it just gives the `DetoxRuntimeError: Detox can't seem to connect to the test app(s)!` error

didn't find much info in the detox trace logs except for an abrupt 
The same tests passes normally while running on an emulator though.
