### ISSUE TITLE
clang: error: linker command failed with exit code 1 (react-native-sentry issue)

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#248]
Running `detox build`, I get the following error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSentry", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/<app name>.app/<app name> normal x86_64
(1 failure)
child_process.js:524
    throw err;
    ^

Error: Command failed: xcodebuild -project ios/<app name>.xcodeproj -scheme <app name> -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.<anonymous> (/Users/<user name>/Documents/react-native-projects/<app name>/node_modules/detox/local-cli/detox-build.js:26:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
```

I have run `pod install` as well as `yarn` too, so there shouldn't be any dependency problems...
I appreciate any help.

**Comment by isnifer** [comment]
@mhyousefi how did you build your application before? Did you have a build command before?
For example, I have my custom build command before and just use if I need:
```json
"detox": {
  "configurations": {
    "ios.sim.debug": {
      "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/tipsi.app",
      "build": "npm run build:ios",
      "type": "ios.simulator",
      "name": "iPhone 6"
    }
  }
}
```
And my build command is a Ruby script:
```js
"build:ios": "scripts/build-ios.rb",
```

**Comment by mhyousefi** [comment]
I have the following in my `package.json` file:
```
"detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/<app name>.app",
        "build": "xcodebuild -project ios/<app name>.xcodeproj -scheme <app name> -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  }
```

**"build": "xcodebuild -project**

**Comment by mhyousefi** [comment]
I performed the following command in my project directory to remove sentry from my project, and it worked. But that is not a real solution if one needs the library.
`react-native unlink react-native-sentry`

**Comment by isnifer** [comment]
@mhyousefi anyway, it's not a detox issue

**Comment by LeoNatan** [comment]
Doesn't look related to detox to me. Make sure your build command works outside of detox and then put it in package.json.
