### ISSUE TITLE
[Android]  `.tap()` method never resolved when render MaskedView

### ISSUE THREAD

**Issue by retyui** [wix/Detox#2489]
**Describe the bug**

I've just added Detox to my App, using a **debug build** I run a test

> Note: we use a react-native-navigation lib

```js
// my.test.js
// skip Onboarding, this tap handle `setRoot()`
await elementById('NavBarCloseButton').tap(); 

// then navigate to specific screen from home screen
await elementById('DiaryTile-emotions').tap()  // this promise never resolved (
```

**I saw the next warning (in the node js process output):**

**BUT** in the emulator, I saw that a tap action was applied and a new screen was pushed

```js
detox[28921] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 2) invoke: {"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["DiaryTile-emotions"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]}

That might be the reason why the test "🍀 Emotion Diary should render diary intro" has timed out.
```

**Also, I saw an error in the Logcat output:** 

```js
	20:49:29.152	DetoxActionHandlers	Test exception
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:443)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
	at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
	at com.wix.invoke.types.Target.invoke(Target.java:59)
	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
	at com.wix.detox.InvokeActionHandler.handle(DetoxActionHandlers.kt:55)
	at com.wix.detox.DetoxManager$4.run(DetoxManager.java:116)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at com.wix.detox.Detox$1.run(Detox.java:214)
	at java.lang.Thread.run(Thread.java:764)
Caused by: androidx.test.espresso.PerformException: Error performing 'com.wix.detox.espresso.action.detoxsingletap@5cfbd85 click - At Coordinates: 799, 618 and precision: 16, 16' on view '(with tag value: is "DiaryTile-emotions" and view has effective visibility=VISIBLE)'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:87)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
	at com.wix.detox.espresso.EspressoDetox.perform(EspressoDetox.java:38)
	... 15 more
Caused by: androidx.test.espresso.AppNotIdleException: Looped for 15183 iterations over 180 SECONDS. The following Idle Conditions failed .
	at androidx.test.espresso.IdlingPolicy.handleTimeout(IdlingPolicy.java:59)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:541)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:447)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEventSequence(UiControllerImpl.java:308)
	at com.wix.detox.espresso.action.DetoxMultiTap.injectEvents(DetoxMultiTap.kt:83)
	at com.wix.detox.espresso.action.DetoxMultiTap.sendTap(DetoxMultiTap.kt:55)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:137)
	at com.wix.detox.espresso.action.RNClickAction.perform(RNClickAction.java:55)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**To Reproduce**

- [x] I have tested this issue on the latest(17.13.2) Detox release and it still reproduces
- [x] I have tested this issue on the next (18.0.0-next.5) Detox release and it still reproduces

Steps to reproduce:

1. integrate detox in the app
2. invoke `.tap()` that trigger `push()` (react-native-navigation) 
3. in the emulator a tap action was applied and a new screen was pushed
4. but `tap()` not resolved

**Expected behavior**
Tap resolve as expected

**Device and Verbose Detox Logs**

- [Detox logs](https://gist.github.com/retyui/6bbf44739c6721517d08caba61f8200d#file-nodejs-log)
- [Device logs](https://gist.github.com/retyui/6bbf44739c6721517d08caba61f8200d#file-logcat-log)

**Environment (please complete the following information):**
 - Detox: 17.13.2 | 18.0.0-next.5
 - React Native: 0.63.3
- react-native-navigation: 6.3.2
 - Node: 12
 - Device: [AOSP emulator](https://github.com/wix/Detox/blob/master/docs/Introduction.AndroidDevEnv.md#android-aosp-emulators)
 - OS: Android
 - Test-runner (select one): `jest-circus`

**Comment by retyui** [comment]
I tried some experiments with opened screen content. if screen render `null` `.tap()` will be resolved successfully... Hmmm

biting off piece by piece render screen content I find out that `<MaskedView/>` component breaks `.tap()`

**Comment by retyui** [comment]
A workground

```diff
// ./index.js
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
+import { View } from 'react-native';
+import * as M from '@react-native-community/masked-view';

+M.default = View;

AppRegistry.registerComponent(appName, () => App);
```

**Comment by d4vidi** [comment]
It seems that your app either holds or leaks an endless animation and thus never turns idle, preventing Detox from ever executing the tap.

> Side note: In due time, we will support Detox' `--debug-synchronization` argument in Android and it'd be easier to spot these kind of errors.

**Comment by tdekoning** [comment]
@retyui  perhaps this pull request will fix the issue you are experiencing: https://github.com/react-native-masked-view/masked-view/pull/98
