### ISSUE TITLE
Detox in Android Emulator cannot connect to local server but emulator browser can

### ISSUE THREAD

**Issue by greenlover1991** [wix/Detox#2559]
**Describe the bug**
I am executing an HTTP request via axios in my e2e tests to a local Apollo server endpoint `http://10.0.2.2:9082/graphql`. But the e2e test just hangs, and throws a timeout. **It seems the e2e test APK(?) cannot find 10.0.2.2:9082**.

But I'm sure my Android emulator is setup properly because:
* I can access the endpoint using the emulator's browser
* the app is also able to retrieve data from the same endpoint
* If I change the endpoint to something like `https://jsonplaceholder.typicode.com/todos/1`, the e2e tests runs fine (so it can retrieve from external source)
* I followed the setup and already added the flag `android:usesCleartextTraffic="true"` in the manifest.

**To Reproduce**

1. Start a local server in your workstation and make sure you can access the endpoint (e.g. localhost:9082/my/api.json) in your workstation's browser.
2. Start your android emulator, and launch the emulator's browser, and make sure you can access the above endpoint via `10.0.2.2:9082/my/api.json`
3. Start your react-native app, make sure that app can also access the endpoint (e.g. in a button click, running `await axios('10.0.2.2:9082/my/api.json')` returns correctly)
4. In your e2e tests:

```javascript
describe('sample test', () => {
  test('do HTTP request', async () => {
    await axios.post('http://10.0.2.2:9082/my/api.json', {}, {timeout: 3000, headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json; charset=utf-8'
    }}) // [BUG] the call will throw a timeout after 3 seconds
  })
})
```

- [ ] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**

Expected behavior is the network request in the e2e tests should not have timed-out since the emulator itself can access the endpoint.

**Screenshots**

* ![Android emulator's browser able to access endpoint](https://user-images.githubusercontent.com/927033/103261377-57d2d600-49dc-11eb-8f1b-c15957851436.png)

**Device and Verbose Detox Logs**

Attached logs:
* [detox_pid_21719.log](https://github.com/wix/Detox/files/5749753/detox_pid_21719.log)
* [emulator-5554 2020-12-29 05-49-20Z.startup.log](https://github.com/wix/Detox/files/5749754/emulator-5554.2020-12-29.05-49-20Z.startup.log)

snippet:

```
detox[21719] DEBUG: [exec.js/EXEC_SUCCESS, #2] List of devices attached
emulator-5554	device


detox[21719] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 5554, host: localhost
detox[21719] DEBUG: [FreeDeviceFinder.js/DEVICE_LOOKUP] Found a matching & free device emulator-5554
detox[21719] DEBUG: [EmulatorDeviceAllocator.js/ALLOCATE_DEVICE] Settled on emulator-5554
detox[21719] DEBUG: [exec.js/EXEC_CMD, #3] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop dev.bootcomplete"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #3] 1

detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-5554', type: 'TestingAVD' })
detox[21719] DEBUG: [exec.js/EXEC_CMD, #4] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #4] 29

detox[21719] DEBUG: [exec.js/EXEC_CMD, #5] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #5] 
detox[21719] DEBUG: [exec.js/EXEC_CMD, #6] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global window_animation_scale 0"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #6] 
detox[21719] DEBUG: [exec.js/EXEC_CMD, #7] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global transition_animation_scale 0"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #7] 
detox[21719] DEBUG: [exec.js/EXEC_CMD, #8] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #8]   mWakefulness=Awake
  mWakefulnessChanging=false
  mWakeLockSummary=0x1
  mUserActivitySummary=0x1
  mWakeUpWhenPluggedOrUnpluggedConfig=false
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false

detox[21719] DEBUG: [exec.js/EXEC_CMD, #9] "/Users/stevengo/Library/Android/sdk/build-tools/30.0.3/aapt" dump badging "/Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/android/app/build/outputs/apk/dev/debug/app-dev-debug.apk" | grep -e "package: name="
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #9] package: name='com.example.app.dev' versionCode='30' versionName='0.0.30-dev' compileSdkVersion='29' compileSdkVersionCodename='10'

detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-5554', bundleId: 'com.example.app.dev' })
detox[21719] DEBUG: [exec.js/EXEC_CMD, #10] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.example.app.dev"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #10] package:com.example.app.dev.test
package:com.example.app.dev

detox[21719] DEBUG: [exec.js/EXEC_CMD, #11] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 uninstall com.example.app.dev
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #11] Success

detox[21719] DEBUG: [exec.js/EXEC_CMD, #12] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.example.app.dev.test"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #12] package:com.example.app.dev.test

detox[21719] DEBUG: [exec.js/EXEC_CMD, #13] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 uninstall com.example.app.dev.test
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #13] Success

detox[21719] DEBUG: [exec.js/EXEC_CMD, #14] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #14] 
detox[21719] DEBUG: [exec.js/EXEC_CMD, #15] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #15] 
detox[21719] DEBUG: [exec.js/EXEC_CMD, #16] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/android/app/build/outputs/apk/dev/debug/app-dev-debug.apk" "/data/local/tmp/detox/Application.apk"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #16] /Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/android/app/build/outputs/apk/dev/debug/app-dev-debug.apk: 1 file pushed, 0 skipped. 206.7 MB/s (41682979 bytes in 0.192s)

detox[21719] DEBUG: [exec.js/EXEC_CMD, #17] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #17] Success

detox[21719] DEBUG: [exec.js/EXEC_CMD, #18] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/android/app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk" "/data/local/tmp/detox/Test.apk"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #18] /Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/android/app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk: 1 file pushed, 0 skipped. 406.9 MB/s (1391844 bytes in 0.003s)

detox[21719] DEBUG: [exec.js/EXEC_CMD, #19] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Test.apk"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #19] Success

detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-5554', bundleId: 'com.example.app.dev' })
detox[21719] DEBUG: [exec.js/EXEC_CMD, #20] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop com.example.app.dev"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #20] 
detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({ deviceId: 'emulator-5554', bundleId: 'com.example.app.dev' })
detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-5554',
  bundleId: 'com.example.app.dev',
  launchArgs: {
    detoxServer: 'ws://localhost:63769',
    detoxSessionId: '6e1326d5-ef5e-5d23-a361-a67a312c5fe7'
  }
})
detox[21719] DEBUG: [exec.js/EXEC_CMD, #21] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "date +\"%m-%d %T.000\""
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #21] 12-29 13:49:11.000

detox[21719] DEBUG: [exec.js/EXEC_CMD, #22] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse tcp:63769 tcp:63769
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #22] 63769

detox[21719] DEBUG: [exec.js/EXEC_CMD, #23] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list instrumentation"
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #23] instrumentation:com.example.app.dev.test/androidx.test.runner.AndroidJUnitRunner (target=com.example.app.dev)

detox[21719] DEBUG: [exec.js/SPAWN_CMD, #24] [pid=21782] /Users/stevengo/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:63769 -e detoxSessionId 6e1326d5-ef5e-5d23-a361-a67a312c5fe7 -e debug false com.example.app.dev.test/androidx.test.runner.AndroidJUnitRunner
detox[21719] DEBUG: [exec.js/EXEC_CMD, #25] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.example\.app\.dev$\""
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #25] u0_a127      29125  6397 4905008 168124 0                   0 R com.example.app.dev

detox[29125] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({
  deviceId: 'emulator-5554',
  bundleId: 'com.example.app.dev',
  launchArgs: {
    detoxServer: 'ws://localhost:63769',
    detoxSessionId: '6e1326d5-ef5e-5d23-a361-a67a312c5fe7'
  },
  pid: 29125
})
detox[21719] TRACE: [Artifact.js/START] starting ADBLogcatRecording
detox[21719] DEBUG: [exec.js/SPAWN_CMD, #26] [pid=21785] /Users/stevengo/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "logcat -T \"12-29 13:49:11.000\" --pid=29125 -f /sdcard/13499987_0.log"
detox[21719] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[21719] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=6e1326d5-ef5e-5d23-a361-a67a312c5fe7)
detox[21719] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=6e1326d5-ef5e-5d23-a361-a67a312c5fe7)
detox[21719] DEBUG: [exec.js/EXEC_CMD, #27] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell du /sdcard/13499987_0.log
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #27] 20	/sdcard/13499987_0.log

detox[21719] TRACE: [exec.js/SPAWN_STDOUT, #24] INSTRUMENTATION_STATUS: class=com.example.app.DetoxTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1

detox[21719] TRACE: [exec.js/SPAWN_STDOUT, #24] INSTRUMENTATION_STATUS: stream=
com.example.app.DetoxTest:
INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS_CODE: 1

detox[21719] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=6e1326d5-ef5e-5d23-a361-a67a312c5fe7
detox[21719] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=6e1326d5-ef5e-5d23-a361-a67a312c5fe7
detox[21719] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=6e1326d5-ef5e-5d23-a361-a67a312c5fe7)
detox[21719] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}
 
detox[29125] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAppReady({
  deviceId: 'emulator-5554',
  bundleId: 'com.example.app.dev',
  pid: 29125
})
ROOT_DESCRIBE_BLOCK[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'ROOT_DESCRIBE_BLOCK' })
sample test[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'sample test' })
detox[21719] INFO:  [97msample test[39m is assigned to [94memulator-5554 (TestingAVD)[39m
detox[21719] INFO:  [1m[37msample test: [39m[22m[90mdo HTTP request[39m
detox[21719] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "sample test do HTTP request"
detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestStart({
  title: 'do HTTP request',
  fullName: 'sample test do HTTP request',
  status: 'running',
  invocations: 1
})
detox[21719] TRACE: [Artifact.js/STOP] stopping ADBLogcatRecording
detox[21719] DEBUG: [exec.js/EXEC_CMD, #28] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "date +\"%m-%d %T.000\""
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #28] 12-29 13:49:16.000

detox[21719] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 21785]: /Users/stevengo/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell logcat -T "12-29 13:49:11.000" --pid=29125 -f /sdcard/13499987_0.log
detox[21719] TRACE: [exec.js/SPAWN_END, #26] /Users/stevengo/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "logcat -T \"12-29 13:49:11.000\" --pid=29125 -f /sdcard/13499987_0.log" terminated with SIGINT
detox[21719] TRACE: [Artifact.js/START] starting ADBLogcatRecording
detox[21719] DEBUG: [exec.js/SPAWN_CMD, #29] [pid=21820] /Users/stevengo/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "logcat -T \"12-29 13:49:16.000\" --pid=29125 -f /sdcard/13499987_1.log"
detox[21719] DEBUG: [exec.js/EXEC_CMD, #30] "/Users/stevengo/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell du /sdcard/13499987_1.log
detox[21719] TRACE: [exec.js/EXEC_SUCCESS, #30] 8	/sdcard/13499987_1.log

detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestFnFailure({
  error: Error: timeout of 3000ms exceeded
      at createError (/Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/node_modules/axios/lib/core/createError.js:16:15)
      at RedirectableRequest.handleRequestTimeout (/Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/node_modules/axios/lib/adapters/http.js:264:16)
      at Object.onceWrapper (events.js:421:28)
      at RedirectableRequest.emit (events.js:315:20)
      at Timeout._onTimeout (/Users/stevengo/Code/ReactNativeProjects/sampleapp-app/frontend/app/node_modules/follow-redirects/index.js:166:13)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7) {
    config: {
      url: 'http://10.0.2.2:9082/graphql',
      method: 'post',
      data: '{"query":"mutation{deleteAllUserCards}"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 3000,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    code: 'ECONNABORTED',
    request: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: false,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 40,
      _requestBodyBuffers: [Array],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [ClientRequest],
      _currentUrl: 'http://10.0.2.2:9082/graphql',
      _timeout: Timeout {
        _idleTimeout: 3000,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 9348,
        _onTimeout: [Function (anonymous)],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 916,
        [Symbol(triggerId)]: 912
      },
      [Symbol(kCapture)]: false
    },
    response: undefined,
    isAxiosError: true,
    toJSON: [Function: toJSON]
  }
})
detox[21719] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "sample test do HTTP request"
detox[21719] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestDone({
  title: 'do HTTP request',
  fullName: 'sample test do HTTP request',
  status: 'failed',
  invocations: 1,
  timedOut: false
})
detox[21719] TRACE: [Artifact.js/STOP] stopping ADBLogcatRecording
```

**Environment (please complete the following information):**
 - Detox: `"detox": "^17.14.3"`
 - React Native: `"react-native": "0.63.4"`
 - Node: v14.15.3
 - Device: Android emulator (Android 10 x86_64)
 - OS: macOS Catalina
 - Test-runner (select one): `jest-circus` (`jest-circus": "^26.6.3"`)

**Comment by greenlover1991** [comment]
Ah, I think I misunderstood how Detox works and got confused with this https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#6-enable-clear-text-unencrypted-traffic-for-detox

> For Detox to work, Detox test code running on the device must connect to the test-running host through it's virtual localhost interface(*) using simple HTTP traffic. 

Since my detox clean up script is NOT executed on the device, so it should not use the 10.0.2.2 but simply localhost

So to fix the issue, I simply changed from:

```javascript
await axios.post('http://10.0.2.2:9082/my/api.json', {}, {timeout: 3000, headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json; charset=utf-8'
    }})
```

To:

```
await axios.post('http://localhost:9082/my/api.json', {}, {timeout: 3000, headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json; charset=utf-8'
    }})
```

Closing this ticket. Thanks

**Comment by d4vidi** [comment]
@greenlover1991 thanks for the detailed info. I am nonetheless a bit baffled by your use case, and would like to better understand what happened. In particular, since your Apollo server runs on the host machine, you actually _should_ be using `10.0.2.2` - as it's the alias for the host's (not emulator's) loopback interface. That in fact means that theoretically, that's what should have worked for you, rather than the `localhost` solution.

Could you maybe try to do the following:
1. Revert back to using `10.0.2.2`.
2. Enable cleartext for 10.0.2.2, specifically, in your AndroidManifest.xml file (as explained by the [doc you've mentioned](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#6-enable-clear-text-unencrypted-traffic-for-detox)).

In any case, one technique that can free you from all of this is the usage of the [`device.reverseTcpPort()` API](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicereversetcpport-android-only), which is equivalent to `adb reverse`.

**Comment by greenlover1991** [comment]
@d4vidi thanks for your response. 

> Could you maybe try to do the following:
> 1. Revert back to using 10.0.2.2.
> 2. Enable cleartext for 10.0.2.2, specifically, in your AndroidManifest.xml file (as explained by the doc you've mentioned).

I have tried this and still failed. I even set the `targetSdkVersion` 27 so it will ignore the cleartext flag, but also failed. 

What my team lead told me is that that detox runs in a separate server (proxy?) so it doesn't run in the emulator device per se, but on the workstation, so it doesn't know what 10.0.2.2 is. Please correct me if wrong. 

But the React Native app code itself is using `10.0.2.2` to communicate with the Apollo server, and it works fine. We only changed the detox test code to use `localhost`.

**Comment by a-tokyo** [comment]
Has any fix been reached for this? Thanks in advance!

**Comment by d4vidi** [comment]
> Has any fix been reached for this? Thanks in advance!

I have no other suggestions, I'm afraid. Nevertheless, in our to try to get a lead on the source of the problem, I would start by trying to reach the Apollo ( / whatever) localhost server via an `adb shell`, namely, leaving the app itself out of the equation.
