### ISSUE TITLE
Unhandled promise in cleanup

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2576]
## Description

Intermittently, there's an error that pops when a tear-down takes place in the end of the suite:
```
UnhandledPromiseRejectionWarning: ChildProcessError: Command failed: "/Users/amitd/Library/Android/sdk/platform-tools/adb" -s emulator-13240 reverse --remove tcp:52331
adb: error: device 'emulator-13240' not found
```

In the very least, that happens in these 2 use cases:
1. Running tests using local Google emulators / Genycloud with the `--cleanup` arg.
2. Running using Genycloud instances; Here, it happens in the global tear-down.

The origin of this error is the handler of instrumentation shutdown - which tries to "unreverse" the connection from the emulator back to the Detox server. It need to somehow support this abrupt shutdown, which occurs due to an emulator tear-down rather than through a controlled clean-up.

Below is an example of the complete error:
```
 PASS  e2e/01.sanity.test.js (14.933 s)
  Sanity
    ✓ should have welcome screen (1664 ms)
    ✓ should show hello screen after tap (1907 ms)
    ✓ should show world screen after tap (1921 ms)

detox[12772] WARN:  at node_modules/jest/node_modules/jest-cli/build/cli/index.js:261:15
 Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
detox[12772] ERROR: [exec.js/EXEC_FAIL, #47] ""/Users/amitd/Library/Android/sdk/platform-tools/adb" -s emulator-13240 reverse --remove tcp:52331" failed with code = 1, stdout and stderr:

detox[12772] ERROR: [exec.js/EXEC_FAIL, #47]
detox[12772] ERROR: [exec.js/EXEC_FAIL, #47] adb: error: device 'emulator-13240' not found

detox[12772] ERROR: at internal/process/warning.js:27:3
 (node:12772) UnhandledPromiseRejectionWarning: ChildProcessError: Command failed: "/Users/amitd/Library/Android/sdk/platform-tools/adb" -s emulator-13240 reverse --remove tcp:52331
adb: error: device 'emulator-13240' not found
 `"/Users/amitd/Library/Android/sdk/platform-tools/adb" -s emulator-13240 reverse --remove tcp:52331` (exited with error code 1)
    at callback (/Users/amitd/dev/Detox2/detox/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
detox[12772] ERROR: at internal/process/warning.js:27:3
 (node:12772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
detox[12772] ERROR: at internal/process/warning.js:27:3
 (node:12772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by noomorph** [comment]
Still relevant, right?

**Comment by d4vidi** [comment]
Ain't seen it for a while. Closing for now.

**Comment by gunnartorfis** [comment]
Same here.

**Comment by sergtimosh** [comment]
Me too.
