### ISSUE TITLE
 No instrumentation runner found on device

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [wix/Detox#2597]
### Describe the bug
 `detox test --configuration android` command fails with 
```
No instrumentation runner found on device emulator-12360 for package com.reach 
```
### Steps To Reproduce

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. I have followed the instructions from the documentation markdown files

### Expected behavior

Tests should run on the test command.

### Detox Trace-Logs

```
a-c-sreedhar-reddy@acreddybook:~/spritle/mobility$ detox test --configuration android --loglevel trace 
detox[32884] INFO:  [test.js] DETOX_CONFIGURATION="android" DETOX_FORCE_ADB_INSTALL=false DETOX_LOGLEVEL="trace" DETOX_READ_ONLY_EMU=false DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1610859420187 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[32897] TRACE: [Detox.js/DETOX_CREATE] created a Detox instance with config:
{"artifactsConfig":{"rootDir":"artifacts/android.2021-01-17 04-57-00Z","plugins":{"log":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"screenshot":{"enabled":true,"shouldTakeAutomaticSnapshots":false,"keepOnlyFailedTestsArtifacts":false},"video":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"instruments":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"timeline":{"enabled":false},"uiHierarchy":{"enabled":false,"keepOnlyFailedTestsArtifacts":false}},"pathBuilder":{"_rootDir":"artifacts/android.2021-01-17 04-57-00Z"}},"behaviorConfig":{"init":{"reinstallApp":true,"exposeGlobals":true},"cleanup":{"shutdownDevice":false},"launchApp":"auto"},"cliConfig":{"configuration":"android","forceAdbInstall":"false","loglevel":"trace","useCustomLogger":"true"},"deviceConfig":{"type":"android.emulator","testBinaryPath":"android/app/build/outputs/apk/staging/debug/app-staging-debug.apk","binaryPath":"android/app/build/outputs/apk/staging/debug/app-staging-debug.apk","build":"npx jetifier && cd android && ./gradlew assembleStagingDebug   -DtestBuildType=debug && cd ..","device":{"avdName":"Pixel_API_28_AOSP"}},"runnerConfig":{"testRunner":"jest","runnerConfig":"e2e/config.json","specs":"e2e"},"sessionConfig":{"autoStart":true,"server":"ws://localhost:40259","sessionId":"e753b79c-9b24-30c7-ae1e-bdf83ce98fbd","debugSynchronization":false},"errorBuilder":{"filepath":"/home/a-c-sreedhar-reddy/spritle/mobility/.detoxrc.json","contents":{"testRunner":"jest","runnerConfig":"e2e/config.json","configurations":{"ios":{"type":"ios.simulator","binaryPath":"SPECIFY_PATH_TO_YOUR_APP_BINARY","device":{"type":"iPhone 11"}},"android":{"type":"android.emulator","testBinaryPath":"android/app/build/outputs/apk/staging/debug/app-staging-debug.apk","binaryPath":"android/app/build/outputs/apk/staging/debug/app-staging-debug.apk","build":"npx jetifier && cd android && ./gradlew assembleStagingDebug   -DtestBuildType=debug && cd ..","device":{"avdName":"Pixel_API_28_AOSP"}}}},"configurationName":"android"}}
detox[32897] INFO:  [DetoxServer.js] server listening on localhost:40259...
detox[32897] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:40259
detox[32897] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"e753b79c-9b24-30c7-ae1e-bdf83ce98fbd","role":"tester"},"messageId":0}
detox[32897] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=e753b79c-9b24-30c7-ae1e-bdf83ce98fbd
detox[32897] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=e753b79c-9b24-30c7-ae1e-bdf83ce98fbd
detox[32897] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"e753b79c-9b24-30c7-ae1e-bdf83ce98fbd","role":"tester"},"messageId":0}
 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #0] "/home/a-c-sreedhar-reddy/Android/Sdk/emulator/emulator" -list-avds --verbose
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #0] Pixel_3a_API_R
Pixel_API_28_AOSP
detox_emu_api_30

detox[32897] DEBUG: [exec.js/EXEC_CMD, #1] "/home/a-c-sreedhar-reddy/Android/Sdk/emulator/emulator" -version 
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #1] Android emulator version 30.3.5.0 (build_id 7033400) (CL:N/A)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.


detox[32897] DEBUG: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 30, minor: 3, patch: 5, toString: [Function: toString] }
detox[32897] DEBUG: [EmulatorDeviceAllocation.js/ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_API_28_AOSP"
detox[32897] DEBUG: [exec.js/EXEC_CMD, #2] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb"  devices
detox[32897] DEBUG: [exec.js/EXEC_SUCCESS, #2] List of devices attached
emulator-12360  device


detox[32897] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 12360, host: localhost
detox[32897] DEBUG: [FreeDeviceFinder.js/DEVICE_LOOKUP] Found a matching & free device emulator-12360
detox[32897] DEBUG: [EmulatorDeviceAllocation.js/ALLOCATE_DEVICE] Settled on emulator-12360
detox[32897] DEBUG: [exec.js/EXEC_CMD, #3] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "getprop dev.bootcomplete"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #3] 1

detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({
  coldBoot: false,
  deviceId: 'emulator-12360',
  type: 'Pixel_API_28_AOSP'
})
detox[32897] DEBUG: [exec.js/EXEC_CMD, #4] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "getprop ro.build.version.sdk"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #4] 28

detox[32897] DEBUG: [exec.js/EXEC_CMD, #5] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "settings put global animator_duration_scale 0"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #5] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #6] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "settings put global window_animation_scale 0"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #6] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #7] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "settings put global transition_animation_scale 0"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #7] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #8] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #8]   mWakefulness=Awake
  mWakefulnessChanging=false
  mWakeLockSummary=0x0
  mUserActivitySummary=0x1
  mWakeUpWhenPluggedOrUnpluggedConfig=false
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false

detox[32897] DEBUG: [exec.js/EXEC_CMD, #9] "/home/a-c-sreedhar-reddy/Android/Sdk/build-tools/29.0.2/aapt" dump badging "/home/a-c-sreedhar-reddy/spritle/mobility/android/app/build/outputs/apk/staging/debug/app-staging-debug.apk" | grep -e "package: name="
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #9] package: name='com.reach' versionCode='30' versionName='2.0.12' compileSdkVersion='28' compileSdkVersionCodename='9'

detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] DEBUG: [exec.js/EXEC_CMD, #10] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm list packages com.reach"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #10] package:com.reach

detox[32897] DEBUG: [exec.js/EXEC_CMD, #11] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 uninstall com.reach
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #11] Success

detox[32897] DEBUG: [exec.js/EXEC_CMD, #12] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm list packages com.reach.test"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #12] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #13] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "rm -fr /data/local/tmp/detox"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #13] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #14] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "mkdir -p /data/local/tmp/detox"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #14] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #15] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 push "/home/a-c-sreedhar-reddy/spritle/mobility/android/app/build/outputs/apk/staging/debug/app-staging-debug.apk" "/data/local/tmp/detox/Application.apk"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #15] /home/a-c-sreedhar-reddy/spritle/mobility/android/app/build/outputs/apk/staging/debug/app-staging-debug.apk: 1 file pushed. 317.4 MB/s (43304105 bytes in 0.130s)

detox[32897] DEBUG: [exec.js/EXEC_CMD, #16] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #16] Success

detox[32897] DEBUG: [exec.js/EXEC_CMD, #17] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 push "/home/a-c-sreedhar-reddy/spritle/mobility/android/app/build/outputs/apk/staging/debug/app-staging-debug.apk" "/data/local/tmp/detox/Test.apk"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #17] /home/a-c-sreedhar-reddy/spritle/mobility/android/app/build/outputs/apk/staging/debug/app-staging-debug.apk: 1 file pushed. 162.4 MB/s (43304105 bytes in 0.254s)

detox[32897] DEBUG: [exec.js/EXEC_CMD, #18] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm install -r -g -t /data/local/tmp/detox/Test.apk"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #18] Success

ROOT_DESCRIBE_BLOCK[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'ROOT_DESCRIBE_BLOCK' })
Example[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'Example' })
detox[32897] INFO:  Example is assigned to emulator-12360 (Pixel_API_28_AOSP)
detox[32897] INFO:  Example: should have welcome screen
detox[32897] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "Example should have welcome screen"
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestStart({
  title: 'should have welcome screen',
  fullName: 'Example should have welcome screen',
  status: 'running',
  invocations: 1
})
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] DEBUG: [exec.js/EXEC_CMD, #19] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "am force-stop com.reach"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #19] 
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-12360',
  bundleId: 'com.reach',
  launchArgs: {
    detoxServer: 'ws://localhost:40259',
    detoxSessionId: 'e753b79c-9b24-30c7-ae1e-bdf83ce98fbd'
  }
})
detox[32897] DEBUG: [exec.js/EXEC_CMD, #20] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "date +\"%m-%d %T.000\""
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #20] 01-17 10:27:03.000

detox[32897] DEBUG: [exec.js/EXEC_CMD, #21] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 reverse tcp:40259 tcp:40259
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #21] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #22] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm list instrumentation"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #22] instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)

detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onHookFailure({
  error: Error: No instrumentation runner found on device emulator-12360 for package com.reach
      at ADB.getInstrumentationRunner (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/exec/ADB.js:250:13)
      at Instrumentation.launch (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:19:24)
      at MonitoredInstrumentation.launch (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:18:5)
      at EmulatorDriver._launchInstrumentationProcess (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:284:5)
      at EmulatorDriver._launchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:267:7)
      at EmulatorDriver._handleLaunchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:120:7)
      at EmulatorDriver.launchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:91:12)
      at Device._doLaunchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/Device.js:85:19)
      at traceCall (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/utils/trace.js:41:20),
  hook: 'beforeEach'
})
detox[32897] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "Example should have welcome screen"
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestDone({
  title: 'should have welcome screen',
  fullName: 'Example should have welcome screen',
  status: 'failed',
  invocations: 1,
  timedOut: false
})
detox[32897] INFO:  Example: should have welcome screen [FAIL]
detox[32897] INFO:  Example: should show hello screen after tap
detox[32897] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "Example should show hello screen after tap"
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestStart({
  title: 'should show hello screen after tap',
  fullName: 'Example should show hello screen after tap',
  status: 'running',
  invocations: 1
})
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] DEBUG: [exec.js/EXEC_CMD, #23] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "am force-stop com.reach"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #23] 
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-12360',
  bundleId: 'com.reach',
  launchArgs: {
    detoxServer: 'ws://localhost:40259',
    detoxSessionId: 'e753b79c-9b24-30c7-ae1e-bdf83ce98fbd'
  }
})
detox[32897] DEBUG: [exec.js/EXEC_CMD, #24] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "date +\"%m-%d %T.000\""
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #24] 01-17 10:27:03.000

detox[32897] DEBUG: [exec.js/EXEC_CMD, #25] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 reverse tcp:40259 tcp:40259
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #25] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #26] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm list instrumentation"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #26] instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)

detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onHookFailure({
  error: Error: No instrumentation runner found on device emulator-12360 for package com.reach
      at ADB.getInstrumentationRunner (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/exec/ADB.js:250:13)
      at Instrumentation.launch (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:19:24)
      at MonitoredInstrumentation.launch (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:18:5)
      at EmulatorDriver._launchInstrumentationProcess (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:284:5)
      at EmulatorDriver._launchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:267:7)
      at EmulatorDriver._handleLaunchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:120:7)
      at EmulatorDriver.launchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:91:12)
      at Device._doLaunchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/Device.js:85:19)
      at traceCall (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/utils/trace.js:41:20),
  hook: 'beforeEach'
})
detox[32897] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "Example should show hello screen after tap"
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestDone({
  title: 'should show hello screen after tap',
  fullName: 'Example should show hello screen after tap',
  status: 'failed',
  invocations: 1,
  timedOut: false
})
detox[32897] INFO:  Example: should show hello screen after tap [FAIL]
detox[32897] INFO:  Example: should show world screen after tap
detox[32897] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: "Example should show world screen after tap"
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestStart({
  title: 'should show world screen after tap',
  fullName: 'Example should show world screen after tap',
  status: 'running',
  invocations: 1
})
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] DEBUG: [exec.js/EXEC_CMD, #27] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "am force-stop com.reach"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #27] 
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({ deviceId: 'emulator-12360', bundleId: 'com.reach' })
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  deviceId: 'emulator-12360',
  bundleId: 'com.reach',
  launchArgs: {
    detoxServer: 'ws://localhost:40259',
    detoxSessionId: 'e753b79c-9b24-30c7-ae1e-bdf83ce98fbd'
  }
})
detox[32897] DEBUG: [exec.js/EXEC_CMD, #28] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "date +\"%m-%d %T.000\""
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #28] 01-17 10:27:03.000

detox[32897] DEBUG: [exec.js/EXEC_CMD, #29] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 reverse tcp:40259 tcp:40259
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #29] 
detox[32897] DEBUG: [exec.js/EXEC_CMD, #30] "/home/a-c-sreedhar-reddy/Android/Sdk/platform-tools/adb" -s emulator-12360 shell "pm list instrumentation"
detox[32897] TRACE: [exec.js/EXEC_SUCCESS, #30] instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)

detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onHookFailure({
  error: Error: No instrumentation runner found on device emulator-12360 for package com.reach
      at ADB.getInstrumentationRunner (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/exec/ADB.js:250:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Instrumentation.launch (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:19:24)
      at MonitoredInstrumentation.launch (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:18:5)
      at EmulatorDriver._launchInstrumentationProcess (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:284:5)
      at EmulatorDriver._launchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:267:7)
      at EmulatorDriver._handleLaunchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:120:7)
      at EmulatorDriver.launchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:91:12)
      at Device._doLaunchApp (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/devices/Device.js:85:19)
      at traceCall (/home/a-c-sreedhar-reddy/spritle/mobility/node_modules/detox/src/utils/trace.js:41:20),
  hook: 'beforeEach'
})
detox[32897] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "Example should show world screen after tap"
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestDone({
  title: 'should show world screen after tap',
  fullName: 'Example should show world screen after tap',
  status: 'failed',
  invocations: 1,
  timedOut: false
})
detox[32897] INFO:  Example: should show world screen after tap [FAIL]
Example[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'Example' })

ROOT_DESCRIBE_BLOCK[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'ROOT_DESCRIBE_BLOCK' })
detox[32897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeCleanup()
detox[32897] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=e753b79c-9b24-30c7-ae1e-bdf83ce98fbd
detox[32897] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
 FAIL  e2e/firstTest.e2e.js
  Example
    ✕ should have welcome screen (181 ms)
    ✕ should show hello screen after tap (124 ms)
    ✕ should show world screen after tap (113 ms)

  ● Example › should have welcome screen

    No instrumentation runner found on device emulator-12360 for package com.reach

      at ADB.getInstrumentationRunner (../node_modules/detox/src/devices/drivers/android/exec/ADB.js:250:13)
      at Instrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:19:24)
      at MonitoredInstrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:18:5)
      at EmulatorDriver._launchInstrumentationProcess (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:284:5)
      at EmulatorDriver._launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:267:7)
      at EmulatorDriver._handleLaunchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:120:7)
      at EmulatorDriver.launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:91:12)
      at Device._doLaunchApp (../node_modules/detox/src/devices/Device.js:85:19)
      at traceCall (../node_modules/detox/src/utils/trace.js:41:20)

  ● Example › should show hello screen after tap

    No instrumentation runner found on device emulator-12360 for package com.reach

      at ADB.getInstrumentationRunner (../node_modules/detox/src/devices/drivers/android/exec/ADB.js:250:13)
      at Instrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:19:24)
      at MonitoredInstrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:18:5)
      at EmulatorDriver._launchInstrumentationProcess (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:284:5)
      at EmulatorDriver._launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:267:7)
      at EmulatorDriver._handleLaunchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:120:7)
      at EmulatorDriver.launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:91:12)
      at Device._doLaunchApp (../node_modules/detox/src/devices/Device.js:85:19)
      at traceCall (../node_modules/detox/src/utils/trace.js:41:20)

  ● Example › should show world screen after tap

    No instrumentation runner found on device emulator-12360 for package com.reach

      at ADB.getInstrumentationRunner (../node_modules/detox/src/devices/drivers/android/exec/ADB.js:250:13)
      at Instrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:19:24)
      at MonitoredInstrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:18:5)
      at EmulatorDriver._launchInstrumentationProcess (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:284:5)
      at EmulatorDriver._launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:267:7)
      at EmulatorDriver._handleLaunchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:120:7)
      at EmulatorDriver.launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:91:12)
      at Device._doLaunchApp (../node_modules/detox/src/devices/Device.js:85:19)
      at traceCall (../node_modules/detox/src/utils/trace.js:41:20)

detox[32884] ERROR: [cli.js] Error: Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
```

### Environment (please complete the following information):
 - Detox:18.1.1
 - React Native:0.59.9
 - Node:12.18.2
 - Device:AOSP 
 - OS: Android
 - Test-runner (select one): `jest-circus`

**Comment by d4vidi** [comment]
@a-c-sreedhar-reddy you've clearly left something out, setting up Detox for this project. Please post on SO and paste the link back here, I will try to help.

**Comment by a-c-sreedhar-reddy** [comment]
HI @d4vidi I have fixed this. But currently I have another issue. https://stackoverflow.com/q/66294619/11537438 can you please help me with this?

**Comment by laisvitoria** [comment]
Hello, I have same problem, what is the resolution?

**Comment by a-c-sreedhar-reddy** [comment]
@laisvitoria Sorry, I do not remember how I fixed it. I should have commented it.
