### ISSUE TITLE
Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource] to become idle timed out

### ISSUE THREAD

**Issue by yungkittty** [wix/Detox#2633]
My e2e tests fail with the following output : 

```
Run yarn start & yarn e2e:test android.emu.release --headless
  yarn start & yarn e2e:test android.emu.release --headless
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-openjdk8-hotspot-normal-latest/x64
    JAVA_HOME_openjdk8_x64: /Users/runner/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-openjdk8-hotspot-normal-latest/x64
yarn run v1.22.5
yarn run v1.22.5
$ react-native start
$ detox test --loglevel verbose --configuration android.emu.release --headless
detox[4902] INFO:  [test.js] DETOX_CONFIGURATION="android.emu.release" DETOX_FORCE_ADB_INSTALL=false DETOX_HEADLESS=true DETOX_LOGLEVEL="verbose" DETOX_READ_ONLY_EMU=false DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1612996337167 DETOX_USE_CUSTOM_LOGGER=true jest --config __e2e__/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          
                 Welcome to React Native!
                Learn once, write anywhere



Downloading Test-Butler APK...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  129k  100  129k    0     0   138k      0 --:--:-- --:--:-- --:--:--  138k
detox[4908] INFO:  [DetoxServer.js] server listening on localhost:49813...
detox[4908] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:49813
detox[4908] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c
detox[4908] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c
detox[4908] DEBUG: [exec.js/EXEC_CMD, #0] "/Users/runner/Library/Android/sdk/emulator/emulator" -list-avds --verbose
detox[4908] DEBUG: [exec.js/EXEC_CMD, #1] "/Users/runner/Library/Android/sdk/emulator/emulator" -version -no-window
detox[4908] DEBUG: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 30, minor: 3, patch: 5, toString: [Function: toString] }
detox[4908] DEBUG: [EmulatorDeviceAllocation.js/ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_API_29_AOSP"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #2] "/Users/runner/Library/Android/sdk/platform-tools/adb"  devices
detox[4908] DEBUG: [exec.js/EXEC_SUCCESS, #2] List of devices attached
emulator-5554	device


detox[4908] DEBUG: [FreeDeviceFinder.js/DEVICE_LOOKUP] Found a matching & free device emulator-5554
detox[4908] DEBUG: [EmulatorDeviceAllocation.js/ALLOCATE_DEVICE] Settled on emulator-5554
detox[4908] DEBUG: [exec.js/EXEC_CMD, #3] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop dev.bootcomplete"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #4] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #5] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #6] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global window_animation_scale 0"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #7] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global transition_animation_scale 0"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #8] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[4908] DEBUG: [exec.js/EXEC_CMD, #9] "/Users/runner/Library/Android/sdk/build-tools/30.0.3/aapt" dump badging "/Users/runner/work/b2c-app/b2c-app/android/app/build/outputs/apk/e2e/release/app-e2e-release.apk" | grep -e "package: name="
detox[4908] DEBUG: [exec.js/EXEC_CMD, #10] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.shotguntheapp.android.e2e"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #11] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.shotguntheapp.android.e2e.test"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #12] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #13] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #14] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/runner/work/b2c-app/b2c-app/android/app/build/outputs/apk/e2e/release/app-e2e-release.apk" "/data/local/tmp/detox/Application.apk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #15] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #16] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/runner/work/b2c-app/b2c-app/android/app/build/outputs/apk/androidTest/e2e/release/app-e2e-release-androidTest.apk" "/data/local/tmp/detox/Test.apk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #17] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Test.apk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #18] "/Users/runner/Library/Android/sdk/build-tools/30.0.3/aapt" dump badging "/Users/runner/work/b2c-app/b2c-app/cache/test-butler-app.apk" | grep -e "package: name="
detox[4908] DEBUG: [exec.js/EXEC_CMD, #19] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.linkedin.android.testbutler"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #20] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #21] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #22] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "./cache/test-butler-app.apk" "/data/local/tmp/detox/Application.apk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #23] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #24] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop com.shotguntheapp.android.e2e"
detox[4908] DEBUG: [exec.js/EXEC_CMD, #25] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "date +\"%m-%d %T.000\""
detox[4908] DEBUG: [exec.js/EXEC_CMD, #26] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse tcp:49813 tcp:49813
detox[4908] DEBUG: [exec.js/EXEC_CMD, #27] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list instrumentation"
detox[4908] DEBUG: [exec.js/SPAWN_CMD, #28] [pid=5190] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:49813 -e detoxSessionId f651d12e-028a-73de-f1a7-93cc45c4ae8c -e debug false com.shotguntheapp.android.e2e.test/com.shotguntheapp.android.DetoxTestAppJUnitRunner
detox[4908] DEBUG: [exec.js/EXEC_CMD, #29] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"com\.shotguntheapp\.android\.e2e$\""
detox[4908] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=app not connected, cannot fw action (sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c)
detox[4908] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=app not connected, cannot fw action (sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c)
detox[4908] DEBUG: [DetoxServer.js/LOGIN] role=app, sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c
detox[4908] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=app, sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c
detox[4908] INFO:  should ...
detox[4908] INFO:  [actions.js] undefined
detox[4908] INFO:  should ... [FAIL]
detox[4908] INFO:  [actions.js] undefined
detox[4908] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 5190]: /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:49813 -e detoxSessionId f651d12e-028a-73de-f1a7-93cc45c4ae8c -e debug false com.shotguntheapp.android.e2e.test/com.shotguntheapp.android.DetoxTestAppJUnitRunner
detox[4908] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c
detox[4908] DEBUG: [exec.js/KILL] sending SIGINT to [pid = 5190]: /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:49813 -e detoxSessionId f651d12e-028a-73de-f1a7-93cc45c4ae8c -e debug false com.shotguntheapp.android.e2e.test/com.shotguntheapp.android.DetoxTestAppJUnitRunner
detox[4908] DEBUG: [exec.js/EXEC_CMD, #30] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:49813
detox[4908] DEBUG: [DetoxServer.js/DISCONNECT] role=app, sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c
detox[4908] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=f651d12e-028a-73de-f1a7-93cc45c4ae8c)
detox[4908] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
FAIL __e2e__/payment.e2e.js (194.474 s)
  ✕ should ... (127038 ms)

  ● should ...

    Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource] to become idle timed out

       5 |   // This goes to the email login screen!
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       6 |   await element(by.id('AuthButtonWithEmail')).tap();
    >  7 |   await element(by.id('AuthButtonToLogin')).tap();
         |                                             ^
       8 | 
       9 |   // This fills the email!
      10 |   await element(by.id('AuthInputEmail')).atIndex(1).tap();

      at loginWithEmail$ (auth.utils.js:7:45)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:154:20)
      at ../node_modules/regenerator-runtime/runtime.js:164:13

  ● should ...

    Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource] to become idle timed out

      37 |   await element(by.id('HomeButtonProfile'))
      38 |     // This makes sure the button is clicked and not the nested icon!
    > 39 |     .tap({ x: 0, y: 0 });
         |      ^
      40 | 
      41 |   // This goes to the settings screen!
      42 |   await element(by.id('ProfileButtonSettings'))

      at logout$ (auth.utils.js:39:6)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:154:20)
      at ../node_modules/regenerator-runtime/runtime.js:189:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:188:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:211:13)
      at AsyncIterator.next (../node_modules/regenerator-runtime/runtime.js:118:21)

detox[4902] ERROR: [cli.js] Error: Command failed: jest --config __e2e__/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e

error Command failed with exit code 1.
Error: Process completed with exit code 1.
```

I don't find any resources online talking about the follwing error : 

`Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource] to become idle timed out`

I'm running my test on GitHub Actions. They work perfectly locally but doesn't on CI. Any ideas ?

**Comment by d4vidi** [comment]
@yungkittty please review the *native-Android* timeout configuration API: https://github.com/wix/Detox/blob/master/examples/demo-react-native/android/app/src/androidTest/java/com/example/DetoxTest.java#L27

Try to use very long time-outs in your tests, esp. when running on CI, and see if it helps. Thanks.

**Comment by yungkittty** [comment]
@d4vidi I changed the way i setup my emulator on the CI and it works now! Thanks for the tips tho <3

**Comment by d4vidi** [comment]
Could you please elaborate?

**Comment by yungkittty** [comment]
I was running my emulator manually on github actions.
Now i'm using [this](https://github.com/marketplace/actions/android-emulator-runner).
Since i'm using this github action it works.
I think it might be because they disable animation. (i'm not sure in fact)

**Comment by d4vidi** [comment]
Hmm nice! Detox also disables the native animations for you, so that's not it. Also, the unsettled animation you've described is a react-native based animation, and it cannot be controlled this way. So again, definitely not it.

**Comment by yungkittty** [comment]
@d4vidi Okay, so I don't know what was wrong. 🤷‍♂️
