### ISSUE TITLE
Can't install detox on ios Sig

### ISSUE THREAD

**Issue by avgurf** [wix/Detox#2722]
### Description
I have updated recently to macOs BigSur 11.2.3 and installed xcode v12.4, and updated my packages using `yarn update` when i try to install detox i get the following error:

```sers/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox
Output:
+ xcodebuild -version
+++ dirname /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/scripts
+ detoxRootPath=/Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox
++ node -p 'require('\''/Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/package.json'\'').version'
+ detoxVersion=12.3.0
++ echo 12.3.0
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=d3f9b80bf0891c73feb4acb42c519d4c27bdea58
+ detoxFrameworkDirPath=/Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58
+ detoxFrameworkPath=/Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58/Detox.framework
+ main
+ '[' -d /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58 ']'
+ '[' '!' -d /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58/Detox.framework ']'
+ echo '/Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58 and trying to rebuild.'
+ rm -rf /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58
+ prepareAndBuildFramework
+ '[' -d /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ extractSources /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ detoxSourcePath=/Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
+ mkdir -p /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ tar -xjf /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/Detox-ios-src.tbz -C /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ buildFramework /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ detoxSourcePath=/Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src...'
+ mkdir -p /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58
+ /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/scripts/build_universal_framework.sh /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src/Detox.xcodeproj /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58
/Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/avig/Library/Detox/ios/d3f9b80bf0891c73feb4acb42c519d4c27bdea58 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/ios_src...
child_process.js:656
    throw err;
    ^

Error: Command failed: /Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at Object.<anonymous> (/Users/avig/Documents/Workspace/kahun/kne.fe/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 94761,
  stdout: null,




error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/local/Cellar/yarn/1.19.2/libexec/lib/cli.js add detox
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction
couldn't test it onther machines so i wonder if anyone else with big sur and xcode 12 had experienced that
1.  Update to maxOs BigSur
2. Install xcode 12
3. run `yarn add detox`

#### Expected behavior
Install completes successfully 

#### Environment (please complete the following information):
 - Detox: 12.3
 - Node: 12.9
 - Device: MacBook pro 2017
 - Xcode: 12.4
 - macOS: 11.2.3

### Logs

- [x] I am providing the `npm install` log below:
[log.txt](https://github.com/wix/Detox/files/6303190/log.txt)

**Comment by d4vidi** [comment]
Hey @avgurf, sorry for the late response. Could you please try to run `detox rebuild-framework-cache` and then reinstall node modules from scratch?

**Comment by Arunsankars1436** [comment]
> Hey @avgurf, sorry for the late response. Could you please try to run `detox rebuild-framework-cache` and then reinstall node modules from scratch?

same error happening  `was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.`

**Comment by d4vidi** [comment]
Could you try to add detox manually to your `package.json` and then install node modules from scratch? (delete `node_modules` beforehand).
@alon-ha anything else you can advise?

**Comment by alon-ha** [comment]
> > Hey @avgurf, sorry for the late response. Could you please try to run `detox rebuild-framework-cache` and then reinstall node modules from scratch?
> 
> same error happening `was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.`

Try to clean and build from xcode
