### ISSUE TITLE
how to fix Process crashed while executing runDetoxTests.java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/modules/core/Timing

### ISSUE THREAD

**Issue by hmsdtak** [wix/Detox#2774]
when I try to run detox test -c android.emu.release --loglevel trace, in the middle of the execution, process is crashing with following error. detox build is successful.
```
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stack=java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/modules/core/Timing;
        at com.wix.detox.reactnative.idlingresources.TimingModuleReflected.<init>(TimersIdlingResource.kt:27)
        at com.wix.detox.reactnative.idlingresources.TimersIdlingResource.checkIdle(TimersIdlingResource.kt:85)
        at com.wix.detox.reactnative.idlingresources.TimersIdlingResource.isIdleNow(TimersIdlingResource.kt:59)
        at com.wix.detox.reactnative.idlingresources.TimersIdlingResource.doFrame(TimersIdlingResource.kt:71)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.modules.core.Timing" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.aggregatorapp.test-QT3EMyqvn7AtIuj4OhYczA==/base.apk", zip file "/data/app/com.aggregatorapp-WLJSHarTiURbc0sBeg4jaQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.aggregatorapp.test-QT3EMyqvn7AtIuj4OhYczA==/lib/x86, /data/app/com.aggregatorapp-WLJSHarTiURbc0sBeg4jaQ==/lib/x86, /data/app/com.aggregatorapp.test-QT3EMyqvn7AtIuj4OhYczA==/base.apk!/lib/x86, /data/app/com.aggregatorapp-WLJSHarTiURbc0sBeg4jaQ==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ... 15 more

INSTRUMENTATION_STATUS: stream=
Process crashed while executing runDetoxTests(com.aggregatorapp.DetoxTest):
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/modules/core/Timing;
        at com.wix.detox.reactnative.idlingresources.TimingModuleReflected.<init>(TimersIdlingResource.kt:27)
        at com.wix.detox.reactnative.idlingresources.TimersIdlingResource.checkIdle(TimersIdlingResource.kt:85)
        at com.wix.detox.reactnative.idlingresources.TimersIdlingResource.isIdleNow(TimersIdlingResource.kt:59)
        at com.wix.detox.reactnative.idlingresources.TimersIdlingResource.doFrame(TimersIdlingResource.kt:71)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.modules.core.Timing" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.aggregatorapp.test-QT3EMyqvn7AtIuj4OhYczA==/base.apk", zip file "/data/app/com.aggregatorapp-WLJSHarTiURbc0sBeg4jaQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.aggregatorapp.test-QT3EMyqvn7AtIuj4OhYczA==/lib/x86, /data/app/com.aggregatorapp-WLJSHarTiURbc0sBeg4jaQ==/lib/x86, /data/app/com.aggregatorapp.test-QT3EMyqvn7AtIuj4OhYczA==/base.apk!/lib/x86, /data/app/com.aggregatorapp-WLJSHarTiURbc0sBeg4jaQ==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ... 15 more

INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS_CODE: -2

detox[11541] DEBUG: [exec.js/EXEC_CMD, #16] "/home/dhanushka/Android/Sdk/platform-tools/adb" -s emulator-14800 shell "ps | grep \"com\.aggregatorapp$\""
detox[11541] TRACE: [exec.js/SPAWN_STDOUT, #15] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
```
any ideas?

**Comment by hmsdtak** [comment]
hey @d4vidi ,Thanks for your reply. 
react-native: 0.63.3
detox version: 14.9
and debug mode also not working.
