### ISSUE TITLE
Need to get the keyboard back in detox after it hides in ios

### ISSUE THREAD

**Issue by nipuniuthpala** [wix/Detox#2788]
Hi, I have a problem typing the text fields in detox. where I hide the keyboard in the first field and then in the 2nd field keyboard is not appearing. could you please help me with this?
I have used functions like  this
 static async addContentFandomEnter() {
    await newPostPage.lbl_title.atIndex(0).typeText('\n');     //keyboard hides after the 1st filed

  }
  static async addContentFandom() {
    await newPostPage.lbl_content.atIndex(0).tap();
    const {fandom_handle: fandom_handle} = getCredentials();
    await newPostPage.lbl_content.atIndex(0).replaceText(fandom_handle);

Log [=========](url)

    Test Failed: First responder “(null)” does not conform to “UITextInput” protocol

      29 |     await newPostPage.lbl_content.atIndex(0).tap();
      30 |     const { handle: handle } = getCredentials();
    > 31 |     await newPostPage.lbl_content.atIndex(0).replaceText(handle);
         |                                              ^
      32 |   }
      33 |   static async addContentFandomEnter() {
      34 |     await newPostPage.lbl_title.atIndex(0).typeText('\n');

      at Function.<anonymous> (../pages/new-post.page.ts:31:46)
      at fulfilled (../../../node_modules/tslib/tslib.js:112:62)

**Comment by nipuniuthpala** [comment]
closed
