### ISSUE TITLE
DetoxRuntimeError: Failed to reach the app over the web socket connection.

### ISSUE THREAD

**Issue by drop-andi** [wix/Detox#2801]
I have this code that works fine and my test passes (--configuration ios):

```
import { by, device, expect, element } from 'detox'

describe('Welcome screen', () => {
  beforeAll(async () => {
    await device.launchApp({ newInstance: true })
  })

  it('should have welcome screen, sign in ', async () => {
    await expect(element(by.id('landing-container'))).toBeVisible()   
  })
})
```

As soon as I update the code to this, it throws the error:

```
const { exists } = require('utils')

describe('Welcome screen', () => {
  beforeAll(async () => {
    await device.launchApp({ newInstance: true })
  })

  it('should have welcome screen, sign in ', async () => {
   await exists('landing-container')  
  })
})
```

This is my utils.js
```
import { by, expect, element } from 'detox'

const exists = async (id: string) => {
  await expect(element(by.id(id))).toBeVisible()
}

module.exports = { exists }
```

Any idea what might be the issue?

This is verbose log:
```
detox[64783] INFO:  [test.js] DETOX_CONFIGURATION="ios" DETOX_LOGLEVEL="verbose" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1621964836761 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/jest.config.js --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 e2e
detox[64784] DEBUG: [WSS_CREATE] Detox server listening on localhost:56253...
detox[64784] DEBUG: [WSS_CONNECTION, #56254] registered a new connection.
detox[64784] DEBUG: [EXEC_CMD, #0] applesimutils --list --byType "iPhone 12 Pro Max"
detox[64784] DEBUG: [EXEC_CMD, #1] applesimutils --list --byId C8046108-AD00-4AA9-AA05-265292D795D7 --maxResults 1
detox[64784] DEBUG: [EXEC_CMD, #2] /usr/bin/xcrun simctl terminate C8046108-AD00-4AA9-AA05-265292D795D7 com.drop.beta.molly
detox[64784] DEBUG: [EXEC_TRY, #2] Terminating com.drop.beta.molly...
detox[64784] DEBUG: [EXEC_SUCCESS, #2] com.drop.beta.molly terminated
detox[64784] DEBUG: [EXEC_CMD, #3] /usr/bin/xcrun simctl uninstall C8046108-AD00-4AA9-AA05-265292D795D7 com.drop.beta.molly
detox[64784] DEBUG: [EXEC_TRY, #3] Uninstalling com.drop.beta.molly...
detox[64784] DEBUG: [EXEC_SUCCESS, #3] com.drop.beta.molly uninstalled
detox[64784] DEBUG: [EXEC_CMD, #4] /usr/bin/xcrun simctl install C8046108-AD00-4AA9-AA05-265292D795D7 "/Users/andisheh/Documents/Code/molly/ios/DerivedData/Molly/Build/Products/Debug-iphonesimulator/Molly.app"
detox[64784] DEBUG: [EXEC_TRY, #4] Installing /Users/andisheh/Documents/Code/molly/ios/DerivedData/Molly/Build/Products/Debug-iphonesimulator/Molly.app...
detox[64784] DEBUG: [EXEC_SUCCESS, #4] /Users/andisheh/Documents/Code/molly/ios/DerivedData/Molly/Build/Products/Debug-iphonesimulator/Molly.app installed
detox[64784] DEBUG: [WSS_CREATE] Detox server listening on localhost:56263...
detox[64784] DEBUG: [WSS_CONNECTION, #56264] registered a new connection.
detox[64784] DEBUG: [EXEC_CMD, #5] applesimutils --list --byType "iPhone 12 Pro Max"
detox[64784] DEBUG: [EXEC_CMD, #6] applesimutils --list --byId EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22 --maxResults 1
detox[64784] DEBUG: [EXEC_CMD, #7] /usr/bin/xcrun simctl boot EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22 
detox[64784] DEBUG: [EXEC_TRY, #7] Booting device EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22...
detox[64784] DEBUG: [EXEC_CMD, #8] /usr/bin/xcrun simctl bootstatus EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22
detox[64784] DEBUG: [EXEC_CMD, #9] /usr/bin/xcrun simctl io EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22 screenshot "/dev/null"
detox[64784] DEBUG: [EXEC_CMD, #10] /usr/bin/xcrun simctl terminate EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22 com.drop.beta.molly
detox[64784] DEBUG: [EXEC_TRY, #10] Terminating com.drop.beta.molly...
detox[64784] DEBUG: [EXEC_SUCCESS, #10] com.drop.beta.molly terminated
detox[64784] DEBUG: [EXEC_CMD, #11] /usr/bin/xcrun simctl uninstall EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22 com.drop.beta.molly
detox[64784] DEBUG: [EXEC_TRY, #11] Uninstalling com.drop.beta.molly...
detox[64784] DEBUG: [EXEC_SUCCESS, #11] com.drop.beta.molly uninstalled
detox[64784] DEBUG: [EXEC_CMD, #12] /usr/bin/xcrun simctl install EED02F4E-FAD4-4EB6-AF75-CA1A83DE1F22 "/Users/andisheh/Documents/Code/molly/ios/DerivedData/Molly/Build/Products/Debug-iphonesimulator/Molly.app"
detox[64784] DEBUG: [EXEC_TRY, #12] Installing /Users/andisheh/Documents/Code/molly/ios/DerivedData/Molly/Build/Products/Debug-iphonesimulator/Molly.app...
detox[64784] DEBUG: [EXEC_SUCCESS, #12] /Users/andisheh/Documents/Code/molly/ios/DerivedData/Molly/Build/Products/Debug-iphonesimulator/Molly.app installed
detox[64784] INFO:  Welcome screen is assigned to C8046108-AD00-4AA9-AA05-265292D795D7 {"type":"iPhone 12 Pro Max"}
detox[64784] DEBUG: [EXEC_CMD, #13] /usr/bin/xcrun simctl terminate C8046108-AD00-4AA9-AA05-265292D795D7 com.drop.beta.molly
detox[64784] DEBUG: [EXEC_TRY, #13] Terminating com.drop.beta.molly...
detox[64784] DEBUG: [EXEC_SUCCESS, #13] com.drop.beta.molly terminated
detox[64784] DEBUG: [EXEC_CMD, #14] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/andisheh/Library/Detox/ios/8bdb3e8148bf971e544f5c0566cb3f7e080943fb/Detox.framework/Detox" /usr/bin/xcrun simctl launch C8046108-AD00-4AA9-AA05-265292D795D7 com.drop.beta.molly --args -detoxServer ws://localhost:56253 -detoxSessionId e74334a3-134d-85ad-c7c1-cf87aa8c2c45 -detoxDisableHierarchyDump YES
detox[64784] DEBUG: [EXEC_TRY, #14] Launching com.drop.beta.molly...
detox[64784] DEBUG: [EXEC_CMD, #15] /usr/bin/xcrun simctl get_app_container C8046108-AD00-4AA9-AA05-265292D795D7 com.drop.beta.molly
detox[64784] INFO:  [AppleSimUtils.js] com.drop.beta.molly launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn C8046108-AD00-4AA9-AA05-265292D795D7 log stream --level debug --style compact --predicate 'process == "Molly"'
detox[64784] DEBUG: [WSS_CONNECTION, #56297] registered a new connection.
detox[64784] INFO:  Welcome screen: should have welcome screen, sign in 
detox[64784] INFO:  Welcome screen: should have welcome screen, sign in  [FAIL]

detox[64784] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
 FAIL  e2e/index.test.ts (22.892 s)
  Welcome screen
    ✕ should have welcome screen, sign in  (18 ms)

  ● Welcome screen › should have welcome screen, sign in 

    DetoxRuntimeError: Failed to reach the app over the web socket connection.

    HINT: 

    Have you forgotten to write 'device.launchApp()' at the beginning
    of your test? If that's not the case, see the other options.

    1. If you don't see your app running on the device, there's a chance
       that your app has crashed prematurely. To get the crash details,
       you can run Detox tests with "--record-logs all" CLI option
       and then inspect the device logs in the artifacts folder.


    2. If your app IS running on the device, yet you see this message:
    a) The native part of Detox failed to connect to the Detox server over
       web sockets. If this is the case, the device's logs should contain
       messages about those failed connection attempts.

    b) The app is running without Detox native code injected.
       Make sure you don't launch it manually. If you don't, examine the logs
       from the device. If you see a crash related to Detox native code, you
       are welcome to report it on our GitHub tracker.
       In case if you are debugging your native code integration with Detox,
       these guides may prove helpful:

       * https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInAndroidStudio.md
       * https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md

    The following package could not be delivered:

    {
      type: 'invoke',
      params: [Object],
      messageId: 1
    }

      2 |
      3 | const exists = async (id: string) => {
    > 4 |   await expect(element(by.id(id))).toBeVisible()
        |                                    ^
      5 | }
      6 |
      7 | module.exports = { exists }

      at utils.tsx:4:36
      at utils.tsx:8:71
      at __awaiter (utils.tsx:4:12)
      at exists (utils.tsx:3:37)
      at index.test.ts:26:11
```

**Comment by laurentDellaNegra** [comment]
+1 same issue here:

jest@26
detox@18

**Comment by alaporterie** [comment]
Hi,

I got the same issue on Android with Detox 18.15.0

detox[47486] ERROR: [APP_UNREACHABLE] Failed to reach the app over the web socket connection.
...
detox[47486] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully

I launched tests with `--record-logs all` and take a look to artifacts folder.
I just saw in detox_pid_xxx.log:
detox[47846] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onHookFailure({
  error: DetoxRuntimeError: Failed to run application on the device

Could you help us please?

Thanks

**Comment by alaporterie** [comment]
Fixed because the path to DetoxTest.java was the wrong path!

So be careful to the path and edit com.example by your com.yourapp

Regards

**Comment by laurentDellaNegra** [comment]
> Fixed because the path to DetoxTest.java was the wrong path!
> 
> So be careful to the path and edit com.example by your com.yourapp
> 
> Regards

thx dude it solved the issue !

**Comment by d4vidi** [comment]
@drop-andi by using `require('utils')` you're importing a preinstall module called `utils` ([for example](https://www.npmjs.com/package//utils)) residing somehwere your project's `node_modules`. Use a relative path in order to require project files (for example, `require('../utils`), or even `require('./utils')`).
