### ISSUE TITLE
detox[7227] ERROR: [cli.js] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/cli/args' is not defined by "exports" in /..../node_modules/jest-cli/package.json

### ISSUE THREAD

**Issue by jacargentina** [wix/Detox#2811]
`detox test -c ios`

```
detox[7227] ERROR: [cli.js] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/cli/args' is not defined by "exports" in /Users/.../myapp/node_modules/jest-cli/package.json
detox[7227] ERROR: [cli.js]     at new NodeError (node:internal/errors:363:5)
detox[7227] ERROR: [cli.js]     at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
detox[7227] ERROR: [cli.js]     at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
detox[7227] ERROR: [cli.js]     at resolveExports (node:internal/modules/cjs/loader:478:36)
detox[7227] ERROR: [cli.js]     at Function.Module._findPath (node:internal/modules/cjs/loader:518:31)
detox[7227] ERROR: [cli.js]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
detox[7227] ERROR: [cli.js]     at resolveFileName (/Users/.../myapp/node_modules/resolve-from/index.js:29:39)
detox[7227] ERROR: [cli.js]     at resolveFrom (/Users/.../myapp/node_modules/resolve-from/index.js:43:9)
detox[7227] ERROR: [cli.js]     at module.exports (/Users/.../myapp/node_modules/resolve-from/index.js:46:47)
detox[7227] ERROR: [cli.js]     at resolveJestCliArgs (/Users/.../myapp/node_modules/detox/local-cli/utils/splitArgv.js:96:18)
detox[7227] ERROR: [cli.js]     at getJestBooleanArgs (/Users/.../myapp/node_modules/detox/local-cli/utils/splitArgv.js:56:12)
detox[7227] ERROR: [cli.js]     at Object.splitJestArgv [as jest] (/Users/.../myapp/node_modules/detox/local-cli/utils/splitArgv.js:120:53)
detox[7227] ERROR: [cli.js]     at prepareJestArgs (/Users/.../myapp/node_modules/detox/local-cli/test.js:156:44)
detox[7227] ERROR: [cli.js]     at Object.test [as handler] (/Users/.../myapp/node_modules/detox/local-cli/test.js:33:25)
detox[7227] ERROR: [cli.js]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

any advice? Thanks!

**Comment by jacargentina** [comment]
It seems jest 27 is not compatible: forcing jest/jest-circut to v26.0.1, it works.

**Comment by noomorph** [comment]
@jacargentina , thanks! Working on the fix.

**Comment by jacargentina** [comment]
Great! waiting for the release. Thanks!

**Comment by noomorph** [comment]
Okay, I am running the publish build in a few minutes. Thanks for the report! ❤️
