### ISSUE TITLE
No instrumentation runner found on device {Name Device} for package com.example.app

### ISSUE THREAD

**Issue by RodgersRomero** [wix/Detox#2827]
Hello i'm trying to execute test in my physical device but i just can't fix this issue

Log

DetoxRuntimeError: No instrumentation runner found on device R58R20X4C4X for package com.shakey.nyarchives.qa

      at ADB.getInstrumentationRunner (../node_modules/detox/src/devices/drivers/android/exec/ADB.js:256:13)
      at Instrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:21:24)
      at MonitoredInstrumentation.launch (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:20:5)
      at AttachedAndroidDriver._launchInstrumentationProcess (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:294:5)
      at AttachedAndroidDriver._launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:277:7)
      at AttachedAndroidDriver._handleLaunchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:125:7)
      at AttachedAndroidDriver.launchApp (../node_modules/detox/src/devices/drivers/android/AndroidDriver.js:96:12)
      at Device._doLaunchApp (../node_modules/detox/src/devices/Device.js:336:35)
      at traceCall (../node_modules/detox/src/utils/trace.js:41:20)

Environment

detox: 18.16.0
react-native: 0.64.2
Device: Android
OS: 11
Test Runner: jest-circus

**Comment by noomorph** [comment]
Cannot help, there is an insufficient amount of debugging information in the report, sorry. 😞
