### ISSUE TITLE
example don't work for release mode on android

### ISSUE THREAD

**Issue by finalight** [wix/Detox#2856]
### Describe the bug

The example that i'm referring to is in the examples folder -> demo-react-native

### Steps To Reproduce

- npm i
- detox build -c android.emu.release
- detox test -c android.emu.release
- device is opened
- app is not opened
- tests are not running

### Expected behavior

Example should work

### Detox Trace-Logs

```
detox test -c android.emu.release
detox[77626] INFO:  [test.js] mocha --config e2e/.mocharc.json --configuration android.emu.release --grep :ios: --invert --use-custom-logger true e2e


  Example
    1) "before all" hook for "should have welcome screen"

detox[77627] ERROR: [APP_UNREACHABLE] Failed to reach the app over the web socket connection.

HINT: 

1. If you don't see your app running on the device, there's a chance
   that your app has crashed prematurely. To get the crash details,
   you can run Detox tests with "--record-logs all" CLI option
   and then inspect the device logs in the artifacts folder.

2. If your app IS running on the device, yet you see this message:
a) The native part of Detox failed to connect to the Detox server over
   web sockets. If this is the case, the device's logs should contain
   messages about those failed connection attempts.

b) The app is running without Detox native code injected.
   Make sure you don't launch it manually. If you don't, examine the logs
   from the device. If you see a crash related to Detox native code, you
   are welcome to report it on our GitHub tracker.
   In case if you are debugging your native code integration with Detox,
   these guides may prove helpful:

   * https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInAndroidStudio.md
   * https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md



  0 passing (23s)
  1 failing

  1) Example
       "before all" hook for "should have welcome screen":
     DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
      at Context.<anonymous> (e2e/example.spec.ts:3:18)
      at processImmediate (internal/timers.js:461:21)



detox[77626] ERROR: [cli.js] Command failed: mocha --config e2e/.mocharc.json --configuration android.emu.release --grep :ios: --invert --use-custom-logger true e2e
```

there are no code change in the example folder, so whatever configuration was there, i just follow it

**Comment by finalight** [comment]
here's the update so far:
it works on devices with API <28

i've checked the example code and it has the xml for the network security config, so I am not sure why is it not working for API >=28
