### ISSUE TITLE
Detox test through ssh mount

### ISSUE THREAD

**Issue by balsloev** [wix/detox#286]
Hi. I am running my React Native project via SSH mount (osxfuse and sshfs) on Mac.
I am trying to get my test up and running, but I get this error when I run: **detox test**

**detox build** is working fine. **detox test** is trying to install the app 10 times and then bail out. 

Can anyone point me in the right direction to solve this issue?

#### Node, Device, Xcode and macOS Versions

* Node: v8.5.0
* Device: iPhone 6
* Xcode: 8.3.3 
* macOS: 10.12.6 

####
```
fr-lap0246:wifiscanner christian$ detox test
node_modules/.bin/mocha e2e --opts e2e/mocha.opts      


detox-server info 15:03:33: server listening on localhost:58580...
detox info 1: Listing devices... 
detox info Device E8CB52D2-505E-4248-B833-E7E1E5219DD6 is already booted 
detox info 3: Uninstalling org.reactjs.native.example.wifiscanner... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
detox info 4: Installing /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app... 
  1) "before all" hook

  0 passing (49s)
  1 failing

  1)  "before all" hook:
     Error: Command failed: fbsimctl --json E8CB52D2-505E-4248-B833-E7E1E5219DD6 install /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app
objc[16334]: Class _TtCs18_EmptyArrayStorage is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73990) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714990). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs20_RawNativeSetStorage is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73a40) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714a40). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs17_CocoaSetIterator is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef88a98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112729a98). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs27_RawNativeDictionaryStorage is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73b08) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714b08). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs24_CocoaDictionaryIterator is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef89a98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x11272aa98). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs17NonObjectiveCBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef8b538) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x11272c538). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs17_stdlib_AtomicInt is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef8d9a8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x11272e9a8). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs19_SwiftNativeNSArray is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73be0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714be0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs24_SwiftNativeNSDictionary is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73c48) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714c48). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs17_SwiftNativeNSSet is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73cb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714cb0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs24_SwiftNativeNSEnumerator is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73d18) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714d18). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs18_SwiftNativeNSData is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73d80) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714d80). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs26_SwiftNativeNSCharacterSet is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73de8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714de8). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs31_stdlib_ReturnAutoreleasedDummy is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73e50) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714e50). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs20_SwiftNativeNSString is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73ec8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714ec8). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs19_NSContiguousString is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73f30) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714f30). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs40_SwiftNativeNSArrayWithContiguousStorage is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef73fb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112714fb0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs21_SwiftDeferredNSArray is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74020) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715020). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs27_ContiguousArrayStorageBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef740b0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1127150b0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs14_VaListBuilder is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef92ec0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112733ec0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtCs13VaListBuilder is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef92fb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112733fb0). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSError is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74148) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715148). One of the two will be used. Which one is undefined.
objc[16334]: Class SwiftObject is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74198) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715198). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftValue is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74210) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715210). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNull is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74260) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715260). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSArrayBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef742b0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1127152b0). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSDictionaryBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74300) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715300). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSSetBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74350) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715350). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSStringBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef743a0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1127153a0). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSEnumeratorBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef743f0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1127153f0). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSDataBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74440) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715440). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSCharacterSetBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef74490) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x112715490). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftNativeNSIndexSetBase is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10ef744e0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1127154e0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC8Dispatch16DispatchWorkItem is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftDispatch.dylib (0x10f2cee58) and /Applications/Xcode.app/Contents/Frameworks/libswiftDispatch.dylib (0x112a34e58). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation20_SwiftNSCharacterSet is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f402ac0) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b63ac0). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation12_DataStorage is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f406058) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b67058). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation12_NSSwiftData is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f402b60) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b63b60). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation25_NSErrorRecoveryAttempter is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f406690) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b67690). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation25NSFastEnumerationIterator is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f406730) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b67730). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation15NSSimpleCString is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f4067e8) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b677e8). One of the two will be used. Which one is undefined.
objc[16334]: Class _TtC10Foundation16NSConstantString is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f406878) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b67878). One of the two will be used. Which one is undefined.
objc[16334]: Class _SwiftTypePreservingNSNumber is implemented in both /usr/local/Cellar/fbsimctl/0.4.0/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10f402c18) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x112b63c18). One of the two will be used. Which one is undefined.
 `fbsimctl --json E8CB52D2-505E-4248-B833-E7E1E5219DD6 install /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app` (exited with error code 1)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:277:5)
      at maybeClose (internal/child_process.js:927:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)



child_process.js:634
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts      
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Object.<anonymous> (/Users/christian/devcba/GIT/wifiscanner/node_modules/detox/local-cli/detox-test.js:46:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
fr-lap0246:wifiscanner christian$ detox test
node_modules/.bin/mocha e2e --opts e2e/mocha.opts      
```

**Comment by balsloev** [comment]
Alle the "Class * is implemented in both .." errors goes away if I install fbsimctl using **brew install fbsimctl --HEAD** - but that is agains [detox documentation](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md#3-install-fbsimctl).

**Comment by rotemmiz** [comment]
Try using verbose log.
I'm not sure what's the status of `fbsimctl` on HEAD, we had pretty bad experience with this project, as it is not stable (we are actually working on removing any dependency of Detox on fbsimctl).

Try installing the app manually on your device and see what fbsimctl's error is
`fbsimctl --json E8CB52D2-505E-4248-B833-E7E1E5219DD6 install /Users/christian/devcba/GIT/wifiscanner/ios/build/Build/Products/Debug-iphonesimulator/wifiscanner.app`

**Comment by balsloev** [comment]
SSH mount caused several problems for me running react-native. I am now running locally.
