### ISSUE TITLE
 Error: is it currently building

### ISSUE THREAD

**Issue by piotrfalba** [wix/detox#291]
#### Description
Test just stops after start.
` 1)  "before all" hook:
     Error: is it currently building ?
      at SimulatorDriver._callee$ (node_modules/detox/lib/devices/IosDriver.js:38:19)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/detox/lib/devices/IosDriver.js:1:1281)
      at node_modules/detox/lib/devices/IosDriver.js:1:1441
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)`

#### Steps to Reproduce
Just started the test.

#### Node, Device, Xcode and macOS Versions

Node: v8.3.0
Device: iPhone 6
Xcode: 9.0
macOS: 10.12.6

**Comment by rotemmiz** [comment]
This is a not-at-all-clear error I added a few days ago when I merged the SwiftSupport branch. The new From Detox 5.7.0 we have a new way delivering Detox framework to the user, instead of bundling a precompiled framework, it is now being built on the user's machine in order to be built with a matching swift version.

The error you see means that the the directory which Detox framework is being built to exists (`~/Library/Detox/{hash}/`) but `Detox.framework` does not exist inside it. This can be caused if you ran `detox test` , the framework build process started, but was interrupted.
I will add a more verbose error there... sorry for that
