### ISSUE TITLE
TypeError: Class constructor DetoxCircusEnvironment cannot be invoked without 'new'

### ISSUE THREAD

**Issue by johhansantana** [wix/Detox#2942]
Hello. I'm trying to setup this library but I am getting this error which I can't really seem to find an answer searching around google.

```
 FAIL  e2e/firstTest.e2e.jsrun...
  ● Test suite failed to run

    TypeError: Class constructor DetoxCircusEnvironment cannot be invoked without 'new'

      21 | }
      22 |
    > 23 | module.exports = CustomDetoxEnvironment;
         |                                                                                 ^
      24 |

      at new CustomDetoxEnvironment (environment.js:23:114)
      at async TestScheduler.scheduleTests (../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (../node_modules/@jest/core/build/runJest.js:387:19)
      at async _run10000 (../node_modules/@jest/core/build/cli/index.js:408:7)
      at async runCLI (../node_modules/@jest/core/build/cli/index.js:261:3)

detox[70597] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' e2e

```

the versions of packages:
```
"jest": "^27.0.6",
"jest-circus": "^27.0.6",
"detox": "^18.20.2",
```

and the environment.js file
```javascript
const {
  DetoxCircusEnvironment,
  SpecReporter,
  WorkerAssignReporter,
} = require('detox/runners/jest-circus');

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  constructor(config, context) {
    super(config, context);

    // Can be safely removed, if you are content with the default value (=300000ms)
    this.initTimeout = 300000;

    // This takes care of generating status logs on a per-spec basis. By default, Jest only reports at file-level.
    // This is strictly optional.
    this.registerListeners({
      SpecReporter,
      WorkerAssignReporter,
    });
  }
}

module.exports = CustomDetoxEnvironment;
```

**Comment by johhansantana** [comment]
I found out why it wasn't working correctly. I had a `babel.config.js` file at the root of my project with the following:

```javascript
module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
};
```

After commenting these lines the error went away and the tests went through. I'm not really sure what these lines really do but the project seems to work fine without it.

**Comment by phuongwd** [comment]
Using this config to resolve

```
"jest": "^27.2.0",
"detox": "^18.20.3",
```

```
module.exports = api => {
  const babelEnv = api.env();
  const plugins = [];
  const presets = [];

  // resolve issue TypeError: Class constructor DetoxCircusEnvironment cannot be invoked without 'new'
  if (babelEnv === 'test') {
    presets.push(['@babel/preset-env']);
    plugins.push(['@babel/plugin-transform-runtime']);
  } else {
    presets.push(['module:metro-react-native-babel-preset']);
  }

  return {
    presets,
    plugins
  };
};

```
