### ISSUE TITLE
DetoxRuntimeError: Failed to run application on the device

### ISSUE THREAD

**Issue by thaole2021** [wix/Detox#2962]
I got the error below when running `detox test` for android emulator,` detox build` is successful.
**Environment**:
Detox: 18.20.2
Node: v10.24.1
Device: Android 29 (Emulator - pixel, Android API 29 Tag/ABI: google_apis_playstore/x86_64)
macOS: 11.2.3

**detox_pid_23290.log**
```detox[23290] TRACE: [WSS_GET_FROM, #app] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread OkHttp Dispatcher(537):\njava.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 2792 free bytes and 2792B until OOM, target footprint 16777216, growth limit 16777216\n\tat okio.Segment.<init>(Segment.java:63)\n\tat okio.SegmentPool.take(SegmentPool.java:48)\n\tat okio.Buffer.writableSegment(Buffer.java:1293)\n\tat okio.Okio$2.read(Okio.java:138)\n\tat okio.AsyncTimeout$2.read(AsyncTimeout.java:237)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)\n\tat okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:453)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:136)\n\tat com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:184)`detox[23290] TRACE: [WSS_GET_FROM, #app] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread OkHttp Dispatcher(537):\njava.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 2792 free bytes and 2792B until OOM, target footprint 16777216, growth limit 16777216\n\tat okio.Segment.<init>(Segment.java:63)\n\tat okio.SegmentPool.take(SegmentPool.java:48)\n\tat okio.Buffer.writableSegment(Buffer.java:1293)\n\tat okio.Okio$2.read(Okio.java:138)\n\tat okio.AsyncTimeout$2.read(AsyncTimeout.java:237)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)\n\tat okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:453)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:136)\n\tat com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:184)``detox[23290] TRACE: [WSS_GET_FROM, #app] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread OkHttp Dispatcher(537):\njava.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 2792 free bytes and 2792B until OOM, target footprint 16777216, growth limit 16777216\n\tat okio.Segment.<init>(Segment.java:63)\n\tat okio.SegmentPool.take(SegmentPool.java:48)\n\tat okio.Buffer.writableSegment(Buffer.java:1293)\n\tat okio.Okio$2.read(Okio.java:138)\n\tat okio.AsyncTimeout$2.read(AsyncTimeout.java:237)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)\n\tat okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:453)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:136)\n\tat com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:184)`detox[23290] TRACE: [WSS_GET_FROM, #app] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread OkHttp Dispatcher(537):\njava.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 2792 free bytes and 2792B until OOM, target footprint 16777216, growth limit 16777216\n\tat okio.Segment.<init>(Segment.java:63)\n\tat okio.SegmentPool.take(SegmentPool.java:48)\n\tat okio.Buffer.writableSegment(Buffer.java:1293)\n\tat okio.Okio$2.read(Okio.java:138)\n\tat okio.AsyncTimeout$2.read(AsyncTimeout.java:237)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)\n\tat okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:453)\n\tat okio.RealBufferedSource.read(RealBufferedSource.java:47)\n\tat com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:136)\n\tat com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:184)```

```
etox[23290] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onHookFailure({ error:
   { DetoxRuntimeError: Failed to run application on the device
   
   HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
       at _callee$ (/Users/thaole/workspace/jobber-mobile/e2e/smokeTest.e2e.js:5:18)
       at tryCatch (/Users/thaole/workspace/jobber-mobile/node_modules/regenerator-runtime/runtime.js:45:40)
```
**emulator-5554 Z.startup.log**
```
08-31 13:36:17.343  8489  8653 I etjobber.jobbe: Alloc concurrent copying GC freed 5(248B) AllocSpace objects, 0(0B) LOS objects, 0% free, 15MB/16MB, paused 551us total 22.526ms
08-31 13:36:17.343  8489  8653 W etjobber.jobbe: Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 2792 free bytes and 2792B until OOM, target footprint 16777216, growth limit 16777216" (VmSize 4179096 kB)
08-31 13:36:17.343  8489  8489 I etjobber.jobbe: WaitForGcToComplete blocked Alloc on ClassLinker for 42.715ms
```
```
--------- beginning of crash
08-31 13:36:17.446  8489  8653 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
08-31 13:36:17.446  8489  8653 E AndroidRuntime: Process: com.getjobber.jobber, PID: 8489
08-31 13:36:17.446  8489  8653 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 2792 free bytes and 2792B until OOM, target footprint 16777216, growth limit 16777216
```
[detox_pid_23290.log](https://github.com/wix/Detox/files/7086004/detox_pid_23290.log)
[emulator-5554 2021-08-31 17-36-23Z.startup.log](https://github.com/wix/Detox/files/7086006/emulator-5554.2021-08-31.17-36-23Z.startup.log)

**Comment by thaole2021** [comment]
I have solved this issue by adding this code into android/app/src/main/java/com/example/MainActivity.java
```
@Override
    protected String getMainComponentName() {
        return "example";
    }

```
Note: "example" is your react-native appName. The appName in index.js at `AppRegistry.registerComponent("example", () => AppProvider);`

**Comment by thaole2021** [comment]
Adding getMainComponentName() will help detox to connect with the app and run the test successfully. But it causes index.js call twice and sometime the app is hang with “Downloading JavaScript” on the screen.
@d4vidi  why do we need getMainComponentName() to get detox work? Does detox use getMainComponentName() to get appName? Any other way that I can setup to get detox connect with the app?
