### ISSUE TITLE
Error: Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.NetworkIdlingResource] to become idle timed out

### ISSUE THREAD

**Issue by baskarkarthik** [wix/Detox#3047]
### Description
After tapping a button, app takes around 60 to 70 seconds for displaying a popup(as per functionality). After tapping app is idle for 60 seconds after that below error message is generating in terminal

Exception:
```
Error: Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.NetworkIdlingResource] to become idle timed out
 at Context.<anonymous> (/Users/username/Documents/Work/Tool/e2e/UnitTest.js:479:43)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

code: (exception is generating after 60 secs from below code)
       ` await element(by.id('btnSubmit')).tap();`

.mocharc.json
`"timeout": 900000`

### Environment

 - Detox:  "17.14.9"
 - React Native: "0.65.1"
 - Node: "14.17.6"
 - Device: "Android Emulator (Pixel 5 Api 30)
 - OS: "Android 11"
 - Test-runner (select one): `mocha`

**Comment by PanArnaud** [comment]
Hi,

I'm facing the same behaviour. Did you fix it?

**Comment by baskarkarthik** [comment]
> Hi,
> 
> I'm facing the same behaviour. Did you fix it?

No. Need Detox team help.

**Comment by arekkubaczkowski** [comment]
The same here, can we count on some help?

**Comment by arekkubaczkowski** [comment]
But actually I have a little different error:
```
    Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.UIModuleIdlingResource] to become idle timed out
```

**Comment by arekkubaczkowski** [comment]
these are the logs when taps on this specific element:
```
12-15 07:32:34.817  3236  3236 D IdlingResourceRegistry: All idling resources are idle.
12-15 07:32:34.819  3236  3236 D IdlingResourceRegistry: All idling resources are idle.
12-15 07:32:34.832  3236  3236 I ViewInteraction: Checking 'MatchesViewAssertion(Detox){viewMatcher=at least 75 percent of the view's area is displayed to the user.}' assertion on view (with tag value: is "disconnect-button" and view has effective visibility=VISIBLE)
12-15 07:32:34.842  3236  3275 I DetoxWSClient: Sending out action 'invokeResult' (ID #7)
12-15 07:32:34.843  3236  3275 I DetoxDispatcher: Done with action 'invoke'
12-15 07:32:34.874  3236  3277 D DetoxWSClient: Received action 'invoke' (ID #8, params={"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["disconnect-button"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]})
12-15 07:32:34.875  3236  3275 I DetoxDispatcher: Handling action 'invoke' (ID #8)...
12-15 07:32:34.876  3236  3275 D Detox   : class com.wix.detox.espresso.DetoxMatcher, matcherForTestId, [disconnect-button]
12-15 07:32:34.876  3236  3275 D Detox   : class androidx.test.espresso.Espresso, onView, [(with tag value: is "disconnect-button" and view has effective visibility=VISIBLE)]
12-15 07:32:34.876  3236  3275 D Detox   : class com.wix.detox.espresso.DetoxViewActions, click, []
12-15 07:32:34.876  3236  3275 D Detox   : class com.wix.detox.espresso.EspressoDetox, perform, [androidx.test.espresso.ViewInteraction@aceede3, com.wix.detox.espresso.action.RNClickAction@728a3e0]
12-15 07:32:34.878  3236  3236 D IdlingResourceRegistry: All idling resources are idle.
12-15 07:32:34.880  3236  3236 D IdlingResourceRegistry: All idling resources are idle.
12-15 07:32:34.880  3236  3236 I ViewInteraction: Performing 'com.wix.detox.espresso.action.detoxsingletap@d7c3699 click' action on view (with tag value: is "disconnect-button" and view has effective visibility=VISIBLE)
12-15 07:32:34.969  3236  3351 D StripeTerminal: class=Terminal message=disconnectReader
12-15 07:32:34.970  3236  3367 D StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
12-15 07:32:34.970  3236  3367 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["didChangeConnectionStatus",{"result":"notConnected"}])
12-15 07:32:34.970  3236  3367 D StripeTerminal: class=ProxyTerminalListener message=onPaymentStatusChange(NOT_READY)
12-15 07:32:34.973  3236  3367 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["didChangePaymentStatus",{"result":"notReady"}])
12-15 07:32:35.020  3236  3348 W ReactNativeJS: EventEmitter.removeListener('didUpdateDiscoveredReaders', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
12-15 07:32:35.079  3236  3348 W ReactNativeJS: EventEmitter.removeListener('didUpdateDiscoveredReaders', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
12-15 07:32:35.186  3236  3348 W ReactNativeJS: EventEmitter.removeListener('didUpdateDiscoveredReaders', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
12-15 07:32:35.193  3236  3348 W ReactNativeJS: EventEmitter.removeListener('didUpdateDiscoveredReaders', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
12-15 07:32:35.474  3236  3247 I inalreactnativ: Background concurrent copying GC freed 115009(5MB) AllocSpace objects, 12(600KB) LOS objects, 49% free, 5MB/11MB, paused 1.883ms total 360.663ms
12-15 07:32:35.572  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.646  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.663  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.687  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.716  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.727  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.748  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.769  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.796  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.809  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.841  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.888  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 2 lines
12-15 07:32:35.897  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.946  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:35.983  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 2 lines
12-15 07:32:36.005  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.046  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.077  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.098  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 1 line
12-15 07:32:36.116  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.155  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.185  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.223  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.266  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.279  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.304  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.356  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 2 lines
12-15 07:32:36.376  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.386  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.414  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.449  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.476  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.516  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.545  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.573  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 1 line
12-15 07:32:36.585  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.605  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.655  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.692  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.733  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.763  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.788  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.800  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 1 line
12-15 07:32:36.819  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.853  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.880  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.896  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.927  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:36.956  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.004  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.026  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.055  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.106  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.115  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.145  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.174  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.226  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.245  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.291  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 2 lines
12-15 07:32:37.315  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.345  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.367  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 1 line
12-15 07:32:37.378  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.399  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.425  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.473  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.527  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.544  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.574  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 1 line
12-15 07:32:37.596  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.620  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.675  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.714  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.742  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.767  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.794  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.806  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.834  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.851  3236  3236 I chatty  : uid=10067(com.example.stripeterminalreactnative) identical 1 line
12-15 07:32:37.886  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.940  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:37.981  3236  3236 I Detox   : UIManagerModule is busy
12-15 07:32:38.039  3236  3236 I Detox   : UIManagerModule is busy
```

**Comment by arekkubaczkowski** [comment]
I am also providing the video of this behavior.
As you can see it taps on the disconnect button and it actually works (we can see that it has been disconnected)
This is the last step of this test scenario so test should be done already but for some reason is still running and throw timeout error at the end.

https://user-images.githubusercontent.com/18654447/146172152-2c7965cf-59f7-4993-a812-fe23e828424e.mp4

**Comment by arekkubaczkowski** [comment]
It turned out that it happens only on React Native >= 0.64.x
after downgrading to 0.64.3 it work correctly

**Comment by mariushorvat** [comment]
It's still happens on RN == 0.70. 
`Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.BridgeIdlingResource] to become idle timed out`
Could someone, please, add this to the backlog? Thanks!

**Comment by HauLe17** [comment]
the same issue, has any way to fix it???

**Comment by d4vidi** [comment]
Hey @HauLe17, @baskarkarthik + everyone involved 👋🏻 
Thank you for submitting your info and voting.

There are 2 things I'd like to point out in regards:
1. Synchronization issues are normally an indication of the fact that something in the app does not work properly. Some examples are: A network request that remains long-pending, a UI component that is sustained in a loop of some sort. As a first step, please try to use our [synchronization guide](https://wix.github.io/Detox/docs/troubleshooting/synchronization) in order to debug potential app issues.

2. We'd be happy to try to help with this and we will definitely reopen the issue accordingly, but we will have to get some kind of a reproduction project to work with. Our custom [Detox template](https://github.com/wix-incubator/DetoxTemplate) project can come in handy. It currently sports an older RN version but we are planning to upgrade it to RN 71 soon.

Happy testing! 🙏🏻

**Comment by amitrajora14** [comment]
I facing the same issue ??

Environment:-
Detox: "20.9.1"
