### ISSUE TITLE
Problem with runnig test( artifactsManager.onHookFailure)

### ISSUE THREAD

**Issue by kolganem** [wix/Detox#3138]
### Description

I use Expo + manage workflow in project. Installed all dev dependencies. Tests are started, the emulator opens, the application runs and opens on emulator, but nothing happens. Waits for a couple of minutes and crashes

### Environment

 - Detox: 19.3.1
 - React Native: 0.64.3
 - Node: 14.17.3
 - Device: Pixel 4 XL API 29
 - OS: WIndows
 - Test-runner : jest

`detox test --loglevel trace` -

```
 artifactsManager.onHookFailure({
  error: DetoxRuntimeError: No instrumentation runner found on device emulator-11210 for package ********.android_client_dev
      at createErrorWithUserStack (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\detox\src\utils\errorUtils.js:33:27)
      at RuntimeDevice.launchApp (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\detox\src\utils\wrapWithStackTraceCutter.js:9:34)
      at _callee$ (D:\Work\Project\*******\At_1\*******\src\Mobile\e2e\firstTest.e2e.js:3:22)
      at tryCatch (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:63:40)
      at Generator.invoke [as _invoke] (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:294:22)
      at Generator.next (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:119:21)
      at tryCatch (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:63:40)
      at invoke (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:155:20)
      at D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:190:11
      at new Promise (<anonymous>)
      at callInvokeWithMethodAndArg (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:189:16)
      at AsyncIterator.enqueue (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:212:13)
      at AsyncIterator.next (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:119:21)
      at Object.<anonymous>.exports.async (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\regenerator-runtime\runtime.js:239:14)
      at _callee (D:\Work\Project\*******\At_1\*******\src\Mobile\e2e\firstTest.e2e.js:2:15)
      at Promise.then.completed (D:\Work\Project\*******\At_1\*******\src\Mobile\node_modules\jest-circus\build\utils.js:391:28),
  hook: 'beforeAll'
})
detox[11144] INFO:  Example: Start app
detox[11144] INFO:  Example: Start app [FAIL]
Example[11144] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'Example' })

ROOT_DESCRIBE_BLOCK[11144] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'ROOT_DESCRIBE_BLOCK' })
detox[11144] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeCleanup()
detox[11144] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
```

**Comment by CentaureaDev** [comment]
yep, observe similar problem. Please advice workaround

**Comment by d4vidi** [comment]
@kolganem I'm a bit confused. The error message you've provided suggests that Detox has failed to run the app on the emulator. Please try to revisit our [Android setup guide](https://wix.github.io/Detox/docs/introduction/android#setup-%EF%B8%8F) and make sure you've set a `testInstrumentationRunner` and created a proper `DetoxTest.java` file in the proper location in your project.
