### ISSUE TITLE
The request was denied by service delegate

### ISSUE THREAD

**Issue by ethantran** [wix/detox#318]
```  
  0 passing (2m)
  2 failing

  1) "before all" hook:
     Error: Command failed: /bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/071BB051-29DB-4B25-B899-829C2D7AF32E/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/071BB051-29DB-4B25-B899-829C2D7AF32E/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/RONIN/Library/Detox/ios/05ea98aa93d326c35745e104035538dc4454d04f/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 071BB051-29DB-4B25-B899-829C2D7AF32E org.reactjs.native.example.trucke --args -detoxServer ws://localhost:58823 -detoxSessionId 9b5cf0c3-a82d-7cef-8194-4b5871f578ae
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "org.reactjs.native.example.trucke" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.
 `/bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/071BB051-29DB-4B25-B899-829C2D7AF32E/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/071BB051-29DB-4B25-B899-829C2D7AF32E/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/RONIN/Library/Detox/ios/05ea98aa93d326c35745e104035538dc4454d04f/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 071BB051-29DB-4B25-B899-829C2D7AF32E org.reactjs.native.example.trucke --args -detoxServer ws://localhost:58823 -detoxSessionId 9b5cf0c3-a82d-7cef-8194-4b5871f578ae` (exited with error code 1)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:277:5)
      at maybeClose (internal/child_process.js:927:16)
      at Socket.stream.socket.on (internal/child_process.js:348:11)
      at Pipe._handle.close [as _onclose] (net.js:545:12)

  2) "after all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```
#### Description
Followed setup instructions but app immediately closes. I can run app normally using react-native run-ios. Detox version 5.8.1

#### Steps to Reproduce

```
detox build --configuration ios.sim.debug
react-native start
detox test --configuration ios.sim.debug
```

#### Node, Device, Xcode and macOS Versions

* Node:8.5.0
* Device: iPhone 5 simulator
* Xcode: 8.3.3
* macOS: Sierra 10.12.5

**Comment by rotemmiz** [comment]
Detox.framework is being compiled into 64bit architectures, while 32bit are omitted. 
Prior to Detox 5.7.0 we were shipping Detox.framework already compiled, and we didn't want the npm package to be huge. In v5.7.0 we started compiling the framework on the user's machine, so technically, I don't think there's a limitation to just create a fat binary and include all architectures. 
@LeoNatan, what do you think ?

Alternatively, just use a newer iPhone model, iPhone 5S and up...

**Comment by LeoNatan** [comment]
Use a different simulator. 32bit is so ancient, I really don't see any point changing the current system.

Why are you using iPhone 5 simulator anyway?
