### ISSUE TITLE
Android unit tests don't run on MacOS

### ISSUE THREAD

**Issue by codebutler** [wix/Detox#3238]
### What happened?

Running Android unit tests on MacOS fails with the error below. This is caused by https://github.com/raphw/byte-buddy/issues/732

Upgrading to the latest Mockito fixes the problem.

```
Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
	at com.sun.proxy.$Proxy22.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:238)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
	at org.mockito.Mockito.mock(Mockito.java:1895)
	at com.wix.detox.adapters.server.DetoxActionHandlersSpec$1$1$1.invoke(DetoxActionHandlersSpec.kt:332)
	at com.wix.detox.adapters.server.DetoxActionHandlersSpec$1$1$1.invoke(DetoxActionHandlersSpec.kt:20)
	at org.spekframework.spek2.runtime.scope.Fixtures.invokeBeforeTestFixtures(fixtures.kt:43)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:102)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:101)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:101)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.invokeBeforeTestFixtures(scopes.kt:146)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:83)
	(Coroutine boundary)
	at org.spekframework.spek2.runtime.Executor$execute$result$2.invokeSuspend(Executor.kt:80)
	at org.spekframework.spek2.runtime.Executor.executeSafely(Executor.kt:121)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:58)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$1.invokeSuspend(Executor.kt:72)
	at org.spekframework.spek2.runtime.Executor$execute$result$2.invokeSuspend(Executor.kt:61)
	at org.spekframework.spek2.runtime.Executor.executeSafely(Executor.kt:121)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:58)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$1.invokeSuspend(Executor.kt:72)
	at org.spekframework.spek2.runtime.Executor$execute$result$2.invokeSuspend(Executor.kt:61)
	at org.spekframework.spek2.runtime.Executor.executeSafely(Executor.kt:121)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:58)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$1.invokeSuspend(Executor.kt:72)
	at org.spekframework.spek2.runtime.Executor$execute$result$2.invokeSuspend(Executor.kt:61)
	at org.spekframework.spek2.runtime.Executor.executeSafely(Executor.kt:121)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:58)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$1.invokeSuspend(Executor.kt:72)
	at org.spekframework.spek2.runtime.Executor$execute$result$2.invokeSuspend(Executor.kt:61)
	at org.spekframework.spek2.runtime.Executor.executeSafely(Executor.kt:121)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:58)
	at org.spekframework.spek2.runtime.TaskRunner$runTask$1$1.invokeSuspend(executors.kt:27)
Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
	at com.sun.proxy.$Proxy22.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:238)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
	at org.mockito.Mockito.mock(Mockito.java:1895)
	at com.wix.detox.adapters.server.DetoxActionHandlersSpec$1$1$1.invoke(DetoxActionHandlersSpec.kt:332)
	at com.wix.detox.adapters.server.DetoxActionHandlersSpec$1$1$1.invoke(DetoxActionHandlersSpec.kt:20)
	at org.spekframework.spek2.runtime.scope.Fixtures.invokeBeforeTestFixtures(fixtures.kt:43)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:102)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:101)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:101)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.invokeBeforeTestFixtures(scopes.kt:146)
	at org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.spekframework.spek2.runtime.TaskRunner$runTask$1.run(executors.kt:26)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@642e5bb3
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:18)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:238)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
	at org.mockito.Mockito.mock(Mockito.java:1895)
	at com.wix.detox.adapters.server.DetoxActionHandlersSpec$1$1$1.invoke(DetoxActionHandlersSpec.kt:332)
	at com.wix.detox.adapters.server.DetoxActionHandlersSpec$1$1$1.invoke(DetoxActionHandlersSpec.kt:20)
	at org.spekframework.spek2.runtime.scope.Fixtures.invokeBeforeTestFixtures(fixtures.kt:43)
	at org.spekframework.spek2.runtime.scope.GroupScopeImpl.invokeBeforeTestFixtures(scopes.kt:102)
	... 17 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 11
JVM vendor name    : JetBrains s.r.o.
JVM vendor version : 11.0.11+0-b60-7772763
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.11+0-b60-7772763
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 12.1

	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:171)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
	... 31 more
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@6e6f3059
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:384)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:358)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:326)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:312)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:101)
	... 37 more
Caused by: java.io.IOException: Cannot run program ""/Users/eric/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents/jre/Contents/Home/bin/java"": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:442)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:377)
	... 41 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 44 more
```

### What was the expected behaviour?

Tests should run successfully on MacOS

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Run tests in Android Studio on MacOS.

### In what environment did this happen?

MacOS 12.1
Android Studio 2021.1.1 P1

**Comment by d4vidi** [comment]
Fixed long ago
