### ISSUE TITLE
Detox 19.5.2 appears broken

### ISSUE THREAD

**Issue by dkoudrinhc** [wix/Detox#3251]
### Description

My detox is trying to update to 19.5.2 (latest version) but appears to fail while the npm run build command is running. Here is the log output:

> detox@19.5.2 postinstall /Users/dmitrikoudrin/hazardco_app_mobile_nativescript/node_modules/detox
> node scripts/postinstall.js

Extracting Detox framework...
tar: Error opening archive: Failed to open '/Users/dmitrikoudrin/hazardco_app_mobile_nativescript/node_modules/detox/Detox-ios.tbz'
child_process.js:651
    throw err;
    ^

Error: Command failed: /Users/dmitrikoudrin/hazardco_app_mobile_nativescript/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.<anonymous> (/Users/dmitrikoudrin/hazardco_app_mobile_nativescript/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {

Is anyone also having this issue and/or are aware of it. Would like to continue using Detox without having to downgrade to previous versions. P.S. 19.4.1 works fine for me.

### Your environment

Detox version: 19.5.2
React Native version: Our project uses nativescript instead of react-native
Node version: 12.18.3
Device model: Iphone 13 Simulator
OS: MacOS Monterey 12.0.1
Test-runner (select one): jest+jasmine

**Comment by mfazekas** [comment]
@dkoudrinhc we've also started to see this errors since yesterday in our CI

https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true

```sh
warning " > detox@19.5.2" has unmet peer dependency "mocha@>=6.0.0".
[20](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:20)
[4/4] Building fresh packages...
[21](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:21)
error /Users/runner/work/maps/maps/example/node_modules/detox: Command failed.
[22](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:22)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[23](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:23)
Exit code: 1
[24](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:24)
Command: node scripts/postinstall.js
[25](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:25)
Arguments: 
[26](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:26)
Directory: /Users/runner/work/maps/maps/example/node_modules/detox
[27](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:27)
Output:
[28](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:28)
Extracting Detox framework...
[29](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:29)
tar: Error opening archive: Failed to open '/Users/runner/work/maps/maps/example/node_modules/detox/Detox-ios.tbz'
[30](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:30)
child_process.js:661
[31](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:31)
    throw err;
[32](https://github.com/rnmapbox/maps/runs/5441028901?check_suite_focus=true#step:6:32)
    ^
```

**Comment by asafkorem** [comment]
Hi @dkoudrinhc and @mfazekas. Thank you for the reports! 
Indeed this version is broken, please use detox v19.5.1 until a new version will be released. We are working to fix this.
