### ISSUE TITLE
Error: Can't open file: /data/local/tmp/detox/Application.apk while running in github actions

### ISSUE THREAD

**Issue by zacharyweidenbach** [wix/Detox#3312]
### What happened?

While running the release variant of the detox android configuration, the tests pass successfully. However, when running in CI (github actions in this case), tests fail at the `detox.init()` stage.

### What was the expected behaviour?

Tests would execute and pass in CI the same as they would locally.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.6.2
React Native version: 0.67.2
Node version: v14.17.0
Device model: NEXUS_5X_API_30
Android version: system-images;android-30;google_apis;x86_64
Test-runner (select one): jest-circus
Java: OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)

### Detox logs

<details><summary>Detox logs</summary>

`trace` level logging shows the hang that occurs at the `detox.init()` step

```
detox[4636] DEBUG: [DEVICE_LOOKUP] Found a matching & free device emulator-5554
detox[4636] DEBUG: [ALLOCATE_DEVICE] Settled on emulator-5554
detox[4636] DEBUG: [EXEC_CMD, #3] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop dev.bootcomplete"
detox[4636] DEBUG: [EXEC_CMD, #4] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[4636] DEBUG: [EXEC_CMD, #5] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"
detox[4636] DEBUG: [EXEC_CMD, #6] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global window_animation_scale 0"
detox[4636] DEBUG: [EXEC_CMD, #7] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global transition_animation_scale 0"
detox[4636] DEBUG: [EXEC_CMD, #8] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[4636] DEBUG: [EXEC_CMD, #9] "/Users/runner/Library/Android/sdk/build-tools/32.0.0/aapt" dump badging "/Users/runner/work/testproject/testproject/TestNative/android/app/build/outputs/apk/testapp/release/app-testapp-release.apk"
detox[4636] DEBUG: [EXEC_CMD, #10] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop com.testproject.test"
detox[4636] DEBUG: [EXEC_CMD, #11] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.testproject.test"
detox[4636] DEBUG: [EXEC_CMD, #12] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages com.testproject.test"
detox[4636] DEBUG: [EXEC_CMD, #13] "/Users/runner/Library/Android/sdk/build-tools/32.0.0/aapt" dump xmlstrings "/Users/runner/work/testproject/testproject/TestNative/android/app/build/outputs/apk/testapp/release/app-testapp-release.apk" AndroidManifest.xml
detox[4636] DEBUG: [EXEC_CMD, #14] "/Users/runner/Library/Android/sdk/build-tools/32.0.0/aapt" dump xmlstrings "/Users/runner/work/testproject/testproject/TestNative/android/app/build/outputs/apk/androidTest/testapp/release/app-testapp-release-androidTest.apk" AndroidManifest.xml
detox[4636] DEBUG: [EXEC_CMD, #15] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
detox[4636] DEBUG: [EXEC_CMD, #16] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
detox[4636] DEBUG: [EXEC_CMD, #17] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/runner/work/testproject/testproject/TestNative/android/app/build/outputs/apk/testapp/release/app-testapp-release.apk" "/data/local/tmp/detox/Application.apk"
detox[4636] DEBUG: [EXEC_CMD, #18] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[4636] ERROR: Exceeded timeout of 300000ms while handling jest-circus "setup" event
```

Further inspection of the logs artifacts produced by detox running in CI reveal the failure occurs at the step of `pm install` of the Application.apk from the tmp directory

```
detox[4636] DEBUG: [EXEC_CMD, #41] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
detox[4636] TRACE: [EXEC_SUCCESS, #41] 
detox[4636] DEBUG: [EXEC_CMD, #42] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
detox[4636] TRACE: [EXEC_SUCCESS, #42] 
detox[4636] DEBUG: [EXEC_CMD, #43] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/runner/work/testproject/testproject/TestNative/android/app/build/outputs/apk/testapp/release/app-testapp-release.apk" "/data/local/tmp/detox/Application.apk"
detox[4636] ERROR: [EXEC_FAIL, #18] ""/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"" failed with error = ChildProcessError: Command failed: "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
Error: Unable to open file: /data/local/tmp/detox/Application.apk
Error: Can't open file: /data/local/tmp/detox/Application.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Can't open file: /data/local/tmp/detox/Application.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:519)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1282)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1248)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:184)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21646)
	at android.os.Binder.shellCommand(Binder.java:929)
	at android.os.Binder.onTransact(Binder.java:813)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4603)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4305)
	at android.os.Binder.execTransactInternal(Binder.java:1159)
	at android.os.Binder.execTransact(Binder.java:1123)
 `"/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"` (exited with error code 255) (code=255), stdout and stderr:
```

</details>

### Device logs

<details><summary>Device logs</summary>
I have the device logs but they do not show any detox-related logging. I could product them if necessary (they are quite long) but having combed through them, I don't see anything like the `java.lang.IllegalArgumentException` pasted above, which leads me to believe the error throws in the java running adb on the host machine and not within the emulator printing out to logcat
</details>

### More data, please!

Build step succeeds without issue. Emulator is started with command:
```
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd NEXUS_5X_API_30 -no-boot-anim -camera-back none -camera-front none -memory 2048 -timezone 'US/Arizona' &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done'
```
and the output of the step does indicate it was successful in starting.

The possible explanations for the error that I can think of are:
- There is a problem with root permissions for the runner in github actions, but I haven't been able to find another issue in the Detox repo similar to this. 
- The previous step to push the release apk to `/data/local/tmp/detox/Application.apk` failed even though it says it succeeded
- The Application.apk is actually corrupt and the build step is succeeding despite this corruption

**Comment by zacharyweidenbach** [comment]
I think I can rule out permissions as a possibility
After following the steps here:
https://stackoverflow.com/a/36266874/16318310

I added a step to the github action workflow and the returning permissions looked good:
```
/Users/runner/Library/Android/sdk/platform-tools/adb shell ls -ld /data/ /data/local/ /data/local/tmp/
drwxrwx--x 47 system system 409[6](https://github.com/synapsestudios/tivity-commercial-product/runs/5889729687?check_suite_focus=true#step:18:6) 2022-04-0[8](https://github.com/synapsestudios/tivity-commercial-product/runs/5889729687?check_suite_focus=true#step:18:8) 11:38 /data/
drwxr-x--x  4 root   root   4096 2022-04-08 11:19 /data/local/
drwxrwx--x  2 shell  shell  4096 2022-04-08 11:19 /data/local/tmp/
```

**Comment by noomorph** [comment]
@d4vidi interesting perspective. Looks like a workaround with `adb push` and consequent installation via shell has its own glitches sometimes.

**Comment by paulclarkin** [comment]
@zacharyweidenbach I'm having the same issue as you, but on Microsoft App Center. 
Would be able to share the Github Step you added please?

**Comment by zacharyweidenbach** [comment]
@paulclarkin 
My steps are nearly identical to the `react-native-firebase` steps, with the exception that I was building the release version of the app for my tests instead of prefetching the bundled JS and running the debug build.
https://github.com/invertase/react-native-firebase/blob/main/.github/workflows/tests_e2e_android.yml
