### ISSUE TITLE
Detox fails to run on xcode v13.3.1 

### ISSUE THREAD

**Issue by cortisiko** [wix/Detox#3331]
### What happened?

Updating from Xcode v13.2.1 to v13.3.1 breaks detox. The app builds successfully but the test do not run. I get a bunch of `Application termination failed` errors

### What was the expected behaviour?

The tests should run irrespective of Xcode version. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

To reproduce:

- ensure you have Xcode v13.3.1 installed
- launch detox
- notice the app builds successfully but the tests do not run. 

### In what environment did this happen?

Detox version: 19.4.0 
React Native version: 0.66.3
Node version: 14.17.3
Device model: 
iOS version: iOS 15.2
macOS version: 11.6.2
Xcode version: 13.2.1
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
Application termination failed.
FBSSystemService reported failure without an error, possibly because the app is not currently running.
 `/usr/bin/xcrun simctl terminate D1A17DE7-3015-4058-B703-1FC59F8B6FB5` (exited with error code 3) (code=3), stdout and stderr:
detox[18708] ERROR: [EXEC_FAIL, #5] 
detox[18708] ERROR: [EXEC_FAIL, #5] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application termination failed.
FBSSystemService reported failure without an error, possibly because the app is not currently running.
detox[18708] ERROR: [DETOX_INIT_ERROR] 
 ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate D1A17DE7-3015-4058-B703-1FC59F8B6FB5 
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application termination failed.
FBSSystemService reported failure without an error, possibly because the app is not currently running.
 `/usr/bin/xcrun simctl terminate D1A17DE7-3015-4058-B703-1FC59F8B6FB5` (exited with error code 3)
    at callback (/Users/vagrant/git/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:390:5)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  code: 3,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawnWithSignal],
    spawnSync: [Function: spawnSync]
  },
  stdout: ‘’,
  stderr: ‘An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):\n’ +
    ‘Application termination failed.\n’ +
    ‘FBSSystemService reported failure without an error, possibly because the app is not currently running.\n’
}
detox[18708] ERROR: [Client.js/ERROR] Detox can’t seem to connect to the test app(s)!
HINT: 
Have you forgotten to call ‘device.launchApp()’ in the beginning of your test?
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs
---
The following package could not be delivered:
{
  type: ‘invoke’,
  params: [Object],
  messageId: 1```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

### More data, please!

_No response_

**Comment by systemride** [comment]
I had the same issue. It looks like upgrading to the latest version `19.6.5` resolves the issue for me.

**Comment by cortisiko** [comment]
@systemride ahh yes thank you, updating to version 19.6.5 did solve my issue. Will close this issue.
