### ISSUE TITLE
[Android + React Native 0.68.1]The app has not responded to the network requests

### ISSUE THREAD

**Issue by xiongemi** [wix/Detox#3338]
### What happened?

got an error with android for react native 0.68.1, works fine for ios.

error:
```
15:31:02.641 detox[62277] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.
```

i have added 
```
android:networkSecurityConfig="@xml/network_security_config"
```
to both android/app/src/debug/AndroidManifest.xml and android/app/src/main/AndroidManifest.xml

### What was the expected behaviour?

should work on android

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.6.5
React Native version: 0.68.1
Node version: v14.17.0
Device model: Pixel_5_API_30
Android version: 
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
15:30:57.533 detox[62277] DEBUG: [WSS_CONNECTION, #53194] registered a new connection.
15:30:57.542 detox[62277] TRACE: [WSS_GET_FROM, #53194] {"messageId":0,"type":"login","params":{"role":"app","sessionId":"55850b8f-d1a3-3104-efba-036e1214da4c"}}
15:30:57.542 detox[62277] TRACE: [WSS_SEND_TO, #app] {"messageId":0,"type":"loginSuccess","params":{"testerConnected":true,"appConnected":true}}
15:30:57.543 detox[62277] TRACE: [SESSION_JOINED] app joined session 55850b8f-d1a3-3104-efba-036e1214da4c
15:30:57.543 detox[62277] TRACE: [WSS_SEND_TO, #tester] {"type":"appConnected"}
15:30:57.543 detox[62277] TRACE: [WS_MESSAGE] {"type":"appConnected"}
 
15:30:57.545 detox[62277] TRACE: [WS_SEND] {"type":"isReady","params":{},"messageId":-1000}
15:30:57.546 detox[62277] TRACE: [WSS_GET_FROM, #tester] {"type":"isReady","params":{},"messageId":-1000}
15:30:57.546 detox[62277] TRACE: [WSS_SEND_TO, #app] {"type":"isReady","params":{},"messageId":-1000}
15:30:57.566 detox[62277] TRACE: [WSS_GET_FROM, #app] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread detox.primary(1165):\njava.lang.NoSuchMethodError: No virtual method addReactInstanceEventListener(Lcom\/facebook\/react\/ReactInstanceManager$ReactInstanceEventListener;)V in class Lcom\/facebook\/react\/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in \/data\/app\/~~a9qlgwC0hyyk5n3hNs2jZg==\/com.mobile-PUIoda_qVyncxT3L73YzUA==\/base.apk)\n\tat com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7656)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)\n\nCheck device logs for full details!"}}
15:30:57.566 detox[62277] TRACE: [WSS_SEND_TO, #tester] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread detox.primary(1165):\njava.lang.NoSuchMethodError: No virtual method addReactInstanceEventListener(Lcom/facebook/react/ReactInstanceManager$ReactInstanceEventListener;)V in class Lcom/facebook/react/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/~~a9qlgwC0hyyk5n3hNs2jZg==/com.mobile-PUIoda_qVyncxT3L73YzUA==/base.apk)\n\tat com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7656)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)\n\nCheck device logs for full details!"}}
15:30:57.585 detox[62277] TRACE: [WS_MESSAGE] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread detox.primary(1165):\njava.lang.NoSuchMethodError: No virtual method addReactInstanceEventListener(Lcom/facebook/react/ReactInstanceManager$ReactInstanceEventListener;)V in class Lcom/facebook/react/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/~~a9qlgwC0hyyk5n3hNs2jZg==/com.mobile-PUIoda_qVyncxT3L73YzUA==/base.apk)\n\tat com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7656)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)\n\nCheck device logs for full details!"}}
 
15:31:02.592 detox[62277] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-5554', bundleId: 'com.mobile' })
15:31:02.595 detox[62312] TRACE: [SPAWN_KILL] sending SIGINT to: /Users/emilyxiong/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:53096 -e detoxSessionId 55850b8f-d1a3-3104-efba-036e1214da4c -e debug false com.mobile.test/androidx.test.runner.AndroidJUnitRunner
15:31:02.597 detox[62277] DEBUG: [SPAWN_END, #27, cpid=62312] /Users/emilyxiong/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:53096 -e detoxSessionId 55850b8f-d1a3-3104-efba-036e1214da4c -e debug false com.mobile.test/androidx.test.runner.AndroidJUnitRunner terminated with SIGINT
15:31:02.598 detox[62277] DEBUG: [EXEC_CMD, #29] "/Users/emilyxiong/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop com.mobile"
15:31:02.604 detox[62277] DEBUG: [EXEC_CMD, #30] "/Users/emilyxiong/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:53096
15:31:02.611 detox[62277] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onHookFailure({
  error: DetoxRuntimeError: Failed to run application on the device
  
  HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
      at /Users/emilyxiong/Code/tmp/nx-react-native-68-1/apps/mobile-e2e/test-setup.ts:4:16
      at Promise.then.completed (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/utils.js:390:28)
      at new Promise (<anonymous>)
      at callAsyncCircusFn (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/utils.js:315:10)
      at _callCircusHook (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/run.js:181:40)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at _runTestsForDescribeBlock (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/run.js:47:7)
      at run (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/run.js:25:3)
      at runAndTransformResultsToJestFormat (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
      at jestAdapter (/Users/emilyxiong/Code/tmp/nx-react-native-68-1/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
      at runTestInternal (/Users/emilyxiong/.nvm/versions/node/v14.17.0/lib/node_modules/jest/node_modules/jest-runner/build/runTest.js:389:16)
      at runTest (/Users/emilyxiong/.nvm/versions/node/v14.17.0/lib/node_modules/jest/node_modules/jest-runner/build/runTest.js:481:34)
      at TestRunner.runTests (/Users/emilyxiong/.nvm/versions/node/v14.17.0/lib/node_modules/jest/node_modules/jest-runner/build/index.js:111:12)
      at TestScheduler.scheduleTests (/Users/emilyxiong/.nvm/versions/node/v14.17.0/lib/node_modules/jest/node_modules/@jest/core/build/TestScheduler.js:333:13),
  hook: 'beforeAll'
})
15:31:02.613 Mobile[62277] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'Mobile' })
15:31:02.614 detox[62277] INFO:  Mobile is assigned to emulator-5554 (Pixel_5_API_30)
15:31:02.615 detox[62277] INFO:  Mobile: should display welcome message
15:31:02.617 detox[62277] INFO:  Mobile: should display welcome message [FAIL]
15:31:02.619 Mobile[62277] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'Mobile' })

15:31:02.619 ROOT_DESCRIBE_BLOCK[62277] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'ROOT_DESCRIBE_BLOCK' })
15:31:02.640 detox[62277] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeCleanup()
15:31:02.641 detox[62277] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

15:31:02.644 detox[62277] TRACE: [EXEC_SUCCESS, #30] 
15:31:02.649 detox[62277] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
Thanks for the report @xiongemi. 

Is there any activity indicator or animation running on app launch?
Also, can you follow our [dealing with synchronization issues doc](https://wix.github.io/Detox/docs/troubleshooting/synchronization)? Can you please run the tests with `--debug-synchronization 500 ` and provide the logs?

**Comment by xiongemi** [comment]
@asafkorem there is no activity indicator. i can see the app launches in simulator, but test still failed.
The error i got:
`No virtual method addReactInstanceEventListener`

```
{"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread detox.primary(343):\njava.lang.NoSuchMethodError: No virtual method addReactInstanceEventListener(Lcom\/facebook\/react\/ReactInstanceManager$ReactInstanceEventListener;)V in class Lcom\/facebook\/react\/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in \/data\/app\/~~EMy4vR8pcSnykJPmt48C8g==\/com.mobile-1cm05cYZOj3rtxyW33Xo8g==\/base.apk)\n\tat com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7656)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)\n\nCheck device logs for full details!"}}
```

the log with --debug-synchronization true:
```
15:26:11.814 detox[90606] TRACE: [SPAWN_STDOUT, #27, cpid=90680] INSTRUMENTATION_STATUS: class=com.mobile.DetoxTest
INSTRUMENTATION_STATUS: current=1

15:26:11.815 detox[90606] TRACE: [SPAWN_STDOUT, #27, cpid=90680] INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.mobile.DetoxTest:
INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS_CODE: 1

15:26:12.204 detox[90606] DEBUG: [WSS_CONNECTION, #51989] registered a new connection.
15:26:12.218 detox[90606] TRACE: [WSS_GET_FROM, #51989] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread detox.primary(343):\njava.lang.NoSuchMethodError: No virtual method addReactInstanceEventListener(Lcom\/facebook\/react\/ReactInstanceManager$ReactInstanceEventListener;)V in class Lcom\/facebook\/react\/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in \/data\/app\/~~EMy4vR8pcSnykJPmt48C8g==\/com.mobile-1cm05cYZOj3rtxyW33Xo8g==\/base.apk)\n\tat com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7656)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)\n\nCheck device logs for full details!"}}
15:26:12.218 detox[90606] WARN:  [DetoxConnection.js/ERROR, #51989] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  messageId: -10000,
  type: 'AppWillTerminateWithError',
  params: [Object]
}
15:26:12.219 detox[90606] TRACE: [WSS_GET_FROM, #51989] {"messageId":0,"type":"login","params":{"role":"app","sessionId":"87836347-226e-8e02-1145-e9070bdb4a14"}}
15:26:12.219 detox[90606] TRACE: [WSS_SEND_TO, #app] {"messageId":0,"type":"loginSuccess","params":{"testerConnected":true,"appConnected":true}}
15:26:12.219 detox[90606] TRACE: [SESSION_JOINED] app joined session 87836347-226e-8e02-1145-e9070bdb4a14
15:26:12.221 detox[90606] TRACE: [WSS_SEND_TO, #tester] {"type":"appConnected"}
15:26:12.222 detox[90606] TRACE: [WS_MESSAGE] {"type":"appConnected"}
 
15:26:12.224 detox[90606] TRACE: [WS_SEND] {"type":"isReady","params":{},"messageId":-1000}
15:26:12.224 detox[90606] TRACE: [WSS_GET_FROM, #tester] {"type":"isReady","params":{},"messageId":-1000}
15:26:12.224 detox[90606] TRACE: [WSS_SEND_TO, #app] {"type":"isReady","params":{},"messageId":-1000}
15:26:15.224 detox[90606] TRACE: [WS_SEND] {"type":"currentStatus","params":{},"messageId":1}
15:26:15.224 detox[90606] TRACE: [WSS_GET_FROM, #tester] {"type":"currentStatus","params":{},"messageId":1}
15:26:15.225 detox[90606] TRACE: [WSS_SEND_TO, #app] {"type":"currentStatus","params":{},"messageId":1}
15:26:15.229 detox[90606] TRACE: [WSS_GET_FROM, #app] {"messageId":1,"type":"currentStatusResult","params":{"status":{"app_status":"idle"}}}
15:26:15.230 detox[90606] TRACE: [WSS_SEND_TO, #tester] {"messageId":1,"type":"currentStatusResult","params":{"status":{"app_status":"idle"}}}
15:26:15.230 detox[90606] TRACE: [WS_MESSAGE] {"messageId":1,"type":"currentStatusResult","params":{"status":{"app_status":"idle"}}}
 
15:26:15.233 detox[90606] INFO:  [APP_STATUS] The app seems to be idle
```

**Comment by hajermay** [comment]
Hello same problem 
any update please ??

**Comment by medbenmoussa** [comment]
hello i have same problem 
any update ??

**Comment by hajermay** [comment]
@medbenmoussa  i used the react-native 0.67  instead 
and it works I think the problem is with the last react native version

**Comment by medbenmoussa** [comment]
@hajermay  I will try with that's thank u so much .

**Comment by d4vidi** [comment]
Looks like we have an issue with RN .68 (integs. of Detox with new RN releases are often not trivial). Please track #3344
