### ISSUE TITLE
[Android] Test app could not be found at path : DetoxRuntimeError

### ISSUE THREAD

**Issue by Anantha-sb** [wix/Detox#3393]
### Description

My issue is most likely due to incorrect `.detoxrc.js` file. I am trying to test on an physical device in staging build. 

I am able to build my project with the following command:

`cd android && ./gradlew clean && ./gradlew assembleDebug && ./gradlew assembleAndroidTest -DtestBuildType=debug && cd ..`

`yarn detox:build:android-debug` successfully builds and generates an androidTest app apk but when I run `yarn detox:e2e:android-debug`, the build fails with DetoxRuntimeError. 

```
`[DetoxRuntimeError: The test APK could not be found at path: '/Users/asb/Documents/AuditPro/android/app/build/outputs/apk/androidTest/debug/androidTest/app-debug-androidTest-androidTest.apk'

HINT: Try running the detox build command, and make sure it was configured to execute a build command (e.g. './gradlew assembleAndroidTest')
For further assistance, visit the Android setup guide: https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md] {
  [Symbol(originalCallSite)]: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ],
  [Symbol(mutatedCallSite)]: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
VError: a BeforeAll hook errored, process exiting: e2e/features/step_definitions/Hooks.js:1: The test APK could not be found at path: '/Users/asb/Documents/AuditPro/android/app/build/outputs/apk/androidTest/debug/androidTest/app-debug-androidTest-androidTest.apk'

HINT: Try running the detox build command, and make sure it was configured to execute a build command (e.g. './gradlew assembleAndroidTest')
For further assistance, visit the Android setup guide: https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md
    at Runtime.runTestRunHooks (/Users/asb/Documents/AuditPro/node_modules/@cucumber/cucumber/src/runtime/run_test_run_hooks.ts:32:19)
    at Runtime.start (/Users/asb/Documents/AuditPro/node_modules/@cucumber/cucumber/src/runtime/index.ts:108:5)
    at runCucumber (/Users/asb/Documents/AuditPro/node_modules/@cucumber/cucumber/src/api/run_cucumber.ts:117:19)
    at Cli.run (/Users/asb/Documents/AuditPro/node_modules/@cucumber/cucumber/src/cli/index.ts:76:25)
    at Object.run [as default] (/Users/asb/Documents/AuditPro/node_modules/@cucumber/cucumber/src/cli/run.ts:38:14)
caused by: DetoxRuntimeError: The test APK could not be found at path: '/Users/asb/Documents/AuditPro/android/app/build/outputs/apk/androidTest/debug/androidTest/app-debug-androidTest-androidTest.apk'`

```
I am not sure why it's looking for an extra **androidTest** in the apk name (app-debug-androidTest-androidTest.apk). As you can see in the below image, test apk is properly generated. 

<img width="1440" alt="Screenshot 2022-05-16 at 3 59 12 pm" src="https://user-images.githubusercontent.com/15376714/168528594-45943f6c-9a0b-4fc6-b416-d1dc665a8c64.png">

My `.detoxrc.js `file:

```
`module.exports ={
    "configurations": {
        "android.att.debug": {
             "binaryPath": "android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
             "build": "cd android && ./gradlew clean && ./gradlew assembleDebug && ./gradlew assembleAndroidTest -DtestBuildType=debug && cd ..",
             "type": "android.attached",
             "device": {
                 "adbName": "19287B294E"
             }
        }
    }
 }`
```

My `package.json`

```
`"scripts": {
        "start": "react-native start",
        "lint": "eslint .",
        "jetify": "npm run jetify",
        "run-android": "react-native run-android",
        "run-android-develop": "react-native run-android --variant develop",
        "run-android-qa": "react-native run-android --variant qa",
        "build-develop": "cd android && ./gradlew app:assembleDevelop",
        "build-qa": "cd android && ./gradlew app:assembleQa",
        "build-uat": "cd android && ./gradlew app:assembleUat",
        "clean": "cd android && ./gradlew clean",
        "print-native-logs": "adb logcat *:S AuditPro:V ReactNative:V",
        "clear-native-logs": "adb logcat -c",
        "start-emulator": "emulator -avd NNSC_API_29",
        "pause-postinstall": "npm run jetify",
        "audit": "npm audit --json | npm-audit-html",
        "detox:build:android-debug": "detox build --configuration android.att.debug",
        "detox:e2e:android-debug": "DETOX_CONFIGURATION=android.att.debug npx cucumber-js"
    },`
```

### Your environment

Detox version: 19.6.9
React Native version: 0.64
Node version: v18.0
Device model: MacPro
Test-runner (select one): cucumber

**Comment by Anantha-sb** [comment]
Closing this. I resolved the issue by configuring `testBinaryPath`.
