### ISSUE TITLE
"before all" hook Timeout exceeded when run the provided example test

### ISSUE THREAD

**Issue by danielfeelfine** [wix/detox#340]
#### Description
I try to ran `detox test` and got the error:
```sh
1)  "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

child_process.js:631
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts
```

**Detox** version **5.8.2**

#### Steps to Reproduce
- Start a fresh React Native project
- User these Detox configs:
```
"detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/ExampleProject.app",
        "build": "xcodebuild -project ios/ExampleProject.xcodeproj -scheme ExampleProject -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 6"
      }
    }
  }
```
- Run the [example.spec.js](https://github.com/wix/detox/blob/master/examples/demo-react-native/e2e/example.spec.js) with [init.js](https://github.com/wix/detox/blob/master/examples/demo-react-native/e2e/init.js) configs
- Use `mocha.opts` as `--recursive --timeout 120000 --bail`

#### Node, Device, Xcode and macOS Versions

* Node: **8.1.2**
* Device: iPhone 6
* Xcode: **9.0**
* macOS: Sierra

**Comment by rotemmiz** [comment]
We won’t be able to help you without a verbose log `—loglevel verbose` and the simulator log

**Comment by danielfeelfine** [comment]
How can I generate a `—loglevel verbose` and a simulator log?

**Comment by danielfeelfine** [comment]
@rotemmiz, the full log:

```bash
detox test --configuration ios.sim.release -l verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release --loglevel verbose


detox info 18:02:14: server listening on localhost:58972...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"dc967aaf-0018-1c7f-6a02-40b735be42ed","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"dc967aaf-0018-1c7f-6a02-40b735be42ed","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: applesimutils --list "iPhone 6" --maxResults=1
detox info 1: Searching for device matching iPhone 6...
detox verb 1: stdout: [
detox verb 1: stdout:   {
detox verb 1: stdout:     "state" : "Booted",
detox verb 1: stdout:     "availability" : "(available)",
detox verb 1: stdout:     "name" : "iPhone 6",
detox verb 1: stdout:     "udid" : "587F7E36-87BF-4CC9-8D80-2308DD01A706",
detox verb 1: stdout:     "os" : {
detox verb 1: stdout:       "version" : "11.0",
detox verb 1: stdout:       "availability" : "(available)",
detox verb 1: stdout:       "name" : "iOS 11.0",
detox verb 1: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 1: stdout:       "buildversion" : "15A372"
detox verb 1: stdout:     }
detox verb 1: stdout:   }
detox verb 1: stdout: ]
detox verb 1: stdout:
detox verb 2: applesimutils --list
detox verb 2: stdout: [
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple TV",
detox verb 2: stdout:     "udid" : "3958E255-45CB-4817-9A59-321CCFAA7439",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "tvOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.tvOS-11-0",
detox verb 2: stdout:       "buildversion" : "15J380"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple TV 4K",
detox verb 2: stdout:     "udid" : "856C8010-2EAC-4E00-A31F-C05372E9E8E1",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "tvOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.tvOS-11-0",
detox verb 2: stdout:       "buildversion" : "15J380"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple TV 4K (at 1080p)",
detox verb 2: stdout:     "udid" : "BD562075-5134-4250-9F37-E3F56A999ADD",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "tvOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.tvOS-11-0",
detox verb 2: stdout:       "buildversion" : "15J380"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad (5th generation)",
detox verb 2: stdout:     "udid" : "22787F42-C8D3-4E55-BBC2-8708D805E00E",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad Air",
detox verb 2: stdout:     "udid" : "7E83A8FD-8260-4D58-B965-8A918DDDEC4E",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad Air 2",
detox verb 2: stdout:     "udid" : "A0570FEA-7870-41D4-87B0-1F528BE037B5",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad Pro (10.5-inch)",
detox verb 2: stdout:     "udid" : "D5056D65-3A3C-4EB2-BF1C-54985B9C6652",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad Pro (12.9-inch)",
detox verb 2: stdout:     "udid" : "8664983C-C67B-44F0-BA44-294FD0D975A4",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad Pro (12.9-inch) (2nd generation)",
detox verb 2: stdout:     "udid" : "1148FC81-AA95-4661-B048-E0C0C752C7F1",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPad Pro (9.7-inch)",
detox verb 2: stdout:     "udid" : "141CB1D0-BF5D-4254-9AA9-BFA83655E4B1",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 5s",
detox verb 2: stdout:     "udid" : "6C9CC3DA-C64E-4022-A4CC-EA7D406ADDA2",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Booted",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 6",
detox verb 2: stdout:     "udid" : "587F7E36-87BF-4CC9-8D80-2308DD01A706",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 6 Plus",
detox verb 2: stdout:     "udid" : "B068CACA-67DC-405F-BD78-C333A11227E6",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 6s",
detox verb 2: stdout:     "udid" : "B9785108-B8C2-4902-AAD5-49183D0492B8",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 6s Plus",
detox verb 2: stdout:     "udid" : "28E6E7AC-9029-46A2-A243-CDFC81D94FDF",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 7",
detox verb 2: stdout:     "udid" : "43A02E09-F454-4A42-A8C3-AFF28AA4CF81",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Booted",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 7 Plus",
detox verb 2: stdout:     "udid" : "359EF6E5-6516-4523-968B-A258741103E7",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 8",
detox verb 2: stdout:     "udid" : "00A7D635-8CA9-4545-BA93-D95D88666987",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone 8 Plus",
detox verb 2: stdout:     "udid" : "AEDEFB8D-5F67-4AD7-A97F-CC439629586E",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone SE",
detox verb 2: stdout:     "udid" : "408D92EE-DC83-45FE-B606-8098DAEA9337",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "iPhone X",
detox verb 2: stdout:     "udid" : "51C82CA7-7D40-43E3-82BA-4CC09C96B1F0",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "11.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "iOS 11.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-0",
detox verb 2: stdout:       "buildversion" : "15A372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple Watch - 38mm",
detox verb 2: stdout:     "udid" : "498AB47B-46CE-4B38-A1B6-90579B08F0B7",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "4.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "watchOS 4.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-4-0",
detox verb 2: stdout:       "buildversion" : "15R372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple Watch - 42mm",
detox verb 2: stdout:     "udid" : "30F5B5D8-8168-4696-A79D-1D0AB4213CA7",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "4.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "watchOS 4.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-4-0",
detox verb 2: stdout:       "buildversion" : "15R372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple Watch Series 2 - 38mm",
detox verb 2: stdout:     "udid" : "969228EC-660F-4B63-9825-A8AE154BDB5F",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "4.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "watchOS 4.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-4-0",
detox verb 2: stdout:       "buildversion" : "15R372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple Watch Series 2 - 42mm",
detox verb 2: stdout:     "udid" : "8FF72EB2-43FA-4A86-A835-402309246E49",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "4.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "watchOS 4.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-4-0",
detox verb 2: stdout:       "buildversion" : "15R372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple Watch Series 3 - 38mm",
detox verb 2: stdout:     "udid" : "580A6C94-2DB4-41A4-B7B4-FE94D343C78E",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "4.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "watchOS 4.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-4-0",
detox verb 2: stdout:       "buildversion" : "15R372"
detox verb 2: stdout:     }
detox verb 2: stdout:   },
detox verb 2: stdout:   {
detox verb 2: stdout:     "state" : "Shutdown",
detox verb 2: stdout:     "availability" : "(available)",
detox verb 2: stdout:     "name" : "Apple Watch Series 3 - 42mm",
detox verb 2: stdout:     "udid" : "E96ABA91-A6A9-433B-95F4-15E621B2DF9D",
detox verb 2: stdout:     "os" : {
detox verb 2: stdout:       "version" : "4.0",
detox verb 2: stdout:       "availability" : "(available)",
detox verb 2: stdout:       "name" : "watchOS 4.0",
detox verb 2: stdout:       "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-4-0",
detox verb 2: stdout:       "buildversion" : "15R372"
detox verb 2: stdout:     }
detox verb 2: stdout:   }
detox verb 2: stdout: ]
detox verb 2: stdout:
detox verb 3: /usr/bin/xcrun simctl uninstall 587F7E36-87BF-4CC9-8D80-2308DD01A706 com.quanto.tentiQ
detox info 3: Uninstalling com.quanto.tentiQ...
detox info 3: com.quanto.tentiQ uninstalled
detox verb 4: /usr/bin/xcrun simctl install 587F7E36-87BF-4CC9-8D80-2308DD01A706 /Users/dtorres/Projects/Quanto/tentiQ/ios/build/Build/Products/Release-iphonesimulator/Quanto.app
detox info 4: Installing /Users/dtorres/Projects/Quanto/tentiQ/ios/build/Build/Products/Release-iphonesimulator/Quanto.app...
detox info 4: /Users/dtorres/Projects/Quanto/tentiQ/ios/build/Build/Products/Release-iphonesimulator/Quanto.app installed
detox verb 5: /usr/bin/xcrun simctl terminate 587F7E36-87BF-4CC9-8D80-2308DD01A706 com.quanto.tentiQ
detox info 5: Terminating com.quanto.tentiQ...
detox info 5: com.quanto.tentiQ terminated
detox verb 6: /bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/587F7E36-87BF-4CC9-8D80-2308DD01A706/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/587F7E36-87BF-4CC9-8D80-2308DD01A706/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/dtorres/Library/Detox/ios/a719a7fd8af96db5fefad3da20b783f61b168620/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 587F7E36-87BF-4CC9-8D80-2308DD01A706 com.quanto.tentiQ --args -detoxServer ws://localhost:58972 -detoxSessionId dc967aaf-0018-1c7f-6a02-40b735be42ed
detox info 6: Launching com.quanto.tentiQ...
detox verb 6: stdout: com.quanto.tentiQ: 21721
detox verb 6: stdout:
detox info 6: com.quanto.tentiQ launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/587F7E36-87BF-4CC9-8D80-2308DD01A706/data/tmp/detox.last_launch_app_log.{out,err}
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
  1) "before all" hook

  0 passing (2m)
  1 failing

  1)  "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.




child_process.js:631
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release --loglevel verbose
    at checkExecSyncError (child_process.js:588:13)
    at Object.execSync (child_process.js:628:13)
    at Object.<anonymous> (/Users/dtorres/Projects/Quanto/tentiQ/node_modules/detox/local-cli/detox-test.js:46:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

**Comment by rotemmiz** [comment]
This is a known issue with Firebase SDK. I am closing this issue and referencing it in the main Firebase SDK issue thread.

https://github.com/wix/detox/issues/270
