### ISSUE TITLE
DetoxRuntimeError: No instrumentation runner found on device null for package

### ISSUE THREAD

**Issue by Anantha-sb** [wix/Detox#3414]
### What happened?

I have been trying to understand this error but cannot pinpoint the reason behind No instrumentation runner. The moment I run the command, it fails. I am also unable to use `--loglevel trace` to get the logs. 

I am able to build the project successfully, generate apks and install them on my physical device but I am unable to execute any tests. 

Command I use to run: ` yarn detox:e2e:android-release`

The error:
```

1) Scenario: I can locate elements by text # e2e/features/element_location/matchers.feature:6
   ✖ Before # e2e/features/step_definitions/Hooks.js:1
       DetoxRuntimeError: No instrumentation runner found on device null for package com.nanosonics.audit_pro
           at _callee2$ (/Users/asb/Downloads/AuditPro/e2e/features/step_definitions/Hooks.js:13:16)
           at tryCatch (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
           at Generator.invoke [as _invoke] (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:293:22)
           at Generator.next (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
           at tryCatch (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
           at invoke (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:154:20)
           at /Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:189:11
           at new Promise (<anonymous>)
           at callInvokeWithMethodAndArg (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:188:16)
           at AsyncIterator.enqueue (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:211:13)
           at AsyncIterator.next (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
           at Object.exports.async (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:238:14)
           at World._callee2 (/Users/asb/Downloads/AuditPro/e2e/features/step_definitions/Hooks.js:11:8)
   - Given I tap on the Log a procedure button by text # e2e/features/step_definitions/MatchersSteps.js:1
   - When I tap on the Low Level Disinfected button by text # e2e/features/step_definitions/MatchersSteps.js:1

2) Scenario: I execute Detox test # e2e/features/onboarding/initialtest.feature:3
   ✖ Before # e2e/features/step_definitions/Hooks.js:1
       DetoxRuntimeError: No instrumentation runner found on device null for package com.nanosonics.audit_pro
           at _callee2$ (/Users/asb/Downloads/AuditPro/e2e/features/step_definitions/Hooks.js:13:16)
           at tryCatch (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
           at Generator.invoke [as _invoke] (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:293:22)
           at Generator.next (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
           at tryCatch (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
           at invoke (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:154:20)
           at /Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:189:11
           at new Promise (<anonymous>)
           at callInvokeWithMethodAndArg (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:188:16)
           at AsyncIterator.enqueue (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:211:13)
           at AsyncIterator.next (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
           at Object.exports.async (/Users/asb/Downloads/AuditPro/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:238:14)
           at World._callee2 (/Users/asb/Downloads/AuditPro/e2e/features/step_definitions/Hooks.js:11:8)
   - Given I start Detox # e2e/features/step_definitions/OnboardingSteps.js:1
```

**`.detoxrc.js`**

```
module.exports ={


    "configurations": {

        "android.att.release": {
            "binaryPath": "android/app/build/outputs/apk/qa/app-qa.apk",
            "testBinaryPath": "android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk",
            "build": "cd android && ./gradlew clean && ./gradlew app:assembleQa && ./gradlew assembleAndroidTest -DtestBuildType=release && cd ..", 
            "type": "android.attached",
            "device": {
                "adbName": "21169B056B"
            }
        }
    }
 }  
```

**Location of the apk:**
<img width="1443" alt="Screenshot 2022-05-23 at 8 56 53 am" src="https://user-images.githubusercontent.com/15376714/169719513-affa4e87-3665-4efd-9ddd-b64a85bf43d2.png">

**android/build.gradle**

```
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
        ext.kotlinVersion = '1.6.0'
    }
subprojects { 
    ext {
        compileSdk = rootProject.ext.compileSdkVersion
        minSdk = rootProject.ext.minSdkVersion
        targetSdk = rootProject.ext.targetSdkVersion
    }
    afterEvaluate { subproject ->
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
                defaultConfig {
                    minSdkVersion rootProject.ext.minSdkVersion
                    targetSdkVersion rootProject.ext.targetSdkVersion
                }
            }
        }
    }
}
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.1')
        classpath "com.github.triplet.gradle:play-publisher:3.4.0-agp4.2"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

}   


```

**Hooks.js**

```
import { BeforeAll, Before, AfterAll } from '@cucumber/cucumber';

import { init, cleanup } from 'detox';
import { detox as config } from '../../../package.json';

BeforeAll( { timeout:60 * 1000 }, async () => {
  await init(config, {reuse: true});
});

Before(async () => {
  // I don't want to delete the app as I don't want to delete the app every time I run the test
  await device.launchApp({delete: false, newInstance: true});
});

AfterAll(async () => {
  await cleanup();
});
```
**Cucumber.js**

```
// eslint-disable-next-line no-shadow-restricted-names
const arguments = [
  '--require-module @babel/register',
  'e2e/features/*/*.feature'
].join(' ');

module.exports = {
  default: arguments
}

```

**Package.json:**

```
"scripts": {
        "start": "react-native start",
        "lint": "eslint .",
        "jetify": "npm run jetify",
        "run-android": "react-native run-android",
        "run-android-develop": "react-native run-android --variant develop",
        "run-android-qa": "react-native run-android --variant qa",
        "build-develop": "cd android && ./gradlew app:assembleDevelop",
        "build-qa": "cd android && ./gradlew app:assembleQa",
        "clean": "cd android && ./gradlew clean",
        "print-native-logs": "adb logcat *:S AuditPro:V ReactNative:V",
        "clear-native-logs": "adb logcat -c",
        "start-emulator": "emulator -avd NNSC_API_29",
        "pause-postinstall": "npm run jetify",
        "audit": "npm audit --json | npm-audit-html",
        "detox:build:android-debug": "detox build --configuration android.att.debug",
        "detox:e2e:android-debug": "DETOX_CONFIGURATION=android.att.debug npx cucumber-js",
        "detox:build:android-release": "detox build --configuration android.att.release",
        "detox:e2e:android-release": "DETOX_CONFIGURATION=android.att.release npx cucumber-js" 
    },
```

APK in android studio:

<img width="990" alt="Screenshot 2022-05-23 at 9 18 19 am" src="https://user-images.githubusercontent.com/15376714/169720332-cfa30c55-b1ad-4275-a8fe-d98f47173282.png">

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.6.9
React Native version: 0.64.2
Node version: v18.0
Device model: -
Android version: 8.1
Test-runner (select one): Cucumber

### Detox logs

When I try yarn detox:e2e:android-release --loglevel trace, I get the following error:

```
asb@AnanthaSBs-MacBook-Pro AuditPro % yarn detox:e2e:android-release --loglevel trace
yarn run v1.22.18
$ DETOX_CONFIGURATION=android.att.release npx cucumber-js --loglevel trace
error: unknown option '--loglevel'
error Command failed with exit code 1.
```

I tried to add --loglevel to package.json but it doesn't work either. 

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by Anantha-sb** [comment]
Before I integrated Detox to this project, I was trying to integrate on another project - to learn. 

When I run  `adb shell pm list instrumentation`,  I see that it is still pointing to package of another project. 

`instrumentation:com.pqaa_detox.test/androidx.test.runner.AndroidJUnitRunner (target=com.pqaa_detox)
`

**Comment by Anantha-sb** [comment]
The test apks getting generated were for debug build but I had configured release variant in my configuration file. My issue is resolved, closing this.
