### ISSUE TITLE
[Android] [APP_UNREACHABLE] Detox can't seem to connect to the test app

### ISSUE THREAD

**Issue by ALexander4295502** [wix/Detox#3477]
### Description

I am trying to run the detox test on the android emulator, and here is my `detox.config.js`:
```javascript
apps: {
    android: {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build:
        'cd android ; ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug ; cd -',
    },
  },
```

And the app can be successfully built by running 
```bash
detox build --configuration android
```

However, when I run with 
```
 detox test -c android --loglevel trace --record-logs all
```

I got the following error:
```bash
16:33:00.434 detox[96777] DEBUG: [MOVE_FILE] moving "/private/var/folders/vp/34250lbn0l1f_qb3gv1m7ppxfrch8m/T/8c1dfb90-94a2-426f-a268-1bc3ae170748.detox.log" to artifacts/android.2022-07-07 23-31-56Z/detox_pid_96777.log
16:33:00.434 detox[96777] DEBUG: [MOVE_FILE] moving "/private/var/folders/vp/34250lbn0l1f_qb3gv1m7ppxfrch8m/T/a06b40f0-2148-4526-bd0f-a1751245f7f8.detox.log" to artifacts/android.2022-07-07 23-31-56Z/detox_pid_96777.json.log
16:33:00.436 detox[96777] ERROR: [APP_UNREACHABLE] Detox can't seem to connect to the test app(s)!

HINT:

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs
```

However, I can manually open the app from the emulator after the test failed, which I think means the app is built without errors

My `DetoxTest.java`: https://gist.github.com/ALexander4295502/8169bf936fff1ac3123f0c9efc2ec7a5

Detox output:
https://gist.github.com/ALexander4295502/7579a794aef61b3153a529f8f333c8ca

A complete emulator logcat can be found in: https://gist.github.com/ALexander4295502/2e65893d681c475ba967c27c3672f1e8
Not sure if it is related, but I do find some errors in the logcat:
```bash
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: Cannot load class. Make sure it is in your apk. Class name: 'org.hamcrest.integration.EasyMock2Adapter'. Message: org.hamcrest.integration.EasyMock2Adapter
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: java.lang.ClassNotFoundException: org.hamcrest.integration.EasyMock2Adapter
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.Class.classForName(Native Method)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.Class.forName(Class.java:454)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource.createPackageInfo(ClassPathPackageInfoSource.java:93)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource.access$000(ClassPathPackageInfoSource.java:37)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$1.load(ClassPathPackageInfoSource.java:50)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$1.load(ClassPathPackageInfoSource.java:47)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.SimpleCache.get(SimpleCache.java:32)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.getSubpackages(ClassPathPackageInfoSource.java:230)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.addTopLevelClassesTo(ClassPathPackageInfoSource.java:243)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.getTopLevelClassesRecursive(ClassPathPackageInfoSource.java:237)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.access$100(ClassPathPackageInfoSource.java:214)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource.getTopLevelClassesRecursive(ClassPathPackageInfoSource.java:77)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.suitebuilder.TestGrouping.testCaseClassesInPackage(TestGrouping.java:134)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.suitebuilder.TestGrouping.addPackagesRecursive(TestGrouping.java:110)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.suitebuilder.TestSuiteBuilder.includePackages(TestSuiteBuilder.java:102)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:377)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6726)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.os.Looper.loopOnce(Looper.java:201)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.os.Looper.loop(Looper.java:288)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: Caused by: java.lang.ClassNotFoundException: org.hamcrest.integration.EasyMock2Adapter
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	... 26 more
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/easymock/IArgumentMatcher;
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	... 26 more
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.easymock.IArgumentMatcher" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~LYVlJkz0VyuwXLYongtrmA==/com.vegareactnative.test-kxCOpSHcYHJgz08hxCRJDQ==/base.apk", zip file "/data/app/~~rbFfM_FR7cqnGr00f8PzGw==/com.vegareactnative-8jEBzbaGEVpkEy_NRg-58w==/base.apk"],nativeLibraryDirectories=[/data/app/~~LYVlJkz0VyuwXLYongtrmA==/com.vegareactnative.test-kxCOpSHcYHJgz08hxCRJDQ==/lib/arm64, /data/app/~~rbFfM_FR7cqnGr00f8PzGw==/com.vegareactnative-8jEBzbaGEVpkEy_NRg-58w==/lib/arm64, /data/app/~~LYVlJkz0VyuwXLYongtrmA==/com.vegareactnative.test-kxCOpSHcYHJgz08hxCRJDQ==/base.apk!/lib/arm64-v8a, /data/app/~~rbFfM_FR7cqnGr00f8PzGw==/com.vegareactnative-8jEBzbaGEVpkEy_NRg-58w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-07 16:32:54.393  9330  9330 W ClassPathPackageInfoSource: 	... 26 more
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: Cannot load class. Make sure it is in your apk. Class name: 'org.hamcrest.integration.JMock1Adapter'. Message: org.hamcrest.integration.JMock1Adapter
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: java.lang.ClassNotFoundException: org.hamcrest.integration.JMock1Adapter
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.Class.classForName(Native Method)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.Class.forName(Class.java:454)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource.createPackageInfo(ClassPathPackageInfoSource.java:93)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource.access$000(ClassPathPackageInfoSource.java:37)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$1.load(ClassPathPackageInfoSource.java:50)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$1.load(ClassPathPackageInfoSource.java:47)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.SimpleCache.get(SimpleCache.java:32)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.getSubpackages(ClassPathPackageInfoSource.java:230)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.addTopLevelClassesTo(ClassPathPackageInfoSource.java:243)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.getTopLevelClassesRecursive(ClassPathPackageInfoSource.java:237)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource$ClassPathPackageInfo.access$100(ClassPathPackageInfoSource.java:214)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.ClassPathPackageInfoSource.getTopLevelClassesRecursive(ClassPathPackageInfoSource.java:77)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.suitebuilder.TestGrouping.testCaseClassesInPackage(TestGrouping.java:134)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.suitebuilder.TestGrouping.addPackagesRecursive(TestGrouping.java:110)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.suitebuilder.TestSuiteBuilder.includePackages(TestSuiteBuilder.java:102)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:377)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6726)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.os.Looper.loopOnce(Looper.java:201)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.os.Looper.loop(Looper.java:288)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: Caused by: java.lang.ClassNotFoundException: org.hamcrest.integration.JMock1Adapter
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	... 26 more
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jmock/core/Constraint;
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	... 26 more
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jmock.core.Constraint" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~LYVlJkz0VyuwXLYongtrmA==/com.vegareactnative.test-kxCOpSHcYHJgz08hxCRJDQ==/base.apk", zip file "/data/app/~~rbFfM_FR7cqnGr00f8PzGw==/com.vegareactnative-8jEBzbaGEVpkEy_NRg-58w==/base.apk"],nativeLibraryDirectories=[/data/app/~~LYVlJkz0VyuwXLYongtrmA==/com.vegareactnative.test-kxCOpSHcYHJgz08hxCRJDQ==/lib/arm64, /data/app/~~rbFfM_FR7cqnGr00f8PzGw==/com.vegareactnative-8jEBzbaGEVpkEy_NRg-58w==/lib/arm64, /data/app/~~LYVlJkz0VyuwXLYongtrmA==/com.vegareactnative.test-kxCOpSHcYHJgz08hxCRJDQ==/base.apk!/lib/arm64-v8a, /data/app/~~rbFfM_FR7cqnGr00f8PzGw==/com.vegareactnative-8jEBzbaGEVpkEy_NRg-58w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-07 16:32:54.395  9330  9330 W ClassPathPackageInfoSource: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

### Your environment

Detox version: 19.7.1
React Native version: 0.68.2
Node version: v16.13.2
Device model: Pixel_3a_API_32_arm64-v8a
OS: macOS Monterey (M1)
Test-runner (select one): jest-circus

**Comment by ALexander4295502** [comment]
after some digging up, I am still unable to figure out the solution of the issue above, but I do find a walkaround as below:
1. follow these instructuions to [setup Detox up as a compiling dependency](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#setting-detox-up-as-a-compiling-dependency)
2. Create a detox test class file by following [this link](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#5-create-a-detox-test-class)
