### ISSUE TITLE
Need help running detox tests for android on Github Actions

### ISSUE THREAD

**Issue by longility** [wix/Detox#3510]
### Description

I am able to run this `detox test` for android on my local computer, but not on Github Actions. The iOS works both local and on Github Actions.

**Can I get more ideas to try, guidance or ways to debug this?**

I've tried many different ways, but it all leads to this error:
<details>
  <summary>Error log</summary>

 ```bash
$ detox test -c android.emu.release --cleanup --headless
15:52:30.158 detox[98451] INFO:  [test.js] DETOX_CLEANUP=true DETOX_CONFIGURATION="android.emu.release" DETOX_HEADLESS=true DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1658937150145 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
15:56:03.440 detox[98464] ERROR: [DETOX_INIT_ERROR] 
 ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null
    at ChildProcess.<anonymous> (/Users/runner/work/siren/siren/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: null,
  childProcess: ChildProcess {
    _events: [Object: null prototype] {
      error: [Function (anonymous)],
      close: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 3,
    connected: false,
    signalCode: 'SIGTERM',
    exitCode: null,
    killed: true,
    spawnfile: '/Users/runner/Library/Android/sdk/platform-tools/adb',
    _handle: null,
    spawnargs: [
      '/Users/runner/Library/Android/sdk/platform-tools/adb',
      '-s',
      'emulator-5554',
      'shell',
      'pm',
      'install',
      '-r',
      '-g',
      '-t',
      '/data/local/tmp/detox/Application.apk'
    ],
    pid: 5803,
    stdin: null,
    stdout: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(async_id_symbol)]: 1083,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stderr: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(async_id_symbol)]: 1084,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdio: [ null, [Socket], [Socket] ],
    [Symbol(kCapture)]: false
  },
  stdout: '',
  stderr: ''
}
INFO    | Discarding the changed state: command-line flag
WARNING | Discarding the changed state (command-line flag).
INFO    | Shutting down gRPC endpoint
INFO    | Shutting down gRPC endpoint
INFO    | Closing down rootcanal.
FAIL e2e/smoke-tests/bottom-tab-navigation.spec.ts (435.497 s)
  bottom tab landing
    ✕ Home tab should land on home screen (1 ms)
    ✕ MyChart tab should land on MyChart screen
    ✕ Profile tab should land on profile screen

  ● bottom tab landing › Home tab should land on home screen

    ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)

  ● bottom tab landing › Home tab should land on home screen

    ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)

  ● bottom tab landing › MyChart tab should land on MyChart screen

    ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5[554](https://github.com/inception-health/siren/runs/7543222237?check_suite_focus=true#step:13:558) shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)

  ● bottom tab landing › MyChart tab should land on MyChart screen

    ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-[555](https://github.com/inception-health/siren/runs/7543222237?check_suite_focus=true#step:13:559)4 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)

  ● bottom tab landing › Profile tab should land on profile screen

    ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)

  ● bottom tab landing › Profile tab should land on profile screen

    ChildProcessError: `/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code null

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)

15:59:48.104 detox[98451] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e

error Command failed with exit code 1.
```
</details>

### Your environment

Detox version: 19.7.1
React Native version: 0.63
Node version: 14
Device model: pixel_4
OS: macOS 11.6.8
Test-runner (select one): jest-circus

**Comment by leezumstein** [comment]
We're running into the same issues.  We've tried manually installing the app APK + test APK before launching detox (which installs fine using the same commands), and then using the [`--reuse`](https://wix.github.io/Detox/docs/api/detox-cli#test) flag to tell it to _skip_ trying to install.  We've been able to get the first test suite to pass, since it skips the install step.  However, once it hits any subsequent tests it seems to ignore the `--reuse` option and will try another install, which then seems to timeout.

Also worth noting we had to almost `4x` all of our timeouts to get this working in GitHub actions.  I almost wonder if we could get a configuration option added for the timeout duration for `adb shell pm install` command?

Verbose log from our attempts this morning:

<details>
<summary>Error output</summary>

```
13:52:59.103 detox[18202] DEBUG: [SPAWN_CMD, #98, cpid=33885] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell "logcat -f /sdcard/134555758_15.log"
13:52:59.112 detox[18202] DEBUG: [EXEC_CMD, #99] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell "screencap /sdcard/134555758_16.png"
13:52:59.405 detox[18202] DEBUG: [EXEC_CMD, #100] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell du /sdcard/134555758_15.log
13:53:04.216 detox[18202] DEBUG: [EXEC_CMD, #101] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell "am force-stop <package name>"
13:53:04.345 detox[18202] DEBUG: [EXEC_CMD, #102] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell "pm list packages <package name>"
13:53:04.433 detox[18202] DEBUG: [EXEC_CMD, #103] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 uninstall <package name>
13:53:05.686 detox[18202] DEBUG: [EXEC_CMD, #104] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell "pm list packages <package name>.test"
13:53:06.632 detox[18202] DEBUG: [EXEC_CMD, #105] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 uninstall <package name>.test
13:53:10.670 detox[18202] DEBUG: [EXEC_CMD, #106] "/Users/runner/Library/Android/sdk/build-tools/33.0.0/aapt" dump xmlstrings "/Users/runner/work/<project name>/<project name>/android/app/build/outputs/apk/staging/release/detox-staging-release.apk" AndroidManifest.xml
13:53:10.702 detox[18202] DEBUG: [EXEC_CMD, #107] "/Users/runner/Library/Android/sdk/build-tools/33.0.0/aapt" dump xmlstrings "/Users/runner/work/<project name>/<project name>/android/app/build/outputs/apk/androidTest/staging/release/detox-staging-release-androidTest.apk" AndroidManifest.xml
13:53:10.734 detox[18202] DEBUG: [EXEC_CMD, #108] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell "rm -fr /data/local/tmp/detox"
13:53:10.994 detox[18202] DEBUG: [EXEC_CMD, #109] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 shell "mkdir -p /data/local/tmp/detox"
13:53:11.107 detox[18202] DEBUG: [EXEC_CMD, #110] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-17300 push "/Users/runner/work/<project name>/<project name>/android/app/build/outputs/apk/staging/release/detox-staging-release.apk" "/data/local/tmp/detox/Application.apk"
13:53:13.596 detox[18202] DEBUG: [SPAWN_CMD, #111, cpid=34371] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk
13:53:58.601 detox[18202] DEBUG: [SPAWN_END, #111, cpid=34371] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk terminated with SIGTERM
13:53:58.724 detox[18202] DEBUG: [SPAWN_CMD, #111, cpid=36137] (Retry #1) /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk
13:54:43.726 detox[18202] DEBUG: [SPAWN_END, #111, cpid=36137] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk terminated with SIGTERM
13:54:43.945 detox[18202] DEBUG: [SPAWN_CMD, #111, cpid=37892] (Retry #2) /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk
13:55:28.948 detox[18202] DEBUG: [SPAWN_END, #111, cpid=37892] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk terminated with SIGTERM
13:55:29.263 detox[18202] DEBUG: [SPAWN_CMD, #111, cpid=39648] (Retry #3) /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk
13:56:14.264 detox[18202] DEBUG: [SPAWN_END, #111, cpid=39648] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-17300 shell pm install -r -g -t /data/local/tmp/detox/Application.apk terminated with SIGTERM
```

</details>

**Comment by leezumstein** [comment]
Could we make [detox/src/devices/common/drivers/android/exec/ADB.js#L11](https://github.com/wix/Detox/blob/a8dc9b2b304853ca36e876103bf47910fa5c5451/detox/src/devices/common/drivers/android/exec/ADB.js#L11) configurable?  Would be happy to take a stab at opening a PR for this.

**Comment by longility** [comment]
> We've tried manually installing the app APK + test APK before launching detox (which installs fine using the same commands)

Interesting that it installs fine using the same commands when doing it manually. What is different? I'm seeing if we can uncover the root cause.

**Comment by leezumstein** [comment]
So we were able to get this working by allowing the `INSTALL_TIMEOUT` constant [here](https://github.com/wix/Detox/blob/a8dc9b2b304853ca36e876103bf47910fa5c5451/detox/src/devices/common/drivers/android/exec/ADB.js#L11) to pull from the system environment so we could make it longer.

If you use [`patch-package`](https://github.com/ds300/patch-package), you can apply the following patch to allow detox to grab `DETOX_INSTALL_TIMEOUT` from the environment.  This was for version `19.7.1`.

<details>
<summary>detox+19.7.1.patch</summary>

```patch
diff --git a/node_modules/detox/src/devices/common/drivers/android/exec/ADB.js b/node_modules/detox/src/devices/common/drivers/android/exec/ADB.js
index 6f7b692..afef302 100644
--- a/node_modules/detox/src/devices/common/drivers/android/exec/ADB.js
+++ b/node_modules/detox/src/devices/common/drivers/android/exec/ADB.js
@@ -8,7 +8,9 @@ const { escape } = require('../../../../../utils/pipeCommands');
 const DeviceHandle = require('../tools/DeviceHandle');
 const EmulatorHandle = require('../tools/EmulatorHandle');
 
-const INSTALL_TIMEOUT = 45000; // TODO Double check 45s makes sense
+const {
+  DETOX_INSTALL_TIMEOUT = '45000' // TODO Double check 45s makes sense
+} = process.env;
 
 class ADB {
   constructor() {
@@ -108,7 +110,7 @@ class ADB {
     const command = (apiLvl >= 23)
       ? `install -r -g -t ${apkPath}`
       : `install -rg ${apkPath}`;
-    const result = await this.adbCmdSpawned(deviceId, command, { timeout: INSTALL_TIMEOUT, retries: 3 });
+    const result = await this.adbCmdSpawned(deviceId, command, { timeout: parseInt(DETOX_INSTALL_TIMEOUT, 10), retries: 3 });
 
     const [failure] = (result.stdout || '').match(/^Failure \[.*\]$/m) || [];
     if (failure) {
@@ -124,7 +126,7 @@ class ADB {
     const command = (apiLvl >= 23)
       ? `pm install -r -g -t ${path}`
       : `pm install -rg ${path}`;
-    return this.shellSpawned(deviceId, command, { timeout: INSTALL_TIMEOUT, retries: 3 });
+    return this.shellSpawned(deviceId, command, { timeout: parseInt(DETOX_INSTALL_TIMEOUT, 10), retries: 3 });
   }
 
   async uninstall(deviceId, appId) {

```

</details>

Example step in our workflow running on `macos-12`:

<details>
<summary>Example workflow step</summary>

```yaml
- name: Run Detox Tests
  timeout-minutes: 20
  env:
    DETOX_INSTALL_TIMEOUT: 90000 # allow up to 1.5 minutes to install, for slower CI environment
  run: |
    yarn detox test --configuration android.emu.ci \
      --force-adb-install \
      --loglevel verbose \
      --debug-synchronization 20000 \
      --take-screenshots failing
```
- We seem to have better success using `--force-adb-install` in the CI environment, and omitting this when running on a local dev machine.  However I'm going to be double checking this now that I have tests executing in GitHub.

</details>

Example of our `.detoxrc.json` configuration:

<details>
<summary>.detoxrc.json</summary>

```json
{
    "testRunner": "jest",
    "runnerConfig": "e2e/config.js",
    "skipLegacyWorkersInjection": true,
    "apps": {
      "android": {
        "type": "android.apk",
        "binaryPath": "android/app/build/outputs/apk/release/detox-release.apk",
        "testBinaryPath": "android/app/build/outputs/apk/androidTest/release/detox-release-androidTest.apk",
        "build": "cd android && ./gradlew assembleRelease assembleReleaseAndroidTest -DtestBuildType=release ; cd .."
      }
    },
    "behavior": {
      "init": {
        "reinstallApp": true,
        "exposeGlobals": true
      },
      "cleanup": {
        "shutdownDevice": true
      }
    },
    "devices": {
      "emulator": {
        "type": "android.emulator",
        "device": {
          "avdName": "<emulator avd name>"
        }
      },
      "emulator.ci": {
        "type": "android.emulator",
        "device": {
          "avdName": "<emulator avd name>"
        },
        "bootArgs": "-no-boot-anim -noaudio -camera-back none",
        "headless": true,
        "gpuMode": "swiftshader_indirect",
        "readonly": true,
        "forceAdbInstall": true
      }
    },
    "configurations": {
      "android.emu": {
        "device": "emulator",
        "app": "android"
      },
      "android.emu.ci": {
        "device": "emulator.ci",
        "app": "android"
      }
    }
  }
```

</details>

Log output from that last run that we finally got to pass.  Worth noting it _still times out_ on the first few install attempts, but the subsequent one goes through fine.  There's definitely something weird going on when trying to install the app from detox, or possibly an issue when the emulator first launches.

<details>
<summary>Log output</summary>

```
15:58:20.505 detox[22748] DEBUG: [EXEC_CMD, #3] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "getprop dev.bootcomplete"
15:58:24.133 detox[22748] DEBUG: [EXEC_CMD, #4] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "getprop ro.build.version.sdk"
15:58:25.616 detox[22748] DEBUG: [EXEC_CMD, #5] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "settings put global animator_duration_scale 0"
15:58:28.453 detox[22748] DEBUG: [EXEC_CMD, #6] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "settings put global window_animation_scale 0"
15:58:28.983 detox[22748] DEBUG: [EXEC_CMD, #7] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "settings put global transition_animation_scale 0"
15:58:29.232 detox[22748] DEBUG: [EXEC_CMD, #8] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
15:58:33.065 detox[22748] DEBUG: [EXEC_CMD, #9] "/Users/runner/Library/Android/sdk/build-tools/33.0.0/aapt" dump badging "/Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/BeamDental-detox-staging-release.apk"
15:58:39.916 detox[22748] DEBUG: [EXEC_CMD, #10] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "am force-stop <package name>"
15:58:40.198 detox[22748] DEBUG: [EXEC_CMD, #11] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "pm list packages <package name>"
15:58:40.324 detox[22748] DEBUG: [EXEC_CMD, #12] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "pm list packages <package name>.test"
15:58:40.448 detox[22748] DEBUG: [EXEC_CMD, #13] "/Users/runner/Library/Android/sdk/platform-tools/adb" -s emulator-14260 shell "am force-stop <package name>"
15:58:40.625 detox[22748] DEBUG: [EXEC_CMD, #14] "/Users/runner/Library/Android/sdk/build-tools/33.0.0/aapt" dump xmlstrings "/Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk" AndroidManifest.xml
15:58:40.667 detox[22748] DEBUG: [EXEC_CMD, #15] "/Users/runner/Library/Android/sdk/build-tools/33.0.0/aapt" dump xmlstrings "/Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/androidTest/release/detox-release-androidTest.apk" AndroidManifest.xml
15:58:43.522 detox[22748] DEBUG: [SPAWN_CMD, #16, cpid=23840] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk
16:00:13.519 detox[22748] DEBUG: [SPAWN_END, #16, cpid=23840] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk terminated with SIGTERM
16:00:13.633 detox[22748] DEBUG: [SPAWN_CMD, #16, cpid=26553] (Retry #1) /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk
16:01:43.635 detox[22748] DEBUG: [SPAWN_END, #16, cpid=26553] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk terminated with SIGTERM
16:01:43.851 detox[22748] DEBUG: [SPAWN_CMD, #16, cpid=29075] (Retry #2) /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk
16:02:49.487 detox[22748] DEBUG: [SPAWN_END, #16, cpid=29075] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/release/detox-release.apk exited with code #0
16:02:49.497 detox[22748] DEBUG: [SPAWN_CMD, #17, cpid=31166] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/androidTest/release/detox-release-androidTest.apk
16:02:51.081 detox[22748] DEBUG: [SPAWN_END, #17, cpid=31166] /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-14260 install -r -g -t /Users/runner/work/<repo name>/<repo name>/android/app/build/outputs/apk/androidTest/release/detox-staging-androidTest.apk exited with code #0
```

</details>

**Comment by longility** [comment]
Thank you for sharing your experiences and experiments to allow me to try something new. I'll let you know of progress when I get around to this soon and what I find out. I'm out next couple of weeks so we shall see.

**Comment by longility** [comment]
I had time to at least create a repo for someone else to fork/clone and debug the issue more easily.
Repo: https://github.com/longility/DetoxExpApp
Failing workflow run: https://github.com/longility/DetoxExpApp/actions/runs/2797196014

**Comment by ablok** [comment]
Have the same issue. Follwing.

**Comment by RohovDmytro** [comment]
I spend way to much time trying to fix this issue. My insights:
- patch detox to increase timeouts (as mentioned about)
- pick best gpu for running os
- play with 
- one strange thing, is the test fail to run if I narrow the build architecture to match the OS and Emulator. When I build android app for all available arch I have less weird errors.

This is a journey. This is my NOT final args:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1548235/189656443-2c8afc59-d251-4949-b408-088a970f6683.png">

Currently I'm trying to play with gpu value.

**Comment by d4vidi** [comment]
Hey all. Just a word from us, maintainers: It's unfortunate to hear that Detox doesn't work smoothly with Github actions. That said, we do not currently have the capacity to explore that because we don't use Github actions this way and are not planning to, either. We would therefore appreciate you going verbose and sharing any bit of information you find on this 🙏🏻

**Comment by d4vidi** [comment]
> However, once it hits any subsequent tests it seems to ignore the `--reuse` option and will try another install, which then seems to timeout.

@leezumstein This doesn't make much sense because all argument are rolled into each test file equivalently as environment variables, and are therefore applicable in each test. Also, empirically, the seems wrong.

**Comment by longility** [comment]
still an issue

**Comment by mrk-han** [comment]
Are y'all using this?
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/22263679/201417832-5fafa200-f3a0-4ccf-b596-064f087b927f.png">

**Comment by longility** [comment]
@mrk-han I do recall trying that and no success.

**Comment by dittmarconsulting** [comment]
All these issues get closed but no one helps. I have the same problem for a month now https://github.com/wix/Detox/issues/3711

**Comment by vladimirevstratov** [comment]
Same problem, struggling with detox and github actions.

**Comment by owens-ben** [comment]
Still an issue, but on Bitrise.
