### ISSUE TITLE
Docsaurus publishing keeps failing on CI

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3528]
### What happened?

In at least the last 2 release (probably more), Docusaurus (Detox website) publishing keeps failing due to some technical reasons related to our CI script, even though Detox gets successfully release to NPM alongside the Git tag, as it should:

```


> website@0.0.0 docusaurus /Users/builder/work/website
--
  | > docusaurus "docs:version" "19.x"
  |  
  | [docs]: version 19.x created!
  | git add .
  | git commit -m "Publish docs version 19.x"
  | On branch master
  | Your branch is up to date with 'origin/master'.
  |  
  | Changes not staged for commit:
  | (use "git add <file>..." to update what will be committed)
  | (use "git restore <file>..." to discard changes in working directory)
  | modified:   ../.npmrc
  |  
  | Untracked files:
  | (use "git add <file>..." to include in what will be committed)
  | ../detox-cli/.npmrc
  | ../detox/.npmrc
  |  
  | no changes added to commit (use "git add" and/or "git commit -a")
  | child_process.js:866
  | throw err;
  | ^
  |  
  | Error: Command failed: git commit -m "Publish docs version 19.x"
  | at checkExecSyncError (child_process.js:790:11)
  | at Object.execSync (child_process.js:863:15)
  | at Object.execSync (/Users/builder/work/node_modules/shell-utils/src/exec.js:8:6)
  | at buildDocsForVersion (/Users/builder/work/scripts/utils/releaseDocumentation.js:18:10)
  | at releaseDocsVersion (/Users/builder/work/scripts/utils/publishNewVersion.js:70:3)
  | at publishNewVersion (/Users/builder/work/scripts/utils/publishNewVersion.js:30:5)
  | at versionTagAndPublish (/Users/builder/work/scripts/ci.release.js:52:5)
  | at run (/Users/builder/work/scripts/ci.release.js:18:3)
  | at Object.<anonymous> (/Users/builder/work/scripts/ci.release.js:59:1)
  | at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  | status: 1,
  | signal: null,
  | output: [ null, null, null ],
  | pid: 96152,
  | stdout: null,
  | stderr: null
  | }
  | npm ERR! code ELIFECYCLE
  | npm ERR! errno 1
  | npm ERR! root@19.8.4 release: `node scripts/ci.release.js`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the root@19.8.4 release script.
  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /Users/builder/.npm/_logs/2022-08-03T11_10_51_563Z-debug.log
  | 1
  | cibuild: restoring buildkite workdir: /usr/local/var/buildkite-agent/builds/agent-153/wix-mobile-oss/detox
  | 🚨 Error: The command exited with status 1
  | user command error: exit status 1

```
Source: https://buildkite.com/wix-mobile-oss/detox/builds/983#0182633d-b98e-4cdb-a48f-298bc4c8282d

### Was it tested on latest Detox?

- [ ] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
Solving this should essentially be straightforward (git hard-reset before this runs?) but verifying fix work is gonna be slightly time-consuming due to the relatively long feedback-loop (make changes -> push -> dummy-release on CI ->)

**Comment by noomorph** [comment]
Why can't we put those files under `.gitignore` and that be it?
