### ISSUE TITLE
 Could not parse CLI arguments supported by "jest-cli" package, see the error below

### ISSUE THREAD

**Issue by Faziki** [wix/Detox#3629]
### What happened?

After going throught the documentation and running `detox test --configuration android` it bombs out and gives the following stack trace

```
detox[28124] ERROR: [cli.js] Could not parse CLI arguments supported by "jest-cli" package, see the error below.
detox[28124] ERROR: [cli.js] Error: Cannot find module '\node_modules\jest-cli\build\cli\args.js'
ERROR: [cli.js]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ERROR: [cli.js]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ERROR: [cli.js]     at Module.require (internal/modules/cjs/loader.js:974:19)
ERROR: [cli.js]     at require (internal/modules/cjs/helpers.js:101:18)
ERROR: [cli.js]     at resolveJestCliArgs \node_modules\detox\local-cli\utils\jestInternals.js:52:12)
ERROR: [cli.js]     at getJestBooleanArgs \node_modules\detox\local-cli\utils\splitArgv.js:54:12)
ERROR: [cli.js]     at Object.splitJestArgv [as jest] \node_modules\detox\local-cli\utils\splitArgv.js:91:53)
ERROR: [cli.js]     at prepareJestArgs \node_modules\detox\local-cli\test.js:170:44)
ERROR: [cli.js]     at Object.test [as handler] \node_modules\detox\local-cli\test.js:38:31)
```

### What was the expected behaviour?

It should run the command as expected in the documentation

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Went through the documentation as this is a fresh install of detox after configuring everything and installing the needed packages (jest, detox and setup the configs etc) I ran `detox test --configuration android` and it bombs out sky high giving this error

```
detox[28124] ERROR: [cli.js] Could not parse CLI arguments supported by "jest-cli" package, see the error below.
detox[28124] ERROR: [cli.js] Error: Cannot find module '\node_modules\jest-cli\build\cli\args.js'
ERROR: [cli.js]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ERROR: [cli.js]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ERROR: [cli.js]     at Module.require (internal/modules/cjs/loader.js:974:19)
ERROR: [cli.js]     at require (internal/modules/cjs/helpers.js:101:18)
ERROR: [cli.js]     at resolveJestCliArgs \node_modules\detox\local-cli\utils\jestInternals.js:52:12)
ERROR: [cli.js]     at getJestBooleanArgs \node_modules\detox\local-cli\utils\splitArgv.js:54:12)
ERROR: [cli.js]     at Object.splitJestArgv [as jest] \node_modules\detox\local-cli\utils\splitArgv.js:91:53)
ERROR: [cli.js]     at prepareJestArgs \node_modules\detox\local-cli\test.js:170:44)
ERROR: [cli.js]     at Object.test [as handler] \node_modules\detox\local-cli\test.js:38:31)
```

### In what environment did this happen?

Detox version:  ` "detox": "^19.12.5",`
React Native version: `"react-native": "0.69.4",`
Node version:` v14.20.0`
Device model: Pixel 4
Android version: 12
Test-runner (select one): jest as recommended by the documentation

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
What Jest version? OS: Windows, I assume? Which shell? cmd, powershell, git bash, ...?

**Comment by Faziki** [comment]
`    "jest": ">=27.2.5",
Windows 11
Powershell

**Comment by noomorph** [comment]
but what jest version exactly you have?

пт, 14 жовт. 2022 р. о 14:33 Pieter Uys ***@***.***> пише:

**Comment by Faziki** [comment]
Thats the jest version I have in my package.json

`
 "jest": ">=27.2.5",
 `

**Comment by noomorph** [comment]
but what version do you have in node_modules/jest/package.json ?

пт, 14 жовт. 2022 р. о 14:36 Pieter Uys ***@***.***> пише:

**Comment by Faziki** [comment]
```
{
  "name": "jest",
  "description": "Delightful JavaScript Testing.",
  "version": "29.2.0",
  "main": "./build/index.js",
  "types": "./build/index.d.ts",
  "exports": {
    ".": {
      "types": "./build/index.d.ts",
      "default": "./build/index.js"
    },
    "./package.json": "./package.json",
    "./bin/jest": "./bin/jest.js"
  },
  "dependencies": {
    "@jest/core": "^29.2.0",
    "@jest/types": "^29.2.0",
    "import-local": "^3.0.2",
    "jest-cli": "^29.2.0"
  },
  "devDependencies": {
    "@tsd/typescript": "~4.8.2",
    "tsd-lite": "^0.6.0"
  },
  "peerDependencies": {
    "node-notifier": "^8.0.1 || ^9.0.0 || ^10.0.0"
  },
  "peerDependenciesMeta": {
    "node-notifier": {
      "optional": true
    }
  },
  "bin": "./bin/jest.js",
  "engines": {
    "node": "^14.15.0 || ^16.10.0 || >=18.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/jest.git",
    "directory": "packages/jest"
  },
  "homepage": "https://jestjs.io/",
  "license": "MIT",
  "keywords": [
    "ava",
    "babel",
    "coverage",
    "easy",
    "expect",
    "facebook",
    "immersive",
    "instant",
    "jasmine",
    "jest",
    "jsdom",
    "mocha",
    "mocking",
    "painless",
    "qunit",
    "runner",
    "sandboxed",
    "snapshot",
    "tap",
    "tape",
    "test",
    "testing",
    "typescript",
    "watch"
  ],
  "publishConfig": {
    "access": "public"
  },
  "gitHead": "ee5b37a4f4433afcfffb0356cea47739d8092287"
}
``

**Comment by hh2k** [comment]
I have just installed Detox and I am getting this issue too. On macos same version of jest.

**Comment by noomorph** [comment]
Downgrade to Jest 28.x meanwhile.

**Comment by Faziki** [comment]
> Downgrade to Jest 28.x meanwhile.

How do you install 28 ?

**Comment by Faziki** [comment]
> > Downgrade to Jest 28.x meanwhile.
> 
> How do you install 28 ?

I went to `node_modules/jest/` deleted the node_modules of jest and ran yarn in the jest folder with the version changed to `  "version": "28.0.0",` but I am still getting the same error

```
detox[28124] ERROR: [cli.js] Could not parse CLI arguments supported by "jest-cli" package, see the error below.
detox[28124] ERROR: [cli.js] Error: Cannot find module '\node_modules\jest-cli\build\cli\args.js'
ERROR: [cli.js]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ERROR: [cli.js]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ERROR: [cli.js]     at Module.require (internal/modules/cjs/loader.js:974:19)
ERROR: [cli.js]     at require (internal/modules/cjs/helpers.js:101:18)
ERROR: [cli.js]     at resolveJestCliArgs \node_modules\detox\local-cli\utils\jestInternals.js:52:12)
ERROR: [cli.js]     at getJestBooleanArgs \node_modules\detox\local-cli\utils\splitArgv.js:54:12)
ERROR: [cli.js]     at Object.splitJestArgv [as jest] \node_modules\detox\local-cli\utils\splitArgv.js:91:53)
ERROR: [cli.js]     at prepareJestArgs \node_modules\detox\local-cli\test.js:170:44)
ERROR: [cli.js]     at Object.test [as handler] \node_modules\detox\local-cli\test.js:38:31)
```

**Comment by noomorph** [comment]
> Thats the jest version I have in my package.json
> "jest": ">=27.2.5",

Change it:

```diff
-  "jest": ">=27.2.5",
+  "jest": "28.x.x",
```

**Comment by Faziki** [comment]
> > Thats the jest version I have in my package.json
> > "jest": ">=27.2.5",
> 
> Change it:
> 
> ```diff
> -  "jest": ">=27.2.5",
> +  "jest": "28.x.x",
> ```
> 
> and reinstall your node modules.

Thank you - works

**Comment by noomorph** [comment]
I'll release a fix today to unblock upgrading to Jest 29.x

**Comment by noomorph** [comment]
ETA is 1 hour approx.

**Comment by noomorph** [comment]
See https://github.com/wix/Detox/releases/tag/19.12.6

**Comment by duongyen24** [comment]
I'm facing this issue on 29.3.1 too

**Comment by d4vidi** [comment]
@duongyen24 Please upgrade to the latest Detox (assuming you meant `19.3.1`
