### ISSUE TITLE
Instructions Use Old sdkmanager

### ISSUE THREAD

**Issue by expanship** [wix/Detox#3670]
### What happened?

This is on page https://wix.github.io/Detox/docs/introduction/android-dev-env

Environment: 
-------------------------------------------
Using Mac Pro, version Verntura 13.0
Java 11

Issue: 
-------------------------------------------
The instructions point to use: 

```
$ANDROID_HOME/tools/bin/sdkmanager "system-images;android-28;default;x86_64"
$ANDROID_HOME/tools/bin/sdkmanager --licenses
```

However, I have updated my sdkmanager, which is now at ~/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager . When I try to run the commands pointed at the original path I receive the error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/jav
```

When I run the command using the latest version it works fine. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by jonathanmos** [comment]
Resolved in https://github.com/wix/Detox/pull/3669
