### ISSUE TITLE
[Detox 20] funpermaproxy.callable | undefined is not a function

### ISSUE THREAD

**Issue by kg-currenxie** [wix/Detox#3690]
### What happened?

```
❯ yarn detox build -c ios.staging
yarn run v1.22.17
$ /Users/frexuz/www/currenxie-mobile-react-native/node_modules/.bin/detox build -c ios.staging
/Users/frexuz/www/currenxie-mobile-react-native/node_modules/detox/src/realms/DetoxContext.js:73
  element = funpermaproxy.callable(() => this[symbols.worker].element);
                          ^
TypeError: undefined is not a function
    at DetoxPrimaryContext.<instance_members_initializer> (/Users/frexuz/www/currenxie-mobile-react-native/node_modules/detox/src/realms/DetoxContext.js:73:27)
    at new DetoxContext (/Users/frexuz/www/currenxie-mobile-react-native/node_modules/detox/src/realms/DetoxContext.js:20:14)
    at new DetoxPrimaryContext (/Users/frexuz/www/currenxie-mobile-react-native/node_modules/detox/src/realms/DetoxPrimaryContext.js:31:5)
    at Object.<anonymous> (/Users/frexuz/www/currenxie-mobile-react-native/node_modules/detox/src/realms/primary.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What was the expected behaviour?

Tried follow the Migration instructions. Expecting build/test to work :)

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 20.0.0
React Native version: 0.70.4
Node version: 14.18.1
Test-runner (select one): jest

Also
-    "jest": "29.3.1",
-    "ts-jest": "29.0.3",

### More data, please!

```
{
  "globalSetup": "detox/runners/jest/globalSetup",
  "globalTeardown": "detox/runners/jest/globalTeardown",
  "maxWorkers": 1,
  "preset": "ts-jest",
  "reporters": ["detox/runners/jest/reporter"],
  "setupFilesAfterEnv": ["./init.ts"],
  "testEnvironment": "detox/runners/jest/testEnvironment",
  "testTimeout": 300000,
  "verbose": true
}
```

init.ts
```
import { device } from 'detox'

beforeAll(async () => {
  await device.launchApp()
})

beforeEach(async () => {
  await device.reloadReactNative()
})
```

detox.config.js
```
module.exports = {
  testRunner: {
    $0: 'jest',
    args: {
      config: 'e2e/config.json',
      _: ['e2e'],
    },
  },
  behavior: {
    init: {
      exposeGlobals: process.env.DETOX_EXPOSE_GLOBALS === '0' ? false : true,
    },
  },
  apps: {
    'ios.staging.app': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Release.Staging-iphonesimulator/CX Staging.app',
      build:
        "RN_SRC_EXT=e2e.ts,e2e.tsx,e2e.js xcodebuild -workspace ios/CurrenxieMobileReactNative.xcworkspace -scheme 'CurrenxieMobileReactNative - Release.Staging' -configuration Release.Staging -sdk iphonesimulator -derivedDataPath ios/build -parallelizeTargets -UseModernBuildSystem=YES | xcpretty",
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      headless: process.env.CI ? true : undefined,
      device: {
        type: 'iPhone 13 Pro',
        os: 'iOS 15.2',
      },
    },
  },
  configurations: {
    'ios.staging': {
      device: 'simulator',
      app: 'ios.staging.app',
    },
  },
}
```

```
❯ cat node_modules/funpermaproxy/package.json
{
  "name": "funpermaproxy",
  "version": "1.0.1",
```

**Comment by noomorph** [comment]
Thank you for the report!

The problem can be resolved either by re-creating `yarn.lock` file.
The generic fix is coming:
Thttps://github.com/wix/Detox/pull/3691

**Comment by noomorph** [comment]
Upgrade your Detox dependency to `^20.0.1`.
If the fix does not help, please reopen the issue.
Thanks for the report! 🙏

**Comment by kg-currenxie** [comment]
recreating yarn.lock worked 👌 20.0.1 should too :)

**Comment by d4vidi** [comment]
@kg-currenxie thanks again for the prompt report!
Would you consider adding `currenxie` to our [showcase page](https://wix.github.io/Detox/showcase)? If so, please tap the `join showcase` button 🙏🏻

**Comment by kg-currenxie** [comment]
Hell yeah we would! :)
