### ISSUE TITLE
Can't tap a Touchable

### ISSUE THREAD

**Issue by sinewave440hz** [wix/detox#372]
I have a Dashboard showing a News Feed which is a list of posts. I am trying to tap a button (TouchableOpacity) in the first post. The button has a testID. When I do: ` await element(by.id('morebutton')).tap();` I get an error saying that multiple elements were found with that ID (and a list of the elements), which is of course to be expected. When I change it to: ` await element(by.id('morebutton')).atIndex(0).tap();`, the test fails with a constraints failure: 

```
Error: Cannot perform action due to constraint(s) failure.
    Exception with Action: {
      "Action Name" : "Tap",
      "Element Description" : "<RCTView:0x7f909c194760; AX=Y; AX.id='morebutton'; AX.label=''; AX.frame={{343, 6166.5}, {24, 40}}; AX.activationPoint={355,
6186.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {24, 40}}; opaque; alpha=1>",
      "Failed Constraint(s)" : "interactable",
      "All Constraint(s)" : "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView'))&& (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
      "Recovery Suggestion" : "Adjust element properties so that it matches the failed constraint(s)."
    }

    [
      {
        "Description" : "Cannot perform action due to constraint(s) failure.",
        "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code" : "1",
        "File Name" : "GREYBaseAction.m",
        "Function Name" : "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
        "Line" : "66"
      }
    ]

      at Client._callee8$ (node_modules/detox/lib/client/Client.js:57:19)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:96:21)
      at step (node_modules/detox/lib/client/Client.js:1:836)
      at node_modules/detox/lib/client/Client.js:1:1035
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:95:7)
      at process._tickCallback (internal/process/next_tick.js:161:9)
```

I have debugged the views and found that the accessibility identifier appears to be correctly set for that button, which has this hierarchy: 

```
RCTView
UIView
UIResponder
NSObject
```

So why is this happening and how can I get more information on where/what the issue is?

* Detox: 5.9.1
* Node: 8.1.4
* Device: Simulator iPhone 8
* Xcode: 9.0.1
* macOS: 10.12.6

(Btw the button is enabled and works on manual press)

**Comment by sinewave440hz** [comment]
Any suggestions on how to proceed?
