### ISSUE TITLE
What are the changes to be done in to run detox tests(demo-react-native)with node version 6.9.1

### ISSUE THREAD

**Issue by vivekmveeresh** [wix/detox#378]
#### Detox, Node, Device, Xcode and macOS Versions

* Detox:5.0.0
* Device: iphone 7 simulator
* Xcode:8.3+
* macOS: as specified in requirement

#### Device and verbose Detox logs

  1) "before all" hook: _callee

  0 passing (76ms)
  1 failing

  1)  "before all" hook: _callee:
     TypeError: URL is not a constructor
      at Detox._callee$ (node_modules/detox/lib/Detox.js:57:49)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/detox/lib/Detox.js:1:1379)
      at node_modules/detox/lib/Detox.js:1:1539
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by rotemmiz** [comment]
You'll need to make changes in detox, and parse the URL manually, 
https://github.com/wix/detox/blob/master/detox/src/Detox.js#L57

`require('url').URL` is probably only available from later versions of node.

**Comment by rotemmiz** [comment]
I am closing this issue. We currently support Node 7.6. You are welcome to add support for Node 6.9 through a PR.
