### ISSUE TITLE
Error: Could not find 'Nexus_5_API_25' on the currently ADB attached devices

### ISSUE THREAD

**Issue by skv-headless** [wix/detox#379]
#### Description

I'm trying to launch demo-react-native tests on android.

<img width="1142" alt="screen shot 2017-10-31 at 18 04 21" src="https://user-images.githubusercontent.com/1488195/32227879-f6a3df46-be65-11e7-8c11-726afa91b698.png">

`./emulator -list-avds` returns `Nexus_5_API_25`
`adb devices` shows that device is connected

#### Steps to Reproduce

can reproduce it both on fresh project (can provide repository if needed) and on detox react-native example https://github.com/wix/detox/tree/master/examples/demo-react-native

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.2
* Node: 8.1.4
* Device: android emulator Nexus_5_API_25
* Xcode: 
* macOS: 10.12.6

#### Device and verbose Detox logs
```
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug


detox-server info 17:49:33: server listening on localhost:58046...
  1) "before all" hook

  0 passing (3s)
  1 failing

  1)  "before all" hook:
     Error: Could not find 'Nexus_5_API_25' on the currently ADB attached devices,
      try restarting adb 'adb kill-server && adb start-server'
      at EmulatorDriver._callee3$ (node_modules/detox/lib/devices/EmulatorDriver.js:51:19)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/detox/lib/devices/EmulatorDriver.js:1:809)
      at node_modules/detox/lib/devices/EmulatorDriver.js:1:969
      at <anonymous>



child_process.js:631
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug
    at checkExecSyncError (child_process.js:588:13)
    at Object.execSync (child_process.js:628:13)
    at runMocha (/Users/headless/open_source/detox/examples/demo-react-native/node_modules/detox/local-cli/detox-test.js:56:6)
    at Object.<anonymous> (/Users/headless/open_source/detox/examples/demo-react-native/node_modules/detox/local-cli/detox-test.js:36:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

I would love to provide more details or fix it myself. But it is hard due to compiled code (maybe you have some tip how to debug it)

**Comment by rotemmiz** [comment]
Hey @skv-headless , please add verbose log (the current one is only with default loglevel . add `--loglevel verbose` to your `detox test` command

`node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug
-- loglevel verbose`

**Comment by skv-headless** [comment]
```
detox-server info 10:20:18: server listening on localhost:52709...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"9374ce57-bf30-0aa7-aafa-43e790f00195","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"9374ce57-bf30-0aa7-aafa-43e790f00195","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: /Users/headless/Library/Android/sdk/tools/emulator -list-avds --verbose
detox verb 1: stdout: Nexus_5_API_25
detox verb 1: stdout:
detox verb Emulator stderr:  qemu-system-x86_64: -audio: invalid option
detox verb Emulator stderr:
detox verb Emulator stdout:  emulator: Android virtual device file at: /Users/headless/.android/avd/Nexus_5_API_25.ini
detox verb Emulator stdout:  emulator: virtual device content at /Users/headless/.android/avd/Nexus_5_API_25.avd
detox verb Emulator stdout:  emulator: virtual device config file: /Users/headless/.android/avd/Nexus_5_API_25.avd/config.ini
detox verb Emulator stdout:  emulator: using core hw config path: /Users/headless/.android/avd/Nexus_5_API_25.avd/hardware-qemu.ini
detox verb Emulator stdout:  emulator: Found AVD target API level: 25
detox verb Emulator stdout:  emulator: Read property file at /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//build.prop
detox verb Emulator stdout:  emulator: No boot.prop property file found.
detox verb Emulator stdout:  emulator: found skin 'nexus_5' in directory: /Users/headless/Library/Android/sdk/skins/
detox verb Emulator stdout:  emulator: autoconfig: -skin nexus_5
detox verb Emulator stdout:  emulator: autoconfig: -skindir /Users/headless/Library/Android/sdk/skins/
detox verb Emulator stdout:  emulator: autoconfig: -kernel /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//kernel-ranchu
detox verb Emulator stdout:  emulator: Target arch = 'x86_64'
detox verb Emulator stdout:  emulator: Auto-detect: Kernel image requires new device naming scheme.
detox verb Emulator stdout:  emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
detox verb Emulator stdout:  emulator: autoconfig: -ramdisk /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//ramdisk.img
detox verb Emulator stdout:  emulator: Using initial system image: /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//system.img
detox verb Emulator stdout:  emulator: autoconfig: -data /Users/headless/.android/avd/Nexus_5_API_25.avd/userdata-qemu.img
detox verb Emulator stdout:  emulator: autoconfig: -initdata /Users/headless/.android/avd/Nexus_5_API_25.avd/userdata.img
detox verb Emulator stdout:  emulator: autoconfig: -cache /Users/headless/.android/avd/Nexus_5_API_25.avd/cache.img
detox verb Emulator stdout:  emulator: autoconfig: -sdcard /Users/headless/.android/avd/Nexus_5_API_25.avd/sdcard.img
detox verb Emulator stdout:  emulator: Physical RAM size: 1536MB
detox verb Emulator stdout:
detox verb Emulator stdout:  emulator: VM heap size 64MB is below hardware specified minimum of 384MB,setting it to that value
detox verb Emulator stdout:  emulator: System image is read only
detox verb Emulator stdout:  emulator: GPU emulation enabled using 'host' mode
detox verb Emulator stdout:  emulator: Found 1 DNS servers: 192.168.1.1
detox verb Emulator stdout:  emulator: trying to load skin file '/Users/headless/Library/Android/sdk/skins//nexus_5/layout'
detox verb Emulator stdout:  emulator: CPU Acceleration: working
detox verb Emulator stdout:  emulator: CPU Acceleration status: HAXM version 6.0.5 (3) is installed and usable.
detox verb Emulator stdout:  emulator: Using default value for kernel Contiguous Memory Allocation.
detox verb Emulator stdout:  emulator: Found 1 DNS servers: 192.168.1.1
detox verb Emulator stdout:  Content of hardware configuration file:
detox verb Emulator stdout:    hw.cpu.arch = x86_64
detox verb Emulator stdout:    hw.cpu.ncore = 2
detox verb Emulator stdout:    hw.ramSize = 1536
detox verb Emulator stdout:    hw.screen = multi-touch
detox verb Emulator stdout:    hw.mainKeys = false
detox verb Emulator stdout:    hw.trackBall = false
detox verb Emulator stdout:    hw.keyboard = true
detox verb Emulator stdout:    hw.keyboard.lid = false
detox verb Emulator stdout:    hw.keyboard.charmap = qwerty2
detox verb Emulator stdout:    hw.dPad = false
detox verb Emulator stdout:    hw.gsmModem = true
detox verb Emulator stdout:    hw.gps = true
detox verb Emulator stdout:    hw.battery = true
detox verb Emulator stdout:    hw.accelerometer = true
detox verb Emulator stdout:    hw.audioInput = true
detox verb Emulator stdout:    hw.audioOutput = true
detox verb Emulator stdout:    hw.sdCard = true
detox verb Emulator stdout:    hw.sdCard.path = /Users/headless/.android/avd/Nexus_5_API_25.avd/sdcard.img
detox verb Emulator stdout:    disk.cachePartition = true
detox verb Emulator stdout:    disk.cachePartition.path = /Users/headless/.android/avd/Nexus_5_API_25.avd/cache.img
detox verb Emulator stdout:    disk.cachePartition.size = 66m
detox verb Emulator stdout:    hw.lcd.width = 1080
detox verb Emulator stdout:    hw.lcd.height = 1920
detox verb Emulator stdout:    hw.lcd.depth = 16
detox verb Emulator stdout:    hw.lcd.density = 480
detox verb Emulator stdout:    hw.lcd.backlight = true
detox verb Emulator stdout:    hw.gpu.enabled = true
detox verb Emulator stdout:    hw.gpu.mode = host
detox verb Emulator stdout:    hw.gpu.blacklisted = no
detox verb Emulator stdout:    hw.initialOrientation = Portrait
detox verb Emulator stdout:    hw.camera.back = emulated
detox verb Emulator stdout:    hw.camera.front = emulated
detox verb Emulator stdout:    vm.heapSize = 384
detox verb Emulator stdout:    hw.sensors.light = true
detox verb Emulator stdout:    hw.sensors.pressure = true
detox verb Emulator stdout:    hw.sensors.humidity = true
detox verb Emulator stdout:    hw.sensors.proximity = true
detox verb Emulator stdout:    hw.sensors.magnetic_field = true
detox verb Emulator stdout:    hw.sensors.orientation = true
detox verb Emulator stdout:    hw.sensors.temperature = true
detox verb Emulator stdout:    hw.useext4 = true
detox verb Emulator stdout:    kernel.path = /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//kernel-ranchu
detox verb Emulator stdout:    kernel.newDeviceNaming = yes
detox verb Emulator stdout:    kernel.supportsYaffs2 = no
detox verb Emulator stdout:    disk.ramdisk.path = /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//ramdisk.img
detox verb Emulator stdout:    disk.systemPartition.initPath = /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//system.img
detox verb Emulator stdout:    disk.systemPartition.size = 2g
detox verb Emulator stdout:    disk.dataPartition.path = /Users/headless/.android/avd/Nexus_5_API_25.avd/userdata-qemu.img
detox verb Emulator stdout:    disk.dataPartition.size = 800m
detox verb Emulator stdout:    avd.name = Nexus_5_API_25
detox verb Emulator stdout:  .
detox verb Emulator stdout:  QEMU options list:
detox verb Emulator stdout:  emulator: argv[00] = "/Users/headless/Library/Android/sdk/tools/qemu/darwin-x86_64/qemu-system-x86_64"
detox verb Emulator stdout:  emulator: argv[01] = "-audio"
detox verb Emulator stdout:  emulator: argv[02] = "none"
detox verb Emulator stdout:  emulator: argv[03] = "-dns-server"
detox verb Emulator stdout:  emulator: argv[04] = "192.168.1.1"
detox verb Emulator stdout:  emulator: argv[05] = "-serial"
detox verb Emulator stdout:  emulator: argv[06] = "null"
detox verb Emulator stdout:  emulator: argv[07] = "-enable-hax"
detox verb Emulator stdout:  emulator: argv[08] = "-smp"
detox verb Emulator stdout:  emulator: argv[09] = "cores=6597069766658"
detox verb Emulator stdout:  emulator: argv[10] = "-m"
detox verb Emulator stdout:  emulator: argv[11] = "1536"
detox verb Emulator stdout:  emulator: argv[12] = "-append"
detox verb Emulator stdout:  emulator: argv[13] = "qemu=1 androidboot.hardware=ranchu clocksource=pit android.qemud=1 console=0 console=0 android.checkjni=1 qemu.gles=1"
detox verb Emulator stdout:  emulator: argv[14] = "-lcd-density"
detox verb Emulator stdout:  emulator: argv[15] = "480"
detox verb Emulator stdout:  emulator: argv[16] = "-kernel"
detox verb Emulator stdout:  emulator: argv[17] = "/Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//kernel-ranchu"
detox verb Emulator stdout:  emulator: argv[18] = "-initrd"
detox verb Emulator stdout:  emulator: argv[19] = "/Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//ramdisk.img"
detox verb Emulator stdout:  emulator: argv[20] = "-drive"
detox verb Emulator stdout:  emulator: argv[21] = "if=none,index=0,id=system,file=/Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//system.img,read-only"
detox verb Emulator stdout:  emulator: argv[22] = "-device"
detox verb Emulator stdout:  emulator: argv[23] = "virtio-blk-pci,drive=system"
detox verb Emulator stdout:  emulator: argv[24] = "-drive"
detox verb Emulator stdout:  emulator: argv[25] = "if=none,index=1,id=cache,file=/Users/headless/.android/avd/Nexus_5_API_25.avd/cache.img"
detox verb Emulator stdout:  emulator: argv[26] = "-device"
detox verb Emulator stdout:  emulator: argv[27] = "virtio-blk-pci,drive=cache"
detox verb Emulator stdout:  emulator: argv[28] = "-drive"
detox verb Emulator stdout:  emulator: argv[29] = "if=none,index=2,id=userdata,file=/Users/headless/.android/avd/Nexus_5_API_25.avd/userdata-qemu.img"
detox verb Emulator stdout:  emulator: argv[30] = "-device"
detox verb Emulator stdout:  emulator: argv[31] = "virtio-blk-pci,drive=userdata"
detox verb Emulator stdout:  emulator: argv[32] = "-drive"
detox verb Emulator stdout:  emulator: argv[33] = "if=none,index=3,id=sdcard,file=/Users/headless/.android/avd/Nexus_5_API_25.avd/sdcard.img"
detox verb Emulator stdout:  emulator: argv[34] = "-device"
detox verb Emulator stdout:  emulator: argv[35] = "virtio-blk-pci,drive=sdcard"
detox verb Emulator stdout:  emulator: argv[36] = "-netdev"
detox verb Emulator stdout:  emulator: argv[37] = "user,id=mynet"
detox verb Emulator stdout:  emulator: argv[38] = "-device"
detox verb Emulator stdout:  emulator: argv[39] = "virtio-net-pci,netdev=mynet"
detox verb Emulator stdout:  emulator: argv[40] = "-show-cursor"
detox verb Emulator stdout:  emulator: argv[41] = "-L"
detox verb Emulator stdout:  emulator: argv[42] = "/Users/headless/Library/Android/sdk/tools/lib/pc-bios"
detox verb Emulator stdout:  emulator: argv[43] = "-vga"
detox verb Emulator stdout:  emulator: argv[44] = "none"
detox verb Emulator stdout:  emulator: argv[45] = "-android-hw"
detox verb Emulator stdout:  emulator: argv[46] = "/tmp/android-headless/emulator-vhoAO2"
detox verb Emulator stdout:  Concatenated QEMU options:
detox verb Emulator stdout:   /Users/headless/Library/Android/sdk/tools/qemu/darwin-x86_64/qemu-system-x86_64 -audio none -dns-server 192.168.1.1 -serial null -enable-hax -smp cores=6597069766658 -m 1536 -append 'qemu=1 androidboot.hardware=ranchu clocksource=pit android.qemud=1 console=0 console=0 android.checkjni=1 qemu.gles=1' -lcd-density 480 -kernel /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//kernel-ranchu -initrd /Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//ramdisk.img -drive if=none,index=0,id=system,file=/Users/headless/Library/Android/sdk/system-images/android-25/google_apis/x86_64//system.img,read-only -device virtio-blk-pci,drive=system -drive if=none,index=1,id=cache,file=/Users/headless/.android/avd/Nexus_5_API_25.avd/cache.img -device virtio-blk-pci,drive=cache -drive if=none,index=2,id=userdata,file=/Users/headless/.android/avd/Nexus_5_API_25.avd/userdata-qemu.img -device virtio-blk-pci,drive=userdata -drive if=none,index=3,id=sdcard,file=/Users/headless/.android/avd/Nexus_5_API_25.avd/sdcard.img -device virtio-blk-pci,drive=sdcard -netdev user,id=mynet -device virtio-net-pci,netdev=mynet -show-cursor -L /Users/headless/Library/Android/sdk/tools/lib/pc-bios -vga none -android-hw /tmp/android-headless/emulator-vhoAO2
detox verb Emulator stdout:  emulator: Starting QEMU main loop
detox verb Emulator stdout:  emulator: Done with QEMU main loop
detox verb Emulator stdout:  emulator: User-config was not changed.
detox verb Emulator stdout:
detox verb 2: /Users/headless/Library/Android/sdk/platform-tools/adb  devices
detox verb 2: stdout: List of devices attached
detox verb 2: stdout: emulator-5554	device
detox verb 2: stdout:
detox verb 2: stdout:
child_process.js:631
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose
    at checkExecSyncError (child_process.js:588:13)
    at Object.execSync (child_process.js:628:13)
    at runMocha (/Users/headless/open_source/detox/examples/demo-react-native/node_modules/detox/local-cli/detox-test.js:56:6)
    at Object.<anonymous> (/Users/headless/open_source/detox/examples/demo-react-native/node_modules/detox/local-cli/detox-test.js:36:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

**Comment by skv-headless** [comment]
@rotemmiz It is working on new emulator. Thank you. You are awesome!

**Comment by linhnh123** [comment]
Hi @skv-headless ,
How to fix it ?

**Comment by skv-headless** [comment]
Just created a new virtual machine

**Comment by linhnh123** [comment]
I tried, but still has the same error. I'm using Android Studio to create a new virtual machine.

**Comment by ghsdh3409** [comment]
@linhnh123 Please check this pull request https://github.com/wix/detox/pull/447.
