### ISSUE TITLE
Detox crashes in 95% of runs when an action is being performed after a `waitFor(element).toBeVisible.whileElement().scroll()`

### ISSUE THREAD

**Issue by yurijmikhalevich** [wix/Detox#3805]
### What happened?

Detox crashes in 95% of runs when an action is being performed after a `waitFor(element).toBeVisible.whileElement().scroll()`.

### What was the expected behaviour?

No crash. The same test suite runs on iOS without any issues.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.1.0
React Native version: 0.70.6
Node version: 16.13.2
Device model: Android Emulator - Pixel 4a API 30
Android version: 11
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
  error: The app has crashed, see the details below:

  @Thread detox.secondary(1152):
  java.lang.AbstractMethodError: abstract method "java.util.Map com.wix.detox.espresso.idlingresources.DescriptiveIdlingResource.getBusyHint()"
  	at com.wix.detox.inquiry.DetoxBusyResource$BusyIdlingResource.getIRDescription(DetoxBusyResource.kt:26)
  	at com.wix.detox.inquiry.DetoxBusyResource$BusyIdlingResource.getDescription(DetoxBusyResource.kt:13)
  	at com.wix.detox.adapters.server.QueryStatusActionHandler.formatStatus(QueryStatusActionHandler.kt:25)
  	at com.wix.detox.adapters.server.QueryStatusActionHandler.handle(QueryStatusActionHandler.kt:14)
  	at com.wix.detox.DetoxMain$initActionHandlers$2$1.handle(DetoxMain.kt:87)
  	at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:64)
  	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
  	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:8)
  	at android.os.Handler.handleCallback(Handler.java:938)
  	at android.os.Handler.dispatchMessage(Handler.java:99)
  	at android.os.Looper.loop(Looper.java:223)
  	at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:50)
  	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
  	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
  	at java.lang.Thread.run(Thread.java:923)
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by yurijmikhalevich** [comment]
Updating detox to 20.1.1 seems to fix this issue.
