### ISSUE TITLE
ios.none configuration type seems broken

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#381]
Trying to debug detox, I ran `detox run-server`, started the test app from Xcode and ran `detox test —configuration ios.none`.

Got the following error:
```
Leo-Natans-Wix-MPB:test lnatan$ detox test --configuration ios.none --loglevel verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.none --loglevel verbose    


detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"test","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"test","role":"tester"},"messageId":0}
detox verb ws  
  1) "before all" hook

  0 passing (55ms)
  1 failing

  1)  "before all" hook:
     TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.join (path.js:1211:7)
      at Device._getAbsolutePath (/Users/lnatan/Desktop/Code/detox/detox/src/devices/Device.js:198:26)
      at Device.prepare (/Users/lnatan/Desktop/Code/detox/detox/src/devices/Device.js:19:29)
      at Detox.init (/Users/lnatan/Desktop/Code/detox/detox/src/Detox.js:70:23)
      at process._tickCallback (internal/process/next_tick.js:103:7)



child_process.js:533
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.none --loglevel verbose    
    at checkExecSyncError (child_process.js:490:13)
    at Object.execSync (child_process.js:530:13)
    at runMocha (/Users/lnatan/Desktop/Code/detox/detox/local-cli/detox-test.js:56:6)
    at Object.<anonymous> (/Users/lnatan/Desktop/Code/detox/detox/local-cli/detox-test.js:36:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: Latest tip
* Node: v7.6.0
* Device: iOS 11.1
* Xcode: Xcode 9.1
* macOS: 10.13.2 beta 1

**Comment by LeoNatan** [comment]
A workaround is to add `”binaryPath”: “ios”`

**Comment by LeoNatan** [comment]
Guys come on! It has been 20 days!

😂

**Comment by noomorph** [comment]
@LeoNatan, is this issue relevant? Could you test on `12.4.0`? If still yes, maybe you might add more details? Or let's just close it?

**Comment by LeoNatan** [comment]
ios.none should not require a `binaryPath` in the config in order to run. The bug is that the JS code fails if that key is not found. 

Here is the issue:
https://github.com/wix/Detox/blob/6c73108a223de3f6a18b36fb3339b79ce8832376/detox/src/devices/drivers/SimulatorDriver.js#L110
