### ISSUE TITLE
DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxSecondaryContext). when running on detox-typescript-expo

### ISSUE THREAD

**Issue by MilanJimi** [wix/Detox#3832]
### Description

I want to test an Expo app with Detox v20.1.1 in Typescript. I have been following multiple guides, but they all seem kind of outdated. Right now, I have managed to get the test to start, but I get this error:
```
    DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxSecondaryContext).

    HINT: If you are using Detox with Jest according to the latest guide, please report this issue on our GitHub tracker:
    https://github.com/wix/Detox/issues
    Otherwise, make sure you call detox.installWorker() beforehand.

      3 | describe('Example', () => {
      4 |   beforeAll(async () => {
    > 5 |     await device.launchApp()
        |                  ^
      6 |   })
      7 |
      8 |   beforeEach(async () => {
```
Do you know what's that all about? I wanted to use detox.init(), but that is no longer defined. Shouldn't this be covered in `globalSetup` that I define in `jest.config.js`?

detoxrc:
```
/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      args: {
        config: 'test/e2e/jest.config.js',
      },
    },
    jest: {
      setupTimeout: 120000,
    },
  },
  apps: {
    ios: {
      type: 'ios.app',
      binaryPath: 'bin/Exponent.app',
      build: 'npm run ios',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone SE (3rd generation)',
      },
    },
  },
  configurations: {
    'ios.sim': {
      device: 'simulator',
      app: 'ios',
    },
  },
}
```

test/e2e/jest.config.js
```
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '..',
  testMatch: ['<rootDir>/**/*.test.ts'],
  testTimeout: 120000,
  maxWorkers: 1,
  reporters: ['detox/runners/jest/reporter'],
  globalSetup: 'detox/runners/jest/globalSetup',
  globalTeardown: 'detox/runners/jest/globalTeardown',
  verbose: true,
}
```

Please help :( 

### Your environment

Detox version: 20.1.1
React Native version: 0.69.6
Node version: v16.15.0
Device model: iOS
OS: iOS
Test-runner (select one): jest

**Comment by noomorph** [comment]
Test environment is incorrect ``testEnvironment: 'node'` – please use the one that Detox provides.

**Comment by noomorph** [comment]
Btw, what was the most helpful guide so far? Which ones were outdates?

**Comment by MilanJimi** [comment]
I just updated to `  testEnvironment: 'detox/runners/jest/testEnvironment',` - same error :( 

I went mostly by 3rd party, since I want to test Expo, and Wix doesn't provide expo coverage.

**Comment by noomorph** [comment]
Could you run `detox test ... --record-logs all` and send me `artifacts/.../detox.trace.json` ?

**Comment by noomorph** [comment]
@MilanJimi I assume you used this one, right? https://docs.expo.dev/build-reference/e2e-tests/

**Comment by MilanJimi** [comment]
detox test --configuration ios.sim --record-logs all
```
[
	{"ph":"M","args":{"name":"primary"},"ts":1673446450442000,"tid":0,"pid":91277,"name":"process_name"},
	{"ph":"M","args":{"sort_index":0},"ts":1673446450442000,"tid":0,"pid":91277,"name":"process_sort_index"},
	{"ph":"M","args":{"name":"lifecycle"},"ts":1673446450442000,"tid":0,"pid":91277,"name":"thread_name"},
	{"ph":"M","args":{"sort_index":0},"ts":1673446450442000,"tid":0,"pid":91277,"name":"thread_sort_index"},
	{"ph":"B","name":"node_modules/.bin/detox test --configuration ios.sim --record-logs all","pid":91277,"tid":0,"cat":"lifecycle","ts":1673446450442000,"args":{"level":10,"cwd":"<redacted>/mobile","data":{"id":"1449e6bc-ded3-29eb-c367-916e3d911fc1","detoxConfig":{"configurationName":"ios.sim","apps":{"default":{"type":"ios.app","binaryPath":"bin/Exponent.app","build":"npm run ios"}},"artifacts":{"rootDir":"artifacts/ios.sim.2023-01-11 14-14-10Z","plugins":{"log":{"enabled":true,"keepOnlyFailedTestsArtifacts":false},"screenshot":{"enabled":true,"shouldTakeAutomaticSnapshots":false,"keepOnlyFailedTestsArtifacts":false},"video":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"instruments":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"uiHierarchy":{"enabled":false,"keepOnlyFailedTestsArtifacts":false}}},"behavior":{"init":{"keepLockFile":false,"reinstallApp":true,"exposeGlobals":true},"cleanup":{"shutdownDevice":false},"launchApp":"auto"},"cli":{"recordLogs":"all","configuration":"ios.sim"},"device":{"type":"ios.simulator","device":{"type":"iPhone SE (3rd generation)"}},"logger":{"level":"info","overrideConsole":true,"options":{"showLoggerName":true,"showPid":true,"showLevel":false,"showMetadata":false,"basepath":"<redacted>/mobile/node_modules/detox/src","prefixers":{},"stringifiers":{}}},"testRunner":{"retries":0,"forwardEnv":false,"bail":false,"jest":{"setupTimeout":120000,"teardownTimeout":30000,"retryAfterCircusRetries":false,"reportWorkerAssign":true},"args":{"$0":"jest","_":[],"args":{"config":"test/e2e/jest.config.js"},"--":[]}},"session":{"autoStart":true,"debugSynchronization":10000}},"detoxIPCServer":"primary-91277","testResults":[],"testSessionIndex":0,"workersCount":0},"v":0}},
	{"ph":"M","args":{"name":"ipc"},"ts":1673446450446000,"tid":1,"pid":91277,"name":"thread_name"},
	{"ph":"M","args":{"sort_index":1},"ts":1673446450446000,"tid":1,"pid":91277,"name":"thread_sort_index"},
	{"ph":"i","name":"Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/detox.primary-91277","pid":91277,"tid":1,"cat":"ipc,ipc-server","ts":1673446450446000,"args":{"level":10,"v":0}},
	{"ph":"i","name":"starting server on  /tmp/detox.primary-91277 ","pid":91277,"tid":1,"cat":"ipc,ipc-server","ts":1673446450446000,"args":{"level":10,"v":0}},
	{"ph":"i","name":"starting TLS server false","pid":91277,"tid":1,"cat":"ipc,ipc-server","ts":1673446450447000,"args":{"level":10,"v":0}},
	{"ph":"i","name":"starting server as Unix || Windows Socket","pid":91277,"tid":1,"cat":"ipc,ipc-server","ts":1673446450447000,"args":{"level":10,"v":0}},
	{"ph":"M","args":{"name":"ws-server"},"ts":1673446450450000,"tid":2,"pid":91277,"name":"thread_name"},
	{"ph":"M","args":{"sort_index":2},"ts":1673446450450000,"tid":2,"pid":91277,"name":"thread_sort_index"},
	{"ph":"i","name":"Detox server listening on localhost:55645...","pid":91277,"tid":2,"cat":"ws-server,ws","ts":1673446450450000,"args":{"level":20,"v":0}},
	{"ph":"i","name":"Serialized the session state at: /private/var/folders/mj/117y860d4mg_799yr9_4hdcw0000gn/T/1449e6bc-ded3-29eb-c367-916e3d911fc1.detox.json","pid":91277,"tid":0,"cat":"lifecycle","ts":1673446450452000,"args":{"level":10,"v":0}},
	{"ph":"B","name":"jest --args.config test/e2e/jest.config.js","pid":91277,"tid":0,"cat":"lifecycle,cli","ts":1673446450452000,"args":{"level":30,"env":{},"v":0}},
	{"ph":"E","pid":91277,"tid":0,"cat":"lifecycle,cli","ts":1673446451220000,"args":{"level":50,"success":false,"code":1,"signal":null,"v":0}},
	{"ph":"i","name":"Detox server has been closed gracefully","pid":91277,"tid":2,"cat":"ws-server,ws","ts":1673446451221000,"args":{"level":20,"v":0}},
	{"ph":"E","pid":91277,"tid":0,"cat":"lifecycle","ts":1673446451222000,"args":{"level":10,"v":0}}
]
```

**Comment by noomorph** [comment]
1. Please run `detox test ... --showConfig` and paste Jest config resolved.

2. Please run `detox test ... -l trace --no-color` and paste here the detailed log.

Thanks!

**Comment by MilanJimi** [comment]
Config
```
{
  "configs": [
    {
      "automock": false,
      "cache": true,
      "cacheDirectory": "/private/var/folders/mj/117y860d4mg_799yr9_4hdcw0000gn/T/jest_dx",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "cwd": "<Redacted>/mobile",
      "detectLeaks": false,
      "detectOpenHandles": false,
      "errorOnDeprecated": false,
      "extensionsToTreatAsEsm": [],
      "fakeTimers": {
        "enableGlobally": false
      },
      "forceCoverageMatch": [],
      "globals": {},
      "haste": {
        "computeSha1": false,
        "enableSymlinks": false,
        "forceNodeFilesystemAPI": true,
        "throwOnModuleCollision": false
      },
      "id": "d751c937b350e4a614bcaad12426b9b1",
      "injectGlobals": true,
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "js",
        "mjs",
        "cjs",
        "jsx",
        "ts",
        "tsx",
        "json",
        "node"
      ],
      "moduleNameMapper": [],
      "modulePathIgnorePatterns": [],
      "prettierPath": "prettier",
      "resetMocks": false,
      "resetModules": false,
      "restoreMocks": false,
      "rootDir": "<Redacted>/mobile",
      "roots": [
        "<Redacted>/mobile"
      ],
      "runner": "<Redacted>/mobile/node_modules/jest-runner/build/index.js",
      "sandboxInjectedGlobals": [],
      "setupFiles": [],
      "setupFilesAfterEnv": [],
      "skipFilter": false,
      "slowTestThreshold": 5,
      "snapshotFormat": {
        "escapeString": false,
        "printBasicPrototype": false
      },
      "snapshotSerializers": [],
      "testEnvironment": "<Redacted>/mobile/node_modules/jest-environment-node/build/index.js",
      "testEnvironmentOptions": {},
      "testLocationInResults": false,
      "testMatch": [
        "**/__tests__/**/*.[jt]s?(x)",
        "**/?(*.)+(spec|test).[tj]s?(x)"
      ],
      "testPathIgnorePatterns": [
        "/node_modules/"
      ],
      "testRegex": [],
      "testRunner": "<Redacted>/mobile/node_modules/jest-circus/runner.js",
      "transform": [
        [
          "\\.[jt]sx?$",
          "<Redacted>/mobile/node_modules/babel-jest/build/index.js",
          {}
        ]
      ],
      "transformIgnorePatterns": [
        "/node_modules/",
        "\\.pnp\\.[^\\/]+$"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": 0,
    "changedFilesWithAncestor": false,
    "ci": false,
    "collectCoverage": false,
    "collectCoverageFrom": [],
    "coverageDirectory": "<Redacted>/mobile/coverage",
    "coverageProvider": "babel",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "detectLeaks": false,
    "detectOpenHandles": false,
    "errorOnDeprecated": false,
    "expand": false,
    "findRelatedTests": false,
    "forceExit": false,
    "json": false,
    "lastCommit": false,
    "listTests": false,
    "logHeapUsage": false,
    "maxConcurrency": 5,
    "maxWorkers": 7,
    "noStackTrace": false,
    "nonFlagArgs": [],
    "notify": false,
    "notifyMode": "failure-change",
    "onlyChanged": false,
    "onlyFailures": false,
    "passWithNoTests": false,
    "projects": [],
    "rootDir": "<Redacted>/mobile",
    "runTestsByPath": false,
    "seed": 702188501,
    "skipFilter": false,
    "snapshotFormat": {
      "escapeString": false,
      "printBasicPrototype": false
    },
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testSequencer": "<Redacted>/mobile/node_modules/@jest/test-sequencer/build/index.js",
    "updateSnapshot": "new",
    "useStderr": false,
    "watch": false,
    "watchAll": false,
    "watchman": true
  },
  "version": "29.3.1"
}
```
trace
```
12:18:06.636 detox[5707] B lifecycle node_modules/.bin/detox test --configuration ios.sim -l trace --no-color
  data: {
    "id": "9face35b-bec0-4a30-4631-07e5847aa430",
    "detoxConfig": {
      "configurationName": "ios.sim",
      "apps": {
        "default": {
          "type": "ios.app",
          "binaryPath": "bin/Exponent.app",
          "build": "npm run ios"
        }
      },
      "artifacts": {
        "rootDir": "artifacts/ios.sim.2023-01-12 11-18-06Z",
        "plugins": {
          "log": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "screenshot": {
            "enabled": true,
            "shouldTakeAutomaticSnapshots": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "video": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "instruments": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "uiHierarchy": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          }
        }
      },
      "behavior": {
        "init": {
          "keepLockFile": false,
          "reinstallApp": true,
          "exposeGlobals": true
        },
        "cleanup": {
          "shutdownDevice": false
        },
        "launchApp": "auto"
      },
      "cli": {
        "configuration": "ios.sim",
        "loglevel": "trace"
      },
      "device": {
        "type": "ios.simulator",
        "device": {
          "type": "iPhone SE (3rd generation)"
        }
      },
      "logger": {
        "level": "trace",
        "overrideConsole": true,
        "options": {
          "showLoggerName": true,
          "showPid": true,
          "showLevel": false,
          "showMetadata": false,
          "basepath": "<Redacted>/mobile/node_modules/detox/src",
          "prefixers": {},
          "stringifiers": {}
        }
      },
      "testRunner": {
        "retries": 0,
        "forwardEnv": false,
        "bail": false,
        "jest": {
          "setupTimeout": 120000,
          "teardownTimeout": 30000,
          "retryAfterCircusRetries": false,
          "reportWorkerAssign": true
        },
        "args": {
          "$0": "jest",
          "_": [],
          "args": {
            "config": "test/e2e/jest.config.js"
          },
          "no-color": true,
          "--": []
        }
      },
      "session": {
        "autoStart": true,
        "debugSynchronization": 10000
      }
    },
    "detoxIPCServer": "primary-5707",
    "testResults": [],
    "testSessionIndex": 0,
    "workersCount": 0
  }
12:18:06.644 detox[5707] i ipc Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/detox.primary-5707
12:18:06.645 detox[5707] i ipc starting server on  /tmp/detox.primary-5707 
12:18:06.645 detox[5707] i ipc starting TLS server false
12:18:06.645 detox[5707] i ipc starting server as Unix || Windows Socket
12:18:06.649 detox[5707] i ws-server Detox server listening on localhost:50021...
12:18:06.651 detox[5707] i lifecycle Serialized the session state at: /private/var/folders/mj/117y860d4mg_799yr9_4hdcw0000gn/T/9face35b-bec0-4a30-4631-07e5847aa430.detox.json
12:18:06.652 detox[5707] B lifecycle jest --args.config test/e2e/jest.config.js --no-color
FAIL test/e2e/starter.test.ts
  Example
    ✕ should have welcome screen

  ● Example › should have welcome screen

    DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxSecondaryContext).

    HINT: If you are using Detox with Jest according to the latest guide, please report this issue on our GitHub tracker:
    https://github.com/wix/Detox/issues
    Otherwise, make sure you call detox.installWorker() beforehand.

      3 | describe('Example', () => {
      4 |   beforeAll(async () => {
    > 5 |     await device.launchApp()
        |                  ^
      6 |   })
      7 |
      8 |   beforeEach(async () => {

      at DetoxSecondaryContext.get [worker] (node_modules/detox/src/realms/DetoxContext.js:117:13)
      at node_modules/detox/src/realms/DetoxContext.js:72:36
      at getter (node_modules/funpermaproxy/lib/permaproxy.js:10:24)
      at Object.get (node_modules/funpermaproxy/lib/permaproxy.js:21:22)
      at Object.launchApp (test/e2e/starter.test.ts:5:18)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.304 s, estimated 1 s
Ran all test suites.
12:18:07.261 detox[5707] E lifecycle Command failed with exit code = 1:
jest --args.config test/e2e/jest.config.js --no-color
12:18:07.262 detox[5707] i ws-server Detox server has been closed gracefully
12:18:07.263 detox[5707] E lifecycle node_modules/.bin/detox test --configuration ios.sim -l trace --no-color
```

**Comment by noomorph** [comment]
```diff
    args: {
      $0: 'jest',
-      args: {
        config: 'test/e2e/jest.config.js',
-      },
    },
```

@MilanJimi

**Comment by MilanJimi** [comment]
Yeah, that does it :D I had the sneaking suspicion it was something in the config.

Thanks a lot!

**Comment by noomorph** [comment]
Does it run your app now? I was just wondering what guide you used primarily - in case if it was Expo's official one, maybe you could contribute and update their E2E guide?

**Comment by MilanJimi** [comment]
I now can launch Expo, which is nice, but I still need to figure out how to reload the app - however that's an Expo problem, not a Detox problem. I'll be able to contribute once I get that sorted.

**Comment by tiagoacastro** [comment]
Has any fix been found for this error?
