### ISSUE TITLE
Detox tests running locally but not in CI/CD pipeline

### ISSUE THREAD

**Issue by alyssaw90** [wix/Detox#3842]
### Description

When running our detox tests locally everything is working as expected. When running the detox test via the Azure pipeline we get a timeout error (see below). The pipeline has worked in the past, but it is now broken. We have used the troubleshooting guidelines but could use some recommendations on what the issue could be. Is it because of the React Native version we are using? Do we need to upgrade our detox version? What versions of React Native does detox support? 

------------

```
23:45:39.016 detox[66548] INFO:  [test.js] mocha --config e2e/.mocharc.json --cleanup --configuration ios.sim.release --grep :android: --invert --artifacts-location /Users/runner/work/1/TestResults/artifacts/ --record-logs all --record-videos all --take-screenshots all --use-custom-logger true e2e


23:49:38.955 detox[66552] INFO:  [AppleSimUtils.js] com.microsoft.mymsft launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 63A63B15-4DBA-41CC-B2A4-373DE87483F2 log stream --level debug --style compact --predicate 'process == "mymicrosoft"'
23:49:43.542 detox[66552] WARN:  [DetoxConnection.js/ERROR, #49673] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  type: 'AppWillTerminateWithError',
  params: [Object],
  messageId: -10000
}
23:49:48.487 detox[66552] WARN:  [DetoxConnection.js/ERROR, #49673] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  messageId: -10000,
  type: 'AppWillTerminateWithError',
  params: [Object]
}
  1) "before all" hook in "{root}"
23:50:39.964 detox[66552] ERROR: [APP_UNREACHABLE] Detox can't seem to connect to the test app(s)!

HINT: 

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs 




  0 passing (5m)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)



23:50:44.329 detox[66548] ERROR: [cli.js] Command failed: mocha --config e2e/.mocharc.json --cleanup --configuration ios.sim.release --grep :android: --invert --artifacts-location /Users/runner/work/1/TestResults/artifacts/ --record-logs all --record-videos all --take-screenshots all --use-custom-logger true e2e

##[error]Bash exited with code '1'.
```

### Your environment

Detox version: 19.13.0
React Native version: 0.65.1
Node version: 14.21.2 (pipeline) 16.17.1 (laptop)
Device model: Azure Pipelines/Mac
OS: Mac OS 12.6.2(pipeline)/12.6.2(laptop)
Test-runner (select one): Other

**Comment by noomorph** [comment]
What do you get in the logs from the device? The message `AppWillTerminateWithError` means a native crash or an unhandled JS error.

**Comment by alyssaw90** [comment]
@noomorph - When I check the pipeline for logs, no logs can be found. My team and I think it is because logs aren't being created. We have also confirmed we are calling the correct flags to create logs. I am going to check again today to see if the logs may have been missed.

**Comment by noomorph** [comment]
@d4vidi do we (technically) support React Native 0.65.x ? I guess we do, right? Maybe 0.59 is an issue, but 60+ is ok, AFAIR.

@alyssaw90 if there's indeed nothing literally, well, you could tweak your ci script to run this log dumper in parallel:

```
/usr/bin/xcrun simctl spawn booted log stream --level debug --style compact --predicate 'process == "mymicrosoft"' &
```

and see what it prints when you get AppWillTerminateWithError.

**Comment by d4vidi** [comment]
We don't check for regressions so I can't give a hard yes on RN .65. I wouldn't be surprised to learn that it's not fully functional.

**Comment by noomorph** [comment]
Related idea: #3854.

**Comment by alyssaw90** [comment]
Thank you @noomorph and @d4vidi for this additional information. I was able to find some logs and going through them this week.

**Comment by adamsrosco** [comment]
@alyssaw90 were you able to resolve the issue. I've noticed unless the react package manager is running the tests timeout. I am able to replicate it locally, have the package manager running and tests pass.

**Comment by alyssaw90** [comment]
We have not been able to resolve the issue. I will pass this on that the timeout could be an issue and test that in our pipeline.

**Comment by noomorph** [comment]
It's unclear for me now what to do about this issue 🤔

**Comment by owens-ben** [comment]
Also having a similar issue with android. It seems like there is an issue with the launchApp() wrapper that makes it time out

https://github.com/wix/Detox/issues/3602

**Comment by owens-ben** [comment]
Bump, spent literally weeks with Bitrise support trying to fix this and it's definitely a Detox issue.

**Comment by akashGautam7009** [comment]
Any solution for this?

**Comment by MuckT** [comment]
@owens-ben & @alyssaw90. I've previously had some similar issues with a different provider. [Wrapping the launch app command in a retry util](https://github.com/valora-inc/wallet/blob/main/e2e/src/utils/retries.js) seemed to help, but might not in your case.

**Comment by akashGautam7009** [comment]
@noomorph Any solution for this issue?

**Comment by owens-ben** [comment]
Still an issue.

**Comment by noomorph** [comment]
Could you share device logs and video recording from your device? Just to make sure, the app runs locally on emulators well enough, right?

**Comment by owens-ben** [comment]
@noomorph yes, it works on android emulators as well as iOS emulators (including in bitrise). 

There essentially are no logs beyond what's been shared. And we can't share a video as the Linux machines do not support vnc.

**Comment by zhouzh1** [comment]
Hey @owens-ben , I also encountered this issue and it took me much time, finally I found it's because of the adb communication is very slow, which caused the apk can't be installed on the emulator. I executed the following commands to restart the adb server and the issue went away.
```
adb kill-server
adb start-server
```
Maybe it's also appropriate for your and other's situation. Good luck. :)
