### ISSUE TITLE
Failed to execute the current status query

### ISSUE THREAD

**Issue by carlosalmonte04** [wix/Detox#3970]
### Description

Detox test hangs on starter.test.js after launching the app on the simulator.
```
 FAIL  e2e/starter.test.js (125.824 s)
  Example
    ✕ should tap on button by id and expect some text to be visible (3 ms)

  ● Example › should tap on button by id and expect some text to be visible

    thrown: "Exceeded timeout of 120000 ms for a hookfalse.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      1 | describe('Example', () => {
    > 2 |   beforeAll(async () => {
        |   ^
      3 |     await device.launchApp();
      4 |   });
      5 |

      at beforeAll (e2e/starter.test.js:2:3)
      at Object.describe (e2e/starter.test.js:1:1)


```

Running  
```
detox test --configuration ios.sim.debug --record-logs all --loglevel trace
```
logs below, _added new lines for easier reading_:

```
13:10:12.756 detox[63590] i ws-client get message
  data: {"params":{"messageId":1,"status":{
  "busy_resources":[
    {"name":"one_time_events","description":{"event":"React Native (bundle load)","object":null}},
    {"name":"run_loop","description":{"name":"Main Run Loop"}},
    {
        "name":"dispatch_queue",
        "description":
               {"queue":"Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)","works_count":1}
    }
  ],
  "app_status":"busy"}},
  "messageId":1,"type":"currentStatusResult"
  }
   
13:10:12.760 detox[63590] i ws-client:APP_STATUS Failed to execute the current status query.
```

```
detox[67243] E Command failed with exit code = 1:
```

Any ideas please? I followed the project setup in the docs

### Your environment

Detox version: 20.4.0
React Native version: 0.71.3
Node version: 18.13.0
Device model: Simulator iPhone 12 iOS 15.2
OS: Monterey 12.4 
Test-runner (select one): jest

**Comment by carlosalmonte04** [comment]
It runs successfully after pressing "R" on the Metro terminal.

**Comment by PeKne** [comment]
I have same problem. The test runner sometimes open the app, but the freezes on the same error.
