### ISSUE TITLE
Detox test not working for Android emulator "Can't seem to connect to test app"- React Native 0.71.4

### ISSUE THREAD

**Issue by hamzaimrann** [wix/Detox#4058]
### What happened?

I am facing the same issue in my react-native boilerplate code, Detox setup for iOS is working perfectly whereas android configuration seems to be causing a crash when running 'detox test' command. I have updated some dependencies that are important in this context: 

- React Native - 0.71.4
- React - 18.2.0
- All of Jest's dependencies  - 29.2.1
- Detox - 20.6.0
- Android SDK - Android NDK: 22.1.7171670

Here is my terminal after running: "detox test -c android.emu.debug --record-logs all" with build successfully generated.

```
16:56:53.100 detox[23705] i Example: should have the login screen first
16:56:56.390 detox[23705] i ""/Users/mac/Library/Android/sdk/platform-tools/adb" -s emulator-16888 shell "ps | grep \"com\.stagingapp$\""" failed with error = ChildProcessError: Command failed: "/Users/mac/Library/Android/sdk/platform-tools/adb" -s emulator-16888 shell "ps | grep \"com\.stagingapp$\""
 `"/Users/mac/Library/Android/sdk/platform-tools/adb" -s emulator-16888 shell "ps | grep \"com\.stagingapp$\""` (exited with error code 1) (code=1), stdout and stderr:

16:56:56.391 detox[23705] i 
16:56:56.391 detox[23705] i 
16:56:58.521 detox[23705] i ""/Users/mac/Library/Android/sdk/platform-tools/adb" -s emulator-16888 shell "ps | grep \"com\.stagingapp$\""" failed with error = ChildProcessError: Command failed: "/Users/mac/Library/Android/sdk/platform-tools/adb" -s emulator-16888 shell "ps | grep \"com\.stagingapp$\""
 `"/Users/mac/Library/Android/sdk/platform-tools/adb" -s emulator-16888 shell "ps | grep \"com\.stagingapp$\""` (exited with error code 1) (code=1), stdout and stderr:

16:56:58.522 detox[23705] i 
16:56:58.523 detox[23705] i 
16:58:53.182 detox[23705] i Detox can't seem to connect to the test app(s)!

HINT: 

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs 



16:58:53.184 detox[23705] i Example: should have the login screen first [FAIL]
16:58:53.198 detox[23705] i Example: should go to welcome screen after logging in
16:58:53.293 detox[23705] i Detox can't seem to connect to the test app(s)!

HINT: 

Have you forgotten to call 'device.launchApp()' in the beginning of your test?
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs

---
The following package could not be delivered:

{
  type: 'invoke',
  params: [Object],
  messageId: 1
}
16:58:53.698 detox[23705] i Detox can't seem to connect to the test app(s)!

HINT: 

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs 



16:58:53.698 detox[23705] i Example: should go to welcome screen after logging in [FAIL]

16:58:54.132 detox[23705] i Detox can't seem to connect to the test app(s)!

HINT: 

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs 



16:58:54.141 detox[23705] i An error occurred while waiting for the app to become ready. Waiting for disconnection...
  error: Failed to run application on the device
  
  HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
16:58:54.142 detox[23705] i The app disconnected.
 FAIL  e2e/firstTest.spec.test.js (163.35 s)
  Example
    ✕ should have the login screen first (120013 ms)
    ✕ should go to welcome screen after logging in (98 ms)

  ● Example › should have the login screen first

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      4 |
      5 | describe("Example", () => {
    > 6 |   beforeEach(async () => {
        |   ^
      7 |     await device.launchApp();
      8 |   });
      9 |

      at beforeEach (e2e/firstTest.spec.test.js:6:3)
      at Object.describe (e2e/firstTest.spec.test.js:5:1)

  ● Example › should go to welcome screen after logging in

    Detox can't seem to connect to the test app(s)!

    HINT: 

    Have you forgotten to call 'device.launchApp()' in the beginning of your test?
    Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs

    ---
    The following package could not be delivered:

    {
      type: 'invoke',
      params: [Object],
      messageId: 1
    }



16:58:54.286 detox[23702] E Command failed with exit code = 1:
jest --config e2e/jest.config.js
```

### What was the expected behaviour?

The 'detox test' command should work on an android emulator as well, just like it is working for iOS. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Run 'detox build -c android.emu.debug' and then 
"detox test -c android.emu.debug"

### In what environment did this happen?

Detox version: 20.6.0
React Native version: 0.71.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: 16.19.1
Device model: Pixel 5 API 33
Android version: 13
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>
[detox.log](https://github.com/wix/Detox/files/11487784/detox.log)

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>
[device.log](https://github.com/wix/Detox/files/11487788/device.log)

**Comment by asafkorem** [comment]
Hey @hamzaimrann, thanks for the report.
Detox is currently compatible with React Native from versions <= 0.70 ([see here](https://github.com/wix/Detox#react-native)), and React Native v0.71 compliance is on our plans for the near future (follow this issue for updates: https://github.com/wix/Detox/issues/3884).
