### ISSUE TITLE
Timeout before emulator loads + terminated due to receipt of signal null

### ISSUE THREAD

**Issue by paulbrittain** [wix/detox#407]
Tests fail when it tries to sent the emulator a key event, but the emulator has only just been started and is booting up.  

**The error:**
```
"before all" hook: _callee:
 Error: Command failed: .../Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
 `.../Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82` (exited with error code 137)
```

**The package.json:**
```
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/app-debug.apk",
        "build": "pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
        "type": "android.emulator",
        "name": "Pixel_XL_API_26"
      }
```

**Longer log:**
```
detox verb Emulator stdout:  emulator: Starting QEMU main loop
detox verb Emulator stdout:  path /Users/myname/.android/avd/Pixel_XL_API_26.avd/system.img.qcow2
detox verb Emulator stdout:  path /Users/myname/.android/avd/Pixel_XL_API_26.avd/vendor.img.qcow2
detox verb Emulator stdout:  emulator: registered 'boot-properties' qemud service
detox verb Emulator stdout:  emulator: Adding boot property: 'ro.opengles.version' = '131072'
detox verb Emulator stdout:  emulator: Adding boot property: 'qemu.sf.fake_camera' = 'both'
detox verb Emulator stdout:  emulator: Adding boot property: 'dalvik.vm.heapsize' = '384m'
detox verb Emulator stdout:  emulator: Adding boot property: 'qemu.hw.mainkeys' = '0'
detox verb Emulator stdout:  emulator: Adding boot property: 'qemu.sf.lcd_density' = '560'
detox verb Emulator stdout:  emulator: goldfish_events.have-dpad: false
detox verb Emulator stdout:  emulator: goldfish_events.have-trackball: false
detox verb Emulator stdout:  emulator: goldfish_events.have-camera: true
detox verb Emulator stdout:  emulator: goldfish_events.have-keyboard: true
detox verb Emulator stdout:  emulator: goldfish_events.have-lidswitch: false
detox verb Emulator stdout:  emulator: goldfish_events.have-touch: false
detox verb Emulator stdout:  emulator: goldfish_events.have-multitouch: true
detox verb Emulator stdout:  emulator: control console listening on port 5554, ADB on port 5555
detox verb Emulator stdout:  Not using any http proxy
detox verb Emulator stdout:  emulator: android_hw_fingerprint_init: fingerprint qemud listen service initialized
detox verb Emulator stdout:
detox verb Emulator stdout:
detox verb Emulator stdout:  emulator: onGuestSendCommand: [0x7fa714a11480] Adb connected, start proxing data
detox verb Emulator stdout:
detox verb 2: /Users/myname/Library/Android/sdk/platform-tools/adb  devices
detox verb 2: stdout: List of devices attached
detox verb 2: stdout: emulator-5554	offline
detox verb 2: stdout:
detox verb 2: stdout:
detox verb 3: /Users/myname/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
  1) "before all" hook: _callee

  0 passing (5s)
  1 failing

  1) "before all" hook: _callee:
     Error: Command failed: /Users/myname/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
 `/Users/myname/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82` (exited with error code 137)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:277:5)
      at maybeClose (internal/child_process.js:927:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)



detox verb ws send: {"type":"cleanup","params":{"stopRunner":true},"messageId":1}
detox verb Emulator stdout:  emulator: _hwFingerprint_connect: connect finger print listen is called
detox verb Emulator stdout:
detox verb Emulator stdout:
detox verb Emulator stdout:  emulator: got message from guest system fingerprint HAL
detox verb Emulator stdout:
detox verb Emulator stdout:
```

If I open the emulator separately before the test I get another error:

```
[detox verb 1: /Users/paulbrittain/Library/Android/sdk/tools/emulator -list-avds --verbose
detox verb 1: stdout: Nexus_5X_API_26_x86
detox verb 1: stdout: Nexus_5_API_23
detox verb 1: stdout: Nexus_5_API_25
detox verb 1: stdout: Nexus_S_API_26
detox verb 1: stdout: Pixel_XL_API_26
detox verb 1: stdout:
detox verb Emulator stdout:  emulator: Android virtual device file at: /Users/paulbrittain/.android/avd/Pixel_XL_API_26.ini
detox verb Emulator stdout:  emulator: virtual device content at /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd
detox verb Emulator stdout:  emulator: virtual device config file: /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd/config.ini
detox verb Emulator stdout:  emulator: using core hw config path: /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd/hardware-qemu.ini
detox verb Emulator stdout:  emulator: Found AVD target API level: 26
detox verb Emulator stdout:  emulator: Read property file at /Users/paulbrittain/Library/Android/sdk/system-images/android-26/google_apis/x86//build.prop
detox verb Emulator stdout:  emulator: No boot.prop property file found.
detox verb Emulator stdout:  emulator: found skin 'pixel_xl' in directory: /Users/paulbrittain/Library/Android/sdk/skins/
detox verb Emulator stdout:  emulator: autoconfig: -skin pixel_xl
detox verb Emulator stdout:  emulator: autoconfig: -skindir /Users/paulbrittain/Library/Android/sdk/skins/
detox verb Emulator stdout:  emulator: autoconfig: -kernel /Users/paulbrittain/Library/Android/sdk/system-images/android-26/google_apis/x86//kernel-ranchu
detox verb Emulator stdout:  emulator: Target arch = 'x86'
detox verb Emulator stdout:  emulator: Auto-config: -qemu -cpu qemu32
detox verb Emulator stdout:  emulator: Auto-detect: Kernel image requires new device naming scheme.
detox verb Emulator stdout:  emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
detox verb Emulator stdout:  emulator: autoconfig: -ramdisk /Users/paulbrittain/Library/Android/sdk/system-images/android-26/google_apis/x86//ramdisk.img
detox verb Emulator stdout:  emulator: Using initial system image: /Users/paulbrittain/Library/Android/sdk/system-images/android-26/google_apis/x86//system.img
detox verb Emulator stdout:  emulator: Using initial vendor image: /Users/paulbrittain/Library/Android/sdk/system-images/android-26/google_apis/x86//vendor.img
detox verb Emulator stdout:  emulator: autoconfig: -data /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd/userdata-qemu.img
detox verb Emulator stdout:  emulator: autoconfig: -initdata /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd/userdata.img
detox verb Emulator stdout:  emulator: autoconfig: -cache /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd/cache.img
detox verb Emulator stdout:  emulator: autoconfig: -sdcard /Users/paulbrittain/.android/avd/Pixel_XL_API_26.avd/sdcard.img
detox verb Emulator stdout:  emulator: Physical RAM size: 1536MB
detox verb Emulator stdout:
detox verb Emulator stdout:  emulator: VM heap size 256MB is below hardware specified minimum of 384MB,setting it to that value
detox verb Emulator stdout:  emulator: System image is read only
detox verb Emulator stdout:  emulator: Found 2 DNS servers: 9.0.138.50 9.0.136.50
detox verb Emulator stdout:  emulator: ERROR: There's another emulator instance running with the current AVD 'Pixel_XL_API_26'. Exiting...
detox verb Emulator stdout:
detox verb Emulator stdout:
detox verb 2: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb  devices
detox verb 2: stdout: List of devices attached
detox verb 2: stdout: emulator-5554	device
detox verb 2: stdout:
detox verb 2: stdout:
detox verb 3: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
detox verb 4: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.appconfigexample
detox verb 5: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.appconfigexample.test
detox verb 6: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/paulbrittain/git/react-native-appconfig/AppConfigExample/android/app/build/outputs/apk/app-debug.apk
detox verb 6: stderr: Success
detox verb 6: stderr:
detox verb 7: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/paulbrittain/git/react-native-appconfig/AppConfigExample/android/app/build/outputs/apk/app-debug-androidTest.apk
detox verb 7: stderr: Success
detox verb 7: stderr:
detox verb 8: /Users/paulbrittain/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.appconfigexample
detox verb adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:57390 -e detoxSessionId a83393d1-9d22-032e-e866-70e5de41fbb6 -e debug false com.appconfigexample.test/android.support.test.runner.AndroidJUnitRunner
detox verb Instrumentation spawned, childProcess.pid:  93971
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb Instrumentation stdout:  INSTRUMENTATION_RESULT: shortMsg=Process crashed.
detox verb Instrumentation stdout:  INSTRUMENTATION_CODE: 0
detox verb Instrumentation stdout:
detox verb instrumentationProcess terminated due to receipt of signal null](url)
```

**Comment by rotemmiz** [comment]
Thanks for reporting this error, we are currently working on a fix for that, hopefully to be released soon
