### ISSUE TITLE
Detox can't tap on iOS software keyboard because of visibility check

### ISSUE THREAD

**Issue by fpmboy** [wix/Detox#4118]
### What happened?

Detox can't tap on iOS software keyboard with error: "View is not hittable at its visible point. Error: View is not visible around point."

App under test is React native application. In my test scenario - i need to validate, that keyboard is present on screen and tap on particular button, f. e. button "."
`await element(by.label('.')).getAttributes().then((res) => console.log(res));`
Correctly find and returns element attributes:
```
11:55:34.134 detox[7094] i user {
  isAccessibilityElement: true,
  activationPoint: { x: 295.5, y: 199.5 },
  elementSafeBounds: { y: 175, x: 269, width: 53, height: 49 },
  frame: { y: 806, x: 269, width: 53, height: 49 },
  label: '.',
  enabled: true,
  hittable: true,
  visible: true,
  normalizedActivationPoint: { x: 0.5, y: 0.5 },
  className: 'UIAccessibilityElementKBKey'
}
```
But when i try to tap on it:
`await element(by.label('.')).tap();`
i got following error:
```
Test Failed: View is not hittable at its visible point. Error: View is not visible around point.
    - view point: {564.5, 374.5}
    - visible bounds: {{0, 0}, {430, 243}}
    - view bounds: {{0, 0}, {430, 243}}
    ---
    Error: Error Domain=DetoxErrorDomain Code=0 "View “<UIKeyboardLayoutStar: 0x7fab9bb59000>” is not visible: View does not pass visibility percent threshold (100)" 
```

`.typeText()` works totally fine, but in my case it's not an option, element i need to interact with - is from 3-d person library. So i can't control testID-s or labels of elements. I can't select it by `element` method, to call method `.typeText()` but i can tap on it to invoke ios software keyboard.

Could you assist on this issue? Detox can't tap on system software keyboard? 

### What was the expected behaviour?

Detox should tap on ios software keyboard. It's visible, not obscured by any other UI elements.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.9.1
React Native version: 0.68.5
Has Fabric (React Native's new rendering system) enabled: no
Node version: 16.20.0
Device model: Simulator iPhone 14 Pro Max
iOS version: 16.4(20E247)
macOS version: 13.4.1 (22F82)
Xcode version: 14.3.1 (14E300c)
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
13:12:08.883 detox[9660] i device app.bundle.name launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 56702C8B-F15C-41D5-BDDA-38B8F533BC58 log stream --level debug --style compact --predicate 'process == "ApplicationRN"'

13:12:19.059 detox[9660] i lifecycle test > tap on keyboard: should tap email, render kayboard, tap dot
13:12:19.120 detox[9660] i child-process:SPAWN_END /usr/bin/xcrun simctl spawn 56702C8B-F15C-41D5-BDDA-38B8F533BC58 log stream --level debug --style compact --predicate "processImagePath beginsWith \"/Users/k.danenkov/Library/Developer/CoreSimulator/Devices/56702C8B-F15C-41D5-BDDA-38B8F533BC58/data/Containers/Bundle/Application/307A6610-0862-4140-B90E-63AFD1BBC22B/ApplicationRN.app\"" exited with code #0
13:12:19.121 detox[9660] i child-process:EXEC_CMD /usr/bin/xcrun simctl get_app_container 56702C8B-F15C-41D5-BDDA-38B8F533BC58 app.bundle.name
13:12:19.293 detox[9660] i child-process:SPAWN_CMD /usr/bin/xcrun simctl spawn 56702C8B-F15C-41D5-BDDA-38B8F533BC58 log stream --level debug --style compact --predicate "processImagePath beginsWith \"/Users/k.danenkov/Library/Developer/CoreSimulator/Devices/56702C8B-F15C-41D5-BDDA-38B8F533BC58/data/Containers/Bundle/Application/307A6610-0862-4140-B90E-63AFD1BBC22B/ApplicationRN.app\""
13:12:22.909 detox[9660] i user {
  elementSafeBounds: { y: 7, x: 300.3333333333333, width: 42.333333333333314, height: 49 },
  hittable: true,
  isAccessibilityElement: true,
  normalizedActivationPoint: { x: 0.5000000000000007, y: 0.5 },
  visible: true,
  className: 'UIAccessibilityElementKBKey',
  label: 'i',
  frame: {
    y: 638,
    x: 300.3333333333333,
    width: 42.333333333333314,
    height: 49
  },
  activationPoint: { x: 321.5, y: 31.5 },
  enabled: true
}
  origin: at test/e2e/deposit.e2e.ts:20:101
13:12:25.257 detox[9660] i child-process:EXEC_CMD /usr/bin/xcrun simctl io 56702C8B-F15C-41D5-BDDA-38B8F533BC58 screenshot "/private/var/folders/2g/3v5c91994cj0jg6jr3jhy8v00000gn/T/efd3b61f-3b59-4eaa-aaaf-5f2c46466e7e.detox.png"
13:12:25.478 detox[9660] i artifact:MOVE_FILE moving "/Users/k.danenkov/Library/Developer/CoreSimulator/Devices/56702C8B-F15C-41D5-BDDA-38B8F533BC58/data/Containers/Data/Application/C958590E-3E51-45CA-8B28-6CD4928A56FA/tmp/3714D000-B9D0-43DF-B650-92BC13C2C5FD.viewhierarchy" to artifacts/ios.2023-07-03 10-11-55Z/✗ test tap on keyboard should tap email, render kayboard, tap dot/ui.viewhierarchy
13:12:25.479 detox[9660] i artifact:MOVE_FILE moving "/Users/k.danenkov/Library/Developer/CoreSimulator/Devices/56702C8B-F15C-41D5-BDDA-38B8F533BC58/data/Containers/Data/Application/C958590E-3E51-45CA-8B28-6CD4928A56FA/tmp/visibilityFailingScreenshots/DETOX_VISIBILITY_UIKeyboardLayoutStar <0x7f9fd42ea000>_SCREEN.png" to artifacts/ios.2023-07-03 10-11-55Z/✗ test tap on keyboard should tap email, render kayboard, tap dot/DETOX_VISIBILITY_UIKeyboardLayoutStar__0x7f9fd42ea000__SCREEN.png
13:12:25.480 detox[9660] i artifact:MOVE_FILE moving "/Users/k.danenkov/Library/Developer/CoreSimulator/Devices/56702C8B-F15C-41D5-BDDA-38B8F533BC58/data/Containers/Data/Application/C958590E-3E51-45CA-8B28-6CD4928A56FA/tmp/visibilityFailingRects/DETOX_VISIBILITY_UIKeyboardLayoutStar <0x7f9fd42ea000>_TEST.png" to artifacts/ios.2023-07-03 10-11-55Z/✗ test tap on keyboard should tap email, render kayboard, tap dot/DETOX_VISIBILITY_UIKeyboardLayoutStar__0x7f9fd42ea000__TEST.png
13:12:25.483 detox[9660] i artifact:MOVE_FILE moving "/private/var/folders/2g/3v5c91994cj0jg6jr3jhy8v00000gn/T/efd3b61f-3b59-4eaa-aaaf-5f2c46466e7e.detox.png" to artifacts/ios.2023-07-03 10-11-55Z/✗ test tap on keyboard should tap email, render kayboard, tap dot/testFnFailure.png
13:12:25.547 detox[9660] i child-process:SPAWN_END /usr/bin/xcrun simctl spawn 56702C8B-F15C-41D5-BDDA-38B8F533BC58 log stream --level debug --style compact --predicate "processImagePath beginsWith \"/Users/k.danenkov/Library/Developer/CoreSimulator/Devices/56702C8B-F15C-41D5-BDDA-38B8F533BC58/data/Containers/Bundle/Application/307A6610-0862-4140-B90E-63AFD1BBC22B/ApplicationRN.app\"" exited with code #0
13:12:25.548 detox[9660] i lifecycle test > tap on keyboard: should tap email, render kayboard, tap dot [FAIL]

13:12:25.565 detox[9660] i artifact:MOVE_FILE moving "/private/var/folders/2g/3v5c91994cj0jg6jr3jhy8v00000gn/T/f3d2a7c3-7ff7-47d8-a4d3-09fd4c245b0f.detox.log" to artifacts/ios.2023-07-03 10-11-55Z/✗ test tap on keyboard should tap email, render kayboard, tap dot/device.log
13:12:25.566 detox[9660] i artifact:MOVE_FILE moving "/private/var/folders/2g/3v5c91994cj0jg6jr3jhy8v00000gn/T/71b4615a-9278-4b41-b0cd-4125a373ccce.detox.log" to artifacts/ios.2023-07-03 10-11-55Z/56702C8B-F15C-41D5-BDDA-38B8F533BC58 2023-07-03 10-12-25Z.startup.log

 FAIL  test/e2e/deposit.e2e.ts (29.337 s)
  test
    tap on keyboard
      ✕ should tap email, render kayboard, tap dot (6415 ms)

  ● test › tap on keyboard › should tap email, render kayboard, tap dot

    Test Failed: View is not hittable at its visible point. Error: View is not visible around point.
    - view point: {621.83333333333326, 38.5}
    - visible bounds: {{0, 0}, {430, 243}}
    - view bounds: {{0, 0}, {430, 243}}
    ---
    Error: Error Domain=DetoxErrorDomain Code=0 "View “<UIKeyboardLayoutStar: 0x7f9fd42ea000>” is not visible: View does not pass visibility percent threshold (100)" UserInfo={NSLocalizedDescription=View “<UIKeyboardLayoutStar: 0x7f9fd42ea000>” is not visible: View does not pass visibility percent threshold (100)}

      23 |       await waitFor(element(by.label('i'))).toBeVisible().withTimeout(3000);
      24 |       await element(by.label('i')).getAttributes().then((res) => console.log(res));
    > 25 |       await element(by.label('i')).tap();
         |                                    ^
      26 |       // await expect(app.keyboard.key1).toBeVisible();
      27 |       // await element(by.label('Удалить')).getAttributes().then((res) => console.log(res));
      28 |       // await element(by.label('Удалить')).tap();

      at Object.<anonymous> (test/e2e/deposit.e2e.ts:25:36)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        29.396 s, estimated 33 s
Ran all test suites.
13:12:25.718 detox[9659] E lifecycle Command failed with exit code = 1:
jest --config test/jest.config.js
13:12:25.719 detox[9659] i ws-server Detox server has been closed gracefully
13:12:25.720 detox[9659] E ws-server connection :63307<->:63325
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

### More data, please!

<details><summary>DETOX_VISIBILITY_UIKeyboardLayoutStar__0x7fab9bb59000__SCREEN</summary>

(https://github.com/wix/Detox/assets/29140464/5ca01f28-ffe7-47ab-9c74-391c8661d584)

</details>

<details><summary>DETOX_VISIBILITY_UIKeyboardLayoutStar__0x7fab9bb59000__TEST</summary>

(https://github.com/wix/Detox/assets/29140464/9c0546e1-6b3d-4b3d-bc0b-ce104a221911)

</details>

<details><summary>testFnFailure</summary>

(https://github.com/wix/Detox/assets/29140464/17219d99-2034-4a53-9ec9-9565b0c4bbd8)

</details>

[ui.viewhierarchy.zip](https://github.com/wix/Detox/files/11935738/ui.viewhierarchy.zip)
[device.log](https://github.com/wix/Detox/files/11935746/device.log)

**Comment by fpmboy** [comment]
BTW found method `.tapBackspaceKey()` -  still failing with similar error:

 ```
Test Failed: View is not hittable at its visible point. Error: Failed to interact with the screen at point: {215, 121.5}.

      18 |     it('should render deposit with open keyboard, tap deposit, render loader', async () => {
      19 |       await expect(app.keyboard.key1).toBeVisible();
    > 20 |       await app.keyboard.keyBackspace.tapBackspaceKey();
```

**Comment by noomorph** [comment]
@asafkorem could you help here?

**Comment by asafkorem** [comment]
> BTW found method `.tapBackspaceKey()` - still failing with similar error:
> 
> ```
> Test Failed: View is not hittable at its visible point. Error: Failed to interact with the screen at point: {215, 121.5}.
> 
>      18 |     it('should render deposit with open keyboard, tap deposit, render loader', async () => {
>      19 |       await expect(app.keyboard.key1).toBeVisible();
>    > 20 |       await app.keyboard.keyBackspace.tapBackspaceKey();
> ```

@fpmboy Could you please share here the screenshot from when the failure occurred?
