### ISSUE TITLE
 DetoxRuntimeError: Cannot boot Android Emulator with the name: 'Android 34'

### ISSUE THREAD

**Issue by Brittognanaraj** [wix/Detox#4135]
### What happened?

I try to ran my test in emulator, But never works and it returns the below error
 ```
● Test suite failed to run

    DetoxRuntimeError: Cannot boot Android Emulator with the name: 'Android 34'

    HINT: Make sure you choose one of the available emulators: Android_34,Pixel_6_API_34_1

      at AVDValidator._assertAVDMatch (../node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:37:13)
      at AVDValidator.validate (../node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:18:16)
      at EmulatorAllocDriver.allocate (../node_modules/detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.js:34:5)
      at Detox._doInit (../node_modules/detox/src/Detox.js:196:26)

```

FYI: detox tests in iOS running smoothly.

### Was it tested on latest Detox?

- [ ] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version:"^19.4.0",
"detox-recorder": "^1.0.151",
React Native version: 0.68.3
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: v20.3.0
Device model: pixel
Android version: 34
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

 ```
● Test suite failed to run

    DetoxRuntimeError: Cannot boot Android Emulator with the name: 'Android 34'

    HINT: Make sure you choose one of the available emulators: Android_34,Pixel_6_API_34_1

      at AVDValidator._assertAVDMatch (../node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:37:13)
      at AVDValidator.validate (../node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:18:16)
      at EmulatorAllocDriver.allocate (../node_modules/detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.js:34:5)
      at Detox._doInit (../node_modules/detox/src/Detox.js:196:26)

```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by noomorph** [comment]
Use Android_34

**Comment by Brittognanaraj** [comment]
This issue closed. Thanks @noomorph

**Comment by bouncydragon** [comment]
Hi, I have this kind of issue the difference is that the app cannot see what kind of emulator should I use, even thou I have a running emulator.

![image](https://github.com/wix/Detox/assets/9712523/03b86aa0-48f0-4629-a7ca-9c99b9785b84)

**Comment by champa-b** [comment]
FAIL e2e/suite.test.js
  ● Test suite failed to run
    DetoxRuntimeError: Cannot boot Android Emulator with the name: 'Pixel_7a_API_29'
    HINT: Make sure you choose one of the available emulators: INFO    | Storing crashdata in: /tmp/android-runner/emu-crash-34.2.16.db, detection is enabled for process: 2243,test
      at AVDValidator._assertAVDMatch (node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:36:13)
      at AVDValidator.validate (node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:18:16)
      at async EmulatorAllocDriver.allocate (node_modules/detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.js:59:5)
      at async /home/runner/work/geo-vendor-mobile/geo-vendor-mobile/node_modules/detox/src/devices/allocation/DeviceAllocator.js:44:22
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.918 s
Ran all test suites.
09:51:10.864 detox[2218] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

> Use Android_34

how can i get to know my device name

**Comment by JB712** [comment]
> FAIL e2e/suite.test.js ● Test suite failed to run DetoxRuntimeError: Cannot boot Android Emulator with the name: 'Pixel_7a_API_29' HINT: Make sure you choose one of the available emulators: INFO | Storing crashdata in: /tmp/android-runner/emu-crash-34.2.16.db, detection is enabled for process: 2243,test at AVDValidator._assertAVDMatch (node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:36:13) at AVDValidator.validate (node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:18:16) at async EmulatorAllocDriver.allocate Test Suites: 1 failed, 1 total Tests: 0 total Snapshots: 0 total Time: 0.918 s Ran all test suites. 09:51:10.864 detox[2218] E Command failed with exit code = 1: jest --config e2e/jest.config.js
> 
> > Use Android_34
> 
> how can i get to know my device name

Might be late, but for anyone passing by: to check your devices name, use command **emulator -list-avds**
