### ISSUE TITLE
App is not launching in Android

### ISSUE THREAD

**Issue by Brittognanaraj** [wix/Detox#4137]
### What happened?

App is installing but not launching in android. It throws below error

`detox[5563] ERROR: ChildProcessError: `/Users/bgr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Test.apk` failed with code 1
    at ChildProcess.<anonymous> (/Users/bgr/Documents/ReactNative/SwellMobile/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
17:42:17.865 detox[5987] DEBUG: [SPAWN_END, #44, cpid=6057] /Users/bgr/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Test.apk exited with code #1
17:42:17.866 detox[5987] ERROR: ChildProcessError: `/Users/zapcom/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Test.apk` failed with code 1
    at ChildProcess.<anonymous> (/Users/bgr/Documents/ReactNative/SwellMobile/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:511:28)
    at Pipe.<anonymous> (node:net:334:12)
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by estiventhneira** [comment]
same problem, any update at this? @Brittognanaraj

**Comment by UgurGumushan** [comment]
Yes. Detox throws this when running android in parallel mode. Use maxWorkers=1 until this is resolved
