### ISSUE TITLE
The app has not responded to the network requests below:   (id = 1) currentStatus: {}   (id = -1000) isReady: {}

### ISSUE THREAD

**Issue by sonujangra-mw** [wix/Detox#4151]
### What happened?

<img width="1755" alt="image" src="https://github.com/wix/Detox/assets/115171357/b9d3eebd-ddf0-46f1-bef5-8fb405746662">

Emulator: Pixel_6_API_33
RN Version: ^0.72.3
Detox Version: ^20.7.0

12:36:47.716 detox[12900] i ws-client:PENDING_REQUESTS The app has not responded to the network requests below:
  (id = 1) currentStatus: {}
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

12:36:52.719 detox[12900] i ws-client:ERROR The pending request #-49642 ("cleanup") has been rejected due to the following error:

The tester has not received a response within 5000ms timeout to the message:

Cleanup {
  type: 'cleanup',
  params: [Object],
  messageId: -49642
}

### What was the expected behaviour?

Unable to run detox test for android. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: ^20.7.0
React Native version: ^0.72.3
Has Fabric (React Native's new rendering system) enabled: (yes/no)  no
Node version: v18.15.0
Device model:  Pixel_6_API_33
Android version:  13
Test-runner (select one): jest / other jest

### Detox logs

<details><summary>Detox logs</summary>

```
12:33:43.583 detox[12897] i ws-server Detox server listening on localhost:56684...
12:33:43.593 detox[12897] B lifecycle jest --config e2e/jest.config.js
12:33:45.017 detox[12900] i  jest-circus@29.6.2 does not match jest@29.5.0.

- jest@29.5.0 resolved path:
	/Users/cookcounty/projects/cch-mobile-app/node_modules/jest/package.json
- jest-circus@29.6.2 resolved path:
	/Users/cookcounty/.nvm/versions/node/v18.15.0/lib/node_modules/jest/node_modules/jest-circus/package.json

Please make sure that your versions match to avoid unexpected behavior!

12:33:45.511 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/emulator/emulator" -list-avds --verbose
12:33:45.589 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/emulator/emulator" -version
12:33:46.962 detox[12900] i device Detected emulator binary version { major: 32, minor: 1, patch: 14, toString: [Function: toString] }
12:33:46.963 detox[12900] i device:ALLOCATE_DEVICE Trying to allocate a device based on "Pixel_6_API_33"
12:33:46.965 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb"  devices
12:33:47.176 detox[12900] i child-process:EXEC_SUCCESS List of devices attached
emulator-5554	device


12:33:47.189 detox[12900] i device:DEVICE_LOOKUP Found a matching & free device emulator-5554
12:33:47.191 detox[12900] i device:ALLOCATE_DEVICE Settled on emulator-5554
12:33:47.192 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop dev.bootcomplete"
12:33:47.391 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "getprop ro.build.version.sdk"
12:33:47.494 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global animator_duration_scale 0"
12:33:47.893 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global window_animation_scale 0"
12:33:48.683 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "settings put global transition_animation_scale 0"
12:33:48.885 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
12:33:49.940 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/build-tools/34.0.0/aapt" dump badging "/Users/cookcounty/projects/cch-mobile-app/android/app/build/outputs/apk/debug/app-debug.apk"
12:33:50.052 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages org.cookcountyhealth.connected"
12:33:50.394 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 uninstall org.cookcountyhealth.connected
12:33:53.388 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list packages org.cookcountyhealth.connected.test"
12:33:53.842 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 uninstall org.cookcountyhealth.connected.test
12:33:55.590 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop org.cookcountyhealth.connected"
12:33:57.394 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/build-tools/34.0.0/aapt" dump xmlstrings "/Users/cookcounty/projects/cch-mobile-app/android/app/build/outputs/apk/debug/app-debug.apk" AndroidManifest.xml
12:33:57.415 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/build-tools/34.0.0/aapt" dump xmlstrings "/Users/cookcounty/projects/cch-mobile-app/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" AndroidManifest.xml
12:33:57.440 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "rm -fr /data/local/tmp/detox"
12:33:57.791 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "mkdir -p /data/local/tmp/detox"
12:33:58.891 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/cookcounty/projects/cch-mobile-app/android/app/build/outputs/apk/debug/app-debug.apk" "/data/local/tmp/detox/Application.apk"
12:34:21.242 detox[12900] i child-process:SPAWN_CMD /Users/cookcounty/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk
12:34:45.694 detox[12900] i child-process:SPAWN_END /Users/cookcounty/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk exited with code #0
12:34:45.695 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 push "/Users/cookcounty/projects/cch-mobile-app/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" "/data/local/tmp/detox/Test.apk"
12:34:45.854 detox[12900] i child-process:SPAWN_CMD /Users/cookcounty/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Test.apk
12:34:46.759 detox[12900] i child-process:SPAWN_END /Users/cookcounty/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Test.apk exited with code #0
12:34:46.760 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse tcp:8082 tcp:8082
12:34:46.799 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop org.cookcountyhealth.connected"
12:34:47.660 detox[12900] i lifecycle starter.test.js is assigned to emulator-5554 (Pixel_6_API_33)
12:34:47.672 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "am force-stop org.cookcountyhealth.connected"
12:34:47.743 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "date +\"%m-%d %T.000\""
12:34:47.820 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse tcp:56684 tcp:56684
12:34:47.861 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "pm list instrumentation"
12:34:47.933 detox[12900] i child-process:SPAWN_CMD /Users/cookcounty/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:56684 -e detoxSessionId 096cb7fe-2924-3e7d-35e8-19a87b21f84c -e debug false org.cookcountyhealth.connected.test/androidx.test.runner.AndroidJUnitRunner
12:34:48.434 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 shell "ps | grep \"org\.cookcountyhealth\.connected$\""

12:35:06.445 detox[12900] i ws-client:APP_STATUS Failed to execute the current status query.
12:36:47.666 detox[12900] i lifecycle Example: should have welcome screen
12:36:47.669 detox[12900] i lifecycle Example: should have welcome screen [FAIL]
12:36:47.675 detox[12900] i lifecycle Example: should show hello screen after tap
12:36:47.676 detox[12900] i lifecycle Example: should show hello screen after tap [FAIL]
12:36:47.677 detox[12900] i lifecycle Example: should show world screen after tap
12:36:47.677 detox[12900] i lifecycle Example: should show world screen after tap [FAIL]

12:36:47.716 detox[12900] i ws-client:PENDING_REQUESTS The app has not responded to the network requests below:
  (id = 1) currentStatus: {}
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

12:36:52.719 detox[12900] i ws-client:ERROR The pending request #-49642 ("cleanup") has been rejected due to the following error:

The tester has not received a response within 5000ms timeout to the message:

Cleanup {
  type: 'cleanup',
  params: [Object],
  messageId: -49642
}

12:36:52.726 detox[12900] i child-process:SPAWN_END /Users/cookcounty/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:56684 -e detoxSessionId 096cb7fe-2924-3e7d-35e8-19a87b21f84c -e debug false org.cookcountyhealth.connected.test/androidx.test.runner.AndroidJUnitRunner terminated with SIGINT
12:36:52.727 detox[12900] i device An error occurred while waiting for the app to become ready. Waiting for disconnection...
  error: Failed to run application on the device

  HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
12:36:52.727 detox[12900] i child-process:EXEC_CMD "/Users/cookcounty/Library/Android/sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:56684
 FAIL  e2e/starter.test.js (182.645 s)
  Example
    ✕ should have welcome screen (3 ms)
    ✕ should show hello screen after tap (1 ms)
    ✕ should show world screen after tap (1 ms)

  ● Example › should have welcome screen

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      2 |
      3 | describe('Example', () => {
    > 4 |   beforeAll(async () => {
        |   ^
      5 |     //await device.launchApp();
      6 |
      7 |     await device.launchApp({ newInstance: true });

      at beforeAll (e2e/starter.test.js:4:3)
      at Object.describe (e2e/starter.test.js:3:1)

  ● Example › should show hello screen after tap

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      2 |
      3 | describe('Example', () => {
    > 4 |   beforeAll(async () => {
        |   ^
      5 |     //await device.launchApp();
      6 |
      7 |     await device.launchApp({ newInstance: true });

      at beforeAll (e2e/starter.test.js:4:3)
      at Object.describe (e2e/starter.test.js:3:1)

  ● Example › should show world screen after tap

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      2 |
      3 | describe('Example', () => {
    > 4 |   beforeAll(async () => {
        |   ^
      5 |     //await device.launchApp();
      6 |
      7 |     await device.launchApp({ newInstance: true });

      at beforeAll (e2e/starter.test.js:4:3)
      at Object.describe (e2e/starter.test.js:3:1)

12:36:52.861 detox[12897] E lifecycle Command failed with exit code = 1:
jest --config e2e/jest.config.js
12:36:52.863 detox[12897] i ws-server Detox server has been closed gracefully
12:36:52.864 detox[12897] E ws-server connection :56684<->:57112
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
08-01 13:11:22.967  9196  9783 D DetoxWSClient: Retrying...
08-01 13:11:22.967  9196  9783 I DetoxWSClient: At connectToServer
08-01 13:11:22.972 31923  9786 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10204 0}
08-01 13:11:22.973  9196  9785 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:24.592  9196  9476 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:24.593  9196  9477 D TrafficStats: tagSocket(153) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:26.165 31986 31986 W Looper  : Slow delivery took 259ms main h=android.os.Handler c=com.android.internal.os.BinderCallsStats$1@82cae02 m=0
08-01 13:11:26.167  9196  9785 D DetoxWSClient: Retrying...
08-01 13:11:26.168  9196  9785 I DetoxWSClient: At connectToServer
08-01 13:11:26.175 31923  9790 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10204 0}
08-01 13:11:26.176  9196  9789 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:26.190 31986 32156 D androidtc: Initializing SystemTextClassifier, type = System
08-01 13:11:26.197 32175 32175 I ClipboardListener: Clipboard overlay suppressed.
08-01 13:11:26.254 32175 32175 I ClipboardListener: Clipboard overlay suppressed.
08-01 13:11:26.643  9196  9476 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:26.648  9196  9477 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:28.657  9196  9476 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:28.668  9196  9477 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:29.182  9196  9789 D DetoxWSClient: Retrying...
08-01 13:11:29.182  9196  9789 I DetoxWSClient: At connectToServer
08-01 13:11:29.191 31923  9795 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10204 0}
08-01 13:11:29.192  9196  9794 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:30.669  9196  9476 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:30.675  9196  9477 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:31.164 31986 31986 W Looper  : Drained
08-01 13:11:32.196  9196  9794 D DetoxWSClient: Retrying...
08-01 13:11:32.196  9196  9794 I DetoxWSClient: At connectToServer
08-01 13:11:32.200 31923  9801 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10204 0}
08-01 13:11:32.200  9196  9800 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:32.678  9196  9476 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:32.684  9196  9477 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:34.688  9196  9476 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:34.694  9196  9477 D TrafficStats: tagSocket(153) with statsTag=0xffffffff, statsUid=-1
08-01 13:11:35.204  9196  9800 D DetoxWSClient: Retrying...
```

</details>

**Comment by eilinwis** [comment]
i guess you're receiving this error due the incompatibility detox 20.7 and react-native 0.72
but i believe that work is in progress

**Comment by MarcelinaZiolkiewicz** [comment]
Same issue here but i have different versions:
Detox version: ^20.13.2
React Native version: ^0.72.6
Did you find any solution?

**Comment by noomorph** [comment]
Well, you can try to launch the app this way (emergency launch), but that's a dead end. It's hard to know what's not idle there. 🤷‍♂️ 

```diff
  beforeEach(async () => {
    await device.launchApp({
+     launchArgs: { detoxEnableSynchronization: 0 },
      newInstance: true
    });
  });
```

**Comment by tamaniniandre** [comment]
it happened to me today

**Comment by joesardo** [comment]
This issue is not stale - I consistently see some form of this on our CICD platform where the test is saying it has not received a network request, usually in the form of:
detox[37716] i The app has not responded to the network requests below:
  (id = 6) invoke: {"type":"action","action":"tap","predicate":{"type":"id","value":"bellsant:Signin","isRegex":false}}
  (id = 7) currentStatus: {}

Very annoying to debug as the element is clearly on the screen and has zero issues running locally. Please look into this 🙏

**Comment by maxmilianf** [comment]
Same here with:
```
    "detox": "^20.23.1",
     "react-native": "0.74.3",
```

**Comment by coltkenn** [comment]
any update on this? i'm suddenly experiencing this on a test case that was previously passing just fine.

**Comment by BartoszLeczycki** [comment]
Same in our case with:
 "react-native": "0.77.0",
 "detox": "^20.32.0",

"The app has not responded to the network requests below: (id = 1) currentStatus: {} (id = -1000) isReady: {}."


It works without trouble on the IOS simulator, but there is a problem with the Android emulator.

**Comment by lodibrahim** [comment]
Same issue here with 
"react-native": "0.76.5",
"detox": "^20.32.0",

**Comment by sarang-001** [comment]
Specifically for android and on ios it works fine 
"detox": "^20.41.3",
"react-native": "^0.81.0",

Getting The tester has not received a response within 5000ms timeout to the message: CurrentStatus { type: 'currentStatus' }

```


sarangupadhye@TPMac-MVNCQ2HC65 tp_mobile_shell_demo_app % detox test --configuration android.att.debug --loglevel verbose
11:03:06.872 detox[41336] i ws-server Detox server listening on localhost:59797...
11:03:06.875 detox[41336] B lifecycle jest --config e2e/jest.config.js
watchman warning:  Recrawled this watch 11 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app' ; watchman watch-project '/Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app'`


 RUNS  e2e/settings.test.ts
11:03:07.735 detox[41336] B ws-server connection :59797<->:59806
11:03:07.784 detox[41336] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb"  devices
11:03:07.813 detox[41336] i child-process:EXEC_SUCCESS List of devices attached
emulator-13508  device


11:03:07.813 detox[41336] i device:DEVICE_LOOKUP Found a matching & free device emulator-13508
11:03:07.814 detox[41336] i device settled on emulator-13508
  data: {
    "id": "emulator-13508",
    "adbName": "emulator-13508"
  }
11:03:07.814 detox[41336] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "getprop ro.build.version.sdk"
11:03:08.020 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/build-tools/36.0.0/aapt" dump badging "/Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/debug/app-debug.apk"
11:03:08.062 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "pm list packages com.shell_demo"
11:03:08.136 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 uninstall com.shell_demo
11:03:08.282 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "pm list packages com.shell_demo.test"
11:03:08.387 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 uninstall com.shell_demo.test
11:03:08.887 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "am force-stop com.shell_demo"
11:03:09.094 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/build-tools/36.0.0/aapt" dump xmlstrings "/Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/debug/app-debug.apk" AndroidManifest.xml
11:03:09.126 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/build-tools/36.0.0/aapt" dump xmlstrings "/Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" AndroidManifest.xml
11:03:09.172 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "getprop ro.build.version.sdk"
11:03:09.224 detox[41342] i child-process:SPAWN_CMD /Users/sarangupadhye/Library/Android/sdk/platform-tools/adb -s emulator-13508 install -r -g -t /Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/debug/app-debug.apk
11:03:09.862 detox[41342] i child-process:SPAWN_END /Users/sarangupadhye/Library/Android/sdk/platform-tools/adb -s emulator-13508 install -r -g -t /Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/debug/app-debug.apk exited with code #0
11:03:09.863 detox[41342] i child-process:SPAWN_CMD /Users/sarangupadhye/Library/Android/sdk/platform-tools/adb -s emulator-13508 install -r -g -t /Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
11:03:09.970 detox[41342] i child-process:SPAWN_END /Users/sarangupadhye/Library/Android/sdk/platform-tools/adb -s emulator-13508 install -r -g -t /Users/sarangupadhye/Documents/csservice-automation_2/tp-mobile-shell/tp_mobile_shell_demo_app/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk exited with code #0
11:03:09.971 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 reverse tcp:8081 tcp:8081
11:03:10.005 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "am force-stop com.shell_demo"
11:03:10.711 detox[41342] i lifecycle settings.test.ts is assigned to AttachedDevice:emulator-13508
11:03:10.712 detox[41342] i user 🧪 Launching app with network sync disabled
  origin: at e2e/settings.test.ts:6:17
11:03:10.714 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "am force-stop com.shell_demo"
11:03:10.757 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "date +\"%m-%d %T.000\""
11:03:10.794 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 reverse tcp:59797 tcp:59797
11:03:10.828 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "pm list instrumentation"
11:03:10.872 detox[41342] i child-process:SPAWN_CMD /Users/sarangupadhye/Library/Android/sdk/platform-tools/adb -s emulator-13508 shell am instrument -w -r -e detoxServer ws://localhost:59797 -e detoxSessionId cabcbd79-c1ac-8dd2-f5c5-de4c8c41f341 -e detoxDisableNetworkSynchronization true -e detoxEnableSynchronization 0 -e debug false com.shell_demo.test/androidx.test.runner.AndroidJUnitRunner
11:03:11.373 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 shell "ps | grep \"com\.shell_demo$\""

11:03:27.016 detox[41342] i ws-client:APP_STATUS Failed to execute the current status query. The pending request #1 ("currentStatus") has been rejected due to the following error:

The tester has not received a response within 5000ms timeout to the message:

CurrentStatus {
  type: 'currentStatus',
  params: {},
  messageId: 1
}
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7) {
  name: 'DetoxRuntimeError'
}
11:03:57.123 detox[41342] i user ✅ App launched successfully
  origin: at e2e/settings.test.ts:11:17
11:03:57.137 detox[41342] i lifecycle Example: should have welcome screen
11:03:57.365 detox[41342] i child-process:SPAWN_END /Users/sarangupadhye/Library/Android/sdk/platform-tools/adb -s emulator-13508 shell am instrument -w -r -e detoxServer ws://localhost:59797 -e detoxSessionId cabcbd79-c1ac-8dd2-f5c5-de4c8c41f341 -e detoxDisableNetworkSynchronization true -e detoxEnableSynchronization 0 -e debug false com.shell_demo.test/androidx.test.runner.AndroidJUnitRunner exited with code #0
11:03:57.365 detox[41342] i child-process:EXEC_CMD "/Users/sarangupadhye/Library/Android/sdk/platform-tools/adb" -s emulator-13508 reverse --remove tcp:59797

11:03:57.370 detox[41342] i lifecycle Example: should have welcome screen [FAIL]


 FAIL  e2e/settings.test.ts (49.795 s)
  Example
    ✕ should have welcome screen (235 ms)

  ● Example › should have welcome screen

    The pending request #2 ("invoke") has been rejected due to the following error:

    The app has unexpectedly disconnected from Detox server.

      12 |
      13 |   it('should have welcome screen', async () => {
    > 14 |     await expect(element(by.text('Welcome to TP Mobile Shell'))).toBeVisible();
         |                                                                  ^
      15 |     await element(by.id('setting-btn')).tap();
      16 |     await expect(element(by.text('Settings'))).toBeVisible();
      17 |   });

      at Object.<anonymous> (e2e/settings.test.ts:14:66)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        49.873 s, estimated 50 s
Ran all test suites.
11:03:57.501 detox[41336] E lifecycle Command failed with exit code = 1:
jest --config e2e/jest.config.js
11:03:57.502 detox[41336] i ws-server Detox server has been closed gracefully
sarangupadhye@TPMac-MVNCQ2HC65 tp_mobile_shell_demo_app % 
```

**Comment by stefanbree** [comment]
still happening on the latest Detox version with Android running on ubuntu GitHub runner
