### ISSUE TITLE
Upgrading Detox from 20.10.0 to 20.12.0 (while on RN:v0.70.5) would cause java.lang.NoSuchMethodException: No such accessible method: matcherForTestId() on class: com.wix.detox.espresso.DetoxMatcher

### ISSUE THREAD

**Issue by mariushorvat** [wix/Detox#4188]
### What happened?

After I upgrade from v.20.10.0 to 20.12.0 I'm starting to get these errors in Android.     

java.lang.NoSuchMethodException: No such accessible method: matcherForTestId() on class: com.wix.detox.espresso.DetoxMatcher
        at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:317)
        at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:279)
        at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
        at com.wix.invoke.types.Target.invoke(Target.java:59)
        at com.wix.invoke.types.Target.invoke(Target.java:55)
        at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
        at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
        at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
        at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
        at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:64)
        at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
        at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:50)
        at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
        at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:920)

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

After I upgrade from v.20.10.0 to 20.12.0 I'm starting to get these errors in Android.  

### In what environment did this happen?

Detox version: 20.12.0
React Native version: 0.70.5
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 18.17.1
Device model: Local Android Studio Emulator 
Android version: 12 - SDK 31
Test-runner (select one): jest / other jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by mariushorvat** [comment]
More data that I've discovered since this issues was opened
1. Detox v20.11.0 up to v20.11.4 work with React Native version: 0.70.5 but only with Android SDK 32 and up
2. Detox v20.12.0 it does NOT work with Android SDK 32, I will update to SDK 33 and report back.

**Comment by andreialecu** [comment]
Seeing the same issue, were you able to find any solutions?

**Comment by andreialecu** [comment]
I resolved this by cleaning via `gradlew clean` and making sure `detox build -c android` runs and succeeds on the new version. 

There were various issues to fix to get the build to run, mostly from us being on an older Detox version and not updating in a while.

**Comment by PavanKumar77707** [comment]
Any Update on above issue? I am facing same error while upgrading detox 20.10.0 to 20.18.4   
 java.lang.NoSuchMethodException: No such accessible method: matcherForTestId() on class: com.wix.detox.espresso.DetoxMatcher
        at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:454)
        at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:419)
        at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
        at com.wix.invoke.types.Target.invoke(Target.java:59)
        at com.wix.invoke.types.Target.invoke(Target.java:55)
        at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
        at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
        at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
        at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
        at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:64)
        at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$6j3pFoicOzYCrlvuw8WBFq5rk88(Unknown Source:0)
        at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)

**Comment by gosha212** [comment]
Hi @NikolaSimsic, Please see my previous commit.
Is it a new project or it stopped working? Can you reproduce it on a side project?

**Comment by PavanKumar77707** [comment]
@gosha212 Thanks for your suggestion. After upgrading the ProGuard settings, I am able to run automation on the latest Android versions without any issues. However, when running existing automation on Fire TV, test cases are failing at the navigation step, where the navigation panel hides and expands when pressing the D-Pad left on the remote. It is not failing immediately but takes more than 10-15 minutes to perform the action.
