### ISSUE TITLE
App crashes when launching

### ISSUE THREAD

**Issue by malwatte** [wix/Detox#4189]
### Description

After creating the builds and starting react-native (`detox build --configuration android.emu.debug && npm start`)
Running `detox test --configuration android.emu.debug` fails with this error.

```
11:55:10.265 detox[39346] i starter.test.js is assigned to emulator-17826 (Pixel_6_API_30)
11:55:11.669 detox[39346] i An error occurred while waiting for the app to become ready. Waiting for disconnection...
  error: Failed to run application on the device
  
  HINT: Most likely, your main activity has crashed prematurely.
  
  Native stacktrace dump:
  java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
  	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~t7F9jKisqGWyL7crU7n_og==/com.mal.test-MVb6rmqSQY9Bvj3ZE7oA3g==/lib/arm64 flags = 0]
  	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/~~WHriDtJQjAZ5h_K-Dtk_0w==/com.mal.test.test-2dfRTqvNCgLyMikX9jtuqA==/base.apk!/lib/arm64-v8a]
  	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
  	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
  	Native lib dir: /data/app/~~t7F9jKisqGWyL7crU7n_og==/com.mal.test-MVb6rmqSQY9Bvj3ZE7oA3g==/lib/arm64
   result: 0
  	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
  	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
  	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
  	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
  	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
  	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:25)
  	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
  	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
  	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:394)
  	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:344)
  	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
  	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
  	at com.mal.test.MainApplication.onCreate(MainApplication.java:75)
  	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
  	at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:483)
  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
  	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
  	at android.os.Handler.dispatchMessage(Handler.java:106)
  	at android.os.Looper.loop(Looper.java:223)
  	at android.app.ActivityThread.main(ActivityThread.java:7656)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  
11:55:11.670 detox[39346] i The app disconnected.
```

But if I open the app manually on the simulator it opens without any issue.

Appreciate if someone can help.
Thanks.

### Your environment

Detox version: 20.12.0
React Native version: 0.68.3
Node version: 16.14.0
Device model: Android Emulator - Pixel 6 - API 30
OS: Mac OS 13.2.1
Test-runner (select one): jest

**Comment by loliveira-lawnstarter** [comment]
Hello, I am facing the same problem and I was not able to resolve the issue with the implementation above.

**Comment by arcifius** [comment]
on `app/build.gradle`, if you remove the part where we check if Hermes is enabled or not and make it always enabled, it apparently works... 

from
```gradle
if (enableHermes) {
    //noinspection GradleDynamicVersion
    implementation("com.facebook.react:hermes-engine:+") { // From node_modules
        exclude group:'com.facebook.fbjni'
    }
} else {
    implementation jscFlavor
}
```
to
```gradle
//noinspection GradleDynamicVersion
implementation("com.facebook.react:hermes-engine:+") { // From node_modules
    exclude group:'com.facebook.fbjni'
}
```

**Comment by loliveira-lawnstarter** [comment]
It has worked for me @arcifius. thanks

**Comment by henrikra** [comment]
@loliveira-lawnstarter What version of 
- React native
- detox
- android emulator and api level

You have?

**Comment by loliveira-lawnstarter** [comment]
Hey, my data is:
React native = "0.69.7"
Detox = "20.13.0"
Emulator and API = "3.2_QVGA_ADP2_API_33"
