### ISSUE TITLE
jest-jasmine2 issues

### ISSUE THREAD

**Issue by sibelius** [wix/detox#419]
I've got this running jest example https://github.com/wix/detox/tree/master/examples/demo-react-native-jest for android

`yarn test-android`

```jsx
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:194
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:195
    Error: spawn adb ENOENT
        at _errnoException (util.js:1024:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
        at onErrorNT (internal/child_process.js:372:16)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rotemmiz** [comment]
Please be more specific about the error... What machine are you running on ? Do you have ANDROID_HOME env var ?

We are about to land a PR (#424) fixing lots of the issues with jest, but this doesn't seem to be related, it seems like there are issues with starting `adb`

**Comment by sibelius** [comment]
mac os x sierra

`ANDROID_HOME = /Users/sibelius/Library/Android/sdk`

adb is working fine on my terminal

**Comment by rotemmiz** [comment]
try running detox test in verbose mode
`detox test -c android.emu.debug -l verbose`

**Comment by sibelius** [comment]
```
node_modules/.bin/jest e2e --runInBand
 rror: Could not create artifacts root dir: undefined/detox_artifacts.2017-11-21T21:50:52.099Z
 server listening on localhost:50032...
 onOpen [object Object]
 send: {"type":"login","params":{"sessionId":"6a044050-493a-0aca-33c9-4293d719fd7b","role":"tester"},"messageId":0}
 onMessage: {"type":"loginSuccess","params":{"sessionId":"6a044050-493a-0aca-33c9-4293d719fd7b","role":"tester"},"messageId":0}
  rbx
 : /Users/sibelius/Library/Android/sdk/tools/emulator -list-avds --verbose
 Nexus_4_API_25
 Nexus_5X_API_26
 Nexus_5_API_26
 O_Nexus_6_API_26_8.0
 Pixel_XL_API_27
 : stdout:
 emulator: Android virtual device file at: /Users/sibelius/.android/avd/Nexus_5X_API_26.ini
 emulator: virtual device content at /Users/sibelius/.android/avd/Nexus_5X_API_26.avd
 emulator: virtual device config file: /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/config.ini
 emulator: using core hw config path: /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/hardware-qemu.ini
 emulator: Found AVD target API level: 26
 emulator: Read property file at /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//build.prop
 emulator: No boot.prop property file found.
 emulator: found skin 'nexus_5x' in directory: /Users/sibelius/Library/Android/sdk/skins/
 emulator: autoconfig: -skin nexus_5x
 emulator: autoconfig: -skindir /Users/sibelius/Library/Android/sdk/skins/
 emulator: autoconfig: -kernel /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//kernel-ranchu
 emulator: Target arch = 'x86'
 emulator: Auto-config: -qemu -cpu qemu32
 emulator: Auto-detect: Kernel image requires new device naming scheme.
 emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
 emulator: autoconfig: -ramdisk /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//ramdisk.img
 emulator: Using initial system image: /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//system.img
 emulator: Using initial vendor image: /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//vendor.img
 emulator: autoconfig: -data /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/userdata-qemu.img
 emulator: autoconfig: -initdata /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/userdata.img
 emulator: autoconfig: -cache /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/cache.img
 emulator: autoconfig: -sdcard /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/sdcard.img
 emulator: Physical RAM size: 1536MB
 mulator stdout: 
 emulator: VM heap size 256MB is below hardware specified minimum of 384MB,setting it to that value
 emulator: System image is read only
 emulator: Found 2 DNS servers: fe80::1272:23ff:feac:7d07 192.168.15.1
 emulator: trying to load skin file '/Users/sibelius/Library/Android/sdk/skins//nexus_5x/layout'
 emulator: CPU Acceleration: working
 emulator: CPU Acceleration status: HAXM version 6.1.2 (4) is installed and usable.
 emulator: found skin 'nexus_5x' in directory: /Users/sibelius/Library/Android/sdk/skins/
 emulator: GPU emulation enabled using 'host' mode
 emulator: Initializing hardware OpenGLES emulation support
 emulator: Found 2 DNS servers: fe80::1272:23ff:feac:7d07 192.168.15.1
 Content of hardware configuration file:
   hw.cpu.arch = x86
   hw.cpu.model = qemu32
   hw.cpu.ncore = 2
   hw.ramSize = 1536
   hw.screen = multi-touch
   hw.mainKeys = false
   hw.trackBall = false
   hw.keyboard = true
   hw.keyboard.lid = false
   hw.keyboard.charmap = qwerty2
   hw.dPad = false
   hw.rotaryInput = false
   hw.gsmModem = true
   hw.gps = true 
   hw.battery = true
   hw.accelerometer = true
   hw.gyroscope = true
   hw.audioInput = true
   hw.audioOutput = true
   hw.sdCard = true
   hw.sdCard.path = /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/sdcard.img
   disk.cachePartition = true
   disk.cachePartition.path = /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/cache.img
   disk.cachePartition.size = 66m
   hw.lcd.width = 1080
   hw.lcd.height = 1920
   hw.lcd.depth = 16
   hw.lcd.density = 420
   hw.lcd.backlight = true
   hw.gpu.enabled = true
   hw.gpu.mode = host
   hw.gpu.blacklisted = no
   hw.initialOrientation = Portrait
   hw.camera.back = emulated
   hw.camera.front = emulated
   vm.heapSize = 384
   hw.sensors.light = true
   hw.sensors.pressure = true
   hw.sensors.humidity = true
   hw.sensors.proximity = true
   hw.sensors.magnetic_field = true
   hw.sensors.magnetic_field_uncalibrated = true
   hw.sensors.gyroscope_uncalibrated = true
   hw.sensors.orientation = true
   hw.sensors.temperature = true
   hw.useext4 = true
   kernel.path = /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//kernel-ranchu
   kernel.newDeviceNaming = yes
   kernel.supportsYaffs2 = no
   disk.ramdisk.path = /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//ramdisk.img
   disk.systemPartition.initPath = /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//system.img
   disk.systemPartition.size = 2562m
   disk.vendorPartition.initPath = /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//vendor.img
   disk.vendorPartition.size = 200m
   disk.dataPartition.path = /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/userdata-qemu.img
   disk.dataPartition.size = 800m
   disk.encryptionKeyPartition.path = /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/encryptionkey.img
   PlayStore.enabled = false
   avd.name = Nexus_5X_API_26
 .ulator stdout: 
 QEMU options list:
 emulator: argv[00] = "/Users/sibelius/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-i386"
 emulator: argv[01] = "-no-audio"
 emulator: argv[02] = "-dns-server"
 emulator: argv[03] = "fe80::1272:23ff:feac:7d07,192.168.15.1"
 emulator: argv[04] = "-serial"
 emulator: argv[05] = "null"
 emulator: argv[06] = "-cpu"
 emulator: argv[07] = "android32"
 emulator: argv[08] = "-enable-hvf"
 emulator: argv[09] = "-smp"
 emulator: argv[10] = "cores=2"
 emulator: argv[11] = "-m"
 emulator: argv[12] = "1536"
 emulator: argv[13] = "-lcd-density"
 emulator: argv[14] = "420"
 emulator: argv[15] = "-kernel"
 emulator: argv[16] = "/Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//kernel-ranchu"
 emulator: argv[17] = "-initrd"
 emulator: argv[18] = "/Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//ramdisk.img"
 emulator: argv[19] = "-object"
 emulator: argv[20] = "iothread,id=disk-iothread"
 emulator: argv[21] = "-nodefaults"
 emulator: argv[22] = "-drive"
 emulator: argv[23] = "if=none,overlap-check=none,cache=unsafe,index=0,id=system,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/system.img.qcow2,read-only,l2-cache-size=1048576"
 emulator: argv[24] = "-device"
 emulator: argv[25] = "virtio-blk-pci,drive=system,modern-pio-notify"
 emulator: argv[26] = "-drive"
 emulator: argv[27] = "if=none,overlap-check=none,cache=unsafe,index=1,id=cache,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/cache.img.qcow2,l2-cache-size=1048576"
 emulator: argv[28] = "-device"
 emulator: argv[29] = "virtio-blk-pci,drive=cache,modern-pio-notify"
 emulator: argv[30] = "-drive"
 emulator: argv[31] = "if=none,overlap-check=none,cache=unsafe,index=2,id=userdata,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/userdata-qemu.img.qcow2,l2-cache-size=1048576"
 emulator: argv[32] = "-device"
 emulator: argv[33] = "virtio-blk-pci,drive=userdata,modern-pio-notify"
 emulator: argv[34] = "-drive"
 emulator: argv[35] = "if=none,overlap-check=none,cache=unsafe,index=3,id=encrypt,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/encryptionkey.img.qcow2,l2-cache-size=1048576"
 emulator: argv[36] = "-device"
 emulator: argv[37] = "virtio-blk-pci,drive=encrypt,modern-pio-notify"
 emulator: argv[38] = "-drive"
 emulator: argv[39] = "if=none,overlap-check=none,cache=unsafe,index=4,id=vendor,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/vendor.img.qcow2,read-only,l2-cache-size=1048576"
 emulator: argv[40] = "-device"
 emulator: argv[41] = "virtio-blk-pci,drive=vendor,modern-pio-notify"
 emulator: argv[42] = "-drive"
 emulator: argv[43] = "if=none,overlap-check=none,cache=unsafe,index=5,id=sdcard,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/sdcard.img.qcow2,l2-cache-size=1048576"
 emulator: argv[44] = "-device"
 emulator: argv[45] = "virtio-blk-pci,drive=sdcard,modern-pio-notify"
 emulator: argv[46] = "-netdev"
 emulator: argv[47] = "user,id=mynet"
 emulator: argv[48] = "-device"
 emulator: argv[49] = "virtio-net-pci,netdev=mynet"
 emulator: argv[50] = "-show-cursor"
 emulator: argv[51] = "-L"
 emulator: argv[52] = "/Users/sibelius/Library/Android/sdk/emulator/lib/pc-bios"
 emulator: argv[53] = "-soundhw"
 emulator: argv[54] = "hda"
 emulator: argv[55] = "-vga"
 emulator: argv[56] = "none"
 emulator: argv[57] = "-append"
 emulator: argv[58] = "qemu=1 androidboot.hardware=ranchu clocksource=pit android.qemud=1 console=0
  android.checkjni=1 qemu.gles=1 qemu.encrypt=1 qemu.opengles.version=131072 cma=288M ndns=2 androidboot.android_dt_dir=/sys/bus/platform/devices/ANDR0001:00/properties/android/"
 emulator: argv[59] = "-android-hw"
 emulator: argv[60] = "/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/hardware-qemu.ini"
 Concatenated QEMU options:
  /Users/sibelius/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-i386 -no-audio -dns-server fe80::1272:23ff:feac:7d07,192.168.15.1 -serial null -cpu android32 -enable-hvf -smp cores=2 -m 1536 -lcd-density 420 -kernel /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//kernel-ranchu -initrd /Users/sibelius/Library/Android/sdk/system-images/android-26/google_apis/x86//ramdisk.img -object iothread,id=disk-iothread -nodefaults -drive if=none,overlap-check=none,cache=unsafe,index=0,id=system,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/system.img.qcow2,read-only,l2-cache-size=1048576 -device virtio-blk-pci,drive=system,modern-pio-notify -drive if=none,overlap-check=none,cache=unsafe,index=1,id=cache,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/cache.img.qcow2,l2-cache-size=1048576 -device virtio-blk-pci,drive=cache,modern-pio-notify -drive if=none,overlap-check=none,cache=unsafe,index=2,id=userdata,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/userdata-qemu.img.qcow2,l2-cache-size=1048576 -device virtio-blk-pci,drive=userdata,modern-pio-notify -drive if=none,overlap-check=none,cache=unsafe,index=3,id=encrypt,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/encryptionkey.img.qcow2,l2-cache-size=1048576 -device virtio-blk-pci,drive=encrypt,modern-pio-notify -drive if=none,overlap-check=none,cache=unsafe,index=4,id=vendor,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/vendor.img.qcow2,read-only,l2-cache-size=1048576 -device virtio-blk-pci,drive=vendor,modern-pio-notify -drive if=none,overlap-check=none,cache=unsafe,index=5,id=sdcard,file=/Users/sibelius/.android/avd/Nexus_5X_API_26.avd/sdcard.img.qcow2,l2-cache-size=1048576 -device virtio-blk-pci,drive=sdcard,modern-pio-notify -netdev user,id=mynet -device virtio-net-pci,netdev=mynet -show-cursor -L /Users/sibelius/Library/Android/sdk/emulator/lib/pc-bios -soundhw hda -vga none -append 'qemu=1 androidboot.hardware=ranchu clocksource=pit android.qemud=1 console=0 android.checkjni=1 qemu.gles=1 qemu.encrypt=1 qemu.opengles.version=131072 cma=288M ndns=2 androidboot.android_dt_dir=/sys/bus/platform/devices/ANDR0001:00/properties/android/' -android-hw /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/hardware-qemu.ini
 emulator: Android qemu version 26.1.4.0 (build_id 4266726) (CL:add3139bafe4f34502c851716afcee834068103a)
 mulator stdout: 
 emulator: Starting QEMU main loop
 path /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/system.img.qcow2
 path /Users/sibelius/.android/avd/Nexus_5X_API_26.avd/vendor.img.qcow2
 emulator: registered 'boot-properties' qemud service
 emulator: Adding boot property: 'ro.opengles.version' = '131072'
 emulator: Adding boot property: 'qemu.sf.fake_camera' = 'both'
 emulator: Adding boot property: 'dalvik.vm.heapsize' = '384m'
 emulator: Adding boot property: 'qemu.hw.mainkeys' = '0'
 emulator: Adding boot property: 'qemu.sf.lcd_density' = '420'
 emulator: goldfish_events.have-dpad: false
 emulator: goldfish_events.have-trackball: false
 emulator: goldfish_events.have-camera: true
 emulator: goldfish_events.have-keyboard: true
 emulator: goldfish_events.have-lidswitch: false
 emulator: goldfish_events.have-touch: false
 emulator: goldfish_events.have-multitouch: true
 emulator: control console listening on port 5554, ADB on port 5555
 mulator stdout: 
 Not using any http proxy
 emulator: android_hw_fingerprint_init: fingerprint qemud listen service initialized
 mulator stdout: 
 mulator stdout: 
 emulator: OpenGL Vendor=[Google (Intel Inc.)]
 emulator: OpenGL Renderer=[Android Emulator OpenGL ES Translator (Intel(R) Iris(TM) Graphics 6100)]
 emulator: OpenGL Version=[OpenGL ES 2.0 (2.1 INTEL-10.28.29)]
 mulator stdout: 
 Your emulator is out of date, please update by launching Android Studio:
  - Start Android Studio
  - Select menu "Tools > Android > SDK Manager"
  - Click "SDK Tools" tab
  - Check "Android Emulator" checkbox
  - Click "OK"t: 
 mulator stdout: 
 mulator stdout: 
 emulator: onGuestSendCommand: [0x7fbd1ace8190] Adb connected, start proxing data
 mulator stdout: 
 : /Users/sibelius/Library/Android/sdk/platform-tools/adb  devices
 List of devices attached
 emulator-5554	offline
 920105423892134a	device
 : stdout:
 : stdout:
 : /Users/sibelius/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
 send: {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxAssertion"},"method":"assertMatcher","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["welcome"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForSufficientlyVisible","args":[]}}]},"messageId":1}
 send: {"type":"currentStatus","params":{},"messageId":2}
 emulator: _hwFingerprint_connect: connect finger print listen is called
 mulator stdout: 
 mulator stdout: 
 emulator: got message from guest system fingerprint HAL
 mulator stdout: 
 mulator stdout: 
 emulator: ### WARNING: /etc/localtime does not point to /usr/share/zoneinfo/, can't determine zoneinfo timezone name
 mulator stdout: 
 send: {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["hello_button"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.action.ViewActions"},"method":"click","args":[]}}]},"messageId":3}
 send: {"type":"currentStatus","params":{},"messageId":4}
 send: {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["world_button"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.action.ViewActions"},"method":"click","args":[]}}]},"messageId":5}
 send: {"type":"currentStatus","params":{},"messageId":6}
 send: {"type":"cleanup","params":{"stopRunner":true},"messageId":7}

 RUNS  e2e/app.test.js

```

- it keeps like that for a lot of time
- it opens the android emulator
- it doesn't open the app on the emulator

**Comment by sibelius** [comment]
```jsx
ChildProcessError: Command failed: /Users/sibelius/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
     `/Users/sibelius/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82` (exited with error code 137)
```

`adb devices` is working fine
```
List of devices attached
emulator-5554	device
```

**Comment by rotemmiz** [comment]
Got it, it's an issue with syncing the boot of API26 emulators, I already started handling this, will report  back soon
