### ISSUE TITLE
App crashes with `java.lang.NoSuchMethodError: No virtual method setFutureLcom/google/common/util/concurrent/ListenableFuture`

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#4304]
### What happened?

After upgrading from Detox 20.14.2 to Detox 20.14.3, some tests in our app began crashing with this error:

```
The pending request #7 ("invoke") has been rejected due to the following error:

The app has crashed, see the details below:

@Thread main(2):
java.lang.NoSuchMethodError: No virtual method setFuture(Lcom/google/common/util/concurrent/ListenableFuture;)Z in class Landroidx/concurrent/futures/ResolvableFuture; or its super classes (declaration of 'androidx.concurrent.futures.ResolvableFuture' appears in /data/app/com.wix.admin.dev-J40McJMsuvNa4tcMtvMwKQ==/base.apk)
	at androidx.test.core.app.DeviceCapture$forceRedrawGlobalWindowViews$1.run(DeviceCapture.kt:168)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Check device logs for full details!
```

### What was the expected behaviour?

It should not crash.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.14.3
React Native version: 0.71.x
Has Fabric (React Native's new rendering system) enabled: no
Node version: 16.20.1
Device model: Pixel 3a
Android version: API 31
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by noomorph** [comment]
Similar issue: https://github.com/slackhq/keeper/issues/108#issuecomment-1489915933
