### ISSUE TITLE
Getting error - Detox worker instance has not been installed in this context (DetoxSecondaryContext) while running detox with updated globalSetup

### ISSUE THREAD

**Issue by jyotsna-hh** [wix/Detox#4308]
### What happened?

I have created a envSetup.ts file with following content - 
```
import { device } from "detox";
module.exports = async () => {
  await require("detox/runners/jest/index").globalSetup();
  await device.launchApp();
};
```

And updated the jest.config.js file with- 
`globalSetup: "<rootDir>/e2e/envSetup.ts"`

Then I have executed the test - 
`detox test -c android.emu.release -l verbose`

Got the error - 
```
12:01:32.379 detox[18527] i ws-server Detox server listening on localhost:56172...
12:01:32.385 detox[18527] B lifecycle jest --config e2e/jest.config.js
12:01:33.847 detox[18530] i user DetoxRuntimeError: Jest: Got error running globalSetup - /Users/jyotsananamdev/detox/detox-framework/e2e/envSetup.ts, reason: Detox worker instance has not been installed in this context (DetoxSecondaryContext).

HINT: If you are using Detox with Jest according to the latest guide, please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues
Otherwise, make sure you call detox.installWorker() beforehand.
    at get [worker] (/Users/jyotsananamdev/detox/detox-framework/node_modules/detox/src/realms/DetoxContext.js:119:13)
    at /Users/jyotsananamdev/detox/detox-framework/node_modules/detox/src/realms/DetoxContext.js:72:36
    at getter (/Users/jyotsananamdev/detox/detox-framework/node_modules/funpermaproxy/lib/permaproxy.js:10:24)
    at Object.get (/Users/jyotsananamdev/detox/detox-framework/node_modules/funpermaproxy/lib/permaproxy.js:21:22)
    at module.exports (/Users/jyotsananamdev/detox/detox-framework/e2e/envSetup.ts:10:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/core/build/runGlobalHook.js:109:13
    at async waitForPromiseWithCleanup (/Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/transform/build/ScriptTransformer.js:160:5)
    at async ScriptTransformer.requireAndTranspileModule (/Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/transform/build/ScriptTransformer.js:808:16)
    at async runGlobalHook (/Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/core/build/runGlobalHook.js:101:9)
    at async runJest (/Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/core/build/runJest.js:327:5)
    at async _run10000 (/Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/core/build/cli/index.js:343:7)
    at async runCLI (/Users/jyotsananamdev/detox/detox-framework/node_modules/@jest/core/build/cli/index.js:198:3)
    at async Object.run (/Users/jyotsananamdev/detox/detox-framework/node_modules/jest-cli/build/run.js:130:37)
  origin: at node_modules/jest-cli/build/run.js:136:15
12:01:33.991 detox[18527] E lifecycle Command failed with exit code = 1:
jest --config e2e/jest.config.js
12:01:34.094 detox[18527] i ws-server Detox server has been closed gracefully
```

### What was the expected behaviour?

This should launch app 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 20.14.3
React Native version:  0.72.7
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: v18.15.0
Test-runner (select one): jest / other -jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
Detox doesn't support creating devices in globalSetup. Please use the official setup guide on the website: https://wix.github.io/Detox

**Comment by jyotsna-hh** [comment]
@noomorph Can we create devices globally in detox ?

**Comment by noomorph** [comment]
What do you mean, @jyotsna-hh ?

**Comment by jyotsna-hh** [comment]
Right now I'm using `await device.launchApp();` command in each script instead I wanted to run it once for all my test scripts. @noomorph

**Comment by noomorph** [comment]
You should use beforeAll() hook in a file under setupFilesAfterEnv. Please refer to Jest documentation
