### ISSUE TITLE
Upgrading 20.13.1 -> 20.14.3 throws  an error upon calling  `waitFor(element(by.id('...))).toBeVisible().withTimeout()`

### ISSUE THREAD

**Issue by Overtorment** [wix/Detox#4310]
### What happened?

Routine upgrading Detox 20.13.1 -> 20.14.3
Looks like everything mostly works, but tests now fail on

```
   await waitFor(element(by.id('SelfTestOk')))
     .toBeVisible()
     .withTimeout(300 * 1000);
```

with error

`    Test Failed: Class 'org.hamcrest.StringDescription' does not implement interface 'java.lang.Iterable' in call to 'java.util.Iterator java.lang.Iterable.iterator()' (de
claration of 'org.hamcrest.BaseDescription' appears in /data/app/io.bluewallet.bluewallet.test-owrQjMwN-xIT9bkz8pcpTQ==/base.apk)`

![image](https://github.com/wix/Detox/assets/1913337/ba8ace02-61f3-4ef1-8bd8-a66546255823)

quickly googling the problem, looks like the issue might be in Espresso, and indeed, inspecting the diff between 20.13.1 and 20.14.3 shows that Espresso was bumped from 3.4.0 to 3.5.1

### What was the expected behaviour?

passing test

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

https://github.com/BlueWallet/BlueWallet/pull/5918

### In what environment did this happen?

Detox version: 20.14.3
React Native version: 0.71.14
Has Fabric (React Native's new rendering system) enabled: no
Node version: 18.17.1
Device model: emu
Android version: 29 AOSP
Test-runner (select one): jest 

### Detox logs

<details><summary>Detox logs</summary>

[detox.log](https://github.com/wix/Detox/files/13761810/detox.log)
[detox.trace.json](https://github.com/wix/Detox/files/13761811/detox.trace.json)

</details>

### Device logs

<details><summary>Device logs</summary>

[device.log](https://github.com/wix/Detox/files/13761807/device.log)
[emulator-15776 2023-12-24 12-25-20Z.startup.log](https://github.com/wix/Detox/files/13761813/emulator-15776.2023-12-24.12-25-20Z.startup.log)

</details>

**Comment by d4vidi** [comment]
@Overtorment thanks for the detailed report! Indeed this looks like there could be further ProGuard rules we might have missed with the bump to the next `Espresso`. @gosha212 WDYT? Could you take care of it?

**Comment by d4vidi** [comment]
```
12-24 12:25:19.924 17808 17887 D DetoxWSClient: Received action 'invoke' (ID #6, params={"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxAssertion"},"method":"waitForAssertMatcher","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["SelfTestOk",{"type":"boolean","value":false}]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForSufficientlyVisible","args":[{"type":"Integer","value":75}]}},{"type":"Double","value":300}]})
12-24 12:25:19.924 17808 17885 I DetoxDispatcher: Handling action 'invoke' (ID #6)...
12-24 12:25:19.925 17808 17885 D Detox   : class com.wix.detox.espresso.DetoxMatcher, matcherForTestId, [SelfTestOk, false]
12-24 12:25:19.926 17808 17885 D Detox   : class androidx.test.espresso.Espresso, onView, [(view.getTag() is "SelfTestOk" and view has effective visibility <VISIBLE>)]
12-24 12:25:19.926 17808 17885 D Detox   : class com.wix.detox.espresso.DetoxMatcher, matcherForSufficientlyVisible, [75]
12-24 12:25:19.926 17808 17885 D Detox   : class com.wix.detox.espresso.DetoxAssertion, waitForAssertMatcher, [androidx.test.espresso.ViewInteraction@fafc69e, (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area), 300.0]
12-24 12:25:19.961 17808 17808 I ViewInteraction: Checking 'MatchesViewAssertion(Detox){viewMatcher=(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)}' assertion on view (view.getTag() is "SelfTestOk" and view has effective visibility <VISIBLE>)
12-24 12:25:19.980 17808 17808 D takeScreenshot: Found 1 global views to redraw
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: Test exception
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: java.lang.reflect.InvocationTargetException
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:443)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.invoke.types.Target.invoke(Target.java:59)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:64)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.os.Handler.handleCallback(Handler.java:873)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.os.Looper.loop(Looper.java:193)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:50)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:4)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at java.lang.Thread.run(Thread.java:764)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: Caused by: java.lang.IncompatibleClassChangeError: Class 'org.hamcrest.StringDescription' does not implement interface 'java.lang.Iterable' in call to 'java.util.Iterator java.lang.Iterable.iterator()' (declaration of 'org.hamcrest.BaseDescription' appears in /data/app/io.bluewallet.bluewallet.test-G3vWW_Wl_2Wqs_H1-46Geg==/base.apk)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at org.hamcrest.BaseDescription.appendValueList(BaseDescription.java:81)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at androidx.test.espresso.matcher.ViewMatchers.getMismatchDescriptionString(ViewMatchers.java:3)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:5)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.wix.detox.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:53)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:14)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.os.Handler.handleCallback(Handler.java:873)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.os.Looper.loop(Looper.java:193)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-24 12:25:20.142 17808 17885 I DetoxActionHandlers: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by d4vidi** [comment]
@Overtorment I wonder, this could be a matter of rebuilding Detox and everything-native from scratch. Could you try a good wipe of everything, following the Detox bump, and a retry?

**Comment by Overtorment** [comment]
Hmm I could give it another try, but on our CI everything gets build from scratch every time, and I initially encountered it on CI. 
Unless there are some steps I can add to our CI to make sure that everything is 100% absolutely surely guaranteed clean..?

**Comment by gosha212** [comment]
Hi @Overtorment,
Can you share what is your version of AGP and what is your compile sdk version?

**Comment by Overtorment** [comment]
@gosha212  `compileSdkVersion = 33`
gradle: `7.4.2`

the rest you can see yourself here, its opensource: https://github.com/BlueWallet/BlueWallet/tree/master/android

**Comment by noomorph** [comment]
Hm, this looks like this, doesn't it? 

https://github.com/android/android-test/issues/1642

**Comment by Overtorment** [comment]
hmm, we do have `minSdkVersion = 28`

**Comment by gosha212** [comment]
@Overtorment thanks you for your detailed feedback! I'm on it

**Comment by gosha212** [comment]
Hi @Overtorment,
I've tried to reproduce the problem locally on my machine the following branch:  renovate/detox-20.x

![Image](https://github.com/wix/Detox/assets/11298548/7c5dbaf8-09be-4ebc-add4-2a7eb56ff407)
Everything works perfect. It look like a problem with your local environment. Try to remove the node_modules, clean android project and rebuild everything again

**Comment by Overtorment** [comment]
renovate bot just sent us a new PR, bumping Detox to 20.14.8  
https://github.com/BlueWallet/BlueWallet/pull/5970

in a changelog I see  `Fixed crash caused by new version of Espresso (3.5.1) by [@​gosha212](https://togithub.com/gosha212) in [#​4305](https://togithub.com/wix/Detox/issues/4305)`

and e2e test passed on those issues I posted in this ticket (but failed on smth else, looks urelated and like smth i should just fix on our end)


soo looks very promising! I will doublecheck, fix the faulty test and will report back

**Comment by Overtorment** [comment]
solved

**Comment by ghuseynova1** [comment]
> solved

@Overtorment  How did you solve this problem?
