### ISSUE TITLE
NoSuchMethodException for scrollToEdge

### ISSUE THREAD

**Issue by aaronpliu** [wix/Detox#4348]
### What happened?

scrollTo(edge) throw java NoSuchMethodException in Detox v20.16.0, see error logs

### What was the expected behaviour?

scrollTo is working in latest detox version

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Directly call scrollTo(edge) method

### In what environment did this happen?

Detox version: v20.16.0
React Native version: 0.71.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: v16.19
Device model:  Android Simulator
Android version: 14 / API 34
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
Error: Exception caugth in scrollTo: Error: DetoxRuntimeError: java.lang.NoSuchMethodException: No such accessible method: scrollToEdge() on class: com.wix.detox.espresso.DetoxAction
       at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:439)
       at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
       at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
       at com.wix.invoke.types.Target.invoke(Target.java:59)
       at com.wix.invoke.types.Target.invoke(Target.java:55)
       at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
       at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
       at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
       at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
       at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:76)
       at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
       at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:62)
       at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
       at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:4)
       at java.lang.Thread.run(Thread.java:1012)

      Check device logs for full details!

       at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:439)
       at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
       at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
       at com.wix.invoke.types.Target.invoke(Target.java:59)
       at com.wix.invoke.types.Target.invoke(Target.java:55)
       at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
       at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
       at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
       at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
       at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:76)
       at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
       at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:62)
       at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
       at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:4)
       at java.lang.Thread.run(Thread.java:1012)


```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by d4vidi** [comment]
Hey @aaronpliu! Please be sure to rebuild everything in your project from scratch. This is usually happens due to a mismatch between Detox's javascript and android-native code.

@gosha212 fyi

**Comment by aaronpliu** [comment]
yup! rebuild app/debug apk. It looks good. But still see #4312 issue.

**Comment by gosha212** [comment]
Hi @aaronpliu , #4312 is also fixed. Let me know if you still have any issue with it. Please provide us an example project in case it doesn't work.
