### ISSUE TITLE
Detox is broken due to detox-server version 6.0.0 not released

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#437]
As mentioned [here](https://github.com/wix/detox/issues/431#issuecomment-347382844).

**Comment by plasticine** [comment]
`6.0.1` seems to be released — think this can be safely closed.

**Comment by ca057** [comment]
Thanks for the fast fixes and releases!

Apparently for me the installation still seems to be broken, running:
```bash
yarn cache clean
yarn add detox@^6.0.1 --verbose
```
produces the following error output (where `<CWD>` is my current working directory):
```bash
# ...
verbose 303.613 Error: <CWD>/node_modules/detox: Command failed.
Exit code: 1
Command: scripts/postinstall.sh
Arguments:
Directory: <CWD>/node_modules/detox
Output:
Extracting Detox sources...
./EarlGrey/build/EarlGrey.build/Debug-iphoneos/EarlGrey.build/Objects-normal/armv7/GREYKeyboard.o: (Empty error message)
tar: Error exit delayed from previous errors.
    at ChildProcess.proc.on (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:29991:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error <CWD>/node_modules/detox: Command failed.
Exit code: 1
Command: scripts/postinstall.sh
Arguments:
Directory: <CWD>/node_modules/detox
Output:




```
Please let me know in case you need any further information, I'm happy to help out.

**Comment by akuschqa** [comment]
I have the same problem with installing **6.0.1** via npm
```
> detox@6.0.1 postinstall /Users/rean/Projects/SpaceNation/spacenation_reactnative/node_modules/detox
> scripts/postinstall.sh

Extracting Detox sources...
./EarlGrey/build/EarlGrey.build/Debug-iphoneos/EarlGrey.build/Objects-normal/armv7/GREYKeyboard.o: (Empty error message)
tar: Error exit delayed from previous errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@6.0.1 postinstall: `scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the detox@6.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by philss** [comment]
I got the same error here while trying to install via `npm install --verbose --save-dev detox`:

```
npm verb stack Error: detox@6.0.1 postinstall: `scripts/postinstall.sh`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid detox@6.0.1
```

**Comment by rotemmiz** [comment]
6.0.2 is out

**Comment by philss** [comment]
Thanks, @rotemmiz!

**Comment by ca057** [comment]
Working again, thanks! 👍
