### ISSUE TITLE
getAttributes() on radio buttons is not working

### ISSUE THREAD

**Issue by pawannomula** [wix/Detox#4370]
### What happened?

I have a radio container with container id "radio-container", trying to get attributes using below code 
`const verificationAttributes = await element(
          by.id('radio-container')
        ).getAttributes();`
tried getAttributes().enabled as well.

My goal is to read labels in the radio container.

### What was the expected behaviour?

`const verificationAttributes = await element( by.id('radio-container')).getAttributes();`
Receiving  verificationAttributes = undefined but expected some elements. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

getAttributes() by Id.

### In what environment did this happen?

Detox version: 20.13.15
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: >= 16
Device model:  Iphone 15
iOS version: 17.2
macOS version: 
Xcode version: 
Test-runner (select one): jest / other Jest

### Detox logs

<details><summary>Detox logs</summary>

```
 ● add beneficiary E2E › adding joint owner as a beneficiary

    TypeError: Cannot read properties of undefined (reading 'toLowerCase')

      101 |         ).getAttributes();
      102 |         if (
    > 103 |           verificationAttributes.label.toLowerCase().includes("phone") ||
          |                                        ^
      104 |           verificationAttributes.label.toLowerCase().includes("email")
      105 |         ) {
      106 |           await element(by.id('radio-container')).tap();

      at Login.toLowerCase (screens/login.js:103:40)
      at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by pawannomula** [comment]
<img width="656" alt="Screenshot 2024-02-12 at 1 38 12 PM" src="https://github.com/wix/Detox/assets/19434596/25b95ecc-b6a3-4d0b-9165-e9b671080a05">
