### ISSUE TITLE
Detox step into infinite wait with message "the app seems to be idle"

### ISSUE THREAD

**Issue by aaronpliu** [wix/Detox#4375]
### What happened?

In a normal test scenario, when an unexpected popup appear or element not found, the detox will loop to print "The app seems to be idle" instead of throwing error or stop. It never exit or continue after a long long time

### What was the expected behaviour?

either exit execution or throw error if no condition meet (e.g. element not visible or exist or unexpected dialog)

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.16.0
React Native version: 0.71.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: v16.19.1
Device model: Android
iOS version: 17
macOS version: 13.6
Xcode version: 14.2
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
The app seems to be idle
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by aaronpliu** [comment]
@d4vidi , @gosha212 would you please take a look at it? no more detailed log to double check, it encountered this error in some test scenarios. for instance, unexpected popup appear, element not found, or page auto refresh...etc.

Thanks in advance

**Comment by aaronpliu** [comment]
Experiencing the issue all the time :-(

**Comment by aaronpliu** [comment]
any workaround to avoid or bypass?

**Comment by gosha212** [comment]
@aaronpliu @KaterinaUK Can you share a sample project please?
How often is it reproduces (Always / Sometime)?

**Comment by KaterinaUK** [comment]
Hi @gosha212 , Unfortunately, I do not have a sample project, it is a private project that I am working on right now. I have it every day, this is the error I can see: `Test Failed: Wait for [LooperIdlingResource-101-mqt_js] to become idle timed out
    at Object.withTimeout (/Users/runner/work/app/app/e2e/new-user.test.js:26:8)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/runner/work/app/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/runner/work/app/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by d4vidi** [comment]
`LooperIdlingResource-101-mqt_js` suggests the Javascript code is running, its as simple is that. The app is working on something.

**Comment by aaronpliu** [comment]
> [@aaronpliu](https://github.com/aaronpliu) [@KaterinaUK](https://github.com/KaterinaUK) Can you share a sample project please? How often is it reproduces (Always / Sometime)?

always or very likely ran into the "wait" issue

**Comment by gosha212** [comment]
Can you upgrade to rn 77 and detox to 20.37 and send us an example project?

**Comment by aaronpliu** [comment]
> Can you upgrade to rn 77 and detox to 20.37 and send us an example project?

Using detox 20.38 and testing on RN 0.74.1 currently. Usually the behavior occur when to encounter a rolling banner or continuous animations

**Comment by gosha212** [comment]
@aaronpliu So this is not a bug. Detox waits for application idle. If you have infinitive animation it will not move to the next step. You have to disable the synchronization. Please follow the following instructions for solving the issue: https://wix.github.io/Detox/docs/troubleshooting/synchronization/
