### ISSUE TITLE
Sometimes detox iOS tests can't start up on Bitrise CI

### ISSUE THREAD

**Issue by adamivancza** [wix/Detox#4384]
### What happened?

Not always, but quite frequently our e2e tests are not starting up on Bitrise CI. Everything worked fine on Xcode 14.2 but we want to update to Xcode 15.2 where this issue is happening. 

### What was the expected behaviour?

Tests are executing without any issue

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.18.3
React Native version: 0.72.5
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 18.18.2
Device model: -
iOS version: 17.0
macOS version: 13.5
Xcode version: 15.2
Test-runner (select one): jest

https://stacks.bitrise.io/stack_reports/osx-xcode-15.2.x

### Detox logs

<details><summary>Detox logs</summary>

```
+ yarn detox reset-lock-file
yarn run v1.22.19
$ /Users/vagrant/git/node_modules/.bin/detox reset-lock-file
Cleaned lock file at: /Users/vagrant/Library/Detox/device.registry.json
Done in 0.16s.
+ yarn detox:test:ios:release --artifacts-location /Users/vagrant/deploy
yarn run v1.22.19
$ detox test --configuration ios.sim.release --record-logs failing --take-screenshots failing  --retries 1 --maxWorkers 2 --record-videos failing --artifacts-location /Users/vagrant/deploy
16:48:08.222 detox[4435] B DETOX_TEST_IOS_APP_ARTIFACT="/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/_artifact_pull148002872/[REDACTED].app" DETOX_ARTIFACTS_LOCATION="/Users/vagrant/deploy" DETOX_CONFIGURATION="ios.sim.release" DETOX_RECORD_LOGS="failing" DETOX_RECORD_VIDEOS="failing" DETOX_RETRIES=1 DETOX_TAKE_SCREENSHOTS="failing" jest --config e2e/jest.config.js --maxWorkers 2 e2e
16:51:39.314 detox[4480] i map_on_list.e2e.ts is assigned to 1A1B136F-8300-4783-9C26-595F9AB4C583 (iPhone 15)
16:51:40.278 detox[4479] i basic_my_lists.e2e.ts is assigned to A1EB58C8-1B61-45DD-9BEB-24DEEBD67562 (iPhone 15)
16:56:43.050 detox[4480] i 
  error: Exceeded timeout of 300000ms while handling jest-circus "hook_start" event
16:56:46.123 detox[4479] i 
  error: Exceeded timeout of 300000ms while handling jest-circus "hook_start" event
16:57:30.486 detox[4479] i IOServiceMatchingfailed for: AppleM2ScalerCSCDriver
16:57:30.540 detox[4480] i IOServiceMatchingfailed for: AppleM2ScalerCSCDriver
17:06:55.213 detox[4480] i 
  error: Exceeded timeout of 300000ms while handling jest-circus "test_fn_failure" event
17:06:57.538 detox[4479] i 
  error: Exceeded timeout of 300000ms while handling jest-circus "test_fn_failure" event
17:12:03.125 detox[4480] i 
  error: Exceeded timeout of 300000ms while handling jest-circus "test_done" event
17:12:03.125 detox[4479] i 
  error: Exceeded timeout of 300000ms while handling jest-circus "test_done" event
17:15:52.058 detox[4480] i Detected an attempt to close an already closing or closed web socket.
Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues
FAIL e2e/tests/multiple_lists/map_on_list.e2e.ts
  ● Test suite failed to run
    Exceeded timeout of 30000ms while tearing down Detox environment
17:18:10.476 detox[4480] i The app has not responded to the network requests below:
  (id = 0) login: {"sessionId":"835fdc19-e6f9-388a-2b9d-60e69b58fc55","role":"tester"}
Unresponded network requests might result in timeout errors in Detox tests.
FAIL e2e/tests/deeplinks.e2e.ts
  ● Test suite failed to run
    The pending request #0 ("login") has been rejected due to the following error:
    The tester has not received a response within 1000ms timeout to the message:
    Login {
      type: 'login',
      params: [Object],
      messageId: 0
    }
/Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:181
        onCompromised: (err) => { throw err; },
                                  ^
Error: Unable to update lock within the stale threshold
    at /Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:109:21
    at newFs.<computed> [as utimes] (/Users/vagrant/git/node_modules/proper-lockfile/lib/adapter.js:20:13)
    at Timeout._onTimeout (/Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:100:20)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ECOMPROMISED'
}
Node.js v18.18.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:28:11.165 detox[4480] i cannot overwrite: "/private/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/4a1038db-0012-4b76-b95e-4142ce926ea3.detox.png" => "/Users/vagrant/deploy/ios.sim.release.2024-02-27 16-48-08Z/testStart.png"
17:28:11.765 detox[4480] i cannot overwrite: "/private/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/574c31cb-e3af-4cf6-bf6a-b4ce8abf9874.detox.png" => "/Users/vagrant/deploy/ios.sim.release.2024-02-27 16-48-08Z/testFnFailure.png"
17:28:12.116 detox[4480] i Suppressed error inside function call.
  error: Error: dest already exists.
      at /Users/vagrant/git/node_modules/detox/node_modules/fs-extra/lib/move/move.js:51:31
      at /Users/vagrant/git/node_modules/universalify/index.js:22:54
17:29:13.357 detox[4479] i com.[REDACTED].staging launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn A1EB58C8-1B61-45DD-9BEB-24DEEBD67562 log stream --level debug --style compact --predicate 'process == "[REDACTED]"'
17:29:13.435 detox[4480] i com.[REDACTED].staging launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 1A1B136F-8300-4783-9C26-595F9AB4C583 log stream --level debug --style compact --predicate 'process == "[REDACTED]"'
```

</details>

### Device logs

<details><summary>Device logs</summary>

device log is HUGE so you can download it from here: https://drive.google.com/file/d/1seyJw5QN0MF1brxsA3NjaajBWvvbvm0b/view?usp=sharing

</details>

**Comment by huszzsolt** [comment]
We have the same issue after Xcode 14.2->15.2 upgrade on Bitrise. Detox: 20.18.1. We have reported to  Bitrise support, but we would need to provide more evidence if this is a Bitrise issue.
We tried with Xcode 15.1, 15.2 (macOS 13.5) and 15.3 (macOS 14.0).

**Comment by adamivancza** [comment]
@huszzsolt I've given a try to execute our e2e tests on the 16.4 simulator on the same stack and that weirdly works without an issue.

**Comment by huszzsolt** [comment]
![Screenshot 2024-03-15 at 15 49 36](https://github.com/wix/Detox/assets/28455856/b829c64f-40f3-4bd7-8fe9-69aaf40c5d57)

Our problem is that we run out of the 6GB memory on Bitrise Medium machines. We also use 2 parallel simulators.
With Xcode 14.2 we had no memory issues.

Upgrading to a Large machine does not make financial sense: 2x the cost, but the testing time is the same.

Also, it looks like node/detox uses about 800MB of memory, SimRender Server about 100MB, so roughly 1GB / simulator is required.

**Comment by noomorph** [comment]
Hm, interesting. @huszzsolt, does the memory usage on the node process vary if you run 1, 2, 3 simulators? What's the dependency? Is it linear?

**Comment by fatlinesofcode** [comment]
similar issues here
```
20.18.3
--DETOX-test-run-dir-- ./artifacts
--DETOX-test--
yarn run v1.22.19
$ detox test --take-screenshots all --configuration ios.sim.release --reuse --loglevel error --artifacts-location "./artifacts" --maxWorkers 1 e2e/000-screens
02:52:18.685 detox[9455] i "SIMCTL_CHILD_GULGeneratedClassDisposeDisabled=YES SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/vagrant/Library/Detox/ios/6b87428b5105771bbfb2f02f32c435e03206164e/Detox.framework/Detox" /usr/bin/xcrun simctl launch 3D607B78-B519-49C9-9893-69E10C677495 au.com.[redacted].shop --args -detoxServer ws://localhost:49567 -detoxSessionId f50e67f3-e274-2b6c-c0f7-ac65f238deea -A_B_test_shop_screen_landing_promo_menu_addition 1 -isConsentGiven 1 -detoxDebugVisibility YES" failed with error = ChildProcessError: Command failed: SIMCTL_CHILD_GULGeneratedClassDisposeDisabled=YES SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/vagrant/Library/Detox/ios/6b87428b5105771bbfb2f02f32c435e03206164e/Detox.framework/Detox" /usr/bin/xcrun simctl launch 3D607B78-B519-49C9-9893-69E10C677495 au.com.adorebeauty.shop --args -detoxServer ws://localhost:49567 -detoxSessionId f50e67f3-e274-2b6c-c0f7-ac65f238deea -A_B_test_shop_screen_landing_promo_menu_addition 1 -isConsentGiven 1 -detoxDebugVisibility YES
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device returned an error for the requested operation.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "au.com.[redacted].shop" failed.
 `SIMCTL_CHILD_GULGeneratedClassDisposeDisabled=YES SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/vagrant/Library/Detox/ios/6b87428b5105771bbfb2f02f32c435e03206164e/Detox.framework/Detox" /usr/bin/xcrun simctl launch 3D607B78-B519-49C9-9893-69E10C677495 au.com.adorebeauty.shop --args -detoxServer ws://localhost:49567 -detoxSessionId f50e67f3-e274-2b6c-c0f7-ac65f238deea -A_B_test_shop_screen_landing_promo_menu_addition 1 -isConsentGiven 1 -detoxDebugVisibility YES` (exited with error code 4) (code=4), stdout and stderr:
02:52:19.072 detox[9455] i 
02:52:19.072 detox[9455] i An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device returned an error for the requested operation.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "au.com.[redacted].shop" failed.
	```
