### ISSUE TITLE
Detox postinstall fails in non-React Native projects

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#4408]
### What happened?

If I try to install `detox` in a fresh or standalone project (without RN dependency), I see this error:

```
npm ERR! code 1
npm ERR! path /Users/yaroslavs/Projects/1/node_modules/detox
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! node:internal/modules/cjs/loader:1147
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'react-native/package.json'
....
```

### What was the expected behaviour?

Detox should be able to install without errors.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

1. Create an empty folder, e.g. `my-project`.
2. Go inside `my-project`.
3. Run: `npm init -y`
4. Run: `npm install detox`

### In what environment did this happen?

Detox version: 20.19.1
React Native version: N/A
Has Fabric (React Native's new rendering system) enabled: N/A
Node version: 20.11.1
Test-runner (select one): N/A

### Detox logs

<details><summary>Detox logs</summary>

```
➜  1 npm install detox
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path /Users/yaroslavs/Projects/1/node_modules/detox
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! node:internal/modules/cjs/loader:1147
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'react-native/package.json'
npm ERR! Require stack:
npm ERR! - /Users/yaroslavs/Projects/1/node_modules/detox/src/utils/rn-consts/rn-consts.js
npm ERR! - /Users/yaroslavs/Projects/1/node_modules/detox/scripts/updateGradle.js
npm ERR! - /Users/yaroslavs/Projects/1/node_modules/detox/scripts/postinstall.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:985:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at parseRNVersion (/Users/yaroslavs/Projects/1/node_modules/detox/src/utils/rn-consts/rn-consts.js:2:23)
npm ERR!     at Object.<anonymous> (/Users/yaroslavs/Projects/1/node_modules/detox/src/utils/rn-consts/rn-consts.js:11:3)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/yaroslavs/Projects/1/node_modules/detox/src/utils/rn-consts/rn-consts.js',
npm ERR!     '/Users/yaroslavs/Projects/1/node_modules/detox/scripts/updateGradle.js',
npm ERR!     '/Users/yaroslavs/Projects/1/node_modules/detox/scripts/postinstall.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v20.11.1
```

</details>

### Device logs

N/A

**Comment by noomorph** [comment]
@instesti try locking to [20.17.1](https://github.com/wix/Detox/releases/tag/20.17.1) . I hope @gosha212 will find an hour to fix that.
