### ISSUE TITLE
Detox test fails after Browserstack integration

### ISSUE THREAD

**Issue by lanilalax** [wix/Detox#4635]
### What happened?

Once after integration of existing detox based tests with Browserstack, following error is noticed.

  was expecting 'CloudPlatform' , got {"type":"error","response":{"method":"launchApp","success":false,"message":""},"messageId":2,"cloudSessionId":"81d6e16e85eeba2ed8d02762f3353120a9425081"}
    Please report this issue on our GitHub tracker:
    https://github.com/wix/Detox/issues

      136 |
      137 |   const loginResponse = await login(email, password);
    > 138 |   await device.launchApp({
          |                ^
      139 |     newInstance: true,
      140 |     delete: isIOS,
      141 |     ...config,

      at launchAuthenticatedApp (utils/auth-utils.ts:138:16)

Detox: 20.26.2

detox.config.js
configurations: {
...
    'android.cloud': {
      device: 'cloud',
      app: 'android.cloud.debug',
      cloudAuthentication: {
        username: '---',
        accessKey: '---',
      },
      session: {
        server: 'wss://detox.browserstack.com/init',
        name: '---',
        build: '---',
        project: '---'
      }
    },
  },

  apps: {
    'android.cloud.debug': {
      type: 'android.cloud',
      app: 'bs://d9f5af24f616766ca427c0a53973d89ca4d7767c',
      appClient: 'bs://db971316764fb9884337409e912ca3223a3a68eb'
    }
}
  devices: {
    'cloud': {
      type: 'android.cloud',
      device: {
        name: 'Samsung Galaxy S21 Plus',
        osVersion: '11.0'
      }
    },
}

### What was the expected behaviour?

The test is expected to run in cloud environment specified, as like in local.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

https://www.browserstack.com/docs/app-automate/detox/getting-started - Followed the steps in Browserstack doc. But, from detox end, it fails.

### In what environment did this happen?

Detox version: 20.26.2 
React Native version: 0.72.14
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 22.8.0
Test-runner (select one): jest 

### Detox logs

 FAIL  e2e/tests/deep-links/deep-links.e2e.ts (111.392 s)
  Deep links
    ✕ navigates to Dining Information via deeplink, checks if Dining list page opens (3 ms)

  ● Deep links › navigates to Home, checks if Home page opens

    was expecting 'CloudPlatform' , got {"type":"error","response":{"method":"launchApp","success":false,"message":""},"messageId":2,"cloudSessionId":"81d6e16e85eeba2ed8d02762f3353120a9425081"}
    Please report this issue on our GitHub tracker:
    https://github.com/wix/Detox/issues

      136 |
      137 |   const loginResponse = await login(email, password);
    > 138 |   await device.launchApp({
          |                ^
      139 |     newInstance: true,
      140 |     delete: isIOS,
      141 |     ...config,

      at launchAuthenticatedApp (utils/auth-utils.ts:138:16)
      at Object.<anonymous> (tests/deep-links/deep-links.e2e.ts:30:5)

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by Mister-CK** [comment]
Are you running with the detox patch Browserstack has provided? They add the cloud config, without that patch it doesn't exists so you cannot run your test.

For me Detox with browserstack works when I run it locally, but when I try to run the exact same script from the pipeline, my app starts, shows my homeScreen for half a second and then crashses (shows a white screen, for the rest of the test).

**Comment by PatoSalazarNascent** [comment]
This is still happening. Exact same description

**Comment by PatoSalazarNascent** [comment]
@lanilalax were you able to solve this issue?. I am running into exactly the same and I am quite lost.
