### ISSUE TITLE
Detox can't seem to connect to the test app(s)!

### ISSUE THREAD

**Issue by SkPratihar1** [wix/Detox#4648]
### What happened?

/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      '$0': 'jest',
      config: 'e2e/jest.config.js'
    },
    jest: {
      setupTimeout: 120000
    },
  
  },
  apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath: 'ios/build/Build/Products/Debug-iphonesimulator/YOUR_APP.app',
      build: 'xcodebuild -workspace ios/YOUR_APP.xcworkspace -scheme YOUR_APP -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build'
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath: 'ios/build/Build/Products/Release-iphonesimulator/YOUR_APP.app',
      build: 'xcodebuild -workspace ios/YOUR_APP.xcworkspace -scheme YOUR_APP -configuration Release -sdk iphonesimulator -derivedDataPath ios/build'
    },
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      testBinaryPath:'/Users/it062305/dev/ProjectCode2024/ero-ev-frontend/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
      build: 'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..',
      reversePorts: [
        8081
      ]
    },
    
    'android.release': {
      type: 'android.apk',
      binaryPath: '/Users/it062305/dev/ProjectCode2024/ero-ev-frontend/android/app/build/outputs/apk/release/app-release.apk',
      testBinaryPath:'/Users/it062305/dev/ProjectCode2024/ero-ev-frontend/android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk',
      build: 'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release'
    }
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 15'
      }
    },
    attached: {
      type: 'android.attached',
      device: {
        adbName: '2bc2f8c'
      }
      
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_9_API_31'
      },
      packageName: "com.eroev.app"
    }
  },
  configurations: {
    'ios.sim.debug': {
      device: 'simulator',
      app: 'ios.debug'
    },
    'ios.sim.release': {
      device: 'simulator',
      app: 'ios.release'
    },
    'android.att.debug': {
      device: 'attached',
      app: 'android.debug'
    },
    'android.att.release': {
      device: 'attached',
      app: 'android.release'
    },
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug',
      launchApp: {
        waitForDebugger: true, // Optional: wait for debugger to be attached before continuing
        connectionTimeout: 60000 // Optional: Set connection timeout to 60 seconds
      }
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release'

    }
  }
};
app is install but app does not launch , "detox": "^20.28.0",  "react-native": "0.75.1",

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>
An error occurred while waiting for the app to become ready. Waiting for disconnection...
  error: Failed to run application on the device
  
  HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
15:24:31.177 detox[18776] i The app disconnected.
15:24:31.179 detox[18776] i Login flow: should login successfully
15:24:31.182 detox[18776] i Login flow: should login successfully [FAIL]
15:24:31.185 detox[18776] i Detox can't seem to connect to the test app(s)!

HINT: 

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs 

 FAIL  e2e/starter.test.js (36.35 s)
  Login flow
    ✕ should login successfully (3 ms)

  ● Login flow › should login successfully

    Failed to run application on the device

    HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.

      52 |   beforeAll(async () => {
      53 |     console.log('Starting beforeAll hook...');
    > 54 |     await device.launchApp({
         |                  ^
      55 |       newInstance: true, 
      56 |       clearLogs: true,
      57 |       launchArgs: {

      at Object.launchApp (e2e/starter.test.js:54:18)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12)

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```  \n    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    \n  </div>\n  <span class="md:block w-full truncate">evc.laravel-studio.io</sp
11-29 13:34:28.185 21146 21146 W unknown:ReactNative: Packager connection already open, nooping.
11-29 13:34:29.125 21146 21146 W unknown:ReactNative: Packager connection already open, nooping.
11-29 13:34:30.681 21146 21197 I ReactNativeJS: Running "ERO EV" with {"rootTag":11}
11-29 13:34:31.488 21146 21197 W ReactNativeJS: 'In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.', { [Component Stack] name: 'Component Stack' }
11-29 13:34:31.754 21146 21197 W ReactNativeJS: 'Looks like you\'re passing an inline function for \'component\' prop for the screen \'Auth\' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it\'s re-created every render. You can pass the function as children to \'Screen\' instead to achieve the desired behaviour.', { [Component Stack] name: 'Component Stack' }
11-29 13:34:32.118 21146 21198 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:34:32.122 21146 21198 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:34:32.123 21146 21198 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:34:32.152 21146 21198 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:34:32.154 21146 21198 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:34:32.154 21146 21198 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:34:32.400 21146 21146 I ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{7f15b8b V.E...... .......D 0,0-1080,2235 #b}
11-29 13:34:42.120 21146 21197 I ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
11-29 13:35:22.619 21465 21465 W unknown:ReactNative: Packager connection already open, nooping.
11-29 13:35:23.544 21465 21465 W unknown:ReactNative: Packager connection already open, nooping.
11-29 13:35:24.945 21465 21508 I ReactNativeJS: Running "ERO EV" with {"rootTag":11}
11-29 13:35:25.616 21465 21508 W ReactNativeJS: 'In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.', { [Component Stack] name: 'Component Stack' }
11-29 13:35:25.835 21465 21508 W ReactNativeJS: 'Looks like you\'re passing an inline function for \'component\' prop for the screen \'Auth\' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it\'s re-created every render. You can pass the function as children to \'Screen\' instead to achieve the desired behaviour.', { [Component Stack] name: 'Component Stack' }
11-29 13:35:26.166 21465 21509 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:35:26.171 21465 21509 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:35:26.171 21465 21509 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:35:26.185 21465 21509 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:35:26.187 21465 21509 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:35:26.188 21465 21509 W unknown:ReactNative: Attempt to set local data for view with unknown tag: -1
11-29 13:35:26.425 21465 21465 I ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{586b76f V.E...... .......D 0,0-1080,2235 #b}
11-29 13:36:05.353 21465 21508 I ReactNativeJS: { data: '<!DOCTYPE html>\n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->\n<head>\n\n\n<title>evc.laravel-studio.io | 522: Connection timed out</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />\n\n\n</head>\n<body>\n<div id="cf-wrapper">\n    <div id="cf-error-details" class="p-0">\n        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">\n            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">\n              <span class="inline-block">Connection timed out</span>\n              <span class="code-label">Error code 522</span>\n            </h1>\n            <div>\n               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=evc.laravel-studio.io" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.\n            </div>\n            <div class="mt-3">2024-11-29 08:06:07 UTC</div>\n        </header>\n        <div class="my-8 bg-gradient-gray">\n            <div class="w-240 lg:w-full mx-auto">\n                <div class="clearfix md:px-8">\n                  \n<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n  <div class="relative mb-10 md:m-0">\n    \n    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    \n  </div>\n  <span class="md:block w-full truncate">You</span>\n  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">\n    \n    Browser\n    \n  </h3>\n  <span class="leading-1.3 text-2xl text-green-success">Working</span>\n</div>\n\n<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n  <div class="relative mb-10 md:m-0">\n    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=evc.laravel-studio.io" target="_blank" rel="noopener noreferrer">\n    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    </a>\n  </div>\n  <span class="md:block w-full truncate">Mumbai</span>\n  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">\n    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=evc.laravel-studio.io" target="_blank" rel="noopener noreferrer">\n    Cloudflare\n    </a>\n  </h3>\n  <span class="leading-1.3 text-2xl text-green-success">Working</span>\n</div>\n\n<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n  <div class="relative mb-10 md:m-0">\n    \n    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    \n  </div>\n  <span class="md:block w-full truncate">evc.laravel-studio.io</sp

</details>

### More data, please!

_No response_

**Comment by champa-b** [comment]
is this resolved
