### ISSUE TITLE
detox test fails to run on windows with jest

### ISSUE THREAD

**Issue by nagyv** [wix/detox#510]
#### Description

after following https://github.com/wix/detox/blob/master/docs/Introduction.Android.md could not get `detox test` run

#### Steps to Reproduce

just run

```
$ node_modules\.bin\detox.cmd test -c android.emu.debug
node_modules/.bin/jest e2e --config=e2e/config.json --runInBand
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:524
    throw err;
    ^

Error: Command failed: node_modules/.bin/jest e2e --config=e2e/config.json --runInBand
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at runJest (C:\Users\Viktor\Projects\tmp\potzak\node_modules\detox\local-cli\detox-test.js:69:6)
    at Object.<anonymous> (C:\Users\Viktor\Projects\tmp\potzak\node_modules\detox\local-cli\detox-test.js:42:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 6.0.4
* Node: 7.10.1
* Device: Windows 10 with nvm

**Comment by rotemmiz** [comment]
Detox doesn't support windows currently. PRs are very welcome though.
You're welcome to open a [Feature request] issue to add support, or better yet, submit a PR.
I'm closing this issue.
