### ISSUE TITLE
When running Android with Expo - ReactInstanceManager is null

### ISSUE THREAD

**Issue by adam-stasiak** [wix/detox#578]
#### Description
In my case everything is working fine for iOS but for Android I have white screen displayed and next app turn off. I noticed that DetoxServerUrl is different inside first log and the another (adb command).

#### Steps to Reproduce

Follow the official guide for Android. Run tests from command line when Expo XDE is on.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: "^7.0.1",
* Node: v9.2.1
* Device: Android Emulator
* Xcode: 9.0 / 9.1
* macOS: 10.13.2
"react-native": "https://github.com/expo/react-native/archive/sdk-23.0.1.tar.gz",

#### Device and verbose Detox logs
```
02-12 13:06:44.773  6980  7014 I DetoxManager: DetoxServerUrl : ws://10.0.2.2:63950
02-12 13:06:44.773  6980  7014 I DetoxManager: DetoxSessionId : fba3e2ab-1012-4c9c-d5a5-a661db005762
02-12 13:06:44.784  6980  7014 E Detox   : Problem calling getInstanceManager()
02-12 13:06:44.784  6980  7014 E Detox   : java.lang.NoSuchMethodException: No similar method getReactNativeHost with params [] could be found on type class app.MainApplication.
02-12 13:06:44.784  6980  7014 E Detox   :     at org.joor.Reflect.similarMethod(Reflect.java:488)
02-12 13:06:44.784  6980  7014 E Detox   :     at org.joor.Reflect.call(Reflect.java:418)
02-12 13:06:44.784  6980  7014 E Detox   :     at org.joor.Reflect.call(Reflect.java:364)
02-12 13:06:44.784  6980  7014 E Detox   :     at com.wix.detox.ReactNativeSupport.getInstanceManager(ReactNativeSupport.java:93)
02-12 13:06:44.784  6980  7014 E Detox   :     at com.wix.detox.ReactNativeSupport.waitForReactNativeLoad(ReactNativeSupport.java:159)
02-12 13:06:44.784  6980  7014 E Detox   :     at com.wix.detox.DetoxManager.start(DetoxManager.java:70)
02-12 13:06:44.784  6980  7014 E Detox   :     at com.wix.detox.Detox$1$1.run(Detox.java:133)
02-12 13:06:44.784  6980  7014 E Detox   :     at android.os.Handler.handleCallback(Handler.java:751)
02-12 13:06:44.784  6980  7014 E Detox   :     at android.os.Handler.dispatchMessage(Handler.java:95)
02-12 13:06:44.784  6980  7014 E Detox   :     at android.os.Looper.loop(Looper.java:154)
02-12 13:06:44.784  6980  7014 E Detox   :     at com.wix.detox.Detox$1.run(Detox.java:136)
02-12 13:06:44.784  6980  7014 E Detox   :     at java.lang.Thread.run(Thread.java:761)
02-12 13:06:44.784  6980  7014 E AndroidRuntime: FATAL EXCEPTION: com.wix.detox.manager
02-12 13:06:44.784  6980  7014 E AndroidRuntime: Process: app, PID: 6980
02-12 13:06:44.784  6980  7014 E AndroidRuntime: java.lang.RuntimeException: ReactInstanceManager is null
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at com.wix.detox.ReactNativeSupport.waitForReactNativeLoad(ReactNativeSupport.java:161)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at com.wix.detox.DetoxManager.start(DetoxManager.java:70)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at com.wix.detox.Detox$1$1.run(Detox.java:133)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:751)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:154)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at com.wix.detox.Detox$1.run(Detox.java:136)
02-12 13:06:44.784  6980  7014 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:761)
02-12 13:06:44.790  6980  7014 I Process : Sending signal. PID: 6980 SIG: 9
```
----
```detox verb adb -s emulator-5556 shell am instrument -w -r -e detoxServer ws://localhost:52419 -e detoxSessionId fd6fccf7-6278-1464-b66f-3bf3676e7af7 -e debug false app/android.support.test.runner.AndroidJUnitRunner 
detox verb Instrumentation spawned, childProcess.pid:  28009
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: numtests=1
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: stream=
detox verb Instrumentation stdout:  app.DetoxTest:
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: test=runDetoxTests
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: class=app.DetoxTest
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: current=1
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS_CODE: 1
detox verb Instrumentation stdout:  
detox verb Instrumentation stdout:  INSTRUMENTATION_RESULT: shortMsg=Process crashed.
detox verb Instrumentation stdout:  INSTRUMENTATION_CODE: 0
detox verb Instrumentation stdout:  
detox verb instrumentationProcess terminated due to receipt of signal null 
 1) "before all" hook

  0 passing (2m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  




  0 passing (2m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



child_process.js:614
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose     
    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at runMocha (/Users/app/node_modules/detox/local-cli/detox-test.js:72:6)
    at Object.<anonymous> (/Users//app/node_modules/detox/local-cli/detox-test.js:50:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)

```

**Comment by adam-stasiak** [comment]
@LeoNatan Could you give any advice how to workaround this issue? Huge blocker for my team.

**Comment by LeoNatan** [comment]
Sorry, I am the iOS guy. 😜
We are having some major Android issues and are looking into them. We have not had time to explore Expo, so I cannot say wether those issues are related or not. Pinging @rotemmiz
