### ISSUE TITLE
Error: app-debug-androidTest.apk could not be found, did you run './gradlew assembleAndroidTest' ?

### ISSUE THREAD

**Issue by daquinons** [wix/detox#613]
#### Description
After setting detox package up and adding all the dependencies in Android, I try to run a sample test and I get this error:

```
  1) "before all" hook

  0 passing (2s)
  1 failing

  1) "before all" hook:
     Error: '/Users/xxx/xxx/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?
```

#### Steps to Reproduce
1. Follow these steps and use this configuration https://github.com/wix/detox/blob/master/docs/Introduction.Android.md

2. Execute `detox init` to set up a first sample test

3. Run the test with `detox test -c android.emu.debug`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* Node: 8.9.1
* Device: Nexus_5X_API_26
* macOS: 10.13.3

#### Device and verbose Detox logs

```
detox test --configuration android.emu.debug -l verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose     


detox-server info 13:53:58: server listening on localhost:63906...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"840b4b0e-7caf-32e1-c960-11dee84d88b0","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"840b4b0e-7caf-32e1-c960-11dee84d88b0","role":"tester"},"messageId":0}
detox verb ws  
detox verb 1: /Users/xxx/Library/Android/sdk/platform-tools/adb  devices 
detox verb 1: stdout: List of devices attached
detox verb 1: stdout: emulator-5554	device
detox verb 1: stdout: 
detox verb 1: stdout: 
detox verb 2: /Users/xxx/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82 
detox verb 3: /Users/xxx/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.package 
detox verb 3: stdout: Success
detox verb 3: stdout: 
detox verb 4: /Users/xxx/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.package.test 
detox verb 5: /Users/xxx/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk 
detox verb 5: stdout: 26
detox verb 5: stdout: 
detox verb 6: /Users/xxx/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /xxx/package/android/app/build/outputs/apk/debug/app-debug.apk 
detox verb 6: stderr: Success
detox verb 6: stderr: 
  1) "before all" hook

  0 passing (2s)
  1 failing

  1) "before all" hook:
     Error: '/xxx/package/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?
      at AttachedAndroidDriver.getTestApkPath (node_modules/detox/src/devices/AndroidDriver.js:43:13)
      at AttachedAndroidDriver.installApp (node_modules/detox/src/devices/AndroidDriver.js:36:43)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



child_process.js:644
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose     
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runMocha (/xxx/package/node_modules/detox/local-cli/detox-test.js:72:6)
    at Object.<anonymous> (/xxx/package/node_modules/detox/local-cli/detox-test.js:50:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

My package.json configuration

```
"detox" : {
		"configurations": {
			"android.emu.debug": {
				"binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
				"build":
				"cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
				"type": "android.attached",
				"name": "Nexus_5X_API_26"
			},
			"android.emu.release": {
				"binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
				"build":
				"cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
				"type": "android.attached",
				"name": "Nexus_5X_API_26"
			}
		}
	}
```

**Comment by markhu** [comment]
The line from your `package.json` that specifies the debug APK to be run doesn't seem to match the path in the initial error at the beginning of your description. Where you able to run `detox build` successfully?

**Comment by daquinons** [comment]
Yeah :(  I don't understand why it tries to find the apk in the /androidTest/ folder, is not specified anywhere.

When I run detox build, I get this error, which is weird because my app/build.gradle uses the minReactNative46 option, and com.android.support.test.espresso:espresso-core:3.0.0 was not in the dependencies of the Getting started guide (I'm sorry in advance, my experience dealing with Android is zero).

Thanks for your help!

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':detox:minReactNative44DebugCompileClasspath'.
> Could not find com.android.support.test.espresso:espresso-core:3.0.0.
  Searched in the following locations:
      file:/xxx/Library/Android/sdk/extras/m2repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.pom
      file:/xxx/Library/Android/sdk/extras/m2repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.jar
      file:/xxx/Library/Android/sdk/extras/google/m2repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.pom
      file:/xxx/Library/Android/sdk/extras/google/m2repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.jar
      file:/xxx/Library/Android/sdk/extras/android/m2repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.pom
      file:/xxx/Library/Android/sdk/extras/android/m2repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.jar
      file:/xxx/.m2/repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.pom
      file:/xxx/.m2/repository/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.jar
      https://jcenter.bintray.com/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.pom
      https://jcenter.bintray.com/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.jar
      file:/xxx/node_modules/react-native/android/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.pom
      file:/xxx/node_modules/react-native/android/com/android/support/test/espresso/espresso-core/3.0.0/espresso-core-3.0.0.jar
  Required by:
      project :detox
> Could not find com.android.support.test.uiautomator:uiautomator-v18:2.1.3.
  Searched in the following locations:
      file:/xxx/Library/Android/sdk/extras/m2repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.pom
      file:/xxx/Library/Android/sdk/extras/m2repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.jar
      file:/xxx/Library/Android/sdk/extras/google/m2repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.pom
      file:/xxx/Library/Android/sdk/extras/google/m2repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.jar
      file:/xxx/Library/Android/sdk/extras/android/m2repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.pom
      file:/xxx/Library/Android/sdk/extras/android/m2repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.jar
      file:/xxx/.m2/repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.pom
      file:/xxx/.m2/repository/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.jar
      https://jcenter.bintray.com/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.pom
      https://jcenter.bintray.com/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.jar
      file:/xxx/node_modules/react-native/android/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.pom
      file:/xxx/node_modules/react-native/android/com/android/support/test/uiautomator/uiautomator-v18/2.1.3/uiautomator-v18-2.1.3.jar
  Required by:
      project :detox

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
313 actionable tasks: 4 executed, 309 up-to-date
child_process.js:644
    throw err;
    ^

Error: Command failed: cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.<anonymous> (/xxx/node_modules/detox/local-cli/detox-build.js:26:6)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```
