### ISSUE TITLE
Detox failing react native app (TrustKit)

### ISSUE THREAD

**Issue by paulvelzeboer** [wix/detox#645]
#### Description
When testing my react native app i get an error which cause failing my test. see the logging below. 

#### Detox, Node, Device, Xcode and macOS Versions
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

#### Device and verbose Detox logs

```
2018-03-27 09:52:18.873 tradingDev[15285:187505] === TrustKit: Proxy-ing NSURLSessionDelegate: Webtrekk.RequestManager
2018-03-27 09:52:18.978 tradingDev[15285:187564] === TrustKit: Proxy-ing NSURLSessionDelegate: RCTHTTPRequestHandler
2018-03-27 09:52:18.979 tradingDev[15285:187564] Swizzling Method(s) not found while swizzling class TSKNSURLSessionDelegateProxy.
2018-03-27 09:52:18.979 tradingDev[15285:187564] Fatal failure: Cannot swizzle -[TSKNSURLSessionDelegateProxy URLSession:task:didCompleteWithError:] in <TSKNSURLSessionDelegateProxy: 0x600000205e70> in /Users/user/testing/detox/mobile/node_modules/detox/ios_src/EarlGrey/EarlGrey/Additions/NSURLSession+GREYAdditions.m:77
2018-03-27 09:52:19.419 [info][tid:main][RCTCxxBridge.mm:951] Invalidating <RCTCxxBridge: 0x6080003cb4f0> (parent: <RCTBridge: 0x60c0000c9ed0>, executor: (null))
2018-03-27 09:52:19.435 [info][tid:main][RCTCxxBridge.mm:213] Initializing <RCTCxxBridge: 0x6040003d7610> (parent: <RCTBridge: 0x60c0000c9ed0>, executor: (null))
2018-03-27 09:52:19.436 [warn][tid:main][RCTModuleData.mm:69] Module ReactLocalization requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
2018-03-27 09:52:19.440 tradingDev[15285:187505] === TrustKit: Proxy-ing NSURLSessionDelegate: RCTMultipartDataTask
      2objc[15285]: Class MPRequest is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MediaPlayer.framework/MediaPlayer (0x11f4a8470) and /Users/user/Library/Developer/CoreS$
2018-03-27 09:52:15.830 tradingDev[15285:187505] Crash handler setup started.
2018-03-27 09:52:15.830 tradingDev[15285:187505] Crash handler setup completed.
2018-03-27 09:52:15.830 tradingDev[15285:187505] Enabling accessibility for automation on Simulator.
2018-03-27 09:52:16.796 [info][tid:main][RCTCxxBridge.mm:213] Initializing <RCTCxxBridge: 0x6080003cb4f0> (parent: <RCTBridge: 0x60c0000c9ed0>, executor: (null))
2018-03-27 09:52:16.812 [warn][tid:main][RCTBridge.m:121] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
2018-03-27 09:52:16.829 [warn][tid:main][RCTModuleData.mm:69] Module ReactLocalization requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
2018-03-27 09:52:16.844 [info][tid:main][RCTRootView.m:301] Running application trading ({
          initialProps =     {
          };
          rootTag = 1;
      })
```

**Comment by LeoNatan** [comment]
I don't see anything in that log. Please post a full verbose log, not a short one.

**Comment by paulvelzeboer** [comment]
hope this is enough log info:

```
verb 6: /bin/cat /dev/null >$HOME/Library/Developer/CoreSimulator/Devices/B1953F94-B243-4C3C-BE43-2E0779DA98DC/data/tmp/detox.last_launch_app_log.out 2>$HOME/Library/Developer/CoreSimulator/Devices/B1953F94-B243-4C3C-BE43-2E0779DA98DC/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/user/Library/Detox/ios/10bb8552ba19e1920ce4481b260f028de03b183a/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err B1953F94-B243-4C3C-BE43-2E0779DA98DC nl.iphone.app.Trading --args -detoxServer ws://localhost:64828 -detoxSessionId 7595b122-fe7b-c92a-0ce0-06e7ca26c8a6
      info 6: Launching nl.iphone.app.Trading...
      verb 6: stdout: nl.iphone.app.Trading: 57747
      verb 6: stdout:
      info 6: nl.iphone.app.Trading launched. The stdout and stderr logs were recreated, you can watch them with:
              tail -F $HOME/Library/Developer/CoreSimulator/Devices/B1953F94-B243-4C3C-BE43-2E0779DA98DC/data/tmp/detox.last_launch_app_log.{out,err}
      verb ws send: {"type":"isReady","params":{},"messageId":-1000}
      verb ws onMessage: {"type":"ready","messageId":-1000,"params":{}}
      verb ws
      verb ws send: {"type":"reactNativeReload","params":{},"messageId":-1000}
      verb ws onMessage: {"type":"AppWillTerminateWithError","messageId":-10000,"params":{"threadNumber":2,"errorDetails":"Signal 6 was raised\n(\n\t0   Detox                               0x00000001050d9d3f _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 469\n\t1   Detox                               0x00000001050d9aeb _ZL17__DTXHandleSignali + 54\n\t2   libsystem_platform.dylib            0x000000010d6f2f5a _sigtramp + 26\n\t3   ???                                 0x000000000000ffff 0x0 + 65535\n\t4   libsystem_c.dylib                   0x000000010d3880eb abort + 127\n\t5   EarlGrey                            0x000000011ab7501e -[NSURLSession(GREYAdditions) greyswizzled_dataTaskWithRequest:completionHandler:] + 910\n\t6   trading                             0x0000000104db54b8 -[RCTHTTPRequestHandler sendRequest:withDelegate:] + 587\n\t7   trading                             0x0000000104dadb93 -[RCTNetworkTask start] + 149\n\t8   trading                             0x0000000104db370d -[RCTNetworking sendRequest:responseType:incrementalUpdates:responseSender:] + 1254\n\t9   trading                             0x0000000104db4ae8 __44-[RCTNetworking sendRequest:responseSender:]_block_invoke + 212\n\t10  EarlGrey                            0x000000011ab509c4 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 36\n\t11  libdispatch.dylib                   0x000000010d240177 _dispatch_call_block_and_release + 12\n\t12  libdispatch.dylib                   0x000000010d2411ba _dispatch_client_callout + 8\n\t13  libdispatch.dylib                   0x000000010d248d3d _dispatch_queue_serial_drain + 654\n\t14  libdispatch.dylib                   0x000000010d2495a0 _dispatch_queue_invoke + 329\n\t15  libdispatch.dylib                   0x000000010d245c97 _dispatch_queue_override_invoke + 477\n\t16  libdispatch.dylib                   0x000000010d24b980 _dispatch_root_queue_drain + 568\n\t17  libdispatch.dylib                   0x000000010d24b6ea _dispatch_worker_thread3 + 119\n\t18  libsystem_pthread.dylib             0x000000010d7041ca _pthread_wqthread + 1387\n\t19  libsystem_pthread.dylib             0x000000010d703c4d start_wqthread + 13\n)","queueName":"com.facebook.react.NetworkingQueue"}}
      verb ws
          1) "before all" hook

        0 passing (9s)
        1 failing

        1) Portfolio -> Make new buy order "before all" hook:
           Error: the string "Signal 6 was raised\n(\n\t0   Detox                               0x00000001050d9d3f _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 469\n\t1   Detox                               0x00000001050d9aeb _ZL17__DTXHandleSignali + 54\n\t2   libsystem_platform.dylib            0x000000010d6f2f5a _sigtramp + 26\n\t3   ???                                 0x000000000000ffff 0x0 + 65535\n\t4   libsystem_c.dylib                   0x000000010d3880eb abort + 127\n\t5   EarlGrey                            0x000000011ab7501e -[NSURLSession(GREYAdditions) greyswizzled_dataTaskWithRequest:completionHandler:] + 910\n\t6   trading                             0x0000000104db54b8 -[RCTHTTPRequestHandler sendRequest:withDelegate:] + 587\n\t7   trading                             0x0000000104dadb93 -[RCTNetworkTask start] + 149\n\t8   trading                             0x0000000104db370d -[RCTNetworking sendRequest:responseType:incrementalUpdates:responseSender:] + 1254\n\t9   trading                             0x0000000104db4ae8 __44-[RCTNetworking sendRequest:responseSender:]_block_invoke + 212\n\t10  EarlGrey                            0x000000011ab509c4 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 36\n\t11  libdispatch.dylib                   0x000000010d240177 _dispatch_call_block_and_release + 12\n\t12  libdispatch.dylib                   0x000000010d2411ba _dispatch_client_callout + 8\n\t13  libdispatch.dylib                   0x000000010d248d3d _dispatch_queue_serial_drain + 654\n\t14  libdispatch.dylib                   0x000000010d2495a0 _dispatch_queue_invoke + 329\n\t15  libdispatch.dylib                   0x000000010d245c97 _dispatch_queue_override_invoke + 477\n\t16  libdispatch.dylib                   0x000000010d24b980 _dispatch_root_queue_drain + 568\n\t17  libdispatch.dylib                   0x000000010d24b6ea _dispatch_worker_thread3 + 119\n\t18  libsystem_pthread.dylib             0x000000010d7041ca _pthread_wqthread + 1387\n\t19  libsystem_pthread.dylib             0x000000010d703c4d start_wqthread + 13\n)" was thrown, throw an Error :)
            at <anonymous>
            at process._tickCallback (internal/process/next_tick.js:160:7)



      child_process.js:614
          throw err;
          ^

      Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release --loglevel verbose
          at checkExecSyncError (child_process.js:574:11)
          at Object.execSync (child_process.js:611:13)
          at runMocha (/Users/user/testing/detox/mobile/packages/test/node_modules/detox/local-cli/detox-test.js:72:6)
          at Object.<anonymous> (/Users/user/testing/detox/mobile/packages/test/node_modules/detox/local-cli/detox-test.js:50:5)
          at Module._compile (module.js:660:30)
          at Object.Module._extensions..js (module.js:671:10)
          at Module.load (module.js:573:32)
          at tryModuleLoad (module.js:513:12)
          at Function.Module._load (module.js:505:3)
          at Function.Module.runMain (module.js:701:10)
```

**Comment by LeoNatan** [comment]
In that log, I see a native crash inside RN's network handler.
Are you sure this is the same error?

**Comment by paulvelzeboer** [comment]
yes its the same error and i dont know for sure if its a bug in detox... error i get:
```
2018-03-28 15:01:21.839 trading[72467:1499664] Fatal failure: Cannot swizzle -[TSKNSURLSessionDelegateProxy URLSession:task:didCompleteWithError:] in <TSKNSURLSessionDelegateProxy: 0x604000206720> in /Users/NO14TY/testing/detox/mobile/node_modules/detox/ios_sr$
LLVM Profile Error: Failed to write file "default.profraw": Permission denied
```

looks like something else is going wrong...

**Comment by LeoNatan** [comment]
Could you please create a demo project, which I can debug? I am not familiar with TrustKit.

**Comment by paulvelzeboer** [comment]
i will try to create an demo project with TrustKit, and i think have the same issue as:

https://github.com/wix/detox/issues/548
