### ISSUE TITLE
Command failed: /usr/bin/xcrun simctl shutdown

### ISSUE THREAD

**Issue by xcarpentier** [wix/detox#671]
I'm using detox on circleci execute into a macos box.

- Detox version: 7.3.3

Stacktrace
```
detox info 14: Shutting down 7171AA16-2E5C-4DEB-B845-7B6DB382CC58... 
  1) "after all" hook

  27 passing (3m)
  1 failing

  1)  "after all" hook:
     ChildProcessError: Command failed: /usr/bin/xcrun simctl shutdown 7171AA16-2E5C-4DEB-B845-7B6DB382CC58
2018-04-12 08:42:16.388 simctl[6192:33658] CoreSimulatorService connection interrupted.  Resubscribing to notifications.
2018-04-12 08:42:16.388 simctl[6192:33660] CoreSimulatorService connection interrupted.  Resubscribing to notifications.
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=53):
Error returned in reply: Connection interrupted
Software caused connection abort
 `/usr/bin/xcrun simctl shutdown 7171AA16-2E5C-4DEB-B845-7B6DB382CC58` (exited with error code 53)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:282:5)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by rotemmiz** [comment]
Does this also happen locally ?
I have a hunch it's a circleci thing.
Try starting up a simulator, then shutting it down, regardless of Detox, see if circleCI likes it...

```sh
/usr/bin/xcrun simctl launch 7171AA16-2E5C-4DEB-B845-7B6DB382CC58
/usr/bin/xcrun simctl shutdown 7171AA16-2E5C-4DEB-B845-7B6DB382CC58
```

**Comment by xcarpentier** [comment]
https://discuss.circleci.com/t/macos-plan-issue-with-xcrun-simctl-shutdown/21839

**Comment by LeoNatan** [comment]
Either way, not a Detox issue.
