### ISSUE TITLE
When setting a custom specs path, incorrect --opts argument is passed to mocha

### ISSUE THREAD

**Issue by sheminusminus** [wix/detox#710]
#### Description
When updating the package.json detox configuration `specs` value to a subdirectory (instead of project root), the argument passed to mocha for `--opts` is still `e2e/mocha.opts`.

My detox configuration in package.json:

```
"detox": {
    "specs": "test/e2e",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/Medean.app",
        "build": "xcodebuild -workspace ios/Medean.xcworkspace -scheme Medean -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/Medean.app",
        "build": "export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -workspace ios/Medean.xcworkspace -scheme Medean -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -quiet",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  }
```

`detox test` fails on:

```
Error: Command failed: node_modules/.bin/mocha test/e2e --opts e2e/mocha.opts --configuration ios.sim.debug     --grep :android: --invert
```

#### Steps to Reproduce
Change the specs path to a subdirectory of project root, move the `e2e` directory to that location, and try to run `detox test`.

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 7.3.5
* React Native: 0.55.3
* Node: 8.9.4
* Device: iPhone 7
* Xcode: 9.3
* macOS: 10.13.4

#### Device and verbose Detox logs
```
** BUILD SUCCEEDED **

node_modules/.bin/mocha test/e2e --opts e2e/mocha.opts --configuration ios.sim.debug     --grep :android: --invert  


detox-server info 12:50:10: server listening on localhost:51238...
detox info 1: Searching for device matching iPhone 7... 
detox info 3: Uninstalling org.reactjs.native.example.Medean... 
detox info 3: org.reactjs.native.example.Medean uninstalled 
detox info 4: Installing /Users/emily/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/Medean.app... 
  1) "before all" hook

  0 passing (2s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



detox info 4: /Users/emily/mobileapp/ios/build/Build/Products/Debug-iphonesimulator/Medean.app installed 
detox info 5: Terminating org.reactjs.native.example.Medean... 
detox info 5: org.reactjs.native.example.Medean terminated 
detox info 6: Launching org.reactjs.native.example.Medean... 
detox info 6: org.reactjs.native.example.Medean launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/E92EA5EE-9C84-492A-B639-72D0F670426D/data/tmp/detox.last_launch_app_log.{out,err} 
child_process.js:644
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha test/e2e --opts e2e/mocha.opts --configuration ios.sim.debug     --grep :android: --invert  
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runMocha (/Users/emily/mobileapp/node_modules/detox/local-cli/detox-test.js:105:6)
    at run (/Users/emily/mobileapp/node_modules/detox/local-cli/detox-test.js:66:7)
    at Object.<anonymous> (/Users/emily/mobileapp/node_modules/detox/local-cli/detox-test.js:56:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Medean@0.0.1 test:e2e:ios: `detox build --configuration ios.sim.debug && detox test --configuration ios.sim.debug`
npm ERR! Exit status 1
```

**Comment by noomorph** [comment]
Did you use `runner-config` option in `package.json` as described here?

https://github.com/wix/detox/blob/master/docs/APIRef.Configuration.md#test-runner-configuration
