### ISSUE TITLE
Can't launch android simulator

### ISSUE THREAD

**Issue by compojoom** [wix/detox#714]
### Description
Updated to 7.3.5 and running `detox test --configuration android.emu.debug` doesn't get past the launching of the emulator. In 7.3.3 the emulator was actually launching. (running the test on iOS works as expected)

#### Steps to Reproduce
"android.emu.debug": {
				"binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
				"build": "pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
				"type": "android.emulator",
				"name": "Nexus_5X_API_26"
			}

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.5
* React Native: 0.55.0
* Node: 9.11
* Device: Nexus_5X_API_26
* Xcode: 9.3
* macOS: 10.13.4

#### Device and verbose Detox logs
```
detox test --configuration android.emu.debug --loglevel verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose    --grep :ios: --invert


detox info 12:11:50: server listening on localhost:49692...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"177f4f09-53b5-dd02-5b93-8d5649a70d81","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"177f4f09-53b5-dd02-5b93-8d5649a70d81","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: /Users/{user}/Library/Android/sdk/tools/emulator -list-avds --verbose
detox verb 1: stdout: KitKat
detox verb 1: stdout: Lolipop
detox verb 1: stdout: Nexus_10_inch_Tablet
detox verb 1: stdout: Nexus_4_API_25
detox verb 1: stdout: Nexus_5X_API_25
detox verb 1: stdout: Nexus_5X_API_26
detox verb 1: stdout: Nexus_5_API_24
detox verb 1: stdout: Nexus_6_API_25
detox verb 1: stdout: Nexux_7inch_Tablet
detox verb 1: stdout: Old_play_services
detox verb 1: stdout:
detox verb /Users/{user}/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio  @Nexus_5X_API_26
detox ERR! Emulator ERROR:  ChildProcessError: `/Users/{user}/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio  @Nexus_5X_API_26` failed with code 1
detox ERR! Emulator ERROR:      at ChildProcess.<anonymous> (/Users/{user}/Documents/Development/Apps/{app}/source/node_modules/child-process-promise/lib/index.js:132:23)
detox ERR! Emulator ERROR:      at ChildProcess.emit (events.js:180:13)
detox ERR! Emulator ERROR:      at maybeClose (internal/child_process.js:936:16)
detox ERR! Emulator ERROR:      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
detox ERR! Emulator ERROR:   { ChildProcessError: `/Users/{user}/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio  @Nexus_5X_API_26` failed with code 1
detox ERR! Emulator ERROR:      at ChildProcess.<anonymous> (/Users/{user}/Documents/Development/Apps/{app}/source/node_modules/child-process-promise/lib/index.js:132:23)
detox ERR! Emulator ERROR:      at ChildProcess.emit (events.js:180:13)
detox ERR! Emulator ERROR:      at maybeClose (internal/child_process.js:936:16)
detox ERR! Emulator ERROR:      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
detox ERR! Emulator ERROR:    stack: 'ChildProcessError: `/Users/{user}/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio  @Nexus_5X_API_26` failed with code 1\n    at ChildProcess.<anonymous> (/Users/{user}/Documents/Development/Apps/{app}/source/node_modules/child-process-promise/lib/index.js:132:23)\n    at ChildProcess.emit (events.js:180:13)\n    at maybeClose (internal/child_process.js:936:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)',
detox ERR! Emulator ERROR:    name: 'ChildProcessError',
detox ERR! Emulator ERROR:    code: 1,
detox ERR! Emulator ERROR:    childProcess:
detox ERR! Emulator ERROR:     ChildProcess {
detox ERR! Emulator ERROR:       _events: { error: [Function], close: [Function] },
detox ERR! Emulator ERROR:       _eventsCount: 2,
detox ERR! Emulator ERROR:       _maxListeners: undefined,
detox ERR! Emulator ERROR:       _closesNeeded: 1,
detox ERR! Emulator ERROR:       _closesGot: 1,
detox ERR! Emulator ERROR:       connected: false,
detox ERR! Emulator ERROR:       signalCode: null,
detox ERR! Emulator ERROR:       exitCode: 1,
detox ERR! Emulator ERROR:       killed: false,
detox ERR! Emulator ERROR:       spawnfile: '/Users/{user}/Library/Android/sdk/tools/emulator',
detox ERR! Emulator ERROR:       _handle: null,
detox ERR! Emulator ERROR:       spawnargs:
detox ERR! Emulator ERROR:        [ '/Users/{user}/Library/Android/sdk/tools/emulator',
detox ERR! Emulator ERROR:          '-verbose',
detox ERR! Emulator ERROR:          '-gpu',
detox ERR! Emulator ERROR:          'host',
detox ERR! Emulator ERROR:          '-no-audio',
detox ERR! Emulator ERROR:          '',
detox ERR! Emulator ERROR:          '@Nexus_5X_API_26' ],
detox ERR! Emulator ERROR:       pid: 59959,
detox ERR! Emulator ERROR:       stdin: null,
detox ERR! Emulator ERROR:       stdout: null,
detox ERR! Emulator ERROR:       stderr: null,
detox ERR! Emulator ERROR:       stdio: [ null, null, null ] },
detox ERR! Emulator ERROR:    stdout: undefined,
detox ERR! Emulator ERROR:    stderr: undefined }
  1) "before all" hook

  0 passing (347ms)
  1 failing

  1)  "before all" hook:
     ChildProcessError: `/Users/{user}/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio  @Nexus_5X_API_26` failed with code 1
      at ChildProcess.<anonymous> (node_modules/child-process-promise/lib/index.js:132:23)
      at maybeClose (internal/child_process.js:936:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)



child_process.js:615
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose    --grep :ios: --invert
    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at runMocha (/Users/{user}/Documents/Development/Apps/{app}/source/node_modules/detox/local-cli/detox-test.js:105:6)
    at run (/Users/{user}/Documents/Development/Apps/{app}/source/node_modules/detox/local-cli/detox-test.js:66:7)
    at Object.<anonymous> (/Users/{user}/Documents/Development/Apps/{app}/source/node_modules/detox/local-cli/detox-test.js:56:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

I'm able to run `/Users/{user}/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio  @Nexus_5X_API_26`in the console and the emulator launches just fine.

**Comment by rotemmiz** [comment]
This fixes your issue
https://github.com/wix/detox/commit/25e59e60538df1fb02b464f19297c4723b136d0e

It's already in master, will be released with next version.

This is happening since there is now double space in the emulator command in case you don't pass --headless indetox params.
You can either fiddle with the file in node modules, or run in headless mode. Not ideal, but a version will be released soon.

**Comment by compojoom** [comment]
@rotemmiz - thanks. Tested and now the Emulator is launching. 

The app is not launching, but at least the emulator is...
