### ISSUE TITLE
Errors when a device is not appear late and are unclear.

### ISSUE THREAD

**Issue by DanielMSchmidt** [wix/detox#756]
#### Description

When I start the tests and don't have the right device set up I normally (read: before parallel test execution) get an error right away warning me that the device could not be started. After this new feature I get a fail reported for each item in the test suite and they all look different. Here are all of the uniquely different ones, so you can get a better picture:

```log
  ● Actions › should scroll to edge

    ReferenceError: element is not defined

      70 |   // edges: 'top'/'bottom'/'left'/'right'
      71 |   it('should scroll to edge', async () => {
    > 72 |     await expect(element(by.text('Text8'))).toBeNotVisible();
      73 |     await element(by.id('ScrollView161')).scrollTo('bottom');
      74 |     await expect(element(by.text('Text8'))).toBeVisible();
      75 |     await element(by.id('ScrollView161')).scrollTo('top');

      at Object.it (03.actions.test.js:72:5)

  ● Actions › should swipe down until pull to reload is triggered

    Can not boot Android Emulator with the name: 'Nexus_5X_API_26',
          make sure you choose one of the available emulators: Nexus_5X_API_27_x86

      48 |     }
      49 |     if (_.indexOf(avds, name) === -1) {
    > 50 |       throw new Error(`Can not boot Android Emulator with the name: '${name}',
      51 |       make sure you choose one of the available emulators: ${avds.toString()}`);
      52 |     }
      53 |

      at EmulatorDriver.acquireFreeDevice (../../src/devices/EmulatorDriver.js:50:13)

  ● Actions › should not wait for long timeout (>1.5s)

    Can not boot Android Emulator with the name: 'Nexus_5X_API_26',
          make sure you choose one of the available emulators: Nexus_5X_API_27_x86

      48 |     }
      49 |     if (_.indexOf(avds, name) === -1) {
    > 50 |       throw new Error(`Can not boot Android Emulator with the name: '${name}',
      51 |       make sure you choose one of the available emulators: ${avds.toString()}`);
      52 |     }
      53 |

      at EmulatorDriver.acquireFreeDevice (../../src/devices/EmulatorDriver.js:50:13)

  ● Actions › should not wait for long timeout (>1.5s)

    ReferenceError: device is not defined

      1 | describe('Actions', () => {
      2 |   beforeEach(async () => {
    > 3 |     await device.reloadReactNative();
      4 |     await element(by.text('Actions')).tap();
      5 |   });
      6 |

      at Object.beforeEach (03.actions.test.js:3:5)

  ● Actions › should not wait for long timeout (>1.5s)

    ReferenceError: element is not defined

      85 |
      86 |   it('should not wait for long timeout (>1.5s)', async () => {
    > 87 |     await element(by.id('WhyDoAllTheTestIDsHaveTheseStrangeNames')).tap();
      88 |     await expect(element(by.id('WhyDoAllTheTestIDsHaveTheseStrangeNames'))).toBeVisible();
      89 |   });
      90 |

      at Object.it (03.actions.test.js:87:5)
``` 

#### Steps to Reproduce

1. Checkout master & follow the [contributing steps](https://github.com/wix/detox/blob/master/docs/Guide.Contributing.md)
2. Make sure you don't have an android simulator named `"Nexus_5X_API_26"`
3. Go to `detox/test` and run `npm run build:android && npm run e2e:android`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.6 
* React Native: - 
* Node: 10.2.1
* Device: Android Emulator
* macOS: 10.13.4

#### Device and verbose Detox logs

I hope they are not needed in this situation / the ones I provided are sufficient

**Comment by rotemmiz** [comment]
As I stated, still missing the docs, this is only for iOS in the meantime.
Android has some issues

**Comment by rotemmiz** [comment]
Mainly the handling of device creation. On iOS it's pretty simple, on Android there are endless permutations of device types we're able to create, and the we need to think what would be the best API for that.

**Comment by DanielMSchmidt** [comment]
I think this might have been a hickup on my machine, closing this for now
