### ISSUE TITLE
Detox test run with artifacts flag '--record-videos failing' succeeds locally, fails on build server

### ISSUE THREAD

**Issue by tachtevrenidis** [wix/detox#814]
I am able to successfully run my tests and see the generated artifacts with Detox 8.0.0 locally on an iOS simulator but when I run the same exact tests on my build server (VSTS) the tests fail with this output:

```
2018-07-05T21:19:17.2962170Z detox verb 7: /usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/dev/null" 
2018-07-05T21:19:17.3531770Z detox ERR! 7: running "/usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/dev/null"" returned 2 
2018-07-05T21:19:17.3591300Z detox ERR! 7: stderr: An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
2018-07-05T21:19:17.3624720Z Error creating the image
2018-07-05T21:19:17.3663260Z  
2018-07-05T21:19:17.7573070Z detox verb 8: /usr/bin/xcrun simctl uninstall 60EA93A8-B5A0-4DBC-AD10-301984090B28 com.company.example.product 
2018-07-05T21:19:17.7599590Z detox info 8: Uninstalling com.company.example.product... 
2018-07-05T21:19:19.0379530Z detox info 8: com.company.example.product uninstalled 
2018-07-05T21:19:19.0431160Z detox verb 9: /usr/bin/xcrun simctl install 60EA93A8-B5A0-4DBC-AD10-301984090B28 "/Users/vsts/agent/2.134.2/work/1/s/items-view/mobile/ios/build/Build/Products/Debug-iphonesimulator/product.app" 
2018-07-05T21:19:19.0486140Z detox info 9: Installing /Users/vsts/agent/2.134.2/work/1/s/items-view/mobile/ios/build/Build/Products/Debug-iphonesimulator/product.app... 
2018-07-05T21:19:21.6118850Z detox info 9: /Users/vsts/agent/2.134.2/work/1/s/items-view/mobile/ios/build/Build/Products/Debug-iphonesimulator/product.app installed 
2018-07-05T21:19:21.6164400Z detox verb 10: /usr/bin/xcrun simctl terminate 60EA93A8-B5A0-4DBC-AD10-301984090B28 com.company.example.product 
2018-07-05T21:19:21.6320810Z detox info 10: Terminating com.company.example.product... 
2018-07-05T21:19:22.0468820Z detox info 10: com.company.example.product terminated 
2018-07-05T21:19:22.2943630Z detox verb 11: /bin/cat /dev/null >/Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.out 2>/Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/vsts/Library/Detox/ios/6835fdc9621ba06e099f505790cc7b06d2e6c1b5/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 60EA93A8-B5A0-4DBC-AD10-301984090B28 com.company.example.product --args -detoxServer ws://localhost:55543 -detoxSessionId 12b92690-5116-590b-246e-3a5b40ebad8d 
2018-07-05T21:19:22.2991030Z detox info 11: Launching com.company.example.product... 
2018-07-05T21:19:22.6131640Z detox verb 11: stdout: com.company.example.product: 7767
2018-07-05T21:19:22.6257710Z  
2018-07-05T21:19:22.6321050Z detox info 11: com.company.example.product launched. The stdout and stderr logs were recreated, you can watch them with:
2018-07-05T21:19:22.6415900Z         tail -F /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.{out,err} 
2018-07-05T21:19:22.6581350Z detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
2018-07-05T21:19:22.6699070Z detox wss 21:19:22: role=tester action=isReady (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:22.6773340Z detox wss 21:19:22: role=testee not connected, cannot fw action (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:24.6601440Z detox wss 21:19:24: role=testee login (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:24.6640510Z detox wss 21:19:24: role=testee action=loginSuccess (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:26.8223780Z detox wss 21:19:26: role=testee action=ready (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:26.8252080Z detox verb ws onMessage: {"type":"ready","messageId":-1000,"params":{}}
2018-07-05T21:19:26.8278170Z detox verb ws  
2018-07-05T21:19:26.8304440Z detox verb SimulatorLogPlugin starting to watch log
2018-07-05T21:19:26.8332150Z detox verb simulator-log-info Tail starting...
2018-07-05T21:19:26.8359020Z detox verb simulator-log-info filename: /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.out
2018-07-05T21:19:26.8387510Z detox verb simulator-log-info encoding: utf-8
2018-07-05T21:19:26.8413870Z detox verb simulator-log-info filesystem.watch present? true
2018-07-05T21:19:26.8442390Z detox verb simulator-log-info useWatchFile: false
2018-07-05T21:19:26.8470620Z detox verb simulator-log-info watch strategy: watch
2018-07-05T21:19:26.8508340Z detox verb simulator-log-info Tail starting...
2018-07-05T21:19:26.8535550Z detox verb simulator-log-info filename: /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.err
2018-07-05T21:19:26.8562570Z detox verb simulator-log-info encoding: utf-8
2018-07-05T21:19:26.8590400Z detox verb simulator-log-info filesystem.watch present? true
2018-07-05T21:19:26.8616540Z detox verb simulator-log-info useWatchFile: false
2018-07-05T21:19:26.8643650Z detox verb simulator-log-info watch strategy: watch
2018-07-05T21:19:26.8671000Z detox verb 12: /usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/2bc5e6b2-d727-4286-9acf-f2cd101eae00.png" 
2018-07-05T21:19:26.8697510Z detox verb SimulatorLogPlugin stopping to watch log
2018-07-05T21:19:26.8743450Z detox verb simulator-log-info Unwatch  /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.out
2018-07-05T21:19:26.8791530Z detox verb simulator-log-info Unwatch  /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.err
2018-07-05T21:19:26.8839660Z detox verb /usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 recordVideo /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/f9038ddb-2b7d-4619-882e-e8573a206726.mp4 
2018-07-05T21:19:26.8873490Z detox verb SimulatorLogPlugin starting to watch log
2018-07-05T21:19:26.8901960Z detox verb simulator-log-info Tail starting...
2018-07-05T21:19:26.8929880Z detox verb simulator-log-info filename: /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.out
2018-07-05T21:19:26.8957160Z detox verb simulator-log-info encoding: utf-8
2018-07-05T21:19:26.8983630Z detox verb simulator-log-info filesystem.watch present? true
2018-07-05T21:19:26.9009860Z detox verb simulator-log-info useWatchFile: false
2018-07-05T21:19:26.9036070Z detox verb simulator-log-info watch strategy: watch
2018-07-05T21:19:26.9062360Z detox verb simulator-log-info Tail starting...
2018-07-05T21:19:26.9089440Z detox verb simulator-log-info filename: /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.err
2018-07-05T21:19:26.9117680Z detox verb simulator-log-info encoding: utf-8
2018-07-05T21:19:26.9160420Z detox verb simulator-log-info filesystem.watch present? true
2018-07-05T21:19:26.9187440Z detox verb simulator-log-info useWatchFile: false
2018-07-05T21:19:26.9218240Z detox verb simulator-log-info watch strategy: watch
2018-07-05T21:19:27.4973280Z detox verb 13: /usr/bin/xcrun simctl terminate 60EA93A8-B5A0-4DBC-AD10-301984090B28 com.company.example.product 
2018-07-05T21:19:27.5001100Z detox info 13: Terminating com.company.example.product... 
2018-07-05T21:19:27.6725890Z detox info 13: com.company.example.product terminated 
2018-07-05T21:19:27.6767180Z detox verb 14: /usr/bin/xcrun simctl uninstall 60EA93A8-B5A0-4DBC-AD10-301984090B28 com.company.example.product 
2018-07-05T21:19:27.6794220Z detox info 14: Uninstalling com.company.example.product... 
2018-07-05T21:19:27.7075250Z detox wss 21:19:27: role=testee disconnect (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:28.6788060Z detox ERR! 14: running "/usr/bin/xcrun simctl uninstall 60EA93A8-B5A0-4DBC-AD10-301984090B28 com.company.example.product" returned 164 
2018-07-05T21:19:28.6825500Z detox ERR! 14: stderr: 2018-07-05 21:19:28.518 simctl[7772:36096] CoreSimulatorService connection interrupted.  Resubscribing to notifications.
2018-07-05T21:19:28.6855640Z An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
2018-07-05T21:19:28.6887570Z Invalid device state
2018-07-05T21:19:28.6922750Z Underlying error (domain=NSMachErrorDomain, code=-308):
2018-07-05T21:19:28.6956460Z 	The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)
2018-07-05T21:19:28.7000930Z  
2018-07-05T21:19:28.7041830Z detox verb 15: /usr/bin/xcrun simctl install 60EA93A8-B5A0-4DBC-AD10-301984090B28 "/Users/vsts/agent/2.134.2/work/1/s/items-view/mobile/ios/build/Build/Products/Debug-iphonesimulator/product.app" 
2018-07-05T21:19:28.7075110Z detox info 15: Installing /Users/vsts/agent/2.134.2/work/1/s/items-view/mobile/ios/build/Build/Products/Debug-iphonesimulator/product.app... 
2018-07-05T21:19:29.3743280Z detox ERR! 15: running "/usr/bin/xcrun simctl install 60EA93A8-B5A0-4DBC-AD10-301984090B28 "/Users/vsts/agent/2.134.2/work/1/s/items-view/mobile/ios/build/Build/Products/Debug-iphonesimulator/product.app"" returned 164 
2018-07-05T21:19:29.3772490Z detox ERR! 15: stderr: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
2018-07-05T21:19:29.3800750Z Unable to lookup in current state: Shutdown
2018-07-05T21:19:29.3830630Z  
2018-07-05T21:19:29.3860520Z detox verb 16: /usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/6d4ee817-413c-43cf-8149-d36410df754d.png" 
2018-07-05T21:19:29.3891910Z detox verb SimulatorLogPlugin stopping to watch log
2018-07-05T21:19:29.3923270Z detox verb simulator-log-info Unwatch  /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.out
2018-07-05T21:19:29.3951120Z detox verb simulator-log-info Unwatch  /Users/vsts/Library/Developer/CoreSimulator/Devices/60EA93A8-B5A0-4DBC-AD10-301984090B28/data/tmp/detox.last_launch_app_log.err
2018-07-05T21:19:29.3979200Z detox verb interruptProcess sending SIGINT to pid 7769 (/usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 recordVideo /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/f9038ddb-2b7d-4619-882e-e8573a206726.mp4)
2018-07-05T21:19:29.4007030Z detox verb stderr: 2018-07-05 21:19:28.513 simctl[7769:36035] CoreSimulatorService connection interrupted.  Resubscribing to notifications.
2018-07-05T21:19:29.4033340Z detox verb stderr: 
2018-07-05T21:19:29.4058400Z detox verb stderr: Recording completed.
2018-07-05T21:19:29.4083280Z detox verb stderr: 
2018-07-05T21:19:29.4109810Z detox verb SimulatorLogRecording moving /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/129e63f4-6ff2-4ed0-8d12-9bf90c510065.log to test-results/detox/ios/✗ product Test Suite Empty State loads/test.log
2018-07-05T21:19:29.4137340Z detox verb SimulatorLogRecording moving /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/24d3a614-7b10-4df5-a967-a200f5bd95fb.log to test-results/detox/ios/60EA93A8-B5A0-4DBC-AD10-301984090B28 2018-07-05 21:19:29Z.startup.log
2018-07-05T21:19:39.7649970Z detox ERR! 16: running "/usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/6d4ee817-413c-43cf-8149-d36410df754d.png"" returned 2 
2018-07-05T21:19:39.7677950Z detox ERR! 16: stderr: Detected file type 'PNG' from extension
2018-07-05T21:19:39.7704500Z An error was encountered processing the command (domain=simctl.SimDisplayScreenshotWriter.ScreenshotError, code=2):
2018-07-05T21:19:39.7731220Z Error creating the image
2018-07-05T21:19:39.7758180Z  
2018-07-05T21:19:39.7784810Z detox ERR! ArtifactsManager Caught exception inside plugin (SimulatorScreenshotter) at phase onAfterEach
2018-07-05T21:19:39.7812930Z detox ERR! ArtifactsManager Error: 16: running "/usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/6d4ee817-413c-43cf-8149-d36410df754d.png"" returned undefined
2018-07-05T21:19:39.7840990Z detox ERR! ArtifactsManager     at Object.execWithRetriesAndLogs (/Users/vsts/agent/2.134.2/work/1/s/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/detox/8.0.0/node_modules/detox/src/utils/exec.js:37:11)
2018-07-05T21:19:39.7867760Z detox ERR! ArtifactsManager     at <anonymous>
2018-07-05T21:19:39.7894060Z detox ERR! ArtifactsManager     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-05T21:19:39.7922280Z detox ERR! ArtifactsManager   { Error: 16: running "/usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/6d4ee817-413c-43cf-8149-d36410df754d.png"" returned undefined
2018-07-05T21:19:39.7949570Z detox ERR! ArtifactsManager     at Object.execWithRetriesAndLogs (/Users/vsts/agent/2.134.2/work/1/s/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/detox/8.0.0/node_modules/detox/src/utils/exec.js:37:11)
2018-07-05T21:19:39.7976810Z detox ERR! ArtifactsManager     at <anonymous>
2018-07-05T21:19:39.8003610Z detox ERR! ArtifactsManager     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-05T21:19:39.8033270Z detox ERR! ArtifactsManager   stack: 'Error: 16: running "/usr/bin/xcrun simctl io 60EA93A8-B5A0-4DBC-AD10-301984090B28 screenshot "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/6d4ee817-413c-43cf-8149-d36410df754d.png"" returned undefined\n    at Object.execWithRetriesAndLogs (/Users/vsts/agent/2.134.2/work/1/s/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/detox/8.0.0/node_modules/detox/src/utils/exec.js:37:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
2018-07-05T21:19:39.8061860Z detox verb ArtifactsManager finalized artifacts successfully
2018-07-05T21:19:39.8087980Z detox verb ws send: {"type":"cleanup","params":{"stopRunner":true},"messageId":1}
2018-07-05T21:19:39.8115150Z detox wss 21:19:39: role=tester action=cleanup (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
2018-07-05T21:19:39.8142390Z detox wss 21:19:39: role=testee not connected, cannot fw action (sessionId=12b92690-5116-590b-246e-3a5b40ebad8d)
```

Any idea why this is happening? I suspect this might not be a Detox issue, but if there are any ideas on what might be missing or misconfigured from my build environment (it is a container-like env) maybe I could get to the bottom of it.

**Comment by noomorph** [comment]
@tachtevrenidis , meanwhile I'll close the issue. If there will be something Detox-specific, please re-open.
