### ISSUE TITLE
React Native latest version (current 0.56) support

### ISSUE THREAD

**Issue by heuism** [wix/detox#821]
Hi guys, 

I have just a quick question about the plan to support latest RN version (current is 0.56).

I can see in the Readme file. there is the limit in the React Native version for Detox support. I am wondering why the support for both iOS and Android is not the same? So to develop and test for both platforms should the project stay under 0.51?

And I am asking for the future plan of updating the project to React Native 0.56 for Firebase issue with the versioning. And when it goes up, it would lose the support from Detox.

Thanks for your support. Best wishes.

**Comment by todorone** [comment]
@heuism Detox works on RN 0.56 on iOS. No clue about Android though...

**Comment by tedk99** [comment]
@todorone what'd you do to make it work?

I'm getting an error related to babel (after I upgraded babel-preset-react-native to : v5,:
    TypeError: Cannot read property 'throwIfClosureRequired' of undefined (While processing preset: "../node_modules/babel-preset-react-native/index.js")

      at _default (../node_modules/babel-preset-react-native/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:19:36)
      at Function.memoisePluginContainer (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
      at Function.normalisePlugin (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
      at ../node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at ../node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at ../node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)

**Comment by vonovak** [comment]
one user reported that they have detox working on android with RN 0.55.4 https://github.com/wix/detox/pull/773#issuecomment-404250381

**Comment by neerajkumar-lad** [comment]
https://stackoverflow.com/questions/51305555/could-not-find-method-missingdimensionstrategy-for-arguments-minreactnative

**Comment by LeoNatan** [comment]
Internally, Wix uses 0.51 currently. So we have to support that as the baseline. Is there something in particular that is not supported with 0.56? iOS or Android? Or is it just the docs not updated to state that it is supported?

**Comment by LeoNatan** [comment]
Ah, I see Android is trailing behind.

@rotemmiz @noomorph Isn't it time to start looking into supporting modern RN? Wix will soon be looking to upgrade the RN and Detox shouldn't be the one to bottleneck them.

**Comment by merunga** [comment]
Hi guys,
I've trying to get detox to work with RN 0.56 with android in Linux, with no luck.

`detox test` fails with RN 0.56 in Linux with this message:
> Plugin 0 specified in "/.../node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/.../node_modules/babel-preset-react-native/index.js")

You can check [this issue](https://github.com/facebook/react-native/issues/19859) that I think is related.

Here's a [fork](https://github.com/merunga/rn-56-test-detox) of the solution proposed in that issue, but with detox already configured.
`yarn test` works but `detox test` throws the *Plugin 0 specified in...* message.

Is this setup supposed to work?

**Comment by avigoldstein** [comment]
I'm experiencing the same issue as @merunga on RN 0.56 with iOS simulator and babel-jest on macOS. My detox builds succeed but I am unable to run tests. 

After reading through these two related issues:
https://github.com/facebook/react-native/issues/19859
https://github.com/facebook/react-native/issues/18962

I think the reason for the issue is that react native 0.56 requires Babel 7 (meaning it also requires babel-preset-react-native of version 5.0.1 or later), but detox still uses Babel 6 (and therefore babel-preset-react-native v4.0.0). I've tried using peer dependencies but those were also unsuccessful.

**Comment by merunga** [comment]
@avigoldstein I'm running my unit test with jest, but ended up using mocha to run e2e tests with detox.

**Comment by noomorph** [comment]
@merunga thanks for the report and [the fork](https://github.com/merunga/rn-56-test-detox). I cannot promise I'll look really soon, there's another important thing on the agenda (`https://github.com/wix/detox/issues/831`). As soon as I release a fix for it, I'll try to look at it.

**Comment by lapto** [comment]
@avigoldstein Running Detox on iOS with jest and RN 0.56.0 works for me after :
Adding `"^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"` in the jest config file for running detox. 
And making sure that the project "react-test-render" version is the same as the one used by react-native  ( for RN 0.56.0 -> 16.4.1).

**Comment by merunga** [comment]
@avigoldstein thanks for your hint!

@noomorph I managed to get detox with jest running using this `e2e/config.json` file:
```
{
  "rootDir": "../",
  "setupTestFrameworkScriptFile": "./e2e/init.js",
  "preset": "react-native",
  "transform": {
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
  }
}
```

and this conf in `package.json`
```
{
  ...
  "detox": {
    "test-runner": "jest",
    "runner-config": "e2e/config.json",
    "configurations": {
      "android.emu.debug": {
       ...
      }
    }
  }
  ...
}
```

It's updated in [the fork](https://github.com/merunga/rn-56-test-detox).

**Comment by YoshiYo** [comment]
@lapto @merunga Thanks you, it works with yours solutions !
The problem is fixed for me with all this configuration : 

```
react-native init project
cd project
npm install detox --save-dev
detox init -r jest
```

And follow the next changes in : 

in `package.json`
```
"jest": {
    "preset": "react-native",
    "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
  },
```
and 
```
"detox": {
    "test-runner": "jest",
    "runner-config": "e2e/config.json",
    "configurations": {
      "ios.sim.debug": ...
    }
  }
```
in `e2e/config.json `
```
{
    "rootDir": "../",
    "setupTestFrameworkScriptFile": "./e2e/init.js",
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
}
```

Don't forget to add you own simulator with the [official doc](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md). 

I hope it will help some of you 🛠😇
I will follow the fork.

**Comment by kevinresol** [comment]
With RN 0.56 on Android it is stuck at the empty screen before RN renders anything. Seems like there some infinite loop going on because I can't even properly kill it (it seems to stay running, unkillable)

**Comment by MJ0826** [comment]
Hi, I am not able to run the test on iOS, with RN 56 and jest, it hangs and gets timed out every time, below is the configuration I am using - 

In pacjage.json

`"detox": {
    "test-runner": "jest",
    "runner-config": "e2e/config.json",
    "specs": "e2e",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/ExampleApp.app",
        "build": "xcodebuild -workspace ios/ExampleApp.xcworkspace -scheme ExampleApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
  }`

and In config.json

`{
    "rootDir": "../",
    "setupTestFrameworkScriptFile": "./e2e/init.js",
    "testEnvironment": "node",
    "preset": "react-native",
    "transform": {
        "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
}`

I am not able to find out the actual cause behind this, can someone please help ?

Thanks

**Comment by kfroemming** [comment]
@MJ0826 I am seeing something similar, can you provide logs with detox test --debug-synchronization 1000. This way we can look and see if we are having a similar issue. Mine is particular to when Detox runs with Jest, and an individual file such as Filename.spec.js has more than 1 `describe` or `it` block. Try running a test with just 1 `describe` that contains an `it`. Maybe we are seeing the same thing.

**Comment by noomorph** [comment]
Please update the version of Detox to 9 to continue this discussion being relevant. The 9 officially supports RN 0.56 on Android, so the bug reports must be specific to the latest version. Thanks in advance.

**Comment by tannera** [comment]
Any news on 0.57.3 support?

**Comment by LeoNatan** [comment]
@tannera Android or iOS? Are you seeing something specific which doesn't work?

**Comment by tannera** [comment]
@LeoNatan No, I just read the Docs that specify support up to <=0.56

**Comment by LeoNatan** [comment]
Please test your project, and **open a new issue** if there is a problem.
