### ISSUE TITLE
Cannot launch app on Android (instrumentationProcess terminated due to receipt of signal SIGTERM)

### ISSUE THREAD

**Issue by anchetaWern** [wix/detox#822]
#### Description

Trying to solve this issue for 3 days now. I've scoured the issues, and tried the [troubleshooting guide](https://github.com/wix/detox/blob/master/docs/Troubleshooting.RunningTests.md) to no avail. 

The problem is that Detox seems to be having problems with launching the app on Android. It installs the app (if it isn't installed yet) but fails to launch it. Here's a [gif](https://media.giphy.com/media/47CeNc13AoZ6TXAjfW/giphy.gif).

If I use the `--reuse` flag while the app is opened, it pulls up the developer menu and then closes the app. Here's a [gif](https://media.giphy.com/media/3CU5uLyJrCGOBRdZHW/giphy.gif)

#### Steps to Reproduce

I'm just trying to get started with end to end testing on RN so I was following the [getting started guide](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md) and [Android Intro](https://github.com/wix/detox/blob/master/docs/Introduction.Android.md). I used `yarn` to install things even though the getting started guide says to use `npm` which nukes the RN project. 

I've setup [a repo that allows you to reproduce the issue here](https://github.com/anchetaWern/rntdd) but here's a summary of what I've done:

1. Initialized a new RN  project at version 0.50. Previously tried 0.51 but no luck with that either:

```
react-native init rntdd  --version react-native@0.50
```

2. Upgraded the project to use Gradle3 by following this tutorial. I ran the project with `react-native run-android` after that and everything worked perfectly.

3. Followed the [Getting Started tutorial](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md). All of it, except for step 4 because that's specific to iOS.

4. [Followed Android introduction](https://github.com/wix/detox/blob/master/docs/Introduction.Android.md). Had problems getting the project to build at first because I was building the default project (not the androidTest one). Also, I wasn't able to follow [this nicely](https://github.com/wix/detox/blob/master/docs/Introduction.Android.md#3-create-android-test-class). And lastly, the note [here](https://github.com/wix/detox/blob/master/docs/Introduction.Android.md#2-add-detox-dependency-to-an-android-project). This was confusing:

> Detox runs on multiple React Native versions, choose the correct build type to support the version you use.
> Available versions:
> minReactNative44: Support for React Native 0.44-0.45
> minReactNative46: Support for React Native 0.46+

I thought it should be the RN version of the project so I placed the following under **android -> defaultConfig** on `android/app/build.gradle`:

```
missingDimensionStrategy "minReactNative", "minReactNative50"
```

But got the error:

```

Could not determine the dependencies of task ':app:processDebugAndroidTestManifest'.
> Could not resolve all task dependencies for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve project :detox.
     Required by:
         project :app
      > Unable to find a matching configuration of project :detox:
          - Configuration 'minReactNative44DebugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative44Debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative44'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Configuration 'minReactNative44DebugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative44Debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative44'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Configuration 'minReactNative44ReleaseApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative44Release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative44'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Configuration 'minReactNative44ReleaseRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative44Release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative44'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Configuration 'minReactNative46DebugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative46Debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative46'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Configuration 'minReactNative46DebugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative46Debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative46'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Configuration 'minReactNative46ReleaseApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative46Release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative46'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Configuration 'minReactNative46ReleaseRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'minReactNative46Release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required minReactNative 'minReactNative50' and found incompatible value 'minReactNative46'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
```

So I used `minReactNative44` instead and I got it to build.

5. Launch a virtual device with Genymotion (Google Nexus 5X - 6.0.0 - API 23) with the following config:

```
{  
   "android.emu.debug":{  
      "binaryPath":"./android/app/build/outputs/apk/debug/app-debug.apk",
      "build":"pushd ./android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
      "type":"android.attached",
      "name":"192.168.57.101:5555"
   }
}
```

Got `192.168.57.101:5555` from `adb devices`.

I also tried with Android emulator (Nexus 5X API 25 x86) with the following config:

```
{  
   "android.emu.debug":{  
      "binaryPath":"./android/app/build/outputs/apk/debug/app-debug.apk",
      "build":"cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
      "type":"android.emulator",
      "name":"Nexus_5X_API_25_x86"
   }
}
```

But no luck either. You can see the logs below. I see to it that I execute `detox build -c android.emu.debug` first before executing any test commands to see if it's working.

6. Execute the following test using `detox test-c android.emu.debug`:

```
describe("Example", () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it("should show hello screen after tap", async () => {
    await element(by.id("hello_button")).tap();
    await expect(element(by.text("Hello!!!"))).toBeVisible();
  });
});
```

You can see the [app code here](https://github.com/anchetaWern/rntdd/blob/master/App.js). The test is passing with detox on iOS.

7. Tried the solutions on every issue, stackoverflow that I can find. And 3 days later I'm here :)

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.0.0
* React Native: 0.50
* Node: 8.3.0
* Device: Android Emulator Nexus_5X_API_25_x86
* Xcode: N/A
* macOS: High Sierra 10.13.5

#### Device and verbose Detox logs

Here's the log that I'm getting when I execute:

```
detox test --configuration android.emu.debug -l verbose --debug-synchronization 2000
```

Log:

```
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose   --debug-synchronization 2000 --grep :ios: --invert     --artifacts-location "artifacts/android.emu.debug.2018-07-11 07:15:41Z"


detox info 15:15:42: server listening on localhost:60082...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"c8b96dc1-2041-c283-c58c-bdc33a9dad8a","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"c8b96dc1-2041-c283-c58c-bdc33a9dad8a","role":"tester"},"messageId":0}
detox verb ws  
detox verb 1: /Users/wernancheta/Library/Android/sdk/emulator/emulator -list-avds --verbose 
detox verb 1: stdout: Nexus_5X_API_25_x86
 
detox verb 2: /Users/wernancheta/Library/Android/sdk/platform-tools/adb  devices 
detox verb 2: stdout: List of devices attached
emulator-5554	device

 
detox verb 3: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop dev.bootcomplete 
detox verb 3: stdout: 1
 
detox verb 4: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82 
detox verb 5: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.rntdd 
detox verb 5: stdout: Success
 
detox verb 6: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.rntdd.test 
detox verb 6: stdout: Success
 
detox verb 7: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk 
detox verb 7: stdout: 25
 
detox verb 8: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/wernancheta/www/mobile/rntdd/android/app/build/outputs/apk/debug/app-debug.apk 
detox verb 8: stdout: Success
 
detox verb 9: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk 
detox verb 9: stdout: 25
 
detox verb 10: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/wernancheta/www/mobile/rntdd/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk 
detox verb 10: stdout: Success
 
detox verb 11: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.rntdd 
detox verb 12: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list instrumentation 
detox verb 12: stdout: instrumentation:com.android.emulator.smoketests/android.support.test.runner.AndroidJUnitRunner (target=com.android.emulator.smoketests)
instrumentation:com.android.smoketest.tests/com.android.smoketest.SmokeTestRunner (target=com.android.smoketest)
instrumentation:com.example.android.apis/.app.LocalSampleInstrumentation (target=com.example.android.apis)
instrumentation:com.rntdd.test/android.support.test.runner.AndroidJUnitRunner (target=com.rntdd)
instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)
 
detox verb /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:60082 -e detoxSessionId c8b96dc1-2041-c283-c58c-bdc33a9dad8a -e debug false com.rntdd.test/android.support.test.runner.AndroidJUnitRunner 
detox verb Instrumentation spawned, childProcess.pid:  10195
detox verb 13: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps -AMo NAME,PID 
detox ERR! 13: running "/Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps -AMo NAME,PID" returned 1 
detox ERR! 13: stderr:  
  1) "before all" hook

  0 passing (8s)
  1 failing

  1) "before all" hook:
     Error: 13: running "/Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps -AMo NAME,PID" returned undefined
      at execWithRetriesAndLogs (node_modules/detox/src/utils/exec.js:37:11)
      at <anonymous>



detox verb ArtifactsManager finalized artifacts successfully
detox verb instrumentationProcess terminated due to receipt of signal SIGTERM 
child_process.js:634
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose   --debug-synchronization 2000 --grep :ios: --invert     --artifacts-location "artifacts/android.emu.debug.2018-07-11 07:15:41Z"
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at runMocha (/Users/wernancheta/www/mobile/rntdd/node_modules/detox/local-cli/detox-test.js:123:6)
    at run (/Users/wernancheta/www/mobile/rntdd/node_modules/detox/local-cli/detox-test.js:78:7)
    at Object.<anonymous> (/Users/wernancheta/www/mobile/rntdd/node_modules/detox/local-cli/detox-test.js:191:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

But before that, I execute `detox build -c android.emu.debug` first. Here's the log of that:

```
cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..

> Configure project :app 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :detox 
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.


BUILD SUCCESSFUL in 3s
```

**Comment by KubaGL** [comment]
I have similar problem with `adb shell ps` returning error. Looks like `-AMo NAME,PID` isn't valid, `ps` takes only pid as a param (at least in adb v. 1.0.40). So far I was only able to fix this issue by editing `src/devices/android/ADB.js` and removing `-AMo NAME,PID` part.

**Comment by anchetaWern** [comment]
@KubaGL thanks for the help! I tried your solution but still no luck :(

I found out that my adb version is 1.0.39:

```
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
```

So I updated `ADB.js` to hardcode the PID which I got by executing `adb shell pidof com.rntdd`. I opened the app first before executing it:

```
  async pidof(deviceId, bundleId) {
    /*
    const processes = await this.shell(deviceId, `ps -A PID`);
    const bundleIndex = processes.indexOf(bundleId + ' ');

    if (bundleIndex === -1) {
      return NaN;
    }

    const pidStart = bundleIndex + bundleId.length + 1;
    const pidEnd = processes.indexOf('\n', pidStart);

    const pidString = (pidEnd === -1)
      ? processes.slice(pidStart)
      : processes.slice(pidStart, pidEnd);
    
    return parseInt(pidString, 10);
    */
    return parseInt('6287', 10);
  }
```

I executed the test using the following command:

```
detox test --configuration android.emu.debug -l verbose --reuse
```

But still no luck. It's still terminating the opened app for some reason so I commented out the following code:

```
async install(deviceId, apkPath) {
    /*
    const apiLvl = await this.apiLevel(deviceId);
    if (apiLvl >= 24) {
      await this.adbCmd(deviceId, `install -r -g ${apkPath}`);
    } else {
      await this.adbCmd(deviceId, `install -rg ${apkPath}`);
    }
    */
  }

  async uninstall(deviceId, appId) {
    //await this.adbCmd(deviceId, `uninstall ${appId}`);
  }

  async terminate(deviceId, appId) {
    //await this.shell(deviceId, `am force-stop ${appId}`);
  }

  async unlockScreen(deviceId) {
    //await this.shell(deviceId, `input keyevent 82`);
  }
```

But still it's terminating the app. 

I got the following log:

```
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose  --reuse  --grep :ios: --invert     --artifacts-location "artifacts/android.emu.debug.2018-07-11 11:22:43Z"


detox info 19:22:44: server listening on localhost:52159...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"d1e507e8-a254-0a7d-4282-af5b2dd41c06","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"d1e507e8-a254-0a7d-4282-af5b2dd41c06","role":"tester"},"messageId":0}
detox verb ws  
detox verb 1: /Users/wernancheta/Library/Android/sdk/emulator/emulator -list-avds --verbose 
detox verb 1: stdout: Nexus_5X_API_25_x86
 
detox verb 2: /Users/wernancheta/Library/Android/sdk/platform-tools/adb  devices 
detox verb 2: stdout: List of devices attached
emulator-5554	device

 
detox verb 3: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop dev.bootcomplete 
detox verb 3: stdout: 1
 
detox verb 4: /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list instrumentation 
detox verb 4: stdout: instrumentation:com.android.emulator.smoketests/android.support.test.runner.AndroidJUnitRunner (target=com.android.emulator.smoketests)
instrumentation:com.android.smoketest.tests/com.android.smoketest.SmokeTestRunner (target=com.android.smoketest)
instrumentation:com.example.android.apis/.app.LocalSampleInstrumentation (target=com.example.android.apis)
instrumentation:com.rntdd.test/android.support.test.runner.AndroidJUnitRunner (target=com.rntdd)
instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)
 
detox verb /Users/wernancheta/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:52159 -e detoxSessionId d1e507e8-a254-0a7d-4282-af5b2dd41c06 -e debug false com.rntdd.test/android.support.test.runner.AndroidJUnitRunner 
detox verb Instrumentation spawned, childProcess.pid:  16534
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: id=ActivityManagerService
detox verb Instrumentation stdout:  
detox verb Instrumentation stdout:  
detox verb Instrumentation stderr:  android.util.AndroidException: INSTRUMENTATION_FAILED: com.rntdd.test/android.support.test.runner.AndroidJUnitRunner
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: com.rntdd
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS_CODE: -1
detox verb Instrumentation stdout:  
detox verb Instrumentation stderr:  
detox verb Instrumentation stderr:  
detox verb Instrumentation stderr:  	at com.android.commands.am.Am.runInstrument(Am.java:890)
detox verb Instrumentation stderr:  	at com.android.commands.am.Am.onRun(Am.java:400)
detox verb Instrumentation stderr:  	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
detox verb Instrumentation stderr:  
detox verb Instrumentation stderr:  	at com.android.commands.am.Am.main(Am.java:121)
detox verb Instrumentation stderr:  	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
detox verb Instrumentation stderr:  	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
detox verb Instrumentation stderr:  
detox verb instrumentationProcess terminated due to receipt of signal null 
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
^Cdetox info ArtifactsManager finalizing all artifacts, this can take some time
detox info ArtifactsManager finalized all artifacts

detox verb ArtifactsManager finalized artifacts successfully
```

**Comment by anchetaWern** [comment]
Ok. I finally got it to work. whew!

Solution by @KubaGL worked. So I updated the `pidof` method on `node_modules/detox/src/devices/android/ADB.js`:

```
async pidof(deviceId, bundleId) {
    const processes = await this.shell(deviceId, `ps`); // this was previously ps -AMo NAME,PID
    const bundleIndex = processes.indexOf(bundleId + ' ');
```

I also had to update `android/app/build.gradle` to use this config:

```
android {
    
    compileSdkVersion 27
    buildToolsVersion '27.0.2'

    defaultConfig {
        applicationId "com.rntdd"
        minSdkVersion 18
        targetSdkVersion 26

       missingDimensionStrategy "minReactNative", "minReactNative46" // previously minReactNative44 (see issue for details)


```

**Comment by neerajkumar-lad** [comment]
@anchetaWern I am also facing the same issue. Do I need to change only this line ?

`const processes = await this.shell(deviceId, `ps`); // this was previously ps -AMo NAME,PID`
I am facing still the same issue after changed as you did.

**Note: the app is getting install in the device and able to start app also.** 

This is my package.json:

```
{
  "name": "sampleApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test-ios": "detox build --configuration ios.sim.debug && detox test --configuration ios.sim.debug",
    "test-android": "detox build --configuration android.emu.debug && detox test --configuration android.emu.debug -l verbose"
  },
  "dependencies": {
    "npm": "^6.1.0",
    "react": "16.2.0",
    "react-native": "0.53.3"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "detox": "8.0.0",
    "jest": "21.2.1",
    "mocha": "^4.1.0",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "detox": {
    "test-runner": "jest",
    "specs": "e2e",
    "configurations": {
      "android.real.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.attached",
        "name": "FA4A3Y900593"
      }
    }
  }
}
```
Please find the attached log for your reference. 
[log.txt](https://github.com/wix/detox/files/2192282/log.txt)

**Comment by noomorph** [comment]
I don't really understand things with tweaking the `adb shell ps -AMo NAME,PID` command.
If there's discrepancy in results between some versions, let's handle it.

@anchetaWern, @KubaGL could you post your `adb shell ps --version` and `adb shell ps --help` output? Mine are:

```
x@y:~$ adb shell ps --version
toybox 0.7.6-android
x@y:~$ adb shell ps --help
usage: ps [-AadefLlnwZ] [-gG GROUP,] [-k FIELD,] [-o FIELD,] [-p PID,] [-t TTY,] [-uU USER,]

List processes.

Which processes to show (selections may be comma separated lists):

-A	All processes
-a	Processes with terminals that aren't session leaders
-d	All processes that aren't session leaders
-e	Same as -A
-g	Belonging to GROUPs
-G	Belonging to real GROUPs (before sgid)
-p	PIDs (--pid)
-P	Parent PIDs (--ppid)
-s	In session IDs
-t	Attached to selected TTYs
-T	Show threads
-u	Owned by USERs
-U	Owned by real USERs (before suid)

Output modifiers:

-k	Sort FIELDs in +increasing or -decreasting order (--sort)
-M	Measure field widths (expanding as necessary)
-n	Show numeric USER and GROUP
-w	Wide output (don't truncate fields)

Which FIELDs to show. (Default = -o PID,TTY,TIME,CMD)

-f	Full listing (-o USER:12=UID,PID,PPID,C,STIME,TTY,TIME,ARGS=CMD)
-l	Long listing (-o F,S,UID,PID,PPID,C,PRI,NI,ADDR,SZ,WCHAN,TTY,TIME,CMD)
-o	Output FIELDs instead of defaults, each with optional :size and =title
-O	Add FIELDS to defaults
-Z	Include LABEL

Command line -o fields:

  ARGS     CMDLINE minus initial path     CMD  Command (thread) name (stat[2])
  CMDLINE  Command line (argv[])          COMM Command filename (/proc/$PID/exe)
  COMMAND  Command file (/proc/$PID/exe)  NAME Process name (argv[0] of $PID)

Process attribute -o FIELDs:

  ADDR  Instruction pointer               BIT   Is this process 32 or 64 bits
  CPU   Which processor running on        ETIME   Elapsed time since PID start
  F     Flags (1=FORKNOEXEC 4=SUPERPRIV)  GID     Group id
  GROUP Group name                        LABEL   Security label
  MAJFL Major page faults                 MINFL   Minor page faults
  NI    Niceness (lower is faster)
  PCPU  Percentage of CPU time used       PCY     Android scheduling policy
  PGID  Process Group ID
  PID   Process ID                        PPID    Parent Process ID
  PRI   Priority (higher is faster)       PSR     Processor last executed on
  RGID  Real (before sgid) group ID       RGROUP  Real (before sgid) group name
  RSS   Resident Set Size (pages in use)  RTPRIO  Realtime priority
  RUID  Real (before suid) user ID        RUSER   Real (before suid) user name
  S     Process state:
        R (running) S (sleeping) D (device I/O) T (stopped)  t (traced)
        Z (zombie)  X (deader)   x (dead)       K (wakekill) W (waking)
  SCHED Scheduling policy (0=other, 1=fifo, 2=rr, 3=batch, 4=iso, 5=idle)
  STAT  Process state (S) plus:
        < high priority          N low priority L locked memory
        s session leader         + foreground   l multithreaded
  STIME Start time of process in hh:mm (size :19 shows yyyy-mm-dd hh:mm:ss)
  SZ    Memory Size (4k pages needed to completely swap out process)
  TCNT  Thread count                      TID     Thread ID
  TIME  CPU time consumed                 TTY     Controlling terminal
  UID   User id                           USER    User name
  VSZ   Virtual memory size (1k units)    %VSZ    VSZ as % of physical memory
  WCHAN What are we waiting in kernel for
```

**Comment by KubaGL** [comment]
@noomorph the problem is that my `adb shell ps` accepts only pid as a param, eg. when I try to run `adb shell ps --help` I get `bad pid '--help'` as an output.

**Comment by noomorph** [comment]
@KubaGL , interesting. Anyway, what Android Image do you use? How can I reproduce your environment?

**Comment by neerajkumar-lad** [comment]
CF-LP00152:sampleApp user.kumar$ adb shell ps --version
error: more than one device/emulator
CF-LP00152:sampleApp user.kumar$ adb shell ps --version
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
CF-LP00152:sampleApp user.kumar$ adb shell ps --help
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
CF-LP00152:sampleApp user.kumar$ adb devices
List of devices attached
FA4A3Y900593	device

**Comment by neerajkumar-lad** [comment]
My android image is Android v5.0.2
HTC device model

**Comment by KubaGL** [comment]
@noomorph Looks like it's because of old version of ps, I used Samsung Galaxy S7 - 7.1.0 - API25 image, ps works fine with these arguments on Samsung Galaxy S8 - 8.0 - API26 image

**Comment by noomorph** [comment]
That's what I am basically saying. Looks like Detox does not have enough
fallbacks to cover various versions of "ps" on devices.

This should be filed as an issue.

בתאריך יום ו׳, 13 ביולי 2018, 14:42, מאת Jakub Ratajczak ‏<
notifications@github.com>:

**Comment by anchetaWern** [comment]
@noomorph I was using Google Nexus 5X - 6.0.0 API 23 on Genymotion and Nexus 5X API 25 on Android emulator. Should I file a separate issue? or did you already?

@neerajkumar-lad did you get it to work? I suggest using Android emulator instead of Genymotion. And with a higher API version (API 26) as @KubaGL has mentioned.

**Comment by neerajkumar-lad** [comment]
These are the Android versions status of adb shell ps --version command:
**Adb version :** 

- Android Debug Bridge version 1.0.40
- Version 4797878

**V5.0 -Lollipop:**
CF-LP00152:sampleApp user.kumar$ **adb shell ps --version**
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME

**V6.0 Marshmallow:**
CF-LP00152:sampleApp user.kumar$ **adb shell ps --version**
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME

**V7.0 Nougat:** 
CF-LP00152:sampleApp user.kumar$ **adb shell ps --version**
bad pid '--version'

**V7.1.1 Nougat:** 
CF-LP00152:sampleApp user.kumar$ **adb shell ps --version**
bad pid '--version'

**V8.0 Oreo:**
CF-LP00152:sampleApp user.kumar$ **adb shell ps --version**
toybox 0.7.3-05146348f7d3-android

**API Level 28 :** 
CF-LP00152:sampleApp user.kumar$ **adb shell ps --version**
toybox 0.7.6-android

Looks like newer version of Android support adb shell ps --version command

**_Note: This has been performed on Android emulator_**

**Comment by noomorph** [comment]
@anchetaWern , @neerajkumar-lad , thank you very much for the input! Yes, I'll create an issue and try to look into it as soon as possible, hopefully today.
