### ISSUE TITLE
Detox not interacting with simulator 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/detox#823]
(node:6040) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
detox-server info 17:41:30: server listening on localhost:53599...
  Guest View
    1) "before each" hook: _callee for "#Access the different tabs"

  0 passing (96ms)
  1 failing

  1) Guest View
       "before each" hook: _callee for "#Access the different tabs":
     ReferenceError: device is not defined
      at Object._callee$ (e2e/GuestMode/GuestView.spec.js:11:8)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at invoke (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:155:20)
      at /Users/yogesh/Documents/Project/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:202:11
      at new Promise (<anonymous>)
      at callInvokeWithMethodAndArg (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:201:16)
      at AsyncIterator.enqueue (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:224:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at Object.runtime.async (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:248:14)
      at Context._callee (e2e/GuestMode/GuestView.spec.js:10:13)

child_process.js:644
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.debug     --grep :android: --invert  
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runMocha (/Users/yogesh/Documents/Project/node_modules/detox/local-cli/detox-test.js:114:6)
    at run (/Users/yogesh/Documents/Project/node_modules/detox/local-cli/detox-test.js:75:7)
    at Object.<anonymous> (/Users/yogesh/Documents/Project/node_modules/detox/local-cli/detox-test.js:181:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by neerajkumar-lad** [comment]
Hey,

can u give more detail on device, as it shows error as **ReferenceError: device is not defined**

**Comment by yogeshthanvi** [comment]
Hi @neerajkumar-lad  solved the issue by updating the detox to latest version and also closing down the issue
