### ISSUE TITLE
Encounter an issue when trying to clean cache and build framework 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/detox#843]
Removing framework binaries from /Users/yogesh/Library/Detox
Dev mode, will build from /Users/yogesh/Documents/appname/node_modules/detox/ios
Building Detox.framework from /Users/yogesh/Documents/appname/node_modules/detox/ios...
child_process.js:644
    throw err;
    ^

Error: Command failed: /Users/punchh_yogesh/Documents/appname/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.<anonymous> (/Users/punchh_yogesh/Documents/appname/node_modules/detox/local-cli/detox-build-framework-cache.js:6:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
--------------------------------------------------------------------------------------------
RN version - 0.55.4
Detox version - 8.0.0

**Comment by rotemmiz** [comment]
Add verbose she'll output to the build framework script.
What is the actual error the shell script produces ? (You can run it manually, /Users/punchh_yogesh/Documents/appname/node_modules/detox/scripts/build_framework.ios.sh)

**Comment by rotemmiz** [comment]
+ update your issue according to template. We can not answer with partial data of your environment.
