### ISSUE TITLE
detox.init() ios hangs 

### ISSUE THREAD

**Issue by oreporan** [wix/Detox#912]
#### Description
Running `detox.init()` using lerna (so runs in several packages) hangs about 50% of the time, causes mocha to reach timeout

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.2.3
* React Native: 0.51.0
* Node: v8.9.4
* Device: iPhone 7
* Xcode: 9.4
* macOS: HighSierra

#### Device and verbose Detox logs
```
[15:45:06][Step 7/7] before detox.init
[15:45:06][Step 7/7] detox info 15:45:06: server listening on localhost:50076...
[15:45:08][Step 7/7] detox info 2: Searching for device matching iPhone 7... 
[15:45:11][Step 7/7] detox info 5: Booting device 044F9BD6-73D3-4496-A5CD-2932B4A6C4BC 
[15:48:29][Step 7/7] detox ERR! 7: running "/usr/bin/xcrun simctl io 044F9BD6-73D3-4496-A5CD-2932B4A6C4BC screenshot "/dev/null"" returned 2 
[15:48:29][Step 7/7] detox ERR! 7: stderr: An error was encountered processing the command (domain=SimulatorKit.SimDisplayScreenshotWriter.ScreenshotError, code=2):
[15:48:29][Step 7/7] Error creating the image
[15:48:29][Step 7/7]  
[15:48:32][Step 7/7] detox info 8: Uninstalling com.asurion.anywhereexpert... 
[15:48:34][Step 7/7] detox info 8: com.asurion.anywhereexpert uninstalled 
[15:48:34][Step 7/7] detox info 9: Installing /Users/Soluto/BuildAgent/work/cdcd1423766ba686/mobile/ios/build/Build/Products/Release-iphonesimulator/Anywhere Expert.app... 
[15:48:43][Step 7/7] detox info 9: /Users/Soluto/BuildAgent/work/cdcd1423766ba686/mobile/ios/build/Build/Products/Release-iphonesimulator/Anywhere Expert.app installed 
[15:48:43][Step 7/7] detox info 10: Terminating com.asurion.anywhereexpert... 
[15:48:44][Step 7/7] detox info 10: com.asurion.anywhereexpert terminated 
[15:48:44][Step 7/7] detox info 11: Launching com.asurion.anywhereexpert... 
[15:48:50][Step 7/7] detox info 11: com.asurion.anywhereexpert launched. The stdout and stderr logs were recreated, you can watch them with:
[15:48:50][Step 7/7]         tail -F /Users/Soluto/Library/Developer/CoreSimulator/Devices/044F9BD6-73D3-4496-A5CD-2932B4A6C4BC/data/tmp/detox.last_launch_app_log.{out,err} 
[15:50:06][Step 7/7] Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
[15:50:06][Step 7/7] Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
[15:50:07][Step 7/7] child_process.js:644
[15:50:07][Step 7/7]     throw err;
[15:50:07][Step 7/7]     ^
[15:50:07][Step 7/7] 
[15:50:07][Step 7/7] Error: Command failed: node_modules/.bin/mocha __tests__/detox/build --opts __tests__/detox/mocha.teamcity.opts --configuration ios.release     --grep :android: --invert     --artifacts-location "artifacts/ios.release.2018-08-30 12:44:54Z"
[15:50:07][Step 7/7]     at checkExecSyncError (child_process.js:601:13)
[15:50:07][Step 7/7]     at Object.execSync (child_process.js:641:13)
[15:50:07][Step 7/7]     at runMocha (/Users/Soluto/BuildAgent/work/cdcd1423766ba686/mobile/node_modules/detox/local-cli/detox-test.js:123:6)
[15:50:07][Step 7/7]     at run (/Users/Soluto/BuildAgent/work/cdcd1423766ba686/mobile/node_modules/detox/local-cli/detox-test.js:78:7)
[15:50:07][Step 7/7]     at Object.<anonymous> (/Users/Soluto/BuildAgent/work/cdcd1423766ba686/mobile/node_modules/detox/local-cli/detox-test.js:191:1)
[15:50:07][Step 7/7]     at Module._compile (module.js:652:30)
[15:50:07][Step 7/7]     at Object.Module._extensions..js (module.js:663:10)
[15:50:07][Step 7/7]     at Module.load (module.js:565:32)
[15:50:07][Step 7/7]     at tryModuleLoad (module.js:505:12)
[15:50:07][Step 7/7]     at Function.Module._load (module.js:497:3)
[15:50:07][Step 7/7] error Command failed with exit code 1.
```

**Comment by noomorph** [comment]
I don't believe that these logs are from Detox 8.2.3, it is 7.x

**Comment by oreporan** [comment]
are you sure?
Could it be prefering the global npm detox over the local one?

**Comment by noomorph** [comment]
Not likely. Why do you install `detox` globally?

**Comment by oreporan** [comment]
Ok in the yarn.lock I see this:


```
detox-server@^7.0.0:
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/detox-server/-/detox-server-7.0.0.tgz#82e571577aa5f867c5ed1fd5b8785e1a9e033ef0"
  dependencies:
    lodash "^4.13.1"
    npmlog "^4.0.2"
    ws "^1.1.0"

detox@^8.0.0:
  version "8.0.0"
  resolved "https://registry.yarnpkg.com/detox/-/detox-8.0.0.tgz#6322d0ea9c27cbe8fd9f22524b8fb004ba2a8a95"
  dependencies:
    child-process-promise "^2.2.0"
    commander "^2.15.1"
    detox-server "^7.0.0"
    fs-extra "^4.0.2"
    get-port "^2.1.0"
    ini "^1.3.4"
    lodash "^4.14.1"
    minimist "^1.2.0"
    npmlog "^4.0.2"
    proper-lockfile "^3.0.2"
    shell-utils "^1.0.9"
    tail "^1.2.3"
    telnet-client "0.15.3"
    tempfile "^2.0.0"
    ws "^1.1.1"
```

whats detox-server?

**Comment by noomorph** [comment]
`detox-server` is not in use now.

**Comment by oreporan** [comment]
ok, so the logs are from detox 8.0.0 from what it seems
should I upgrade to 8.2.3?

**Comment by noomorph** [comment]
I don't think it is going to solve your problem, but anyway it won't hurt.

**Comment by LeoNatan** [comment]
Run your test with `--debug-synchronization 1000` and paste the log output here. Thanks
