### ISSUE TITLE
Detox is failing to find elements that are clearly there

### ISSUE THREAD

**Issue by jwaldrip** [wix/Detox#929]
#### Description
When running detox it fails > 80% of the time by not finding elements that are not only there visually, but also visible in its search tree. This usually happens when scrolling on a scroll view and then looking for a <TouchableHighlight> to press.

#### Steps to Reproduce
Hard to reproduce on its own. But would love to hop on a chat/screen share with someone and show them. Note, it happens more on CI than it does locally, probably because of less powerful machines. But it does crash locally as well after running in a while loop in my shell.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.2.3
* React Native: 0.55.4
* Node: 10.9
* Device: iOS
* Xcode: 9.4
* macOS: High Sierra 

#### Device and verbose Detox logs
```
 FAIL  e2e/onboarding.test.js (326.439s)
  onboarding
    ✕ :ios: a user can be onboarded (81395ms)
    ✓ :ios: a user requiring parent consent can be onboarded (86362ms)
    ✓ a user can edit payable account info (36492ms)
    ✓ user can set bank account as payable account (36600ms)
    location services
      ✓ skips the screen if permissions are set to 'always' (20551ms)
      ✓ renders screen with 'Enable' button if location permissions are unset (23121ms)

  ● onboarding › :ios: a user can be onboarded

    Failed: [Error: Error: Cannot perform action due to constraint(s) failure.
    Exception with Action: {
      "Action Name":  "Tap",
      "Element Description":  "<RCTView:0x7fc42dce0c00; AX=Y; AX.id='save-button'; AX.label='Save'; AX.frame={{20, 528}, {335, 63.5}}; AX.activationPoint={187.5, 559.75}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 63.5}}; opaque; alpha=1>",
      "Failed Constraint(s)":  "interactable",
      "All Constraint(s)":  "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
      "Recovery Suggestion":  "Adjust element properties so that it matches the failed constraint(s)."
    }


    [
      {
        "Description":  "Cannot perform action due to constraint(s) failure.",
        "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code":  "1",
        "File Name":  "GREYBaseAction.m",
        "Function Name":  "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
        "Line":  "66"
      }
    ]

    Hierarchy: <UIWindow:0x7fc42df36680; AX=N; AX.frame={{0, 0}, {375, 667}}; AX.activationPoint={187.5, 333.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 667}}; opaque; alpha=1>
      |--<UITransitionView:0x7fc42ded17b0; AX=N; AX.frame={{0, 0}, {375, 667}}; AX.activationPoint={187.5, 333.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 667}}; opaque; alpha=1>
      |  |--<UIView:0x7fc42dce28e0; AX=N; AX.frame={{0, 0}, {375, 667}}; AX.activationPoint={187.5, 333.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 667}}; opaque; alpha=1>
      |  |  |--<RCTView:0x7fc42dce1ff0; AX=N; AX.label='Skill Details  Software Testing Gig Availability What type of gig requests would you like to receive for this skill? Select Volunteer, Paid, or both.  Volunteer  Paid Hourly Rate $ Years Experience Keywords (Optional) Save Cancel'; AX.frame={{0, 0}, {750, 1334}}; AX.activationPoint={375, 667}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {750, 1334}}; opaque; alpha=1>
      |  |  |  |--<RCTScrollView:0x7fc43787ce00; AX=N; AX.label='Skill Details  Software Testing Gig Availability What type of gig requests would you like to receive for this skill? Select Volunteer, Paid, or both.  Volunteer  Paid Hourly Rate $ Years Experience Keywords (Optional) Save Cancel'; AX.frame={{0, 0}, {375, 667}}; AX.activationPoint={187.5, 333.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 667}}; opaque; alpha=1>
      |  |  |  |  |--<RCTCustomScrollView:0x7fc43785a000; AX=N; AX.frame={{0, 0}, {375, 667}}; AX.activationPoint={187.5, 333.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 667}}; opaque; alpha=1>
      |  |  |  |  |  |--<UIImageView:0x7fc42dcefb30; AX=N; AX.frame={{369.5, 3}, {2.5, 328.5}}; AX.activationPoint={370.75, 167.25}; AX.traits='UIAccessibilityTraitImage'; AX.focused='N'; frame={{369.5, 3}, {2.5, 328.5}}; alpha=0; UIE=N>
      |  |  |  |  |  |--<UIImageView:0x7fc42dcef900; AX=N; AX.frame={{3, 415.5}, {366.5, 2.5}}; AX.activationPoint={186.25, 416.75}; AX.traits='UIAccessibilityTraitImage'; AX.focused='N'; frame={{3, 415.5}, {366.5, 2.5}}; alpha=0; UIE=N>
      |  |  |  |  |  |--<RCTScrollContentView:0x7fc42dce1b20; AX=N; AX.label='Skill Details  Software Testing Gig Availability What type of gig requests would you like to receive for this skill? Select Volunteer, Paid, or both.  Volunteer  Paid Hourly Rate $ Years Experience Keywords (Optional) Save Cancel'; AX.frame={{0, 0}, {375, 672}}; AX.activationPoint={187.5, 336}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 672}}; opaque; alpha=1>
      |  |  |  |  |  |  |--<RCTView:0x7fc42dce1810; AX=N; AX.label='Software Testing Gig Availability What type of gig requests would you like to receive for this skill? Select Volunteer, Paid, or both.  Volunteer  Paid Hourly Rate $ Years Experience Keywords (Optional) Save Cancel'; AX.frame={{0, 37}, {375, 635}}; AX.activationPoint={187.5, 354.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 37}, {375, 635}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc42dce1500; AX=N; AX.label='Cancel'; AX.frame={{20, 601.5}, {335, 45.5}}; AX.activationPoint={187.5, 624.25}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{20, 564.5}, {335, 45.5}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dc62c90; AX=Y; AX.id='styled-button'; AX.label='Cancel'; AX.frame={{20, 601.5}, {335, 45.5}}; AX.activationPoint={187.5, 624.25}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 45.5}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dc62980; AX=N; AX.label='Cancel'; AX.frame={{20, 601.5}, {335, 45.5}}; AX.activationPoint={187.5, 624.25}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 45.5}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42dc62750; AX=Y; AX.label='Cancel'; AX.frame={{162, 614.5}, {51, 20}}; AX.activationPoint={187.5, 624.5}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{142, 13}, {51, 20}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc42dce0f10; AX=N; AX.label='Save'; AX.frame={{20, 528}, {335, 63.5}}; AX.activationPoint={187.5, 559.75}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{20, 491}, {335, 63.5}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dce0c00; AX=Y; AX.id='save-button'; AX.label='Save'; AX.frame={{20, 528}, {335, 63.5}}; AX.activationPoint={187.5, 559.75}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 63.5}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dce08f0; AX=N; AX.label='Save'; AX.frame={{20, 548}, {335, 43.5}}; AX.activationPoint={187.5, 569.75}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 20}, {335, 43.5}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42dce06c0; AX=Y; AX.label='Save'; AX.frame={{169.5, 560}, {36, 20}}; AX.activationPoint={187.5, 570}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{149.5, 12}, {36, 20}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc42dcecef0; AX=N; AX.label='Keywords (Optional)'; AX.frame={{20, 423}, {335, 100}}; AX.activationPoint={187.5, 473}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{20, 386}, {335, 100}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTInputAccessoryView:0x7fc42dcfb1d0; AX=N; AX.frame={{20, 423}, {0, 0}}; AX.activationPoint={20, 423}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTInputAccessoryViewContent:0x7fc42dcfb3d0; AX=N; AX.frame={{20, 423}, {0, 0}}; AX.activationPoint={20, 423}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dcbb6d0; AX=N; AX.frame={{20, 456}, {335, 67}}; AX.activationPoint={187.5, 489.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 33}, {335, 67}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dcbb3c0; AX=N; AX.frame={{20, 456}, {335, 64}}; AX.activationPoint={187.5, 488}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 64}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTMultilineTextInputView:0x7fc42dcc6d70; AX=N; AX.frame={{20, 456}, {335, 63}}; AX.activationPoint={187.5, 487.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 63}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |  |--<RCTUITextView:0x7fc437809000; AX=Y; AX.id='keywords-input'; AX.value='I am a robot'; AX.frame={{20, 456}, {335, 63}}; AX.activationPoint={25, 461}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 63}}; opaque; alpha=1; text='I am a robot'>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<UIImageView:0x7fc42dcef5b0; AX=N; AX.frame={{349.5, 497}, {2.5, 19}}; AX.activationPoint={350.75, 506.5}; AX.traits='UIAccessibilityTraitImage'; AX.focused='N'; frame={{329.5, 41}, {2.5, 19}}; alpha=0; UIE=N>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<UIImageView:0x7fc42dcef380; AX=N; AX.frame={{23, 513.5}, {329, 2.5}}; AX.activationPoint={187.5, 514.75}; AX.traits='UIAccessibilityTraitImage'; AX.focused='N'; frame={{3, 57.5}, {329, 2.5}}; alpha=0; UIE=N>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<UILabel:0x7fc42dc51340; AX=N; AX.label='Add any additional words (separated by commas) that will help requesters find and hire you for this skill.'; AX.frame={{20, 461}, {335, 58}}; AX.activationPoint={187.5, 490}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 5}, {335, 58}}; opaque; hidden; alpha=1; UIE=N; text='Add any additional words (separated by commas) that will help requesters find and hire you for this skill.'>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<_UITextContainerView:0x7fc42dcb60c0; AX=N; AX.frame={{20, 456}, {335, 25}}; AX.activationPoint={187.5, 468.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 25}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dcc6a60; AX=N; AX.label='Keywords (Optional)'; AX.frame={{20, 423}, {335, 33}}; AX.activationPoint={187.5, 439.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 33}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dcc02a0; AX=N; AX.label='Keywords (Optional)'; AX.frame={{20, 423}, {335, 33}}; AX.activationPoint={187.5, 439.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {335, 33}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42dcbf860; AX=Y; AX.label='Keywords (Optional)'; AX.frame={{20, 438}, {335, 17.5}}; AX.activationPoint={187.5, 446.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 15}, {335, 17.5}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc42dcc5d30; AX=N; AX.label='Years Experience'; AX.frame={{20, 348}, {167.5, 75}}; AX.activationPoint={103.75, 385.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{20, 311}, {167.5, 75}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTInputAccessoryView:0x7fc42dc50d00; AX=N; AX.frame={{20, 348}, {0, 0}}; AX.activationPoint={20, 348}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTInputAccessoryViewContent:0x7fc42dcc5080; AX=N; AX.frame={{20, 348}, {0, 0}}; AX.activationPoint={20, 348}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dc21240; AX=N; AX.frame={{20, 381}, {167.5, 42}}; AX.activationPoint={103.75, 402}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 33}, {167.5, 42}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dc4dbb0; AX=N; AX.frame={{20, 381}, {167.5, 39}}; AX.activationPoint={103.75, 400.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 39}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTSinglelineTextInputView:0x7fc42dea2810; AX=N; AX.frame={{20, 381}, {167.5, 38}}; AX.activationPoint={103.75, 400}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 38}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |  |--<RCTUITextField:0x7fc42e89ce00; AX=Y; AX.id='years-experience-input'; AX.value='10'; AX.frame={{20, 381}, {167.5, 38}}; AX.activationPoint={37, 399.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 38}}; alpha=1; text='10'>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<UIFieldEditor:0x7fc43786e800; AX=N; AX.value='10'; AX.frame={{20, 381}, {168, 38}}; AX.activationPoint={104, 400}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {168, 38}}; alpha=1; text='10'>
      |  |  |  |  |  |  |  |  |  |  |  |  |  |--<_UITextFieldContentView:0x7fc42de90d70; AX=N; AX.frame={{20, 381}, {168, 38}}; AX.activationPoint={104, 400}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {168, 38}}; alpha=1; UIE=N>
      |  |  |  |  |  |  |  |  |  |  |  |  |  |  |--<UITextSelectionView:0x7fc42dcced50; AX=N; AX.frame={{20, 381}, {0, 0}}; AX.activationPoint={20, 381}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1; UIE=N>
      |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |--<UIView:0x7fc435825430; AX=N; AX.frame={{36, 389}, {2, 21}}; AX.activationPoint={37, 399.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{16, 8}, {2, 21}}; opaque; alpha=1; UIE=N>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<UIAccessibilityTextFieldElement:0x6080008483d0; AX=Y; AX.value='10'; AX.frame={{20, 381}, {167.5, 38}}; AX.activationPoint={37, 399.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dea2500; AX=N; AX.label='Years Experience'; AX.frame={{20, 348}, {167.5, 33}}; AX.activationPoint={103.75, 364.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 33}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42de90a60; AX=N; AX.label='Years Experience'; AX.frame={{20, 348}, {167.5, 33}}; AX.activationPoint={103.75, 364.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 33}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42de8e840; AX=Y; AX.label='Years Experience'; AX.frame={{20, 363}, {167.5, 17.5}}; AX.activationPoint={103.75, 371.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 15}, {167.5, 17.5}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc435837e60; AX=N; AX.label='Hourly Rate $'; AX.frame={{20, 273}, {167.5, 75}}; AX.activationPoint={103.75, 310.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{20, 236}, {167.5, 75}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTInputAccessoryView:0x7fc435830ac0; AX=N; AX.frame={{20, 273}, {0, 0}}; AX.activationPoint={20, 273}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTInputAccessoryViewContent:0x7fc435837880; AX=N; AX.frame={{20, 273}, {0, 0}}; AX.activationPoint={20, 273}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 0}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42ddf1ad0; AX=N; AX.label='$'; AX.frame={{20, 306}, {167.5, 42}}; AX.activationPoint={103.75, 327}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 33}, {167.5, 42}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc435838790; AX=N; AX.label='$'; AX.frame={{20, 306}, {10.5, 37}}; AX.activationPoint={25.25, 324.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {10.5, 37}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42dd7c150; AX=Y; AX.label='$'; AX.frame={{20, 314.5}, {11, 20}}; AX.activationPoint={25.5, 324.5}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 8.5}, {11, 20}}; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dd68ea0; AX=N; AX.frame={{35, 306}, {152.5, 39}}; AX.activationPoint={111.25, 325.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{15, 0}, {152.5, 39}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTSinglelineTextInputView:0x7fc43590e030; AX=N; AX.frame={{35, 306}, {152.5, 38}}; AX.activationPoint={111.25, 325}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {152.5, 38}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |  |--<RCTUITextField:0x7fc42fa1d000; AX=Y; AX.id='hourly-rate-input'; AX.value='10'; AX.frame={{35, 306}, {152.5, 38}}; AX.activationPoint={111.25, 325}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {152.5, 38}}; alpha=1; text='10'>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<_UITextFieldContentView:0x7fc42dfe2dd0; AX=N; AX.frame={{35, 306}, {153, 38}}; AX.activationPoint={111.5, 325}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {153, 38}}; alpha=1; UIE=N>
      |  |  |  |  |  |  |  |  |  |  |  |  |--<UIAccessibilityTextFieldElement:0x60400084a170; AX=Y; AX.value='10'; AX.frame={{35, 306}, {152.5, 38}}; AX.activationPoint={111.25, 325}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc43590dd20; AX=N; AX.label='Hourly Rate'; AX.frame={{20, 273}, {167.5, 33}}; AX.activationPoint={103.75, 289.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 33}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc43591c150; AX=N; AX.label='Hourly Rate'; AX.frame={{20, 273}, {167.5, 33}}; AX.activationPoint={103.75, 289.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {167.5, 33}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc435900ae0; AX=Y; AX.label='Hourly Rate'; AX.frame={{20, 288}, {167.5, 17.5}}; AX.activationPoint={103.75, 296.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 15}, {167.5, 17.5}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc42dea1a30; AX=N; AX.label=' Volunteer  Paid'; AX.frame={{20, 171}, {335, 102}}; AX.activationPoint={187.5, 222}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{20, 134}, {335, 102}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dea1720; AX=N; AX.label=' Paid'; AX.frame={{120, 171}, {70, 102}}; AX.activationPoint={155, 222}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{100, 0}, {70, 102}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42dea14f0; AX=Y; AX.id='icon-button-text'; AX.label='Paid'; AX.frame={{141, 251}, {28, 17.5}}; AX.activationPoint={155, 259.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{21, 80}, {28, 17.5}}; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dea0ff0; AX=Y; AX.id='icon-paid'; AX.label=''; AX.frame={{120, 176}, {70, 70}}; AX.activationPoint={155, 211}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 5}, {70, 70}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42dea0dc0; AX=Y; AX.label=''; AX.frame={{146.5, 196.5}, {17, 28.5}}; AX.activationPoint={155, 210.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{26.5, 20.5}, {17, 28.5}}; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42dedd6d0; AX=N; AX.label=' Volunteer'; AX.frame={{20, 171}, {70, 102}}; AX.activationPoint={55, 222}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {70, 102}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deba650; AX=Y; AX.id='icon-button-text'; AX.label='Volunteer'; AX.frame={{25, 251}, {60, 17.5}}; AX.activationPoint={55, 259.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{5, 80}, {60, 17.5}}; alpha=1>
      |  |  |  |  |  |  |  |  |  |--<RCTView:0x7fc42deba150; AX=Y; AX.id='icon-volunteer'; AX.label=''; AX.frame={{20, 176}, {70, 70}}; AX.activationPoint={55, 211}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 5}, {70, 70}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deb9f20; AX=Y; AX.label=''; AX.frame={{40.5, 196.5}, {29, 28.5}}; AX.activationPoint={55, 210.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20.5, 20.5}, {29, 28.5}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deb9b00; AX=Y; AX.label='What type of gig requests would you like to receive for this skill? Select Volunteer, Paid, or both.'; AX.frame={{20, 122.5}, {335, 34}}; AX.activationPoint={187.5, 139.5}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 85.5}, {335, 34}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deb98d0; AX=Y; AX.label='Gig Availability'; AX.frame={{20, 92.5}, {335, 25.5}}; AX.activationPoint={187.5, 105.25}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 55.5}, {335, 25.5}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deb96a0; AX=Y; AX.label='Software Testing'; AX.frame={{20, 47}, {335, 31}}; AX.activationPoint={187.5, 62.5}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{20, 10}, {335, 31}}; alpha=1>
      |  |  |  |  |  |  |--<RCTView:0x7fc42deb9390; AX=N; AX.label='Skill Details '; AX.frame={{0, 0}, {375, 37}}; AX.activationPoint={187.5, 18.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 37}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |--<RCTView:0x7fc42deb9080; AX=Y; AX.label=''; AX.frame={{0, 0}, {40, 37}}; AX.activationPoint={20, 18.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {40, 37}}; opaque; alpha=1>
      |  |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deb8e50; AX=Y; AX.label=''; AX.frame={{10, 9.5}, {20.5, 17.5}}; AX.activationPoint={20.25, 18.25}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{10, 9.5}, {20.5, 17.5}}; alpha=1>
      |  |  |  |  |  |  |  |--<RCTTextView:0x7fc42deb8c20; AX=Y; AX.label='Skill Details'; AX.frame={{0, 10}, {375, 17.5}}; AX.activationPoint={187.5, 18.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 10}, {375, 17.5}}; alpha=1>]

      175 |   });
      176 | 
    > 177 |   it(":ios: a user can be onboarded", async () => {
          |   ^
      178 |     await launchApp({
      179 |       permissions: { camera: "YES", photos: "YES", location: "always" }
      180 |     });

      at Env.it (../../../node_modules/jest-jasmine2/build/jasmine_async.js:102:24)
      at Suite.<anonymous> (onboarding.test.js:177:3)
      at Object.<anonymous> (onboarding.test.js:17:1)
```

**Comment by viniciusoliveira01** [comment]
Same problem here!

**Comment by marzieh-kazemi** [comment]
Same problem here!

**Comment by kfroemming** [comment]
I am also running into this on CircleCI. Locally everything is fine.

**Comment by zeinMch** [comment]
Same problem :(

**Comment by LeoNatan** [comment]
Did you read the the error description? It doesn’t say it cannot find it, it says the item cannot be interacted with. Check why that is the case.
