### ISSUE TITLE
Specify device name?

### ISSUE THREAD

**Issue by compojoom** [wix/detox#948]
I'm running into this bug https://github.com/facebook/FBSimulatorControl/issues/490
and I'm trying to see if my tests are going to run on iOS 11.4 for the time being. 
In Xcode I've downloaded ios 11 and I've created a new simulator with it. 

I deleted the simulator with ios12. So currently when I run this:
`$ applesimutils --list --byName "iPhone 8"`
i get
```

[
  {
    "deviceType" : {
      "name" : "iPhone 8",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8"
    },
    "state" : "Shutdown",
    "availability" : "(available)",
    "name" : "iPhone 8",
    "udid" : "A0D6B14E-B07B-4156-80CC-CAEAE548F00E",
    "os" : {
      "version" : "11.4",
      "availability" : "(available)",
      "name" : "iOS 11.4",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-11-4",
      "buildversion" : "15F79"
    }
  }
]
```

but when I run my test I get:
```
detox[93098] INFO:  [DetoxServer.js] server listening on localhost:60549...
detox[93098] ERROR: [index.js/DETOX_INIT_ERROR]
 Error: Can't find a simulator to match with "iPhone 8", run 'xcrun simctl list' to list your supported devices.
      It is advised to only state a device type, and not to state iOS version, e.g. "iPhone 7"
    at AppleSimUtils.findDevicesUDID (/node_modules/detox/src/devices/ios/AppleSimUtils.js:46:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

what am I missing here?

**Comment by compojoom** [comment]
okay, a stupid comma.... 

For other wondering, specify name like this:
`"name": "iPhone 7, iOS 11.4"`
