### ISSUE TITLE
Issue with the latest update of Xcode ?

### ISSUE THREAD

**Issue by YoshiYo** [wix/detox#949]
Hi team,

I think there is an issue with the latest update of Xcode. 
Or maybe, it comes with MacOS Mojave. 
After a `rm -rf node_modules` and a `yarn`, this is the output of the install. 

```
[5/5] 📃  Building fresh packages...
[-/4] ⠄ waiting...
[4/4] ⠄ detox
[-/4] ⠄ waiting...
error /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments:
Directory: /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox
Output:
+++ dirname /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/scripts
+ detoxRootPath=/Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox
++ node -p 'require('\''/Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/package.json'\'').version'
+ detoxVersion=8.1.1
++ echo 8.1.1
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=661d1420e265bba4b1f13ef63bf279e2cb593b43
+ detoxFrameworkDirPath=/Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43
+ detoxFrameworkPath=/Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43/Detox.framework
+ main
+ '[' -d /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43 ']'
+ '[' '!' -d /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43/Detox.framework ']'
+ echo '/Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43 and trying to rebuild.'
/Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43 was found, but could not find Detox.framework inside it. This means that the Detox frameworkbuild process was interrupted.
         deleting /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43 and trying to rebuild.
+ rm -rf /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43
+ prepareAndBuildFramework
+ '[' -d /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ extractSources /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ detoxSourcePath=/Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ tar -xjf /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/Detox-ios-src.tbz -C /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ buildFramework /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ detoxSourcePath=/Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src...'
Building Detox.framework from /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src...
+ mkdir -p /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43
+ /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/scripts/build_universal_framework.sh /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/ios_src/Detox.xcodeproj /Users/guillaumef/Library/Detox/ios/661d1420e265bba4b1f13ef63bf279e2cb593b43/DetoxBuild
child_process.js:621
    throw err;
    ^

Error: Command failed: /Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:600:11)
    at Object.execFileSync (child_process.js:618:13)
    at Object.<anonymous> (/Users/guillaumef/Documents/work/quorum/quorumsco/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

I did the update of Xcode and Mojave in the same time. I didn't try between the two actions. 
Maybe it's not that. I don't know.

Regards,
Guillaume.

**Comment by noomorph** [comment]
It looks like your detox version is pretty much outdated.

**Comment by noomorph** [comment]
What is your result with Detox 9.0.2?
