### ISSUE TITLE
detox test failed

### ISSUE THREAD

**Issue by makoy21** [wix/Detox#972]
#### Description
Trying to run detox test

#### Steps to Reproduce
`detox test`

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 9.0.4
* React Native: 0.57.2
* Node: v8.11.1
* Device: iPhone 7
* Xcode: 10.0
* macOS: 10.14

#### Device and verbose Detox logs
`
configuration="ios.sim.debug" loglevel="verbose" artifactsLocation="artifacts/ios.sim.debug.2018-10-06 10-20-30Z" node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
 FAIL  e2e/firstTest.spec.js
  ● Test suite failed to run

    Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/TestApp"

      at ../node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (../node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (../node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (../node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (../node_modules/babel-core/lib/transformation/pipeline.js:46:16)
`

`Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.44s
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
child_process.js:644
    throw err;
    ^

Error: Command failed: node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runJest (node_modules/detox/local-cli/detox-test.js:154:6)
    at run (node_modules/detox/local-cli/detox-test.js:85:7)
    at Object.<anonymous> (node_modules/detox/local-cli/detox-test.js:217:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

**Comment by noomorph** [comment]
What is relation to Detox?
