### ISSUE TITLE
postinstall fails

### ISSUE THREAD

**Issue by FrankSalad** [wix/Detox#983]
#### Description
Attempting to clone and build react-native-navigation v2 showcase: https://wix.github.io/react-native-navigation/v2/#/docs/showcases 

#### Steps to Reproduce
```
git clone -b v2 git@github.com:wix/react-native-navigation.git
cd react-native-navigation
npm install
```

Also attempted `yarn install`, same issue. `yarn install` log attached below
#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.1.6 
* React Native: 0.51.1
* Node: v8.12.0
* Device: MacBook Pro, Early 2015
* Xcode: Version 10.0 (10A255)
* macOS: Mojave 10.14

#### Device and verbose Detox logs

```
react-native-navigation temporal$ yarn install
yarn install v1.10.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.51.1" has incorrect peer dependency "react@16.0.0".
warning " > react-native-view-overflow@0.0.3" has unmet peer dependency "react-native-windows@>=0.41.0-rc.1".
[4/4] 📃  Building fresh packages...
[3/3] ⠠ detox
[-/3] ⠠ waiting...
error /Users/temporal/dev/react-native-navigation/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/temporal/dev/react-native-navigation/node_modules/detox
Output:
+++ dirname /Users/temporal/dev/react-native-navigation/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/temporal/dev/react-native-navigation/node_modules/detox/scripts
+ detoxRootPath=/Users/temporal/dev/react-native-navigation/node_modules/detox
++ node -p 'require('\''/Users/temporal/dev/react-native-navigation/node_modules/detox/package.json'\'').version'
+ detoxVersion=8.1.6
++ echo 8.1.6
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=d21e7a1ba19c8a97d6b6e01180c2a22e3727c460
+ detoxFrameworkDirPath=/Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460
+ detoxFrameworkPath=/Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460/Detox.framework
+ main
+ '[' -d /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460 ']'
+ '[' '!' -d /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460/Detox.framework ']'
+ echo '/Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460 and trying to rebuild.'
+ rm -rf /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460
/Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460 and trying to rebuild.
+ prepareAndBuildFramework
+ '[' -d /Users/temporal/dev/react-native-navigation/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ extractSources /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ detoxSourcePath=/Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ tar -xjf /Users/temporal/dev/react-native-navigation/node_modules/detox/Detox-ios-src.tbz -C /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ buildFramework /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ detoxSourcePath=/Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src...'
+ mkdir -p /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460
Building Detox.framework from /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src...
+ /Users/temporal/dev/react-native-navigation/node_modules/detox/scripts/build_universal_framework.sh /Users/temporal/dev/react-native-navigation/node_modules/detox/ios_src/Detox.xcodeproj /Users/temporal/Library/Detox/ios/d21e7a1ba19c8a97d6b6e01180c2a22e3727c460/DetoxBuild
child_process.js:625
    throw err;
    ^

Error: Command failed: /Users/temporal/dev/react-native-navigation/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at Object.<anonymous> (/Users/temporal/dev/react-native-navigation/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```

**Comment by LeoNatan** [comment]
That’s a very old Detox release. What is the point of opening this issue?
